### ISSUE TITLE
Estudio

### ISSUE THREAD

**Issue by vnramirez** [IIC2115/Syllabus#1]
Estimados,

Se asume que cada lunes tenemos que tener estudiado todo lo que haya sido agregado/actualizado a Syllabus? Acabo de pullear varios archivos de materia, pero no han habido nuevos anuncios sobre lo que hay que tener estudiado para el lunes.

Saludos y gracias de antemano.

**Comment by halobel** [comment]
Hola Vicente, perdón por la demora en responder. Es efectivamente como dices, y tal como lo mencionamos en clases, la materia que entra en el laboratorio corresponde a la que está en el Syllabus, en la carpeta correspondiente a la materia que estamos viendo. En particular, para mañana lo que entra es orientación a objetos.
Puedes encontrar un calendario tentativo en el programa, donde se indica que materia corresponde a cada laboratorio.
Saludos

**Comment by vnramirez** [comment]
Gracias por responder. Junto con varios compañeros no sabíamos si sólo entraba el IPYNB 01 del capítulo 1 (Objetos en Python), o todos los IPYNB del capítulo 1 (Properties, Herencia, etc.)

Saludos!
