### ISSUE TITLE
Especificación tipo de variable para humedad actual y óptima

### ISSUE THREAD

**Issue by JaviOrtizH** [IIC2115/Syllabus#10]
Hola! 

Tengo una duda acerca de cómo definir la variable humedad_actual y humedad_optima, ya que nos dice que debe ser float, pero no estoy segura si podría dejarla como entero (entre 0 y 100) o necesariamente debe ser "continua".

Muchas gracias 😊

**Comment by pcseisdedos** [comment]
Hola, disculpa por la hora y la demora. Lo que tu describes es un int y se especifíca que es un float en el enunciado (acepta decimales).

¡Saludos!
Pablo 😁👍
