### ISSUE TITLE
Tests Laboratorio 1

### ISSUE THREAD

**Issue by llloyola** [IIC2115/Syllabus#10]
Hola! Tengo una consulta, ¿subirán tests para que podamos probar nuestro código del Laboratorio 1? Me gustaría probar mi código con más ejemplos además de los que salen en el enunciado.

Edit: No me quedó claro la parte del enunciado que dice "además de esto, el tiempo de ejecución de sus algoritmos no debe sobrepasar cierto límite (serán entregados la semana del 4 de octubre)". ¿ Eso quiere decir que entregarán el tiempo límite para los problemas y/o los tests mismos?

**Comment by halobel** [comment]
Hola, no tenemos considerado subir tests, la idea es que los desarrollen uds. mismo como parte del proceso de solución.
En relación a los tiempos de ejecución, acabo de actualizar el enunciado con los tiempos para cada problema.
