### ISSUE TITLE
A1

### ISSUE THREAD

**Issue by MariaJoseSilva** [IIC2115/Syllabus#10]
Hola! 
Tengo algunas preguntas sobre la actividad 1.
1. Podemos asumir que todas las personas tienen padre y madre o ninguno, es decir, nadie tiene solo el rut del padre y no el de la madre o viceversa.

2. Si existe más de un descendiente más lejano ¿se puede entregar solo el nombre de uno de ellos o deben ser todos? 
(Lo mismo con la familia más grande, pero vi que en otra issue se preguntaba)

3. Podemos asumir que las familias de distintos apellidos son independientes entre ellas y no existe ninguna persona que las conecte? 

4. En la consulta Agregar Persona, la persona que se quiere agregar tendrá los mismos datos que tienen las personas en personas.json y si es así, también vendrá en formato de diccionario?

Muchas gracias, buena semana.

**Comment by RonaldoSosa** [comment]
Hola. Respondiendo a tus preguntas:

1. Sí, se puede asumir que tienen padre y madre, o nada.
2. Bastaría con mostrar solo una, pero deberían indicar que solo mostraran una, en caso de haber más. Lo mismo con la familia más grande.
3. Es algo que podría pasar, pero una persona siempre va a pertenecer a una única familia, dada por el apellido.
4. Si, tendrá los mismos datos, pero el formato lo define cada uno. Recuerden que siempre tienen que incluir una ejecución de ejemplo de cada consulta, y se usará dicho formato para corregir.

**Comment by MariaJoseSilva** [comment]
Muchas gracias!
Respecto a la pregunta 2, se refiere a indicarlo como una consideración/supuesto en el texto? O hay que indicarlo en la respuesta de cada consulta donde haya más de un descendiente lejano

**Comment by RonaldoSosa** [comment]
Hola. Pueden dejar un supuesto, como comentario en el código o texto, que diga algo como: "En caso de existir más de un descendiente más lejano solo se retornará el primero encontrado que cumpla la condición".
