### ISSUE TITLE
Prints y demora del programa

### ISSUE THREAD

**Issue by tafuenza** [IIC2115/Syllabus#10]
Tenemos problemas con la cantidad de prints al momento de ejecutar el programa, dado que cada persona tiene 3 eventos (Llegar, subirse y bajarse) y cada tren 2 eventos (Salir y llegar a estacion) son demasiado los prints que se imprimen en consola.
Algún Consejo?
Gracias

**Comment by FGarridoV** [comment]
Si te da mucho problema agrupa los print cada una hora y así haces print masivos cada hora. 

Colab en ocasiones se marea, si te está dando problemas y crees que es eso, te recomiendo bajar el ipynb y correrlo en jupyter a ver como le va con los recursos de tu computadora.

Saludos
Francisco

**Comment by iasantibanez** [comment]
Hola estimado,
intente agrupar los prints como tu dijiste pero no veo mucha mejora dado que siguen siendo demasiados (incluso cuando omito prints de algún evento, por ej: llegadas). Existirá otra alternativa a la mencionada que podamos intentar?

Slds

**Comment by Hernan4444** [comment]
Hola, 
Lo otro que pueden hacer es agrupar la acción sin considerar a la persona en particular, ejemplo: "Llegaron X personas", "se bajaron Y personas", "Se subieron Z personas". En vez de indicar el evento por cada persona.

Saludos ✌️
