### ISSUE TITLE
Problema 2 L05

### ISSUE THREAD

**Issue by mtbobillier** [IIC2115/Syllabus#100]
Hola! Haciendo el ejercicio 2 mi función me retorna otra solución posible:
[[8, 4], [5, 3, 4], [1, 5, 6], [12], [7, 2, 3]]
¿Está bien que existan varias soluciones para el mismo problema o es necesario que me entregue el mismo output del enunciado?
Saludos!

**Comment by FGarridoV** [comment]
Esta bien! Basta con que encuentres una solución correcta.

Saludos
