### ISSUE TITLE
Usar SQLite

### ISSUE THREAD

**Issue by vtorresg** [IIC2115/Syllabus#100]
Hola! Se puede usar SQLite (igual que la tarea 4) para acceder a la base de datos, y realizar lo pedido en vez de pandas? 
Saludos!

**Comment by FGarridoV** [comment]
No te lo recomiendo para nada. Recuerda que uno de los objetivos del curso es aprender nuevas herramientas. SQLite ya lo sabes usar. Ahora, formalmente si cumples las exigencias del laboratorios, podrías no usar Pandas, pero verás que es mucho más fcil y amigable que SQLite.

Saludos,
Francisco
