### ISSUE TITLE
Misión 3 c)  duda de enunciado sobre país a escoger

### ISSUE THREAD

**Issue by almartinezlissie** [IIC2115/Syllabus#100]
No me queda claro en la misión 3 c en la parte que dice "el país donde ese idioma es oficial y predominante que deje la mayor  huella" , ahí debo primero tomar los países donde es oficial y predominante, y a los que resulten elegir el de mayor huella o  tomo altiro el que sea oficial, predominante y con mayor huella?

**Comment by Jamidd** [comment]
Para cada idioma (los 5 mas hablados), busca los países donde sea oficial y predominante (tu defines lo que tomas por predominante) y de esos muestra el que tiene la mayor huella ecológica. 
Saludos,
Jaime.

**Comment by almartinezlissie** [comment]
muchas gracias :)
