### ISSUE TITLE
Bonus b)

### ISSUE THREAD

**Issue by FernandaNavarroE** [IIC2115/Syllabus#101]
Hola!! respecto a lo que se pide en el bonus b), se asume que cada ciudad contribuye de forma homogénea a la huella ecológica del país, es necesario hacer un proporcional respecto a su población o queda a nuestro criterio?? 

Saludos!!

**Comment by Jamidd** [comment]
Cada país tiene una distribución del uso de distintos lenguajes. Esa misma distribución aplica para cada país de ese país. Con eso debes obtener la cantidad de personas que hablan cada idioma en cada ciudad. 
Saludos,
Jaime.
