### ISSUE TITLE
Prueba de eficiencia

### ISSUE THREAD

**Issue by FelipeUlloan** [IIC2115/Syllabus#101]
Para este laboratorio, cuales serían los inputs que nos recomiendan probar para medir la eficiencia?
Por ejemplo, para la pregunta 1 con un N=20 anda bien, pero ya con 30 la demora salta de 0.2seg a 70seg :(

**Comment by halobel** [comment]
Hola @FelipeUlloan, para las preguntas de este lab, más que eficiencia, buscamos que efectivamente utilicen la materia que se pide. La eficiencia debiese venir sola al usar esos tópicos, por lo que no es necesario que te preocupes excesivamente de eso.

**Comment by Amanriquez11** [comment]
Estimado profesor, quizás deberían ser mas explícitos en esto, pues en el enunciado aparece que la prueba de eficiencia y correctitud de resultados valdrá un 50%, lo cual confunde respecto a lo que acaba de enunciar ahora.
Fuera de esto tengo una duda respecto al problema 3, resolví el problema mediante dos funciones, una que me permite calcular la mediana ( ordeno la lista con un sort()) y otra que resuelve el problema en si, es bastante eficiente ( puede correr listas de 100 mil datos en menos de un segundo) sin embargo nose si estoy ocupando la materia que se pide, para ordenar la lista y calcular la mediana esta bien ocupar un sort() ? o debería crear la función de ordenamiento yo mismo ? 
@halobel

**Comment by halobel** [comment]
Con respecto a lo primero que mencionas, sin duda, tienes razón, debimos haber sido más explícitos en eso en el enunciado. El tema es que la ponderación sigue siendo la adecuada, ya que de igual manera evita soluciones de fuerza bruta. Más que nada, velo como que si usas la materia que corresponde (y de una manera razonable), el 50% de la eficiencia ya lo tienes asegurado.
Con respecto al problema 3, no entiendo a lo que te refieres con resolver el problema en si. Del uso de la materia, esperamos que en ese ejercicio utilicen ordenamiento. Ahora, cual algoritmo usar, va a depender del tamaño de la lista a **ordenar**, ya que los algoritmos que vimos tienen distinta complejidad computacional.

**Comment by FelipeUlloan** [comment]
para el problema 3, cuales serían los valores aprox que deberían tener las listas? solo números del 1 al 10? o del 1 al 100? esto para hacer los random y generar listas para probar la eficiencia
