### ISSUE TITLE
Asignación de alumnos a grupos P2 - Lab 5

### ISSUE THREAD

**Issue by javiprado** [IIC2115/Syllabus#102]
Hola!
En la pregunta 2 del laboratorio 5, en el ejemplo que se da, se utilizan todos los puntajes de la lista para armar los grupos ¿esto siempre tiene que ser así? Es decir, siempre tengo que asignar a todos los alumnos a algún grupo?

**Comment by cmujicai** [comment]
tengo la misma pregunta @FGarridoV  y @halobel

**Comment by halobel** [comment]
Sí, siempre es necesario asignar todos a algún grupo, y en caso que no se pueda, la respuesta es una lista vacía.
