### ISSUE TITLE
Nueva Base de Datos con rotulaciones

### ISSUE THREAD

**Issue by FGarridoV** [IIC2115/Syllabus#102]
Estimados,

En el siguiente link podrán encontrar una nueva base de datos con registros. Esta ya incluye los que ustedes estaban trabajando e incorpora nuevos datos. Por lo que basta con sobre escribir la base de datos anterior. La estructura es es la misma.

[LINK DE DESCARGA ](https://www.dropbox.com/s/bhnn9clv44rnudz/Dataset2.db?dl=0)

Además, les comentaré cierta información de los datos:

* Existen robos de combustible durante la tarde del 11-10-2018 y el día 04-07-2018. Poner atención a los IMEI 867162025816745, 867162025466061, 867162025466129, 
867162025467291, 867162025467523, 867162025468018, 867162025472283, 
867162025473406, 867162025817156, 867162025824327, 867162025824350.
* Podría existir una falla en el vehículo de sensor IMEI 867162025478264.

Espero con esto puedan reconocer algunos casos para verificar y validar sus modelos!

Éxito con la tarea y ánimo con el fin de semestre,
Francisco

**Comment by MarceloBuneder** [comment]
La nueva base de datos "Dataset2" muestra saltos en el odometro, por ejemplo el vehículo 867162025478264 que mencionaron que tenia error en el sensor, al graficar su nivel de estanque vs el odometro, se puede apreciar que los datos de odometro pasan de los 204.000 km a 228.000 km.

Esto no sucedía en la primera base de datos y me gustaría saber si es un error de la nueva base o si tenemos que modificar nuestro trabajo y adaptarnos a estos nuevos datos.

**Comment by Thomasmurrayh** [comment]
Así mismo sucede con las fechas de los registros, para el vehículo de imei 867162025465600 los registros saltan de 2018-07-04 23:36:07 a 2018-10-01 08:52:07. Es necesario considerar los registros del mes de Julio?

**Comment by FGarridoV** [comment]
@MarceloBuneder @Thomasmurrayh Efectivamente hay registros de fechas que no necesariamente están consecutivas. Por lo que si pueden observarse saltos en los datos.

Por otro lado, recuerden que sus modelos deben estar trabajados de forma genérica, por lo que no debieran depender de los datos que les entregamos. Es decir, no es necesario adaptarse a los nuevos datos, sino que deben ser capaces de identificar los casos solicitados independientemente el dataset.

saludos,
Francisco

**Comment by jfmorenosm** [comment]
Este gráfico del camión 867162025466061 el día 10-10-2018, se "llena de bencina" de a poco (se puede ver que es diagonal). ¿Es un error del sensor? ¿La caída es un robo?
![grafico](https://user-images.githubusercontent.com/42227284/47818998-f8afa300-dd37-11e8-9feb-3897ad839381.png)

**Comment by FGarridoV** [comment]
Eso es lo que debes decir con tus criterios!
