### ISSUE TITLE
L05 Problema 3

### ISSUE THREAD

**Issue by kdcarreno** [IIC2115/Syllabus#103]
la solución del ejemplo creo que debería ser 1.

a=5  viajes = [2,3,4,2,3,6,8,4,5]

para año 6 :
[2,3,4,2,3] --> 2*4<=6  no

para año 7 :
[3,4,2,3,6]--> 2*2<=8 si

para año 8:
[4,2,3,6,8]--> 2*3<=4 no

para año 9:
[2,3,6,8,4]--> 2*6<=5 no

Me confirman por favor @halobel @FGarridoV

**Comment by halobel** [comment]
Hola @kdcarreno, para calcular la mediana, debes primero ordenar los datos de menor a mayor (o al revés). Si no haces eso, el elemento central será aleatorio, por lo que no tendría sentido obtener su valor.

**Comment by asnunez1** [comment]
Hola! Sólo para estar segura: ¿Se puede importar numpy para calcular la mediana de las listas?

**Comment by FelipeUlloan** [comment]
para el valor de a, debemos asumir que siempre será impar? o debemos hacer la excepción para cuando es par y calcular la mediana con los (sumade2valorescentrales)/2 ?
