### ISSUE TITLE
Robos de bencina dados

### ISSUE THREAD

**Issue by vtorresg** [IIC2115/Syllabus#103]
Hola! ¿Los imeis de los camiones que supuestamente hay robos según el issue que subieron tienen que ser todos detectados por nuestro algoritmo? O puede que me den algunos de ellos solamente, justificando el procediminento?

Saludos!

Vicente

**Comment by FGarridoV** [comment]
La ideal del Laboratorio es que justifiques tu procedimiento y seas capaz de mostrar una lógica coherente a la hora de detectar los problemas. Los datos que les marcamos son solo una ayuda para logren realizar una modelación con mayor conocimiento de los datos.
