### ISSUE TITLE
GoogleColab:  DatabaseError: database disk image is malformed

### ISSUE THREAD

**Issue by ndcamhi98** [IIC2115/Syllabus#103]
Hola, al cargar la base de datos, me aparece un error que no he podido solucionar:

DatabaseError: database disk image is malformed

Necesito trabajar en colab  porque es el único lugar  donde el comando row_ranks() corre bien. Pero sin esto quede estancado.

**Comment by Jamidd** [comment]
Quizás se corrompió el archivo, intenta descargar de nuevo la base de datos y probarla. 
Sino mandame un mail con fotos del problema y la base de datos que te esta causando el problema y vemos que se puede hacer. 
En todo caso si te funciona en colab y puedes trabajar ahí no debería haber ningún problema en la corrección. 
Saludos, 
Jaime

**Comment by ndcamhi98** [comment]
¡Hola!

Gracias por la ayuda, pero la verdad es que he descargado y vuelto a cargar
la base de datos  en el colab de google varias veces pero realmente no me
funciona. El problema es que TENGO que trabajar en colab, ya que en jupyter
la version que tengo de sqlite es mas vieja no me deja usar los comandos
para hacer rank (como el row_rank()).

Te adjunto el problema a ver si lo podemos arreglar, y si no se puede, me
podrias dar una forma de actualizar mi sqlilte de jupyter para poder tener
la funcion row_rank(). (para poder usarla tengo q tener la version 3.25
para arriba y tengo la 3.23)

¡Saludos!

**Comment by Jamidd** [comment]
No me salen los adjunto, reenviamelo a jamiddleton@uc.cl plz.
Saludos, 
Jaime
