### ISSUE TITLE
[L03] [FORMATO] [ARCHIVO .PY]

### ISSUE THREAD

**Issue by dilanlopeg** [IIC2115/Syllabus#104]
hola!, tengo dudas sobre el formato de entrega del archivo .py del lab, este solo debe tener las consultas definidas, ejecutadas? de ser asi no se deben incluir los cursor.fetchall(consulta) ? o da lo mismo como en la actividad?

**Comment by Jamidd** [comment]
En este caso da un poco lo mismo, ya que no va a haber corrección automática. Simplemente preocupate que este ordenado y legible todo. 
Saludos,
Jaime
