### ISSUE TITLE
L05- problemas con deepcopy()

### ISSUE THREAD

**Issue by isabelladahdal** [IIC2115/Syllabus#104]
Hola!! 
Tengo un problema en la pregunta 1, estoy iterando y quiero generar una copia de la lista para no alterar la original, pero cuando uso deepcopy me aparece el siguiente error : 'list' object has no attribute 'deepcopy'
¡Gracias!

**Comment by Sabarriga** [comment]
Hola! Según yo se usa así, si te sigue tirando error no cacho :(
>>> import copy
>>> lista_copiada = copy.deepcopy(lista_original)
