### ISSUE TITLE
Formato reporte 

### ISSUE THREAD

**Issue by rpmalonnek** [IIC2115/Syllabus#106]
en el enunciado dicen que el reporte con las justificaciones del modelo debe estar en formato ipynb, esta sección de la tarea puede estar en pdf si no contiene codigos ?

**Comment by FGarridoV** [comment]
Igualmente debes entregar tus códigos y que estos logren ejecutar la predicción solicitada. Pero el informe puede ser entregado en PDF y de preferencia en LATEX.

Saludos

**Comment by fjgran** [comment]
Hola, como están?
Disculpa pero en el enunciado en ninguna parte sale que el informe tiene que ser en Latex, sino que tiene que ser dentro del mismo archivo .ipynb. Que cosa de verdad hay que hacer para la entrega?
![captura](https://user-images.githubusercontent.com/42157658/47796767-c08e6d00-dd03-11e8-9a63-d091202d86f7.PNG)

**Comment by FGarridoV** [comment]
Estás en lo correcto se pide que el informe esté en **.ipynb**. Solo le respondí a tu compañero que preguntó si **puede** entregarlo en PDF y de hacerlo, que de preferencia lo haga en LATEX.

Saludos

**Comment by AndresNavarrete** [comment]
Hola a todos,
solo por aclarar: ¿existe bonificación por hacer este reporte en latex? ¿Entregar el .pdf de otra forma tiene la misma calificación?
Saludos
