### ISSUE TITLE
¿Creación de tablas o solo inserción ? 

### ISSUE THREAD

**Issue by almartinezlissie** [IIC2115/Syllabus#106]
Hola, aun no me queda claro si yo ocupé las tablas vacías que venían en la última base de datos, debo entregar mi laboratorio solo insertando los datos necesarios en estas tablas ya creadas, o debo de todos modos  crear estas tablas ocupando lo que ya viene como referencia. Si es que el caso fuera solo insertar lo datos en estas tablas ya creadas ¿No importa que aparezca el dato de capital siendo que en el enunciado aparece como una de las columnas que debíamos ignorar?

**Comment by Jamidd** [comment]
Puedes usar las tablas de regalo, pero igual debes tener el código que las generaría (aunque este comentado). Parte de la M1 es saber que son capaces de crear las tablas. 
Saludos, 
Jaime.

**Comment by Nsanhueza7** [comment]
@Jamidd Pero en el correo que envió el profesor se da a entender que no es necesario o se puede interpretar así... Al final si es que hay que colocar crearlas, será un comando innecesario si es que ya se rellenaron las propuestas ("Create Table if not exists...). Quedo atento a la respuesta, muchas gracias de antemano.
![Captura de Pantalla 2020-10-17 a la(s) 22 51 05](https://user-images.githubusercontent.com/67332598/96356906-41023000-10cb-11eb-9572-89c04da4706c.png)

**Comment by nicifuentes** [comment]
yo interpreté como mi compañera el correo, yo solo las llené!

**Comment by Jamidd** [comment]
Pueden llenarlas, pero parte de la M1 es saber que son capaces de crear sus propias tablas. Por eso dejen comentado el código que eventualmente sería capaz de crear las tablas. No es necesario que la ejecuten. No tienen que cambiar nada del código que tienen actualmente, solo agregar las 4 lineas (comentadas) que crearían las tablas.
Saludos,
Jaime
