### ISSUE TITLE
Ponderación de puntaje por problema

### ISSUE THREAD

**Issue by asnunez1** [IIC2115/Syllabus#106]
Hola! Tengo la siguiente duda: En clases se dijo que había un error en los puntajes de los problemas de este laboratorio y que se iban a modificar (ya que según el enunciado el total suma 7 puntos y debería sumar 6 puntos entre los 3 ejercicios). 
¿Cómo quedarían las nuevas ponderaciones de puntaje para cada problema? Gracias!

**Comment by FGarridoV** [comment]
Estimado,

Los puntajes serán:
p1) 1.5 pts
p2) 2 pts
p3) 2.5 pts

Saludos,
Francisco
