### ISSUE TITLE
Problemas repositorio

### ISSUE THREAD

**Issue by aiiglesias** [IIC2115/Syllabus#107]
Quiero revisar mi repositorio para ver si efectivamente mi tarea se subio bien pero al intentarlo me dice que hay un error. Pruebo abriendo tareas pasadas y pasa lo mismo, hay algun error o es un problema mio??

**Comment by fagomez2** [comment]
Hola Agustín! ¿Podrías subir alguna captura de pantalla o algo más descriptivo? No me ha pasado antes, quiero entender tu error para ver cómo te podemos ayudar.
