### ISSUE TITLE
Duda al trabajar con atributo de la tabla: GDP per capita

### ISSUE THREAD

**Issue by faaceituno** [IIC2115/Syllabus#107]
Hola, al momento de querer insertar los datos de la tabla city en mi nueva tabla, este atrbuto me causa problemas y me tira error. Yo supongo que es porque esta escrito con espacios. Esto se puede solucionar de alguna manera?

**Comment by Jamidd** [comment]
prueba utilizando ' " '. cursor.execute(f"""SELECT "GDP per Capita", .....
Saludos,
Jaime
