### ISSUE TITLE
list index out of range

### ISSUE THREAD

**Issue by isabelladahdal** [IIC2115/Syllabus#108]
Hola!!
Al copiar con deepcopy mi lista y agregarle un elemento, para luego usar recursión(agregando esta nueva lista como parámetro), me aparece el error "list index out of range" ¿Cómo puedo solucionarlo?
¡Muchas gracias!

**Comment by FGarridoV** [comment]
Te recomiendo verificar la línea del error, lo más probable es que tengas un llamado a un objeto de la lista del estilo 
`algunaLista[algunIndice]`
Tu error indica que 'algunIndice' es más grande que el tamaño de la lista.

Procura revisar que estas llamando y si existe tal objeto.

Saludos
