### ISSUE TITLE
L03: Uso de TOP en jupyter

### ISSUE THREAD

**Issue by FranciscaUlloa** [IIC2115/Syllabus#108]
Hola! he querido ocupar TOP para algunas de mis consultas y no me deja, al parecer es por versión de SQL que es 3.21, como puedo hacer para que me funcione en jupyter? alguna recomendación o quizás alguna forma de actualizar mi versión? porque vi que habian respondido esto y subieron un código pero sólo funcionaba para el google collab (lo intenté por ahí y aún así me tiraba la versión 3.21).

**Comment by Jamidd** [comment]
Te refieres a algo asi https://www.tutorialgateway.org/python-sql-select-top/?
Saludos,
Jaime

**Comment by FranciscaUlloa** [comment]
No esuqe en la misión 4 no puedo cumplir con todo lo pedido, ya que mi versión de sql es la 3.21 y no puedo ocupar códigos como el row number o el TOP. por lo que necesito alguna manera para actualizar mi versión de SQL en jupyter.

**Comment by pelayouc** [comment]
Yo tengo el mismo problema, porfavor necesito ayuda ya que sin row number no puedo hacer nada de la misión 4

**Comment by Jamidd** [comment]
https://serverfault.com/questions/953845/how-to-update-sqlite3-from-python
básicamente tienen que instalar una nueva versión de python.
Pd. no se los recomiendo mucho. Se puede hacer sin el row_number y top es muy reemplazable por limit. 
Saludos,
Jaime.
