### ISSUE TITLE
formato de respuesta 

### ISSUE THREAD

**Issue by acdelgado1** [IIC2115/Syllabus#109]
Hola! Si para una consulta primero hice otras consultas para ir sabiendo cómo hacerla, es necesario dejar estas "pre consultas" en la entrega o solo dejo una que es la final?? 
Gracias :)

**Comment by Jamidd** [comment]
Solo debes dejar la consulta final, la idea es que apretamos el botón "restart and run all" obtengamos todas las respuestas solicitadas. También es importante que la entrega este ordenada y bien comentada, así se facilita la corrección y se evitan mal entendidos que requieran re-correcciones.  
Saludos,
Jaime

**Comment by rosariopenalabbe** [comment]
Hola! entonces no ponemos connection.close() despues de cada consulta? sólo al inicio y final?

**Comment by Jamidd** [comment]
dejalo al final nomas.
Saludos,
Jaime

**Comment by rscheelv** [comment]
hola! estoy intentando que me quede como lo que dice jaime del "restart & run all" pero me tira error de que mis tablas ya están creadas, entonces no sé si a la hora de que alguien más abra mi .py le pasará lo mismo o se ejecutará bien. Respecto a lo mismo, si pasa el mismo error, puedo dejar el codigo con drop table?

**Comment by Jamidd** [comment]
En el caso de la revisión no debería pasar ya que no tendríamos tus tablas. Para quedar tranquilo, puedes revisar si están, y borrarlas antes de crear la nuevas y llenarlas.
Saludos,
Jaime

**Comment by rscheelv** [comment]
perfecto, gracias!
