### ISSUE TITLE
Reporte bencina y detección de errores

### ISSUE THREAD

**Issue by jfmorenosm** [IIC2115/Syllabus#109]
Dos preguntas:
1.- Es necesario indicar cuanta bencina roban?
2.- Este gráfico del camión 867162025466061 el día 10-10-2018, se "llena de bencina" de a poco (se puede ver que es diagonal). ¿Es un error del sensor? ¿La caída es un robo?
![grafico](https://user-images.githubusercontent.com/42227284/47822815-4df1b180-dd44-11e8-9678-bba2fd2b7c38.png)

**Comment by FGarridoV** [comment]
No se pide la cantidad de robo, pero si te sirve para algún supuesto, adelante!

saludos
