### ISSUE TITLE
Formato de entrega tarea.

### ISSUE THREAD

**Issue by vtorresg** [IIC2115/Syllabus#11]
Hola, cómo puedo convertir un archivo .py a .ipynb y que quede por módulos?
Saludos,
Vicente.

**Comment by FGarridoV** [comment]
No creo que exista una herramienta ya que tu decides como son los modulos. Por lo tanto deberas hacer copy/paste en un notebook y separarlo en celdas.

Saludos,
Francisco

**Comment by vtorresg** [comment]
Gracias. En el archivo function_simulator.py importé el codigo principal para crear las funciones pedidas. Al hacer lo mismo en los archivos .ipynb no me reconoce el codigo principal.
¿Cómo lo hago?. Puedo incluir solamente los archivos en .py dado que así me funciona?
Saludos.
