### ISSUE TITLE
A1

### ISSUE THREAD

**Issue by josesh11** [IIC2115/Syllabus#11]
hola, estaba realizando la actividad y me percate, que en el archivo json, una persona con rut 12millones y tanto, tiene como padres a personas con ruts 16millones ...esto es correcto? porque va en contra de la logica...ya que si es...las personas con ruts mas pequeños, serian las mas jovenes(esto relacionado a otra pregunta que viene despues)

aqui un extracto de lo que digo

},
"12928618-1": {
  "nombre": "Justin",
  "apellido": "Carrillo",
  "sexo": "m",
  "rut padre": "16446564-2",
  "rut madre": "14543256-k"
},
 agradecederia la aclaracion, muchas gracias

**Comment by JorgeAndresM** [comment]
Hola! en clases dijeron que no importaba y que había que trabajar normalmente
