### ISSUE TITLE
Exponencial

### ISSUE THREAD

**Issue by gonzaloriveros** [IIC2115/Syllabus#11]
Si la exponencial me indica en cuántos turnos más se genera un viaje, entonces al inicio de la simulación debería almacenar todos los viajes que se generarán a lo largo de la simulación? Es decir, no debo ver en cada turno si se generan viajes, sino que lo conozco de antemano. Estoy en lo correcto?

**Comment by vnramirez** [comment]
Tengo la misma duda.
No tenemos nada de materia de simulación. Si es que en cada turno, cada camino-borde, oficina y hogar pueden decir "voy a generar un viaje en x turnos más", ¿cómo voy guardando esa información?
Por ejemplo, puede que en el turno 0, una oficina determine que va a generar un viaje en 4 turnos más (¿cómo guardo esa información "temporal"?). Luego, en el siguiente turno, puede que la misma oficina decida generar un viaje en 2 turnos más... ¿Cómo voy guardando (y luego utilizando) estas informaciones intertemporales?
Con la materia del capítulo 1 ni idea. He intentado buscar ayuda en internet pero no me han servido/no las he entendido.

**Comment by sidiaz2** [comment]
Tengo el mismo comentario que Vicente. Es posible que nos entreguen material que nos enseñe a hacer simulaciones? Considerando que los contenidos están exclusivamente enfocados en clases. Por otro lado, para próximas tareas creo que sería positivo compartir las asignaciones de puntajes, ya que si no puedo realizar toda la tarea considerando lo acotado del tiempo, me gustaría saber en qué enfocarme.
