### ISSUE TITLE
Como determinar la región más pobre M3

### ISSUE THREAD

**Issue by faaceituno** [IIC2115/Syllabus#110]
Hola, me entro un duda en en M3, cuando hablan de la region mas pobre se debe calcular usando el atributo GNP o GDP?
Y se debe luego sumar en cada pais de una region o queda a nuestra interpretacion?

**Comment by Jamidd** [comment]
Una región es una conjunto de países. Por lo que sea como decidas calcular la "riqueza" de un país, la suma de la "riqueza" de todos los países seria la "riqueza" de la región. 
Saludos,
Jaime

**Comment by sregonesi** [comment]
> Una región es una conjunto de países. Por lo que sea como decidas calcular la "riqueza" de un país, la suma de la "riqueza" de todos los países seria la "riqueza" de la región.
> Saludos,
> Jaime

Y la riqueza es GDP o GNP??

**Comment by pcseisdedos** [comment]
Tal como se aclaró en la lectura del enunciado, ese tipo de cosas las deben decidir ustedes.

Saludos,
Pablo
