### ISSUE TITLE
Duda pregunta 2

### ISSUE THREAD

**Issue by vgrivera** [IIC2115/Syllabus#110]
Hola
Revisando el enunciado del ejercicio II, tengo una duda sobre el recorrido en el tablero.
Cada Ruta recorrida es única? Puedo volver a pasar sobre algún tramo por el que ya pasé anteriormente? 
Gracias

**Comment by kdcarreno** [comment]
Para que pasarías sobre un tramo ya recorrido ? podrías quedarte en un loop.

**Comment by fagomez2** [comment]
Podrías volver a pasar por una ruta si así lo quieres, ya que se te pide una solución válida (cualquiera). El problema es que, tal y como menciona @kdcarreno , podrías quedarte atrapado en un loop. Te recomiendo tener algún método "anti loops" si quieres que tu programa tenga todo el puntaje en el criterio de eficiencia.

**Comment by mblejeune** [comment]
Hola! tengo una duda con respecto a esto mismo, en la lista obtenida de la ruta se puede repetir un mismo punto (x,y) ? o necesariamente yo solo debo pasar una vez por esa posicion? (ya que hice mi problema evitando loops, pero este solo me deja pasar una vez máximo por cada posicion y nosé si eso esté bien)
