### ISSUE TITLE
Duda Pregunta 1

### ISSUE THREAD

**Issue by DanteZM** [IIC2115/Syllabus#111]
Hola!

El enunciado dice que se espera que los problemas "sean resueltos utilizando los conocimientos del capítulo 2 del curso", osea, que no es necesario usar recursión en este problema, cierto? Lo que pasa es que lo resolví sin recursión, pero sí usando distintas estructuras de datos.

Saludos!

**Comment by DanteZM** [comment]
> Hola!
> 
> El enunciado dice que se espera que los problemas "sean resueltos utilizando los conocimientos del capítulo 2 del curso", osea, que no es necesario usar recursión en este problema, cierto? Lo que pasa es que lo resolví sin recursión, pero sí usando distintas estructuras de datos.
> 
> Saludos!

**Comment by DanteZM** [comment]
Hola! 
Otra duda de la misma pregunta: en la parte b sobre minimizar costos, ¿siempre se debe cortar la madera completa? Lo digo por este caso:

Input: 
7
[ (3,3) , (4,9) , (5,10) , (6,17) , (7,17) , (8,20) ]

Técnicamente, la tabla se podría cortar entera obteniendo pedazos de 3 y 4 con un costo de 12, pero también se podría obtener dos pedazos de 3 con un costo de 6 y un sobrante de 1, por lo que la última opción minimiza aún más los costos. 

Gracias!

**Comment by fagomez2** [comment]
Hola! Sobre tu primera pregunta, estará bien mientras cumplas el pedido de **hacer soluciones eficientes, i.e., sin usar fuerza bruta**. Si son estructuras de datos no vistas en clases, te recomiendo poner una pequeña explicación de por qué / para qué te sirve esa EDD en particular. 

Sobre tu segunda pregunta, en el ejemplo que pusiste estarías haciendo tres cortes, dos de 3 y uno de 1. Como en tu lista no se incluyen cortes de dimensión 1, tu respuesta no sería válida.

**Comment by simonerenard** [comment]
@fagomez2 entonces hay criterios distintos si estamos maximizando utilidad o minimizando costo?

Porque en clases dijeron que si para una tabla de largo 13, entregaba más utilidad 2 cortes de 6 y se elimina ese 1 restante, sí es una respuesta válida. Ejemplo de esto:

Input:
13
[ (3,3) , (4,9) , (5,10) , (6,17)  ]

Ahora, con lo que dices en la issue de arriba significa que no se puede usar el mismo criterio para los costos?
