### ISSUE TITLE
Corrección laboratorios

### ISSUE THREAD

**Issue by pelayouc** [IIC2115/Syllabus#111]
Para la corrección de los laboratorios, si no llego a la respuesta final de la misión, pero llevo un paso intermedio y lo explico bien y además explico lo que me falta esto cuenta para algo? o solo se revisa que se llegue a la respuesta final?

Cabe destacar que los comentarios de mi código los pongo en el .ipynb y no en el .py

**Comment by pcseisdedos** [comment]
Eso se evaluará caso a caso en la corrección de los laboratorios.

Saludos,
Pablo 😁👍
