### ISSUE TITLE
Pauta de los laboratorios

### ISSUE THREAD

**Issue by javiolivas** [IIC2115/Syllabus#112]
Profesores, tengo la duda sobre si es posible que se suban las pautas de los laboratorios pasados. Si bien puede ser que para los primeros dos laboratorios es difícil tener una pauta única, para los siguientes que eran problemas más acotados si debiese haber una solución "eficiente" como se pedía. Seria de bastante ayuda tener estas pautas para ver como se resolvían y ver nuestros propios errores para no caer en estos mismos, ya que aún no tenemos las correcciones de los últimos 4 laboratorios.

**Comment by halobel** [comment]
Hola, vamos a hacer todo lo posible por publicar pronto soluciones de algunos de los ejercicios anteriores. En cualquier caso, nuestra idea es que el feedback que acompaña a la nota sirva como pauta, aunque creo que aún nos falta para llegar a eso, además de que por un tema de tiempo, lo hace complejo.

**Comment by antoniacatalina** [comment]
Se hace más difícil aún si la nota que nos suben no acompaña feedback, ojalá los ayudantes se rigieran por alguna pauta más estricta para que todos recibiéramos lo mismo. Es demasiado distinta la manera de corregir y el feedback que se entrega (en mi caso ni siquiera hay).

**Comment by fagomez2** [comment]
@antoniacatalina ¿En qué lab no tienes feedback? Todos deberían tener alguno para cada evaluación, avísanos si no es tu caso para arreglarlo.

**Comment by halobel** [comment]
Hola @antoniacatalina, la pauta para corregir es bastante esctricta en cuanto a puntaje y tópico a evaluar. Dado que son varios ayudantes corrigiendo, siempre existirán diferencias de criterio, sobre todo en los laboratorios 1 y 2 por la temática, pero estas son pequeñas y debiesen tener una influencia muy baja en la nota. Si no es ese tu caso, o si no recibiste feedback, por favor indícanos para corregirlo.

**Comment by pcseisdedos** [comment]
Revisar #125
