### ISSUE TITLE
Problema 2

### ISSUE THREAD

**Issue by kdcarreno** [IIC2115/Syllabus#113]
Cual será el tamaño para probar eficiencia?

O(n^2) cuando se empieza a demorar más de 1 seg ? (aprox)

**Comment by kdcarreno** [comment]
Otra duda , me salió este error

unhashable type: 'list' 

estaba ingresando una lista dentro de una tupla ( [a,b], [c,d] )
después intente tupla dentro de tupla y "convietiendo" mis valores a string con str([a,b])... no entiendo como arreglarlo

**Comment by fagomez2** [comment]
Hola! @halobel o @FGarridoV responderán a tu primera pregunta. 

Con respecto a la segunda, básicamente significa que **no puedes usar como llave de un diccionario ningún objeto que sea mutable**, es decir, que pueda cambiar en el tiempo, como lo son las listas. Como llave puedes usar strings, ints, tuplas o cualquier otro objeto que sea inmutable.

**Comment by halobel** [comment]
Hola, ya actualicé el enunciado de laboratorio con el requisito de eficiencia, es menos de 1s en un mapa de 200x200.
