### ISSUE TITLE
Corrección automática L02

### ISSUE THREAD

**Issue by alejoeyzaguirre** [IIC2115/Syllabus#113]
Hola! 

Quería saber si es necesario que en el archivo .py del L02, debiese tener incorporado en el Problema Löbel Finder, la función que nos entregaron para poder leer el input info_recomendaciones.txt, llamada get_rec_info().  

Me tinca que por incorporarla, tengo un error de formato en mi .py

Saludos y Gracias!

**Comment by FranciscaUlloa** [comment]
Me paso lo mismo!, yo pensaba que si o si tenía que estar

**Comment by pcseisdedos** [comment]
No es necesario tener esa función incorporada, dado que se ocupa para ejecutar su código y en el .py no debe haber ejecuciones. Basta con que el input siga el formato descrito. De cualquier manera, si no dejaron ejecuciones en el código no debieran tener problemas de formato incluso si lo subieron con esa función en el .py. Ahora bien, si ejecutaron la función para leer el archivo `info_recomendaciones.txt` se va a caer y no podrán acceder al puntaje del script.

Espero haber aclarado sus dudas, cualquier comentario o consulta díganme.

Saludos,
Pablo 😁👍

**Comment by alejoeyzaguirre** [comment]
Buenísimo, gracias!
