### ISSUE TITLE
Formulario recorreccion

### ISSUE THREAD

**Issue by bombanex** [IIC2115/Syllabus#114]
Estaba intentando abrir el formulario de recorrección para la segunda tarea pero me aparece que no se puede abrir porque se puede responder solo una vez. Respondí el formulario de la primera tarea, pero el de esta no lo e abierto. Que puede hacer para enviar mi recorreccion?

**Comment by fagomez2** [comment]
Hola! Pregunté a los profesores y me dijeron que ya está arreglado el tema. Confirma por acá que pudiste mandar a recorregir correctamente para cerrar la issue.

**Comment by bombanex** [comment]
Si, ya pude mandar a recorregir. Gracias!
