### ISSUE TITLE
Nota avance

### ISSUE THREAD

**Issue by simonerenard** [IIC2115/Syllabus#115]
Hola! 

A mi no me aparece mi nota de avance del L02, abrí un issue en mi repositorio pero al parecer a los ayudantes no les llegan las issue que uno crea en esa carpeta.

¿Debo contactar a alguien en particular para pedirle que me suba esa nota?

Gracias de antemano.

**Comment by cmujicai** [comment]
Hola,

tampoco tengo nota de avance del Lab 02, que hay que hacer?

**Comment by Jamidd** [comment]
Revisen sus issues.
Jaime Middleton

**Comment by FelipeUlloan** [comment]
yo tampoco la tengo

**Comment by lrosses** [comment]
Yo tampoco

**Comment by halobel** [comment]
Estamos trabajando para corregir este problema, dentro de poco debiesen estar.

**Comment by mzrojas** [comment]
a mi tampoco me aparece!

**Comment by simonerenard** [comment]
Ahí me apareció! Gracias
