### ISSUE TITLE
No se si poner los import o no el archivo .py

### ISSUE THREAD

**Issue by carlos-bertoglio** [IIC2115/Syllabus#116]
Tengo este codigo:
import operator
from test_recomendaciones import get_rec_info

Se pone o no en el archivo.py? porque yo creo que por eso no se importó bien.

**Comment by pcseisdedos** [comment]
Debieras importar todas las librerías que ocupas para resolver tus problemas (solo librerías permitidas). Respecto al get_rec_info, eso va a arrojar un error, porque nosotros no tendremos ese archivo en tu carpeta. Te recomiendo revisar #113.

Saludos,
Pablo 😁👍

**Comment by carlos-bertoglio** [comment]
Sí vi esa issue pero no entendí bien tu respuesta, y ahora lo que entendí es que tengo que borrar esto:
from test_recomendaciones import get_rec_info
entendí bien? 
Muchas gracias
