### ISSUE TITLE
Revisión inputs L02

### ISSUE THREAD

**Issue by FGarridoV** [IIC2115/Syllabus#117]
Estimados,

Para que puedan revisar sus L02 deben hacer los siguientes pasos:

1. Conocer la semilla utilizada:
    - Para cada problema se utilizaron las siguientes semillas:
        - P1a: **1SI** con **S** en [1,2,3] e **I** en [1 a 10]
        - P2a: **2SI** con **S** en [1,2,3] e **I** en [1 a 10]
        - P2b: **3SI** con **S** en [1,2,3] e **I** en [1 a 10]
        - P3a: **4SI** con **S** en [1,2,3] e **I** en [1 a 10]
       
        Cada semilla utiliza S (size) y I (instancia) de acuerdo a los grupos indicados, por ejemplo, La instancia 5 de size 2 en el problema P2b sería: I = 5, S = 2 -> 325

2. Generar el input mediante el código de generador de input de cada problema, indicando la semilla y el tamaño del size utilizado.

3. Determinar la respuesta que genera su código

4. Ingresarla como input en la función de verificación. Si retorna 1 es correcta, si retorna 0 es incorrecta.

**El código pauta (pautase ha subido a la carpeta Pautas/Laboratorios/ScriptL02**

EJEMPLO

```python
import pauta
import L02 #entregable de cada uno de ustedes

semilla = 111 
size = 10

inputEjemplo = pauta.inputs_p2b(semilla, size)
respAlumno = L02.motor_lobel(*inputEjemplo)
ver = pauta.verificar_p2b(respAlumno, inputEjemplo)

# si ver es 1 -> correcta
# si ver es 0 -> incorrecta
```

**Comment by sregonesi** [comment]
Hola Francisco,
Estoy medio perdido con la explicación.

1. Dices
```
Cada semilla utiliza S (size) y I (instancia) de acuerdo a los grupos indicados, por ejemplo, La instancia 5 de size 2 en el problema P2b sería: I = 5, S = 2 -> 325
````
Como llegas al 325? Me perdí con esa formula


2. Por otro lado, intenté probar el código y falta un archivo que no puedo encontrar. Se me cae en
https://github.com/IIC2115/Syllabus/blob/d6098f7ee80c339711b1a31fa543f77fbdaf77b0/Pautas/Laboratorios/ScriptL02/pauta.py#L468
¿Dónde puedo encontrar este archivo?


3. Y por último. ¿Dónde veo el `S` y `l` que utilizaron para corregir mi tarea? Me aparecen números que no están en el rango de lo que dices
(Adjunto mi tabla de la p3a)
![image](https://user-images.githubusercontent.com/69522667/97247612-c62dc900-17de-11eb-8b02-f045160aff43.png)

Gracias!

**Comment by fmundurraga** [comment]
Por favor explicar estoy en la misma situación.
Gracias

**Comment by FGarridoV** [comment]
Lo aclaro a continuación:

1.- Es porque el problema 2b es del estilo 3SI (el tercer problema) el I es 5 (en el ejemplo) y con size del segundo grupo S = 2. Por eso 3SI es 325.

2.- Debes cargar el archivo que esta en la carpeta del Lab2 que contiene los inputs.

3.- Están en orden, el primero es 1, luego 2 y 3. Por eso, solo puede ser 1, 2 o 3.

Saludos,
Francisco
