### ISSUE TITLE
Detener todas las recursiones al encontrar una solución

### ISSUE THREAD

**Issue by niherrera** [IIC2115/Syllabus#117]
Si se realizan múltiples recursiones simultaneamente y una de ellas llega a una solución, la única manera de detener todas las otras recursiones es usando una variable global?

**Comment by Jamidd** [comment]
A que te refieres con simultáneamente?
Estas usando threading?

Jaime Middleton

**Comment by niherrera** [comment]
Me refiero a que en una iteración del problema 2 le digo al programa que haga una recursion con el punto de arriba, una recursion con el punto de abajo, una recursion con el punto de la izquierda y una una recursion con el punto de la derecha.  En una iteración puede que el problema encuentre la solución con la recursion del punto de arriba pero igual va a continuar haciendo las recursiones del resto de los puntos. Como puedo detener todas las otras recursiones sin usar una variable global?

**Comment by Jamidd** [comment]
Las recursiones no se hacen en paralelo. 

Para terminar, es una opción el tener una variable global pero no fan de eso.

Lo que podrías hacer es retornar None o lo que tu decidas que sea conveniente y retornar al tiro en caso de que se reciba. (Estoy asumiendo que estas guardando el path en una variable global)

Otra opción, (si estas retornando el path) es revisar que este (n,n) en la ultima posición del path.

Jaime Middleton
