### ISSUE TITLE
Nota avance

### ISSUE THREAD

**Issue by bombanex** [IIC2115/Syllabus#118]
Me sigue sin aparecer mi nota de avance del lab02. Donde la puedo encontrar?

**Comment by roaastudillo** [comment]
Yo no tengo nota de avance en ninguno de los dos labs :(

**Comment by pcseisdedos** [comment]
Todavía no hemos podido subir las notas parciales, de todas formas puse un comentario en las issues respectivas de sus repositorios privados con su nota parcial
