### ISSUE TITLE
Conteo de valores LAB04

### ISSUE THREAD

**Issue by paulavonbrand** [IIC2115/Syllabus#118]
Hola!! mediante df.describe() puedo obtener que la cantidad de "Revenue" que hay es de **3764** valores, pero al usar df[['Revenue']].value_counts(), me sale que lenght es **3567**, ¿Por qué sucede esto?
PD: se que value.counts() es para datos no numericos y Revenue es numerico, pero no entiendo porque arroja una cantidad distinta de todas formas,

**Comment by FGarridoV** [comment]
Value counts determina la frecuencia de cada valor en la columna, su largo hace referencia a la cantidad de datos diferentes. Y el valor asociado es la frecuencia de cada valor.
