### ISSUE TITLE
Problema 2. Ruta inexistente

### ISSUE THREAD

**Issue by mlirarrazaval** [IIC2115/Syllabus#119]
Hola!
Hay alguna limitación para los valores k que tiene cada celda? Por que de acuerdo a eso, podría pasar que no existiera ruta factible entre el inicio y la meta. Por ejemplo:
[1 2]
[3 4]

Comenzando en el 1, me puedo mover al dos o tres, pero después no tengo a donde moverme (no puedo dar ni 2 ni 3 pasos). La idea ahí es que se den los pasos que se pueda o que retornemos que entonces no hay una ruta factible?

Gracias!

**Comment by FelipeUlloan** [comment]
me sumo a esta pregunta y tomando su ejemplo, podría ser entonces una ruta factible el [(0,0);(0,1);(1,1)] considerando que podría pasar del 2 al 4 y me detendría en 4 pues ya llegué a mi destino aun cuando me sobren pasos?

**Comment by halobel** [comment]
Hola, efectivamente existen mapas sin rutas factibles. En ese caso, deben retornar una lista vacía. Con respecto a la segunda pregunta, la solución sólo debe considerar rutas donde se llegue con la cantidad de pasos justos al final. No es válido que sobren pasos.
