### ISSUE TITLE
Misiones 1 y 2 se hacen para cada año?

### ISSUE THREAD

**Issue by paulavonbrand** [IIC2115/Syllabus#119]
Hola!! Quería preguntar si las primeras misiones debemos hacerlas para cada año o no, por lo que yo entiendo del enunciado si debiese ser así. (Hacer lo que pide M1 y M2 para 2014, 2015, 2016, 2017) Pero siento que sería como demasiado largo el lab, y prácticamente hacer como lo mismo para cada año, por eso me entró la duda de si lo estoy entendiendo como es ono.
Gracias

**Comment by FGarridoV** [comment]
Justamente ese tipo pensamiento buscamos, si crees que es repetitivo hacer algo y no aporta, no lo hagas. De verdad que buscamos que hagan un trabajo libre en ese sentido. Justifica lo hagas, no hay "una pauta clara", sino que son más bien tus argumentos los que cuentan.

**Comment by paulavonbrand** [comment]
Gracias profe!
Para la misión de limpieza y depuración debemos hacerlo con las tablas que contienen las columnas que consideramos relevantes cierto ? no para tooda la tabla supongo jaaj
Y sobre la recorreción del P02, si no me ha llegado nada al repositorio personal es que me "rechazaron la recorreción" o es que aun no esta lista?

**Comment by FGarridoV** [comment]
Si tu crees que es bueno considerar más columnas, puede hacerlo. Como te comentaba, busca siempre apuntar a tu objetivo, si tu consideras que es bueno tomar mas columnas en cuenta, hazlo.

pd. Siempre te va a llegar algo, así que espera a que el bot los envíe.

Saludos
