### ISSUE TITLE
funcion  horarios(bajo,valle.punta)

### ISSUE THREAD

**Issue by agrudsky95** [IIC2115/Syllabus#12]
Hola, en el enunciado dice que la función horarios(bajo,valle,punta), debe cambiar las tasas y correr una simulación para entregar resultados estadísticos.
¿Estoy quiere decir que la función simular_verboso() debe ir dentro de la función horarios?

**Comment by Hernan4444** [comment]
@agrudsky95 no es necesario, simular_verboso() corre la simulación creando print, mientras que hoarios corre la simulación pero guarda estadísticas específicas, pero no realiza print.

**Comment by agrudsky95** [comment]
entonces la funcion horarios contiene todo lo que contiene simular verboso pero sin prints? solo los prints de las estadisticas que se solicitan?

**Comment by Hernan4444** [comment]
precisamente 👍
