### ISSUE TITLE
Problema conexión jupyter notebook

### ISSUE THREAD

**Issue by Isidora-Pemjean** [IIC2115/Syllabus#12]
Hola, estoy teniendo constantemente el problema que jupyter notebook me informa problemas de conexión aunque tenga
 internet, la única forma que se me soluciona es volviéndolo a abrir desde la consola, pero no se me guarda nada. No se cual podría ser mi problema, si es algo del computador o del programa

![Problema conexión jupyter notebook](https://user-images.githubusercontent.com/80857597/112768884-959fc480-8ff4-11eb-86af-82c49b326183.png)

![Problema conexión jupyter notebook 2](https://user-images.githubusercontent.com/80857597/112768928-d39ce880-8ff4-11eb-9780-55d2a659d62b.png)

Esta última foto es de cuando lo vuelvo a cargar

![Problema conexión jupyter notebook 3](https://user-images.githubusercontent.com/80857597/112768955-fa5b1f00-8ff4-11eb-84f2-5606cbef490a.png)

**Comment by pcseisdedos** [comment]
Hola, de casualidad tienes anaconda? A veces genera problemas con instalación de jupyter o con el kernel. Te dejo algunos links que puedes revisar.
1. [Link 1](https://stackoverflow.com/questions/31280465/ipython-notebook-connection-failed-issue)
2. [Link 2](https://github.com/jupyter/notebook/issues/4630)
3. [Link 3](https://github.com/jupyter/notebook/issues/5024)

Saludos,
Pablo 😁👍

**Comment by bf** [comment]
How did you fix this issue?
