### ISSUE TITLE
subir lab

### ISSUE THREAD

**Issue by kdcarreno** [IIC2115/Syllabus#120]
Hola,  estoy tratando de subir mi lab (atrasado) y no me deja .

remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/IIC2115/repositorio-2019-1-kdcarreno.git/'

Hace poco cambié la clave porque la había olvidado. Como subo mi lab ?

**Comment by fagomez2** [comment]
Karla! Recuerdas la nueva clave? O se te olvidó completamente?
Si quieres puedes cambiarla con este link:
          https://help.github.com/en/articles/updating-your-github-access-credentials
De ahí debería estar todo bien. Al momento de hacer git push, deberías poner la nueva clave y subirse sin problemas.

**Comment by kdcarreno** [comment]
Lo logré subir. Nuevo problema...El form de atrasos dice "recurso no disponible"

https://docs.google.com/forms/d/1no0BQIlv5ET1iAvhJAw8lqec1CX-VE6IQz71t4CQyr0/formrestricted?edit_requested=true

**Comment by fagomez2** [comment]
Cuando intento acceder al link desde mi correo uc me deja, pero cuando intento desde otro correo me sale "Recurso no disponible". Prueba cerrando sesión de tus otros correos/abriendo desde otro navegador a ver si resulta

**Comment by fagomez2** [comment]
Estuve leyendo sobre tu primer problema. Para la otra, prueba reiniciar tu consola y luego hacer `git fetch`. Es posible que eso haga que git pida su nueva contraseña (si no, git asume que tu contraseña no ha cambiado y te la guarda automáticamente)

**Comment by kdcarreno** [comment]
ok. Con el correo uc funciona. Qué es el hash y de dónde lo saco?

**Comment by fagomez2** [comment]
En el formulario debería salir un link:
https://git-scm.com/book/en/v2/Git-Basics-Viewing-the-Commit-History
Si en la consola usas `git log`, podrás ver una suerte de "historial de commits", cada uno tiene un autor, una fecha y un hash que funciona como identificador del commit. Eso es lo que te pedimos, de manera de que el ayudante sepa claramente cuál es el commit que quieres que se revise.
