### ISSUE TITLE
Misión 1 L04 

### ISSUE THREAD

**Issue by FernandaNavarroE** [IIC2115/Syllabus#120]
Holaa!! Tengo una duda sobre la misión uno. Uno puede partir analizando un subconjunto de columnas mayores a 10 elegidas bajo algún criterio y luego al final mostrar sólo 10 de estas? o es necesario elegir estas 10 y realizar los análisis de solo estas columnas? 

Espero que se haya entendido, saludos!

**Comment by FGarridoV** [comment]
Eres libre de hacer lo que consideres necesario. Si tienes un plan para explorar más de 10 columnas, adelante!
