### ISSUE TITLE
MISION 2 Resolución de conflicto

### ISSUE THREAD

**Issue by rosariopenalabbe** [IIC2115/Syllabus#121]
Hola! Si a una columna le resuelvo outliers y nulos, eso cuenta como dos resoluciones de conflictos o sólo una por ser una columna?.
Gracias!!

**Comment by clementeramirez** [comment]
Hola! me sumo a la pregunta. para la m2 5 resoluciones de conflictos distintas se refiere a limpiar los (valores por defecto, nulos, incompletos, outliers o posibles inconsistencias) de 5 columnas distintas? o de 5 maneras DISTINTAS? Tambien, que significan los valores por defecto?
muchas gracias

**Comment by emapazvaldes** [comment]
Me sumo :) gracias!!!

**Comment by rosariopenalabbe** [comment]
Hola! a alguien le respondieron esto?

**Comment by paulavonbrand** [comment]
me sumo a la pregunta

**Comment by FGarridoV** [comment]
Se entiende por resolución de conflicto a cómo ustedes van a eliminar, imputar o administrar las columnas de la M2. No es necesario que expliquen columna por columna sino que a modo general entregando algún ejemplo.

Por ejemplo, una resolución de conflicto sería:
"En las columnas X, Y y Z, se propone eliminar las filas que poseen datos nulos por [...] a continuación se presenta como se aplica la resolución de conflicto en la columna X"

De esas, deben ser 5 diferentes (puede ser más de una resolución de conflicto por columna)
