### ISSUE TITLE
M6 y M7

### ISSUE THREAD

**Issue by jlcasanova2** [IIC2115/Syllabus#122]
Para resolver estas misiones, creo las columnas con: ALTER TABLE nombre_tabla ADD COLUMN nombre_nueva_columna TEXT, y luego uso UPDATE para rellenear los valores de la nueva columna con los valores del día, para eso uso un comando de sql llamado substr que separa el tiempo entre la fecha y la hora, pero mi problema es que se pone solo el valor de la primera fecha en todas las filas, ¿Por qué puede suceder eso?

Gracias

**Comment by fagomez2** [comment]
Hola! En teoría lo que haces debería solucionar tu problema. ¿Cuántas consultas en SQL estás haciendo? Puede ser que estés haciendo solo un update y esa información la pones en cada columna

**Comment by mblejeune** [comment]
Hola! tengo una duda con respecto a estas misiones, logré agregar las columnas con los datos pedidos pero se demora el código en efectuarlo, ¿importa que se demore mucho tiempo en resolver? uso un for para updatear cada fila. Gracias!

**Comment by sidiaz2** [comment]
Hola! Tengo el mismo problema que @mblejeune . Por otro lado, después de ocupar el comando UPDATE con executemany, si hago una query dentro de la función me demuestra que se cambiaron los valores para la nueva columna, pero si ejecuto una query fuera de la función no se cambiaron los valores. Alguien sabe por qué puede pasar esto?

Gracias!

**Comment by sidiaz2** [comment]
Me di cuenta que cuando cierro la conexión, se borran los cambios que hice con UPDATE. Alguna idea de por qué puede pasar esto?

**Comment by ardelriog** [comment]
@sidiaz2 quizá no estás haciendo commit?

**Comment by sidiaz2** [comment]
@ardelriog sí era eso! Gracias!
