### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by paulavonbrand** [IIC2115/Syllabus#122]
![image](https://user-images.githubusercontent.com/68405224/97783050-f0331280-1b73-11eb-89b4-728c683db19e.png)
 Hola! me apareció este error cuando corri mi código de nuevo, al principio no me paraecía! ¿Qué debo hacer para arreglarlo?
Gracias!!

**Comment by FGarridoV** [comment]
Ese no es un error, es solo una advertencia de que estas tratando de guardar un valor en un subconjunto de DataFrame. Comúnmente ocurre cuando usas la función `loc[]`
