### ISSUE TITLE
LAB07

### ISSUE THREAD

**Issue by cmujicai** [IIC2115/Syllabus#124]
En el enunciado esta ubicado "instant_speed" antes que "measurement_speed" y en ese orden había creado la tabla. Pero en la base "muy pequeña", por lo menos en los "nombres de las columnas" aparece "measurement_speed" antes que "instant_speed". ¿Que hago? hago mi tabla nuevamente y le hago caso a ese orden, o al orden del enunciado?

**Comment by FGarridoV** [comment]
El orden de las columnas es el de la base de datos (csv)

Saludos,
Francisco
