### ISSUE TITLE
Uso de Python como tal

### ISSUE THREAD

**Issue by jahernandez2** [IIC2115/Syllabus#125]
Tengo una duda con el uso de Python. Hasta que punto podemos usarlo? Por ejemplo, podemos guardar en variables datos de distintos años y en base a eso hacer un Histograma? O eso ya sería dejar de usar pandas?

**Comment by jahernandez2** [comment]
Tengo una duda con el uso de Python. Hasta que punto podemos usarlo? Por ejemplo, podemos guardar en variables datos de distintos años y en base a eso hacer un Histograma? O eso ya sería dejar de usar pandas?

**Comment by FGarridoV** [comment]
Como dice en el enunciado debes utilizar pandas para el análisis de datos y trabajo de DataFrames. Pandas permite y facilita este trabajo, las visualizaciones y construcción de histogramas. Puedes usar python, pero no queremos que uses for ni iteraciones de forma indiscriminada. Por ejemplo, no usar for a nivel de filas pero si a nivel de columnas.
