### ISSUE TITLE
graficar 4 columnas en un mismo gráfico

### ISSUE THREAD

**Issue by paulavonbrand** [IIC2115/Syllabus#126]
Hola!! Puedo graficar por ejemplo la columna Revenue para todos los años en un mismo gráfico? He buscado pero no he pillado nada

**Comment by FGarridoV** [comment]
La opción más directa que se me ocurre es que tus columnas de Revenue estén separadas por año en un nuevo DataFrame (una columna por año) y luego construir el gráfico usando las columnas de Revenue por año.
