### ISSUE TITLE
Recorrecciones

### ISSUE THREAD

**Issue by martinrafols** [IIC2115/Syllabus#126]
Hola quería saber donde se mandaban las recorrecciones (en mi caso quiero mandar a recorregir el lab 02, le mande un mail a un ayudante y no he tenido respuesta y no me quiero quedar fuera del plazo).
Quedo atento a sus comentarios,

**Comment by pcseisdedos** [comment]
El formulario de recorrección del lab 2 es [este](https://forms.gle/56G2QtQiGCXiGeYZ8), se puede mandar a recorregir hasta hoy.
Pablo.
