### ISSUE TITLE
M8

### ISSUE THREAD

**Issue by eljaker** [IIC2115/Syllabus#127]
Porque en esta misión hay dos ejemplos de input?

Según la descripción: "Obtenga todas las emisiones de un día cualquiera para un bus en específico" debiese ser válido solo el primer ejemplo de input o no (el que si incluye una patente)?

**Comment by cmujicai** [comment]
en esta misma pregunta, se espera que retornemos el measurement_id de cada emision o un npumero con el total de emisiones según el caso

**Comment by fagomez2** [comment]
Para la pregunta de @eljaker, lo considero un error del enunciado. Como la consulta es para un día y bus específicos, necesitas ambos datos como input.

**Comment by fagomez2** [comment]
Con respecto a la pregunta de @cmujicai, me inclino a pensar que ambas son correctas (porque estás identificando correctamente las emisiones de un día y bus específicos). Te recomiendo hacer la primera. Si la segunda resultaba ser la opción correcta, solo te faltaría contar los resultados obtenidos. Confirmaré con el profesor si dejamos las dos como opciones correctas o si les pedimos un único formato.

**Comment by cmujicai** [comment]
@fagomez2 Perfecto. Por favor confirmar si es un error de enunciado, gracias

**Comment by FGarridoV** [comment]
@eljaker como se mencionó en clases, era un error de digitación en el enunciado. Si, es válido solo el primero. Ahora lo actualicé en el Syllabus sin el error.

@cmujicai Dado que la pregunta dice: "Obtenga todas las emisiones ..." debes retornar todas las emisiones que cumplan con el criterio. Por consiguiente, retornar los measurement_id es una respuesta válida.
