### ISSUE TITLE
M12 "total de kilómetros-persona"

### ISSUE THREAD

**Issue by arbanados** [IIC2115/Syllabus#128]
¿En la Misión 12  a qué se refiere el enunciado con "determinar el total de kilómetros-persona"? ¿Son dos resultados distintos?

**Comment by FGarridoV** [comment]
No! Si un carro A con 3 personas recorre 2 km y un carro B con 4 personas recorre 1 km. Entonces recorren 3*2+4*1 kilómetros-persona.

**Comment by javiprado** [comment]
Esos kilómetros recorridos, son simplemente la variable distance_kms? o como tengo un rango horario tengo que calcular la distancia que recorrió cada bus en esa hora (osea restar mis distance_kms inicial y final) y con ese dato calcular los kilómetros-persona?

**Comment by FGarridoV** [comment]
dice: "para buses despachados en ese horario"...

**Comment by vnramirez** [comment]
@javiprado debiese ser total_kms, creo...

**Comment by simonerenard** [comment]
¿Puedo crear más columnas en mi base de datos aunque no me lo pida el enunciado con tal de facilitar mi consulta SQL?

**Comment by MaJesusVergara** [comment]
Hola! Este resultado debe estar separado por día? o basta que este separado para cada servicio y sentido?

Saludos y gracias!!

**Comment by mblejeune** [comment]
@FGarridoV Hola, creo que la respuesta no deja claro cual variable usar si total_kms o distance_kms, ya que de por sí al solo leer la misión 12 cuesta mucho entender qué es lo que quieren que se haga, por favor para los laboratorios que vienen podrían expresar mejor lo que se pide o si preguntamos algo responder directamente lo que queremos saber, ya que tomar esta variable mal en este caso, arroja un resultado mal y por lo tanto, la pregunta no estaría correcta. Esto no ocurre solo para esta misión, sino que a mí parecer costó mucho interpretar qué se quería con otras misiones también. Se agradecería por lo tanto una mejor explicación en los próximos laboratorios. 

Muchas gracias!!!

**Comment by arbanados** [comment]
Se me aclaró perfecto el enunciado con el primer comentario y ejemplo. Gracias @FGarridoV !
