### ISSUE TITLE
No Module Named "Seaborn"

### ISSUE THREAD

**Issue by alejoeyzaguirre** [IIC2115/Syllabus#128]
Hola! Si bien ya descargué en mi Terminal la librería **seaborn** (con el comando pip Install seaborn), a la hora de importarla en mi Jupyter Notebook, me arroja un error del tipo:
"No Module named 'Seaborn'". ¿Por qué esta pasando eso? ¿Cómo lo soluciono?

Gracias!

**Comment by pcseisdedos** [comment]
Seguramente tienes varias versiones de python, instalaste seaborn en una y jupyter ejecuta otra, te recomiendo revisar bien eso.

Saludos,
Pablo 😁👍

**Comment by alejoeyzaguirre** [comment]
Perdón mi ignorancia, pero como puedo revisar eso, y si es así solucionarlo?

**Comment by Jamidd** [comment]
Fijate en el Kernel que esta usando Jupyter.
Para saber si tienes varias versiones busca en C:\Program Files (asumo que tienes windows) cuantas carpetas PythonXX tienes.
Saludos, 
Jaime.
