### ISSUE TITLE
Duda fillna() con alguna condición

### ISSUE THREAD

**Issue by Giovinco24** [IIC2115/Syllabus#129]
Hola! como puedo hacer una condición para rellenar los nulos con fillna. A lo que me refiero es que quiero rellenar los valores nulos con un valor solo cuando se cumpla una condición. Por ejemplo, rellenar Variable_x con 1 si la Variable_y es mayor a "Numero_x" y rellenar Variable_x con 3 si la Variable_y es menor a "Numero_x". Eso si, los datos con los que quiero rellenar vienen de una tabla dinamica.

**Comment by Giovinco24** [comment]
estoy haciendolo igual a como lo muetran en el capitulo del curso, pero la funcion fage me esta entregando un data frame, entonces me tira error en el value

**Comment by pelayouc** [comment]
me sumo a la duda

**Comment by Jamidd** [comment]
Una forma simple, pero no estoy seguro que sea la mejor, sería ir recorriendo el dataframe y revisando. O creando mascaras de booleanos de la condición. `df[df[col] > num]`
Saludos, 
Jaime.
