### ISSUE TITLE
Duda M3

### ISSUE THREAD

**Issue by vgrivera** [IIC2115/Syllabus#129]
Hola, 
Tengo una duda de la M3 sobre lo que tiene que retornar. La respuesta debo retornarla en una lista de tuplas? 
Gracias!

**Comment by asnunez1** [comment]
Tengo la misma duda con la M3, y no me queda clara la M3 en general: ¿Cómo se pueden identificar las expediciones que realiza esa patente ('GRHD-15')? y ¿cómo es el output que deberíamos retornar? Gracias!

**Comment by FGarridoV** [comment]
Debes identificarlas como dice la instrucción de la pregunta: "... Identifique las expediciones mediante expedition_id, line_code y direction...". Dejo a su criterio la estructura del retorno.

**Comment by simonerenard** [comment]
¿Pero ese identificar puede ser como cantidad? Ej: 20 expediciones
¿O tiene que decir todos componentes de esa expedición?
