### ISSUE TITLE
Librerías permitidas L1

### ISSUE THREAD

**Issue by JuanVial1997** [IIC2115/Syllabus#13]
Hola, espero que esten muy bien ! Tengo una duda existen librerías prohibidas para la realización del laboratorio ?

**Comment by JuanVial1997** [comment]
LO quiero usar, porque el tiempo de resolución del algoritmo rondea entre los 15 segundo y lo unico que se me ocurre es hacerle un filter con un data frame de pandas y usar drop en la copia de ese data frame (el DataFrame son las rutinas)

**Comment by pcseisdedos** [comment]
No se puede ocupar pandas para eso en este lab.

Saludos,
Pablo 😁👍
