### ISSUE TITLE
Equivalencia operador matemático ^ con **

### ISSUE THREAD

**Issue by manalvarezc** [IIC2115/Syllabus#13]
Estimados:
En python ahora el signo ^ no es equivalente con ** ? Porque por ejemplo al realizar la operación 3^2 me daba como resultado 1.
Gracias

**Comment by pcseisdedos** [comment]
Tal como mencionas, son operadores distintos. Te recomiendo revisar [este link](https://data-flair.training/blogs/python-operator/#:~:text=Python%20operator%20is%20a%20symbol,Python%20Arithmetic%20Operator)

Saludos,
Pablo 😁👍
