### ISSUE TITLE
Posición en matriz del viaje

### ISSUE THREAD

**Issue by mblejeune** [IIC2115/Syllabus#13]
Tengo una duda con respecto a la eleccion de la posición en la matriz que debo utilizar si genero un viaje, por ejemplo, aleatoriamente se me indica que en mi turno 0 debo generar un viaje en una celda camino, a partir de esto mi código reconoce cuales celdas que sean camino de la matriz entregada me sirven para generar un viaje, y de estas celdas que me sirvan, como elijo cual usar? puedo elegir con random en cual celda de camino hago el viaje ? porque puedo tener muchas opciones de celdas caminos para generarlo que me sirven.

Gracias!

**Comment by FGarridoV** [comment]
Todas podrían generar viajes. Por lo tanto debes evaluar todos los posibles sitios que podrían generar viajes.

Saludos,
Francisco

**Comment by mblejeune** [comment]
@FGarridoV No era esa mi pregunta, quizás me expresé mal, yo tengo hecha ya la parte de evaluar los posibles “caminos” (celdas con número respectivo) dentro de la matriz que nos dan, pero antes se debe crear el viaje y que este sea de tipo camino, si en mi turno me sale que debe haber un viaje de tipo camino( así entendí el enunciado, que la probabilidad que da la exponencial es el tiempo(turno) en donde ocurrirá el evento viaje en “camino”), luego debo elegir en cuál celda (hay muchas posibles que cumplen con restricciones) de la matriz hacer el viaje, para elegir la celda ¿puedo realizarlo simplemente con un random? Porque según entendí, la exponencial no se usa para esto, sino para saber en qué “momento” se genera el viaje, no en cuál posición dentro de la matriz

**Comment by FGarridoV** [comment]
Te entendí eso. Revisa el issue #6 (ahi aclaro que son en todos los finales de vias, no solo caminos). Respecto a tu pregunta puntual, es como te digo. Te daré un ejemplo.

"Piensa que en el mapa hay 3 celdas que generan viajes, para cada celda debes determinar cuando van a generar un próxim viaje. Es decir, cada una tiene su propia distribución exponencial." A eso me refiero que debes revisarlas todas. 

Por lo que vi tu entendiste que generas con una exponencial el siguiente viaje y quieres escoger donde generarlo. Eso no es asi.

Saludos,
Francisco
