### ISSUE TITLE
Sobre archivo function_simulator.py

### ISSUE THREAD

**Issue by shiflix** [IIC2115/Syllabus#13]
Hola,

No me queda claro cómo deben ser las funciones, ya que para poder saber información sobre la simulación deberían recibir otro input. Por ejemplo, el caso de capacidad_tren(estaciones) se necesita saber los resultados de la simulación, pero no se puede llamar a la variable global desde esa función

Como se deberían hacer estas funciones para obtener esos datos de la simulación?

Saludos,
Lucas

**Comment by Hernan4444** [comment]
Hola, 

> pero no se puede llamar a la variable global desde esa función

¿Porque dices que no se puede llamar a la variable?

En verdad hay varias formas, una que si tienes el objeto simulación, lo importes (`from simulación import Simulador`) , dentro de la función instancias dicho objeto (`variable_simulacion = Simulador(parametros)` y finalmente lo ejecutes (`variable_simulación.empezar()`) para que se realice la simulación y guarde las estadísticas que deseas.

Sería algo de este estilo:

```python
from simulación import Simulador
def capacidad_tren(estaciones):
    variable_simulacion = Simulador(parametros)
    variables_simulacion.empezar()
    return variable_simulacion.capacidad_tren(estaciones) # el método capacidad_tren busca las estadísticas solicitadas.
```

Otra opción es tener instanciada y ejecutada la simulación fuera de la función, y desde dentro de la función solo solicitar datos. Algo analogo a esto:

```python
datos = [1,2,3,4,5]
def function():
    for elemento in datos:
        print(elemeto)
```

Como vez, no es necesario usar `global` en si, solo estás accediendo a una variable compartida por todas las funciones. En este caso es una lista, pero podría ser un objeto `Simulacion`.

Saludos ✌️
