### ISSUE TITLE
Limites de sensores en lab 01

### ISSUE THREAD

**Issue by sregonesi** [IIC2115/Syllabus#13]
Hola!
Tengo una pregunta.

Hay varios sensores y restricciones que tienen límites. Qué pasa cuando se exceden esos limites?
* Tiro error?
* Llego al limite?
* O no dejo que se ejecute la acción?

Por ejemplo, si al tomate le aplico el método `cosechar(100)`, pero el tomate tenía `n_tomates=60`, que hago?
En este mismo ejemplo, si es antes del medio dia intento cosechar un tomate cherry, que pasaría (error, lo ignoro, o que)

**Comment by FGarridoV** [comment]
Puedes hacer cualquier cosa que consideres "Razonable". Piensa que tienes que convencernos de que lo que vas a programar y que sea "Lógico". Mientras lo justifiques y tenga sentido tu acción, entonces, esta bien :).

En tu caso, cualquiera de las opciones que indicas me parece "razonable" con su debida justificación. Voy a ser bastante insistente en este tipo de respuestas. Uno de nuestros objetivos en el curso es que sean capaces de responder muchas de sus dudas usando criterio. Si lo justifican, vale. Pero piensen que tienen que convencernos..
