### ISSUE TITLE
Misión 6

### ISSUE THREAD

**Issue by FernandaNavarroE** [IIC2115/Syllabus#130]
Hola!! Tengo muchas dudas respecto a la misión 6, incluso ni siquiera entiendo muy bien lo que hay que hacer. ¿Podrían subir algún ejemplo al respecto? Se puede ocupar la librería "statsmodels" para cumplir esta misión? 
cómo se determina las mejores y peores 5 acciones? respecto a qué criterio o indicador? 

Saludos!!

**Comment by Jamidd** [comment]
La idea es que utilices los datos que tienes para ir generando las predicciones para los siguientes años hasta llegar al 2030.
Respecto a la librería, dejalo en no, pero te confirmo mañana. 
Tu debes decidir el criterio, mientras lo justifiques bien no hay problema.
