### ISSUE TITLE
Solución a las misiones desde la 9 en adelante

### ISSUE THREAD

**Issue by vnramirez** [IIC2115/Syllabus#130]
Estimados,

Desde la misión 9 en adelante se nos piden conteos o encontrar el máximo número de emisiones por patente, etc. Es estrictamente necesario usar SÓLO la materia de bases de datos para responder la pregunta?
En otras palabras, puedo hacer una consulta "conveniente" y utilizar el output de la consulta para responder a la misión? O debo hacer una consulta más específica y responder a la misión inmediatamente?

Por ejemplo, para la misión 9: hacer una consulta que me retorne tuplas únicas (patente, linea) y luego hacer una función que vea cuántas veces aparece una patente en distintas líneas.

Saludos y gracias

**Comment by FGarridoV** [comment]
Estimado, 

Como dice el enunciado se debe emplear SQLite para responder directamente las preguntas planteadas. De este modo, se espera que toda la lógica de la respuesta ente dentro de SQL. Python solo puede ser utilizado para definir el método y retornar la respuesta.
