### ISSUE TITLE
ImportError: DLL load failed:

### ISSUE THREAD

**Issue by FranciscaUlloa** [IIC2115/Syllabus#131]
![image](https://user-images.githubusercontent.com/69482269/98170019-0c181a80-1ecc-11eb-8d99-cd6dcca201fd.png)

Hola tengo ese problema y no sé que hacer D:

**Comment by Jamidd** [comment]
Échale un ojo a esto, creo que es problema del disco duro.
https://answers.microsoft.com/en-us/windows/forum/all/not-enough-memory-resources/7af6f731-48b4-4111-ba0e-f14fb55aec77
