### ISSUE TITLE
Duda Misión 11

### ISSUE THREAD

**Issue by DanteZM** [IIC2115/Syllabus#131]
Hola!

En la misión 11, ¿a qué se refiere con "retorne una tabla"?, es decir, ¿debo usar "CREATE TABLE" o es un output como el de las otras misiones previas?

Saludos!

**Comment by FGarridoV** [comment]
es un output como el de las otras misiones previas

saludos

**Comment by DanteZM** [comment]
Gracias! Otra duda, sé que sólo se pueden usar los comandos de sqlite, pero ¿puedo usar comandos de python para mostrar el resultado más amigable?, osea usar un for, para iterar sobre la respuesta final y mostrar un output que sea más fácil de entender?

**Comment by FGarridoV** [comment]
Mientras no estés usando python para resolver la pregunta, no hay problema!
