### ISSUE TITLE
L07 "database is locked"

### ISSUE THREAD

**Issue by aaguzman11** [IIC2115/Syllabus#132]
Hola! quiero agregar una columna en la base de datos, pero me dice que la base de datos está bloqueada.. ¿Cómo podría arreglar eso?

Gracias!

**Comment by pcastrob** [comment]
A mi me pasó y lo solucioné cerrando la conexión previa a la base: connection.close()

**Comment by aaguzman11** [comment]
pero como cerrarías la conexión previa a la base? si la tienes que tener abierta para modificar la tabla?

**Comment by pcastrob** [comment]
Lo que me pasaba a mi es que había quedado abierta de alguna conexión anterior. Si estás segura de que está cerrada quizá la solución sea otra.

**Comment by pcastrob** [comment]
*cerrada antes de abrirla para agregar la nueva columna

**Comment by aaguzman11** [comment]
Pucha si están todas cerradas.. gracias igual!

**Comment by eljaker** [comment]
Me paso lo mismo, prueba reiniciando el kernel, al menos a mi me funcionó!

**Comment by FGarridoV** [comment]
Estimados,

El flujo para que no existan bloqueos debiera ser: 
abrir una conexión -> "hacer algo" -> cerrar la conexión.

Además, como menciona @eljaker los bloqueos se producen porque la conexión de la base de datos se encuentra ocupado por otro servicio. Para eso deben reiniciar el kernel y asegurarse de que el flujo de su código sea como el que indico arriba.
