### ISSUE TITLE
P03

### ISSUE THREAD

**Issue by jahernandez2** [IIC2115/Syllabus#132]
Conversando con varias personas y sobre todo con como corrigieron mi P03, me gustaría comentar algo. 

Sin ánimos de ofender a nadie, creo que se debe tener más meticulosidad y menos arbitrariedad al momento de corregir. Esto no tiene que ver con la nota, ya que para eso existe la re corrección, si no de la forma en la cual se hacen las cosas que nos pasan a llevar como alumnos. 
En mi caso, me señalaron cosas que directamente no estaban en el enunciado y que incluso, pregunté si se podían hacer, llegando a ponerme 0 puntos en esa pregunta. Es por esto que existen los enunciados y las instancias de preguntas, para poder tener claro que se puede hacer y que no. Es muy injusto que uno, luego de preguntar y leer, cuando se supone que ya tienes todo claro de lo que se puede hacer y no, alguien te diga que lo hiciste mal, y te invalidan toda tu pregunta.

Espero que con este mensaje logre mi objetivo de poder ser más apegado a lo establecido, ya que como alumno hago eso y me esperaría lo mismo de todos.

Saludos y espero haber sido claro en que no quiero ofender a nadie, sino de que hagamos las cosas más justamente.

**Comment by jtjara1** [comment]
x2. Quisiera saber aparte el criterio de evaluación, porque literal dijeron, cito mail "Hola Jose,
Tanquilo, en esta actividad no evaluamos correctitud del output con un script, sino la lógica detrás de la consulta. Por lo tanto, puedes acceder al puntaje incluso con un output incorrecto (sale explicado en el enunciado).". En este caso, el ayudante me pone que la idea esta "muy bien", pero un detalle afecta al output esperado y simplemente me pone 1/2 ptos, cuando eso sería algo regular, ya que "muy bien" son palabras mayores. De igual manera comentaré esto mismo en la corrección. 

Espero no haber sonado pesado, pero encuentro que la forma en que me evaluaron fue horrible :)
