### ISSUE TITLE
L04 Columnas relevantes

### ISSUE THREAD

**Issue by Marion-Odette-Solis** [IIC2115/Syllabus#133]
Hola, me di cuenta que siempre que la variación del precio es negativa, la Class es de 0.
Puedo usar la columna de variación de precio como predictor en el modelo para Class? considerando que se deben calcular modelos independientes, nose si puedo usar ese cruce de información.
Gracias!

**Comment by Jamidd** [comment]
No puedes usar ni Price Var ni Class como atributos de un modelo, ya que estos son los valores que debes predecir.
