### ISSUE TITLE
Duda output mision 9

### ISSUE THREAD

**Issue by vdelacarrera** [IIC2115/Syllabus#134]
Hola! Me gustaría saber como es la forma del output de la misión 9. No entiendo muy bien a qué se refiere el enunciado con "Retorne las patentes de los buses asociados a la cantidad de líneas en que se usan".
Hay que retornar simplemente cuáles son las patentes que usan más de una línea o hay que especificar cuantas lineas usa cada patente también?
Agradezco un output tipo

**Comment by fagomez2** [comment]
Hola! Los buses pueden ser usados en varias líneas diferentes. Lo que te pedimos es que escribas los buses que han sido utilizados en más de una línea acompañados de la cantidad de líneas en las que aparece cada bus.

Por ejemplo, si todos los buses han sido usados solo una vez excepto el `ABCDE1` que aparece en las líneas `2,3,4` y el bus `LFODT6` que ha aparecido en las líneas `2,3,4,5,6,7,8`, tu resultado debería ser algo como:

`ABCDE1 - 3`
`LFODT6 - 7`

Como no pedimos un formato para la salida, eres libre de decidir el tuyo mientras se entienda la asociación Patente, Cantidad de líneas. Así, `[(ABCDE1, 3), (LFODT6, 7)]` también sería un output correcto.
