### ISSUE TITLE
P04 - fillna limit

### ISSUE THREAD

**Issue by Marion-Odette-Solis** [IIC2115/Syllabus#135]
Hola, llevo mucho tiempo pegada buscando documentación que me permita rellenar los valores NaN con un limite, de modo que se puedan mantener proporciones, en particular para la categoría sex.
Pero en Stack sale que hay un bug en el 'limit' que lleva casi dos años y aun no se logra solucionar y en realidad nose que otra opción considerar, porque cómo se rellenen los datos tiene una gran parte del puntaje :c

Dejo los links de lo que he revisado:
https://stackoverflow.com/questions/48320345/pandas-dataframe-a-limit-for-fillna-has-not-been-implemented-yet
https://github.com/pandas-dev/pandas/issues/16284
https://github.com/pandas-dev/pandas/pull/4915
https://github.com/pandas-dev/pandas/blob/v1.1.4/pandas/core/frame.py#L4311-L4328

**Comment by FGarridoV** [comment]
Te recomiendo que revises en el syllabus cuando imputamos valores (en el ejemplo de hipotecas). En el ejemplo imputamos los NaN por grupos.
