### ISSUE TITLE
Pregunta función datepart 

### ISSUE THREAD

**Issue by niherrera** [IIC2115/Syllabus#135]
¿Por qué al usar la función Datepart(hour ,dispatch_time) me sale el error no such column: hour, si los elementos del dispatch_time tienen la hora en que sucede?

**Comment by fagomez2** [comment]
Hola! Sugiero que revises bien cómo estás haciendo tu consulta. Te digo esto porque según el comando Datepart de SQL lo que estás haciendo debería funcionar bien. Te mando un link para que pruebes y quizás así encuentres tu error.
https://www.w3schools.com/sql/trysqlserver.asp?filename=trysql_func_sqlserver_datepart
