### ISSUE TITLE
Sobrepasé el límite de espacio de GitHub

### ISSUE THREAD

**Issue by roaastudillo** [IIC2115/Syllabus#136]
Hola,

Tengo un problema. El otro día bajé todas las bases de datos y las guardé en mi carpeta del L07 para ir probando con las distintas instancias. El problema fue que ahora traté de hacer commit de lo que tenía de avancé y olvidé tenía estas bases de datos, y me sale que sobrepasé el límite de capacidad del github. El mayor problema es que lo trato de borrar, y tampoco me deja. Por lo que no puedo subir ni bajar nada a mi repositorio.

Auxilio jaja

Saludos

**Comment by Jamidd** [comment]
Voy a borrar el archivo .db de tu repo y el checkpoint de jupyter. 
Dame 2 min and try again.

Jaime Middleton

**Comment by Jamidd** [comment]
Exactamente que te sale en el error?
El archivo .db no era muy pesado.
Intenta sacar los archivos pesados de la carpeta y hacer push, o mejor aún, agregalos al gitignore.

**Comment by roaastudillo** [comment]
El error que me tira es:

remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
remote: error: Trace: b0a4500c392f3130a0515401bd05bf2b
remote: error: See http://git.io/iEPt8g for more information.
remote: error: File L07/emisiones7d.csv is 149.89 MB; this exceeds GitHub's file size limit of 100.00 MB
remote: error: File L07/emisiones30d.csv is 635.07 MB; this exceeds GitHub's file size limit of 100.00 MB
To https://github.com/IIC2115/repositorio-2019-1-roaastudillo.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://github.com/IIC2115/repositorio-2019-1-roaastudillo.git'

**Comment by Jamidd** [comment]
Lo que está intentando decir ese error es que el archivo "emisiones7d.csv" y "emisiones30d.csv" sobrepasan el limite de tamaño de cada archivo que subes. No puedes subir archivos mas grandes que 100MB, eso no significa que te quedaste sin espacio en github (no estoy seguro si eso es posible).
Sorry por borrarte el archivo, me atonte al hacerlo.
Para solucionar el problema agrega los archivos al gitignore y debería estar todo ok.
Avisame como va.

Jaime Middleton

**Comment by roaastudillo** [comment]
Es que ya los eliminé de mi carpeta.

Pero al parecer, como se llenó el espacio, mi repositorio no terminó el commit anterior, entonces no puede hacer commits nuevos hasta que ese termine, y no termina porque sobrepasó el límite :'(

**Comment by Jamidd** [comment]
Intenta  >>git stash save "archivos muy grandes"
y después hacer hacer git add commit push de nuevo.

Jaime Middleton

**Comment by roaastudillo** [comment]
No me funcionó nada de eso :(

Lo que hice fue borrar todo mi repositorio de mi computador (habiendo guardado mi avance) y hacer git clone desde mi repositorio de internet. (Para que separ por si a alguien más le pasó)

Gracias igual :) 
Perdón por el SPAM gente

**Comment by mzrojas** [comment]
Hola! A mí me pasó lo mismo, porque entré a mi repositorio y me acabo de dar cuenta de que no se subió mi avance parcial del L08 pese a que el cuando lo subí varias veces el lunes en la clase me salía:
Enumerating objects: 11, done.
Counting objects: 100% (11/11), done.
Delta compression using up to 4 threads
Compressing objects: 100% (10/10), done.
Writing objects: 100% (10/10), 28.33 MiB | 1.50 MiB/s, done.
Por lo que asumí que se había subido bien, al parecer, según noté ahora, el error me salió después. 
¿Qué puedo hacer con el avance parcial? ¿Hay alguna forma de mostrar que si lo hice?

Gracias!
