### ISSUE TITLE
prints en .py P04

### ISSUE THREAD

**Issue by paulavonbrand** [IIC2115/Syllabus#137]
Hola!! solo para asegurarme, puedo dejar los prints en el .py para esta actividad??

**Comment by paulavonbrand** [comment]
ayudaaaa

**Comment by pcseisdedos** [comment]
Si, en esta actividad tampoco es relevante si están o no los prints en el .py, yo te recomiendo dejarlos.

Saludos,
Pablo 😁👍

**Comment by paulavonbrand** [comment]
gracias!
