### ISSUE TITLE
Aclaraciones sobre line_id y total_kms

### ISSUE THREAD

**Issue by FGarridoV** [IIC2115/Syllabus#137]
Estimados,

1. Revisando en detalle las bases de datos, el campo **line_id** hace referencia a un servicio, no a un servicio-sentido. Esto quiere decir, que por ejemplo el **C02 ida** y **C02 regreso** tienen el mismo **line_id**. 
De este modo, si han creado una tabla "LINES" que presenta el servicio (sin importar el sentido) pueden usar line_id sin problemas. Por otro lado, si su tabla LINES representa el servicio-sentido, entonces deberán usar los campos "line_code" y "direction" como ID ó  unir los campos, "line_code + direction". Acá pueden usar el operador "||" para unir campos.
Para responder las misiones, pueden considerar que su tabla LINES representa lineas-sentido ó linea. Procuren aclararlo en el readme.

2. El campo total_kms difiere en algunas expediciones para un mismo servicio-sentido. Si modeló total_kms dentro de LINES basta con que use el máximo de los total_kms dentro de las expediciones del servicio sentido. Si lo modela dentro de EXPEDITIONS úselo normalmente.

saludos,
Francisco

**Comment by Mcarriagada** [comment]
Creo que no me queda del todo claro la explicación de la 1. Por ejemplo, si mi llave primaria en la entidad "Lines" es el line_id, no tendría problemas en este caso? Según lo que entiendo, es que si mi llave primaria fuera {line_code, direction} debería unir los campos mediante el operador ||. No estoy seguro de esto último
