### ISSUE TITLE
dudas varias

### ISSUE THREAD

**Issue by kdcarreno** [IIC2115/Syllabus#139]
**duda1.**  ¿como puedo mostrar dos elementos al mismo tiempo?
si hola y mundo son query sql

hola = blabla(SELECT blabla)
mundo = blabla(SELECT blabla)

for (i,j) in (hola, mundo):
 print (i,j)  
## ERROR : too many values to unpack (expected 2)

**duda2:** como puedo llamar a algo guardado en una variable? en qué formato guarda sql ?
cursor.execute("SELECT DISTINCT expedition_id FROM tabla WHERE condición")
ABC = cursor.fetchall()
## ABC se ve [('exp1',), ('exp2',),('exp3',),('exp_bla',)]

ABC es lista, tupla, etc ? cómo puedo revisar cada 'elemento' de ABC ?

**duda3** relacionado a 2
for i in elementos:
        cursor.execute("SELECT  bla FROM tabla WHERE var_id = '{}' " .format(i) )

OperationalError: unrecognized token: "5b60f89f1582e21c48b8b649"

También probé 
for i in elementos:
        cursor.execute("SELECT  bla FROM tabla WHERE var_id = %s " % i )

OperationalError: unrecognized token: "5b60f89f1582e21c48b8b649"

**duda4** relacionado a 2
si quiero llamar a más de un campo como variable siempre repito 
%s y al final de la linea % i, j, k  o es %i %j %k ?

en caso de escribir con llaves '{ }' 
- necesariamente debo poner comilla simple ?
- si escribo más de una llave, las variables van todas juntas en .format (var1, var2, var3) del final o son varios format, tipo .format(var1) . format(var2) etc

**duda5** 
al ingresar como parámetro una patente tenía problemas con el guion '-' , lo solucioné con '{}'
pero vuelvo a tener problemas si la patente la consigo dentro de la función. Por ejemplo,

cursor.execute(SELECT license_plate FROM tabla WHERE condicion)
a=cursor.fetchall()
cursor.execute(SELECT bla FROM tabla WHERE licente_plate='a')

ERROR

----- 
gracias

**Comment by Jamidd** [comment]
Respuestas:
1) estas intentando sacar valores de dos listas distintas, pero python no sabe como manejar eso. Para hacer lo que tu quieres usa for x, y, in zip(hola, mundo):
2) si quieres saber que tipo de dato es una variable puede usar la función type(). type(cursor.fetchall()) -> list 
3) imprime i y ve que te entrega. Me tinca que hay algo raro ahí.
4) si, cuando son strings en tu tipo de dato de la tabla y .format (var1, var2, var3) 
5) fetchall() entrega una lista. 

Jaime Middleton

**Comment by kdcarreno** [comment]
huston, de mi duda 3. Sigo con el mismo error 
" unrecognized token: num_hexadecimal " 

No se me ocurre como hacer lo que quiero **únicamente** en sql. Entonces estoy haciendo una secuencia de instrucciones. Estas son:

SELECT DISTINCT (campo) FROM Tabla WHERE condicion
fetchall --> entrega una lista 
crear lista aux

for exp_i in lista:
SELECT  COUNT (campo) FROM tabla WHERE expedition_id = '{}' " % exp_i )
guardar valor de "count" en lista auxiliar


si hago uso de esas listas auxiliares hay descuento? cuánto?
en caso de no haber descuento (y tambien para saber cómo se hace) como arreglo el error mencionado?

**Comment by fagomez2** [comment]
Karla! Se les pide que hagan las consultas mediante SQLite, por lo que no puedes usar lógica de Python (como listas auxiliares) para responder las misiones. Si ocupas Python como elemento central para hacer la consulta, tendrás cero puntos. Ahora, si lo ocupas para algún detalle menor (como imprimir línea por línea las respuestas o aplicarles algún formato), en eso no habrá problemas.

Sobre el error `OperationalError: unrecognized token`, nunca me había pasado, pero al buscarlo en StackOverflow  salen referencias a un error en el formato de la consulta. Aquí algunos consejos: 

- No usar formateo de strings directamente, hay una sintaxis que involucra el signo `?` para insertar strings. Ver link de referencia: https://stackoverflow.com/questions/31431393/unrecognized-token-in-sqlite-statement
- Si aun así quieres usar formateo de strings para las consultas, cuidado en dónde lo estás usando. Si lo aplicas al cursor obtendrás un error. Ver link de referencia: https://stackoverflow.com/questions/41015330/sqlite3-operationalerror-unrecognized-token
- Algunos strings con caracteres especiales (como espacios, guiones o demás) deben de ir entre comas. Así, `2011-0629T14:14:14Z` probablemente arroje error, pero `'2011-0629T14:14:14Z'` estará bien. Link de referencia: https://stackoverflow.com/questions/39303010/python-sqlite3-unrecognized-token
- Si ocupas `true/false` (valores booleanos), debes cambiarlos a `1/0`
