### ISSUE TITLE
preferencia viaje en oficina

### ISSUE THREAD

**Issue by jlcasanova2** [IIC2115/Syllabus#14]
En el enunciado sale un orden de preferencia para ingresar el viaje generado en una celda Hogar en una celda de vialidad, pero para los viajes generados en Oficina no dice nada. ¿Sigo la misma regla?

Gracias

**Comment by FGarridoV** [comment]
Si, la misma regla

Saludos,
Francisco

**Comment by jlcasanova2** [comment]
Gracias gracias
Jose Luis
