### ISSUE TITLE
Definición de cónyuges (A1)

### ISSUE THREAD

**Issue by Fopazov** [IIC2115/Syllabus#14]
Tengo una pregunta de definición de cónyuge. ¿Se puede asumir que corresponde a la persona sin padres cuyos descendientes **no comparten su apellido**? Si es así, podría instanciar un árbol que me facilitaría la definición de los algoritmos. 
Gracias de antemano

**Comment by RonaldoSosa** [comment]
Hola. Sí, es posible asumir eso perfectamente.
