### ISSUE TITLE
Crear archivo readme.md

### ISSUE THREAD

**Issue by otdelpozo** [IIC2115/Syllabus#14]
Hola ¿Como se crea el archivo readme.md? 
saludos

**Comment by Hernan4444** [comment]
Hola, si tienes un editor de texto como Atom, sublime, Visual Studio Code, pones crear nuevo archivo y al momento de guardar te aseguras que sea con extensión **.md**. 

Otra opción es usar un escritor online como https://stackedit.io/

Saludos ✌️
