### ISSUE TITLE
Problema con los datos de Movie

### ISSUE THREAD

**Issue by nencinav** [IIC2115/Syllabus#14]
Al revisar los datos respectivos a la actividad 1, pude notar que hay autores con nombres como ",", "(",etc. . A modo de ejemplo, adjunto una foto. De igual manera, existe mas de un actor con el mismo nombre ("Harrison Ford"), entonces al ver su primera y su última película, existe una diferencia de 98 años. (Supe que eran diferentes actores porque lo busque en internet, pero tienen exactamente el mismo nombre).
¿Esto es normal, hay que borrar esos casos o cómo se procede?

![Captura de Pantalla 2021-04-05 a la(s) 18 51 21](https://user-images.githubusercontent.com/80851830/113636106-ee4c0e80-963f-11eb-8257-a13447d72789.png)

**Comment by nopaez** [comment]
Encontré exactamente lo mismo, tengo las mismas dudas sobre qué hacer.
Me sumo a la consulta!

**Comment by pcseisdedos** [comment]
En esta oportunidad no es necesario que lo tomen en cuenta, pero es bien visto. Sin embargo, en las siguientes si esperamos que se hagan cargo de este tipo de cosas.

Respecto a la pregunta de si es normal, totalmente. Las bases de datos reales están llenas de errores, así que es importante que se familiaricen con ellas y aprendan a depurarlas.

Saludos,
Pablo 😁👍
