### ISSUE TITLE
crecimiento y decrecimiento lineal que tiene que tener luz exterior invernadero, L01

### ISSUE THREAD

**Issue by FranciscaUlloa** [IIC2115/Syllabus#14]
Hola! no entiendo bien cómo hacer lo del crecimiento y decrecimiento lineal que tiene que tener la luz exterior del invernadero, me podrían dar alguna sugerencia? que busque pero salen códigos en los cuales me tengo que crear una función antes, entonces estoy confundida.
Muchas gracias!

**Comment by FGarridoV** [comment]
A la larga debes construir una función lineal que te permita determinar la luz en función de la hora del día. 
Si sabes que a las 6 am la luz es 0 y a las 12 es 100. Determina a cuánto crece por hora, lo mismo para los demás casos.
