### ISSUE TITLE
M6 L08

### ISSUE THREAD

**Issue by cmujicai** [IIC2115/Syllabus#140]
Para la misión 6, usamos una línea como "C01" o diferenciamos entre "C01 I" y "C01 R" (en ese caso C01 tiene dos lineas)

**Comment by FGarridoV** [comment]
Puedes usar cualquiera de los dos criterios, deja especificado cómo consideras una línea. Lo importante es que seas consistente a lo largo de todo el lab.

Saludos

**Comment by kdcarreno** [comment]
Una duda, dónde tendria que agregar un WHERE para incluir la condición de sum(line_code)>1 ?

si agrego un COUNT dentro del FROM me tira error. y si pongo un WHERE al final (después del GROUP BY) también tira error.

cursor6.execute("SELECT Bus_table.license_plate, COUNT(Recorrido_table.line_id) FROM ((Gps_table INNER JOIN Bus_table ON Gps_table.bus_id = Bus_table.bus_id) INNER JOIN Recorrido_table ON Gps_table.line_id = Recorrido_table.line_id) GROUP BY Bus_table.license_plate ")
