### ISSUE TITLE
p03, no se como unir las df :c PORFA 

### ISSUE THREAD

**Issue by jtjara1** [IIC2115/Syllabus#141]
para la p1, descompuse las tablas según especie, sexo e isla, para rellenar los datos.  Ahora quiero volver a unir mis tablas "verticalmente" para que todas queden como una y no sé como hacerlo :c ayudaaaa.

Ej: tabla 1:           a b
                          0  1

tabla 2:              a  b
                          2  3

unión tabla 1 y 2:
                        a  b
                       0   1
                       2    3
ayudaaaaaaaa

**Comment by pcseisdedos** [comment]
Hola, revisa [esto](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.append.html)

Saludos,
Pablo 😁👍

**Comment by jtjara1** [comment]
GRACIAS!
