### ISSUE TITLE
M1

### ISSUE THREAD

**Issue by kdcarreno** [IIC2115/Syllabus#141]
Acabo de notar que al crear mi tabla lo hice igual que la semana pasada. Entonces tengo muchas celdas repetidas, ya que antes era leer el csv y copiar el valor de la celda N veces.

En google encontre un IF NOT, pero no entiendo en qué parte de la sintaxis iría. ejemplo de google

CREATE TABLE IF NOT EXISTS  articles (
                        id INTEGER PRIMARY KEY,
                        reference VARCHAR(32) NOT NULL,
                        name TEXT NOT NULL, ... )

yo entiendo que ese if not aplica para la tabla. " si no existe la tabla, entonces crear tabla".
Otro comando que he ocupado es DISTINCT, pero eso es en un SELECT. Entonces tampoco aplicaría.

cómo podría usar el IF NOT para los valores ? o alguna otra sugerencia

**Comment by fagomez2** [comment]
Hola! No entiendo bien qué es lo que quieres lograr. ¿Quieres evitar insertar la misma línea del CSV varias veces en tu tabla? ¿O quieres traspasar información desde la tabla **Emisiones** a tus nuevas tablas? 

Para el primer caso, podrías usar funciones de Python para regular que no haya repetición, como `sets` o listas con la información que quieres (en donde con `if` evitas agregar información repetida). Aunque es lo más directo, ten cuidado con esto, porque podría ser muy ineficiente.

Para el segundo caso se me ocurren dos opciones. La primera: en SQL puedes usar `INSERT IGNORE` para hacer lo siguiente:

- Si la fila no existe en la tabla, se inserta normalmente
- Si la fila existe, no pasa nada (SQL normalmente arrojaría un error/advertencia al hacer esto)

Otra opción válida es utilizar `INSERT UPDATE` para hacer lo siguiente:

- Si la fila no existe en la tabla, se inserta normalmente
- Si la fila existe, se aplica `DELETE `sobre el valor inicial y luego un `INSERT `con la nueva información

**Comment by kdcarreno** [comment]
Es que en la mision 2 o 3, donde tengo que decir cuantas filas y columnas hay en mis tablas. Todas tienen la misma cantidad de filas, lo cual me parece sospechoso. Mi conclusión es que estoy insertando cada fila del csv en mi base de datos tipo "copy-paste" y creo que eso es justamente lo que se quiere evitar en este lab.

**Comment by fagomez2** [comment]
Exactamente. Te recomiendo que veas qué es lo que hay en cada una de tus tablas. Si todas tienen la misma cantidad de filas, entonces muy probablemente estés repitiendo información (un tabla con varias filas con información muy similar que podrían ser separadas en varias tablas con menos filas cada una).

Para ilustrar que te podría estar pasando, te doy un ejemplo: imagina que tienes una tabla de series de televisión y actores que actuaron en ella. Te pasan una tabla con la siguiente información:

`NOMBRE_SERIE, AÑO_ESTRENO, DURACIÓN_SERIE, ACTOR`

Y las tres primeras filas son:

`'Game of Thrones Season 8', '2019', '6 míseros capítulos', 'Emilia Clarke'`
`'Game of Thrones Season 8', '2019', '6 míseros capítulos', 'Kit Harrington'`
`'Game of Thrones Season 8', '2019', '6 míseros capítulos', 'Peter Dinklage'`

Si te fijas, no tiene sentido que repitas la información de la serie (nombre, año estreno y duración) para cada actor que quieras poner en tu tabla, por lo que decides separarla en `SERIE` y `ACTOR_SERIE`. La tabla `SERIE` quedará como:

`NOMBRE_SERIE, AÑO_ESTRENO, DURACIÓN_SERIE,`
`'Game of Thrones Season 8', '2019', '6 míseros capítulos'`

En tanto, la tabla `ACTOR_SERIE` quedará:

`NOMBRE_SERIE, ACTOR`
`'Game of Thrones Season 8', 'Emilia Clarke'`
`'Game of Thrones Season 8, 'Kit Harrington'`
`'Game of Thrones Season 8', 'Peter Dinklage'`

Como puedes ver en este pequeño ejemplo, tus nuevas tablas no siempre quedan con la misma cantidad de filas que la tabla original, pero sí conservan la misma información de una forma no redundante. Esto es lo que les pedimos que hagan para la modelación de la tarea.
