### ISSUE TITLE
M12

### ISSUE THREAD

**Issue by cmujicai** [IIC2115/Syllabus#142]
Solo para confirmar, en la misión 12 solo piden CUANTAS expediciones cumplen con lo requerido? Es decir el output es por ejemplo : 20? o es necesario retornar el id_expedition de cada una que cumpla?. Gracias

**Comment by fagomez2** [comment]
Hola! Se pide el número de expediciones (Ejemplo: 25). Si retornas la lista de id's, aunque en teoría está correcto, puede que tengas un pequeño descuento por no respetar el formato del output.
