### ISSUE TITLE
M1. Visualizar tipos y consulta de estadísticos.

### ISSUE THREAD

**Issue by CristobalUrzua** [IIC2115/Syllabus#143]
Hola!

En el apartado M1 nos comentan:" Con los DataFrames ya creados, visualice los tipos de datos y consulte algunos estadísticos generales con los métodos revisados en clases". 

Lo que pasa es que puedo visualizar solo algunos tipos de datos de algunas columnas porque son muchas (Esto con .dtypes). ¿Con eso bastará? ¿O es mejor que visualice específicamente los tipos de datos de las columnas que utilizaré para mi laboratorio completo?

Espero su respuesta,

Gracias.

**Comment by FGarridoV** [comment]
Lo importante es que te sirva a ti la misión, procura entender bien como son los datos, como distribuyen, etc. La idea es que te sirva para el resto de las misiones. Por tanto, eres libre de ser creativo en como mostrar la información solicitada en el enunciado (incluso la cantidad de datos).
