### ISSUE TITLE
L04. Columnas a elegir

### ISSUE THREAD

**Issue by VicenteDelRio** [IIC2115/Syllabus#144]
Hola!
Una vez que elijo mis 10 columnas a partir de estas desarrollo las misiones que vienen a continuación??
O se tiene que ocupar toda la base de datos para el resto de las misiones
(Se que esta sujeto a cada uno pero cual es el camino a seguir)
Gracias

**Comment by faaceituno** [comment]
Tengo la misma duda

**Comment by RodrigoEterovic** [comment]
Tambien

**Comment by FGarridoV** [comment]
La Misión uno es para que ustedes realicen una exploración de sus datos, no necesariamente son las columnas con las que deben trabajar. Para es ese proceso de análisis, luego pueden utilizar todas las columnas si lo consideran apropiado. No se aten por la primera misión.
