### ISSUE TITLE
Función "MAX()"

### ISSUE THREAD

**Issue by IgnacioInfanteRiba** [IIC2115/Syllabus#144]
Se tiene la siguiente situación:

SELECT columna, MAX(elementos) FROM tabla

Si en "tabla" hay varios valores iguales a MAX(elementos), ¿la función MAX() los retorna todos?

**Comment by fagomez2** [comment]
Hola! Hasta donde se las funciones `MIN` y `MAX `retornarán un único máximo. Si lo necesitas, hay formas de retornar todos los elementos de valor máximo en SQL.
