### ISSUE TITLE
Mejores features misión 5

### ISSUE THREAD

**Issue by FernandaNavarroE** [IIC2115/Syllabus#145]
Hola!! Tengo una duda respecto a la elección de las mejores features para predecir la variable de variación de precio. Estas deben ser elegidas probando modelos? Es que me genera duda que donde los modelos que conocemos son seudamente aleatorio respecto a su partida, la métrica o el valor con el que se está comparando va cambiando, a pesar de trabajar con las mismas variables, entonces no me queda claro de qué forma debo determinar cuál de las features será mejor para predecir. 

Saludos!

**Comment by FGarridoV** [comment]
Si, debes estimar modelos para determinar que features son las que mejor predicen la variación del precio.
