### ISSUE TITLE
Cómo hacer return

### ISSUE THREAD

**Issue by mairiondo** [IIC2115/Syllabus#145]
El enunciado dice que la estructura de las preguntas debe ser:
def misión():
       return respuesta

Es obligación que en el return venga la respuesta, o también se puede hacer print(cursor.fetchall ()) para mostrarla?

En el caso de que solo se pueda hacer return, cómo lo hago? Cuando asigno en una variable la consulta, y luego retorno esa variable, me sale <sqlite3.Cursor at 0x1dc96e6a110> en vez del valor.

Saludos

**Comment by cjvergara1** [comment]
Yo creo que sucede porque estás cerrando la conexión y después pones el cursor.fetchall(). Lo que yo hago es guardar el resultado en una variable y después retornar dicha variable.
cursos.execute()
resultado = cursor.fetchall()
connection.close()
return resultado

**Comment by fagomez2** [comment]
Hola! @cjvergara1 te dio una buena forma de solucionar tu problema. Les pedimos que respeten el formato de entrega para facilitar las correcciones. Además, el no hacerlo podría traerles descuentos por formato.

**Comment by mairiondo** [comment]
gracias @cjvergara1 , ahí me funcionó
