### ISSUE TITLE
Consultas sqlite

### ISSUE THREAD

**Issue by josefinabravo** [IIC2115/Syllabus#146]
Hola, tengo duda sobre si para cada misión se debe hacer únicamente una consulta o si se pueden hacer varias.

**Comment by fagomez2** [comment]
Hola! En el enunciado no hay nada especificado acerca del número de consultas SQL por misión, así que puedes usar más de una. Lo que es importante que respetes es que en la lógica de tu respuesta no debes usar Python.

**Comment by aiiglesias** [comment]
A que te refieres con que no se puede usar python?

**Comment by FGarridoV** [comment]
Python solo debe ser intermediario entre tú y la base de datos, es decir, la lógica de la respuesta debe estar en SQLite. Python solo debe usar para mostrar o retornar los resultados.
