### ISSUE TITLE
Consulta M9

### ISSUE THREAD

**Issue by vgrivera** [IIC2115/Syllabus#147]
Hola!
En el enunciado dice "Obtenga la media de kilometros recorridos hasta las 13:30 hrs de buses despachados entre 11 y 13 hrs" . No entiendo la pregunta (especificamente lo de las 13:30) , ya que el campo que estoy usando para responder es dispatch_time

**Comment by arbanados** [comment]
Según lo que entiendo yo del enunciado, no podi hacerlo sólo con dispatch_time. Ya que hay dos condiciones temporales distintas: 
1. kilómetros recorridos hasta las 13:30 (es decir, gps_time menor a 13:30)
2. despachados entre 11 y 13 (es decir, dispatch_time)

**Comment by fagomez2** [comment]
@arbanados está bien. Hay dos condiciones distintas sobre la temporalidad y debes considerar ambas.
