### ISSUE TITLE
Unique constraint failed

### ISSUE THREAD

**Issue by aiiglesias** [IIC2115/Syllabus#148]
Al intentar ingresar los datos a las nuevas tablas me sale "IntegrityError  Unique constraint failed" y no he logrado saber que es ni como se resuelve. Alguna idea?

**Comment by Sabarriga** [comment]
@aiiglesias  Según yo cuando creaste las tablas le debes haber puesto algo así como "PRIMARY KEY" o algo así a alguna de las id de la tabla que te falla. Y seguramente cuando estás ahora intentando agregar nuevas filas de información estás cayendo en alguna redundancia que tú le habías dicho al sistema no existiría por el hecho de ser una PRIMARY KEY. 

En resumen, yo creo que estás definiendo mal una de las siguientes cosas:
1. El ponerle PRIMARY KEY cuando no corresponde
2. Al entregarle los datos a la tabla

Eso, espero que alguien corrobore lo que dije pero por mientras podrías intentar revisando eso

**Comment by fagomez2** [comment]
Hola! Estuve leyendo de ese error y normalmente ocurre cuando violas una restricción de unicidad, es decir, estás intentando agregar datos a la tabla que ya están, pero la tabla tiene una restricción de no repetir esa información. Esto puede pasar, tal y como dijo @Sabarriga, por usar PRIMARY KEY sobre una columna y luego intentar agregarla más de una vez. También podría pasar que usaste UNIQUE sobre una o varias columnas y luego intentaste agregarlas más de una vez.

Link de referencia: https://stackoverflow.com/questions/29037793/sqlite-integrityerror-unique-constraint-failed/29038336
