### ISSUE TITLE
[L08] - M11

### ISSUE THREAD

**Issue by roaastudillo** [IIC2115/Syllabus#149]
Hola! 

Tengo dudas con la misión 11 porque no entiendo bien lo que me piden.
¿Hay que retornar las coordenadas de origen y destino de cada servicio? ¿Se considera como un servicio al line_id?
De ser así, si tengo **n** servicios (distintos line_id), ¿significa que mi output tienen que ser  **2*n elementos** de latitude y longitude?

Gracias :)

**Comment by fagomez2** [comment]
Hola! Debes retornar latitud y longitud de todos los terminales. Si suponemos que todos los servicios tienen diferentes terminales de origen y destino, entonces estás en lo correcto, serían **2*n elementos de latitude y longitude**. Si se repite algún origen y destino, entonces serán menos.
