### ISSUE TITLE
Consulta Misión 3

### ISSUE THREAD

**Issue by nencinav** [IIC2115/Syllabus#15]
Para la misión 3, dice que se deben crear funciones encapsuladas para cada uno de las consultas. ¿Pueden ser métodos en vez de funciones u obligatoriamente hay que crear funciones externas?

**Comment by pcseisdedos** [comment]
En esta oportunidad pueden ser métodos, pero ten cuidado de cumplir el formato en futuras evaluaciones si es que se especifican nombres de funciones o el orden e los parámetros.

Saludos,
Pablo 😁👍

**Comment by mangelesortiz** [comment]
@pcseisdedos sobre tu respuesta me queda una duda. Eso signifca que para la misión 3, el enunciado esperaría que se hiciera con funciones externas a las clases entonces?

> En esta oportunidad pueden ser métodos, pero ten cuidado de cumplir el formato en futuras evaluaciones si es que se especifican nombres de funciones o el orden e los parámetros.
> 
> Saludos,
> Pablo 😁👍

**Comment by pcseisdedos** [comment]
En esta oportunidad pueden ser métodos, pero más adelante utilizaremos scripts de corrección automática, por lo que deberán seguir las instrucciones de formato.

Saludos,
Pablo 😁👍
