### ISSUE TITLE
Importacion de datos desde Google Colab

### ISSUE THREAD

**Issue by mtago1** [IIC2115/Syllabus#15]
Hola! tengo una duda con respecto a la carga del archivo .json en mi codigo. Lo esto haciendo de esta manera:

from google.colab import files
import json
archivo_subido = files.upload()

ya que estoy trabajando desde Google Colab. 
No se si deberia cambiarlo para entregarla, porque pensaba que quiza a los ayudantes no les resultaria correr esas lineas de codigo.

Quedo atenta a su respuesta!
gracias

**Comment by RonaldoSosa** [comment]
Hola. No sería necesario modificarlo.
