### ISSUE TITLE
Llegada de personas

### ISSUE THREAD

**Issue by jiechevarria** [IIC2115/Syllabus#15]
Hola, me surgio una duda: son 10 procesos Poisson (1 por estacion, es decir, a cada estacion llegan personas segun un proceso Poisson) o es un Proceso Poisson general (es decir, se crean personas como proceso Poisson y luego se les asigna una estacion)

**Comment by Hernan4444** [comment]
@jiechevarria se tenía plasmado como un proceso por estación.
