### ISSUE TITLE
Uso librerías externas

### ISSUE THREAD

**Issue by CataWied** [IIC2115/Syllabus#15]
Hola, me gustaría saber si está permitido el uso de librerías externas?
Gracias

**Comment by Jamidd** [comment]
Que clase de librerías?

Jaime Middleton

**Comment by CataWied** [comment]
numpy. (no para la exponencial ni para la uniforme)

**Comment by halobel** [comment]
En general, no hay problema en usar librerías externas, a menos que estas solucionen todo.
En este caso, a pesar de que creo que no es necesario, no veo problema en que uses numpy.

**Comment by FGarridoV** [comment]
En este lab en particular no debes usar nada estocástico de librerías externas

**Comment by CataWied** [comment]
Puedo usar el np.random.choice?

**Comment by FGarridoV** [comment]
No, no se puede usar nada estocastico. Eso lo puedes con comodoro.uniforme().

**Comment by eljaker** [comment]
Creo que se deben poner de acuerdo antes de las tareas para definir eso, yo ya tengo mi codigo con np.random.choice y es muy encima para hacer ese tipo de cambios (no es que sea muy dificil cambiarlo para usara comodoro.uniforme) pero no le veo sentido si la tarea apunta a otra cosa

**Comment by halobel** [comment]
Creo que tienes una confusión @eljaker, nadie prohibió el uso de librerías externas (fíjate bien lo que se dice más arriba en https://github.com/IIC2115/Syllabus/issues/15#issuecomment-475101084).
Ahora, en particular con respecto al uso de funciones estocásticas, en clases mencionamos muchas veces que debían utilizar las funciones de comodoro.py para la generación de números aleatorios, no otra.
