### ISSUE TITLE
L08 - Duda con las relaciones

### ISSUE THREAD

**Issue by aaguzman11** [IIC2115/Syllabus#150]
Hola! Tengo un problema al querer contar filas que cumplan con ciertos requisitos cuando hay que relacionar entre tablas.
¿Está mal contar las filas de una columna cuando estoy separando mi solución por grupos? 
Por ejemplo, si quiero que me retorne la cuenta de alguna columna, y estoy haciendo GROUP BY "algo" (además de las relaciones entre ids como condición)... me debería contar la cantidad de filas que pertenezcan a ese grupo?? porque me esta retornando el total de filas de la tabla asociada a la columna que quiero contar.

No se si se entiende mucho, gracias!

**Comment by fagomez2** [comment]
Está bien la idea que quieres hacer. Si te entiendo bien, quieres contar agrupando por grupos. Por ejemplo, si tienes una lista de personas con diferentes datos y uno de ellos la nacionalidad, la consulta que quieres hacer es equivalente a contar cuántas personas de cada país hay.

De ser así, te sugiero leer más sobre GROUP BY en el siguiente link: https://www.w3schools.com/sql/sql_groupby.asp

**Comment by aaguzman11** [comment]
Si, es que lo que pasa es que el COUNT me está agarrando todas las filas de la columna que le entrego, independiente de si se cumplen o no las condiciones.

Estoy relacionando mis tablas de datos con las relacionales a través de sus IDs en el WHERE, eso está bien? claramente mi problema es que no debo estar relacionando bien las tablas. Muchas gracias

**Comment by FGarridoV** [comment]
Si, lo ideal es relacionar las tablas mediante ids dentro del WHERE. Eso te va a generar una tabla nueva, en ella puedes hacer un SELECT para contar las filas.
