### ISSUE TITLE
[IMPORANTE][PLAZO EXTRA]

### ISSUE THREAD

**Issue by lcoronata** [IIC2115/Syllabus#150]
Quería hacer una solicitud con respecto al plazo extra, entiendo que mucha gente se ha visto complicada con el plazo del laboratorio y no tengo problema alguno con que el cambio (dado que mucha gente respondió la issue anterior) , pero yo personalmente y seguro mucho del resto de alumnos sacrificamos varias cosas con el fin de poder tener listo el lab para hoy y poder empezar bien el nuevo lab desde mañana. Es por esto que quería pedir la posibilidad de que no se aplazara lo que es el nuevo lab, ya que algunos ya estábamos totalmente programados para la actividad y lab entrantes, y este cambio de planes nos perjudica. 

Quiero recalcar que no veo ningún problema en que se de el plazo del L04, pero me gustaría que el resto pudiéramos mantener los plazos normales en lo que es L05 y P05.

**Comment by mfletelier** [comment]
Me pasa lo mismo!  No  tengo problema y entiendo el plazo extra, pero en lo personal me complica  que se corra el L05 una semana más tarde.

**Comment by VicenteScholl** [comment]
Totalmente de acuerdo! Creo que dar la libertad para trabajar desde antes en el L05 nos beneficia a todos

**Comment by FGarridoV** [comment]
Estimados,

Disculpen la demora, lo conversamos con el cuerpo docente y la verdad es complicado organizar el curso si dividimos a la mitad trabajando en laboratorio 4 y a la otra mitad en laboratorio 5. Entendemos que para algunos  las nuevas fechas pueden no ser tan convenientes, sin embargo, seguimos estando dentro del período oficial de clases, por lo que en rigor se pueden hacer evaluaciones. Además, desde un principio fuimos transparentes respecto a la semana de holgura, puesto que anunciamos que la ocuparíamos en caso de ser necesario, en este caso muchos de tus compañeros lo solicitaron y consideramos que lo mejor era hacer uso de esta semana de holgura prevista en el calendario.

Consideramos su propuesta, pero lamentablemente en este caso no vamos a poder acceder a tu solicitud, espero puedan organizarse con sus otras responsabilidades y aprovechar el último capítulo del curso para rendir y aprender de la forma que esperan.
