### ISSUE TITLE
Consulta a tabla original

### ISSUE THREAD

**Issue by MaJesusVergara** [IIC2115/Syllabus#151]
Hola!!

Se puede hacer una consulta a la tabla original de emisiones que contiene todas las columnas solo para "imprimir" los resultados??

Es que para una mision hice varias consultas a las tablas del modelo entidad relacion para fijar la condiciones de lo que piden, pero una vez que quiero llamar a los resultados finales de las distintas tablas no me funciona muy bien el INNER JOIN, pero al realizar una consulta a la tabla original condicionada a las consultas previas ahí sí me funciona.

Saludos y gracias!!!

**Comment by fagomez2** [comment]
Hola! Lamentablemente no está permitido hacer eso, se les pide responder las misiones tres en adelante usando únicamente el nuevo modelo. Si pasaste la información correctamente, las consultas no necesitan ocupar la tabla original.

Quizás el INNER JOIN no sea lo que necesitas para tu respuesta de esa misión en particular. Existen otros tipos de JOIN. Te mando un link donde puedes aprender más de ellos: https://www.w3schools.com/sql/sql_join.asp
