### ISSUE TITLE
Duda  features M5

### ISSUE THREAD

**Issue by joaquinnavarro1** [IIC2115/Syllabus#152]
Tengo una duda respecto de la M5. En esta piden indicar las mejores 10 features, pero mi duda es, ¿estas features deben ser de las columnas que elegí en la M1? y con esto me surge otra duda: ¿Para la M2 en adelante, tengo que usar sólo las 10 columnas que escogí en la M1?

**Comment by FGarridoV** [comment]
No, pueden ser distintas a las de M1. En la primera misión estas explorando los datos. Por ende, también es No a tu segunda pregunta.
