### ISSUE TITLE
L04-->M5

### ISSUE THREAD

**Issue by VicenteDelRio** [IIC2115/Syllabus#153]
Hola
En la M5 solo tenemos que elegir 10 features que a nuestro criterio son las mas relevante a la hora de determinar la variación del precio de una acción (especificando los criterios)

**Comment by VicenteDelRio** [comment]
Y otra pregunta si para la M6 se puede considerar la variables 'Class' para estimar el modelo

**Comment by FGarridoV** [comment]
> Hola
> En la M5 solo tenemos que elegir 10 features que a nuestro criterio son las mas relevante a la hora de determinar la variación del precio de una acción (especificando los criterios)

Claro, debes determinar mediante la estimación de un modelo, cuales son las 10 features que mejor predicen la variación del precio.



> Y otra pregunta si para la M6 se puede considerar la variables 'Class' para estimar el modelo

No
