### ISSUE TITLE
 TypeError: function takes exactly 2 arguments (1 given)

### ISSUE THREAD

**Issue by kdcarreno** [IIC2115/Syllabus#154]
no entiendo de qué reclama.. ayuda?

CREATE TABLE BUS_TABLE ( bus_id TEXT NOT NULL, license_plate TEXT NOT NULL, bus_capacity INT NOT NULL) CONSTRAINT BUS_TABLE_PK PRIMARY KEY (bus_id)    

TypeError: function takes exactly 2 arguments (1 given)

**Comment by kdcarreno** [comment]
@diflores @bamavrakis @pcerdam @fagomez2

**Comment by fagomez2** [comment]
Karla! El error se refiere a que estás utilizando una función que requiere dos argumentos, pero solo le estás pasando uno.

Ejemplo: 
```
def sumar(a, b):
    return a + b

print(sumar(10, 3))  # Bien, imprime 13
print(sumar(10))  # Malo, tira error
```
Sobre la consulta que quieres hacer, no necesitas marcar una PRIMARY KEY  como NOT NULL, eso se hace automáticamente.

Puedes repasar más sobre sintaxis de restricciones y llaves primarias en el siguiente link: https://www.w3schools.com/sql/sql_primarykey.asp

Pd.: @diflores y @pcerdam ya no son ayudantes del curso (que en paz descansen).
