### ISSUE TITLE
función "fage"

### ISSUE THREAD

**Issue by paulavonbrand** [IIC2115/Syllabus#155]
![image](https://user-images.githubusercontent.com/68405224/98720176-34da5d00-236f-11eb-82fd-78402473a772.png)

Hola!! al utilizar la función fage que estaba en la materia de clases, pero adecuandola al problema obviamente, como que elimina datos nulos al correr el código, pero no todos, quedan 44 valores perdidos y si vuelvo a correr la misma línea del código ahí se van todos. Dejo foto de esas lineas!! ¿Por qué pasa esto?
(definí "table más arriba")

**Comment by paulavonbrand** [comment]
ayuda porfii

**Comment by FGarridoV** [comment]
Revisa bien como la adaptaste en tu código. Estas creando sub grupos de Sector y Class. Asegúrate que tu "table" tengo todos esos subgrupos. En el material, al aplicarse los elimina completamente, por lo que sugiero revises bien tus tablas.

**Comment by paulavonbrand** [comment]
Hola profe, gracias por responder. En mi "table" tengo aquellos subgrupos:
table = df14_limpia.pivot_table(values='Revenue', index='Sector' ,columns='Class', aggfunc=np.median)
Por lo que no entiendo :( Me podría explicar un poco más he tratado harto rato de cachar q onda y me pasa lo mismo todo el rato

**Comment by paulavonbrand** [comment]
Gracias profe!! No se donde puede estar el error, ya que hice prácticamente lo mismo que en el material de clases, pero al rellenar los valores perdidos quedan 44 valores nan. adjunto foto de esta parte del código:
![image](https://user-images.githubusercontent.com/68405224/98827524-bd133d80-2415-11eb-81d1-ea6d2922f562.png)

**Comment by paulavonbrand** [comment]
Al final logré que funcionara lo anterior, pero al tratar de hacerlo como para todas las columnas, me tira el sgte error: "value" parameter must be a scalar, dict or Series, but you passed a "DataFrame" a partir de un fillna, lo cual es raro pq en la documentación de pandas dice: "value: scalar, dict, Series, or DataFrame", osea que el value si puede ser un data frame, 
dejo foto de mi código:
*lista14 posee las columnas a las cuales deseo eliminarles los valores perdidos:
![image](https://user-images.githubusercontent.com/68405224/98859803-7dfae180-2441-11eb-9c62-a2bf77de06e8.png)

**Comment by paulavonbrand** [comment]
ayuda

**Comment by FGarridoV** [comment]
Me cuesta seguir tu error, pero intuyo que el problema lo esta generando tu iteración. Yo crearía una copia de df14_limpia para crear el pivot, porque en tu segunda linea la vuelves a modificar para la siguiente iteración. te recomiendo ir haciendo prints para que encuentres el error, sino, puede programar una función apply que haga lo que necesitas.

**Comment by FGarridoV** [comment]
@paulavonbrand Volví a revisar lo que comentaste, y al leer la documentación de fillna(), efectivamente dice que acepta DataFrame, pero que debes especificar la columna que vas a utilizar. De no hacerlo te genera el error que enviaste.
