### ISSUE TITLE
Función de python 

### ISSUE THREAD

**Issue by niherrera** [IIC2115/Syllabus#155]
Si hago una consulta con SQL puedo usar después la función len para saber el largo de esa función?

**Comment by niherrera** [comment]
Perdón es el largo de la respuesta de la consulta

**Comment by fagomez2** [comment]
Hola! Te pedimos que no utilices `len` u otra función de Python para responder las misiones. Si quieres saber la cantidad de elementos, te pueden servir `COUNT `y `GROUP BY` de SQL. Puedes encontrar más información en el siguiente link:
https://www.w3schools.com/sql/sql_count_avg_sum.asp
