### ISSUE TITLE
L04 -> M4 -> Rendimiento modelos

### ISSUE THREAD

**Issue by pelayouc** [IIC2115/Syllabus#157]
Holaa, me quedó una duda con respecto a esta misión. Ya apliqué el proceso de validación a todos los modelos que conozco, ahora debo aplicar testeo a todos estos modelos? o solo al mejor de ellos en cuanto a validación?

**Comment by Jamidd** [comment]
El set de test es solo para saber el rendimiento en un set de datos no vistos antes y es lo que se "publicita". En este caso solo te pedimos que entregues el del mejor modelo.
Saludos, 
Jaime.
