### ISSUE TITLE
near "(": syntax error

### ISSUE THREAD

**Issue by kdcarreno** [IIC2115/Syllabus#158]
No entiendo que parentesis está mal... en ambos casos no funciona 
cursor5.execute("SELECT Bus_table.bus_id FROM Bus_table WHERE (RIGHT(Bus_table.license_plate,1)%2) = 0")

cursor5.execute("SELECT Bus_table.bus_id FROM Bus_table WHERE RIGHT(Bus_table.license_plate,1)%2 = 0")

**Comment by fagomez2** [comment]
Hola! ¿Cuando usas `%` te refieres a la operación módulo/resto de la división? Si es así, la sintaxis correcta en SQL es MOD (número, base) de acuerdo a este link:
https://www.w3schools.com/sql/func_mysql_mod.asp
Así, creo que en lugar de usar `WHERE variable % 2 = 0`, deberías ocupar `WHERE MOD(variable, 2) = 0`. 
EDIT: Sorry por la hora, no servirá para el LAB, pero al menos quedará la respuesta por si a alguien le sirve en un futuro.
