### ISSUE TITLE
L04- Limpieza de datos

### ISSUE THREAD

**Issue by jtjara1** [IIC2115/Syllabus#158]
Hola! quería preguntar lo siguiente sobre las 5 medidas de la p2. Existen diferentes maneras de trabajar con valores extremos, pero yo lo hice eliminando el 3% superior e inferior de la df (Vi en internet que recomendaban eso y en el ejemplo también se trabajaba con financial data). Primero eliminé el 3% superior de los datos, pero al hacer un describe, me di cuenta que el percentil 25 estaba muy alejado del min, por lo que también procedí a eliminar el 3% inferior (son comandos distintos). Mi pregunta es si esto cuenta como 2 medidas por separados o no, ya que primero elimino los valores extremos superiores, pero después me pareció pertinente eliminar los inferiores. Espero que se entienda mi consulta

**Comment by pcseisdedos** [comment]
Yo creo que ambos caen en la categoría de outliers, por lo que no veo mucha diferencia la verdad. De todas formas hay bastantes cosas que puedes arreglar, por lo que las 5 que debes mostrar no creo que sean un problema. Yo te recomiendo contarla como una y elegir otras 4 aparte de esta para mostrar.

Saludos,
Pablo 😁👍
