### ISSUE TITLE
[L04] [M04] [Dimensiones entre datos de entrenamiento y testeo] [inconsistencia de dimensiones] 

### ISSUE THREAD

**Issue by dilanlopeg** [IIC2115/Syllabus#159]
hola, para mi caso en particular, uni los df del 2014 hasta el 2017 en uno solo (llamemoslo union), realice los mismos procesos de limpieza para este nuevo df (union) y el df del 2018. 
el problema es que a la hora de testear los datos y comparar la predicción de de union con el y_test del 2018 me arroja error de inconsistencia en el numero de muestras.
que puedo hacer para solucionar esto? hay algun comando que solucione este problema?

**Comment by pcseisdedos** [comment]
Hola Dilan, creo que estás un poco confundido, naturalmente no tiene mucho sentido comparar la predicción sobre una base de datos con los resultados esperados de otra, lo que debes hacer es ocupar tu modelo (luego de entrenar y validar con los datos de 2014 a 2017) sobre los datos de 2018 y luego comparar esa predicción con el dato real correspondiente. Es decir, debes entrenar y validar con los datos de 2014 a 2017 y luego testear con los de 2018.

Saludos,
Pablo 😁👍
