### ISSUE TITLE
P2: Ninjas 

### ISSUE THREAD

**Issue by javieracatalan** [IIC2115/Syllabus#16]
Hola! Una consulta, en el caso borde de estar en un escalón en un lado (por ejemplo lado IZQ), y que justo arriba se pueda subir porque el escalón está bueno y que al saltar hacia el otro lado el escalón también esté bueno, en ese caso qué elección se debe priorizar? Porque ambos movimientos serían válidos, o se debe entender como que el Ninja salta hacia al otro lado solo en caso de que el no pueda subir hacia arriba? 

Gracias!

**Comment by pcseisdedos** [comment]
Esa es una forma de resolverlo, pero en general probar todas las posibles combinaciones no es un enfoque eficiente.

Saludos,
Pablo 😁👍
