### ISSUE TITLE
Múltiples cónyuges

### ISSUE THREAD

**Issue by memadrid** [IIC2115/Syllabus#16]
Hola, quería saber si es posible que una persona tenga hijos con cónyuges distintos en el modelamiento de este problema. 
Gracias.

**Comment by fagomez2** [comment]
Michelle! Dejaremos eso a criterio de cada pareja. En todo caso, este punto no debería cambiar mucho la forma en que modeles el problema

**Comment by memadrid** [comment]
Gracias :) otra consulta, para el requisito cantidad de personas por generación, ¿los cónyuges se cuentan como parte de la generación de esa familia? ¿y este requisito se aplica a todos los árboles existentes en el momento, o se especificará para que familia se debe utilizar?

**Comment by fagomez2** [comment]
@fnquinteros  respondió esto en la issue #17
