### ISSUE TITLE
Uso del orden de las peliculas

### ISSUE THREAD

**Issue by TomasFuenzalida** [IIC2115/Syllabus#16]
Hola, tengo una duda sobre los años a utilizar. Al cargar los datos, se cargan en una lista y me di cuenta que las películas están ordenadas por año. ¿Podemos utilizar ese orden para definir la primera película en que aparece un actor y luego ir solo cambiando la ultima película en la que aparece ese mismo actor?
Pregunto lo anterior para no estar revisando 2 fechas a la hora de actualizar el primer y ultimo año en que aparece el actor (punto 3 de la misión 3)

**Comment by pcseisdedos** [comment]
No puedes asumir que las películas están ordenadas por año.

Saludos,
Pablo 😁👍
