### ISSUE TITLE
Descendiente más lejano

### ISSUE THREAD

**Issue by Fopazov** [IIC2115/Syllabus#16]
¿Basta con que se entregue el nombre de uno de los descendientes más lejanos, o tienen que ser todos los más lejanos? (se puede dar el caso en que haya varios)

**Comment by jorgee02** [comment]
Hola! Tengo la misma pregunta

**Comment by RonaldoSosa** [comment]
Hola. Bastaría con mostrar solo uno, pero deberían indicar que solo mostraran uno, en caso de haber más.

**Comment by Josefinafp** [comment]
Descendiente es siempre menor, pero está raro el enunciado, ya que dice "entendiéndose por más lejano como la persona que se encuentra a la mayor distancia de parentesco directo.". En ese caso consideraría también a los ascendentes de esta persona o no?
Si yo soy la menor y en la EDD está hasta mi bisabuelo, como no tengo descendencia no retorno a nadie?

**Comment by RonaldoSosa** [comment]
Hola. Recuerda que por descendiente por definición se refiere a los hijos, nietos y asi en adelante; lo otro que mencionas se referiría a un ancestro. Cuando se dice "entendiéndose por más lejano como la persona que se encuentra a la mayor distancia de parentesco directo", se refiere a como deben interpretar la expresión "más lejano". Respecto a lo último, si eres la menor y no tienes descendencia no deberías de retornar a ninguna persona pero deberías señalar esta situación, por ejemplo, imprimir algo como "La persona de rut 12345678-9 no tiene descendientes".
