### ISSUE TITLE
Generación y conteo de viajes

### ISSUE THREAD

**Issue by niherrera** [IIC2115/Syllabus#16]
Cuando se genera un viaje por ejemplo en un hogar, debo posicionar y contabilizar ese viaje en la celda del hogar y en el siguiente turno moverlo a la vialidad o debo posicionarlo y contabilizarlo en la vialidad inmediatamente?

**Comment by Jamidd** [comment]
Debes posicionarlo en la vialidad inmediatamente. Si se generara en un hogar podrías posicionarlos ahí, pero que harías en caso de que se genere en uno de los bordes del mapa? 
En todo caso, con este tipo de preguntas puedes decidir tu lo que consideres mas lógico y dejarlo explicitado en el README.  

Jaime Middleton
