### ISSUE TITLE
Avance Parcial Semana 10

### ISSUE THREAD

**Issue by isalvador95** [IIC2115/Syllabus#161]
Estimad@s, ayer no pude asistir a la clase y no me queda claro, por el nuevo sistema de avance parcial, si debo llegar a la clase de la próxima semana con la misión 7 realizada y sacar la 8, 9 y 10 en clases o podría llegar eventualmente con la 10 lista. Muchas gracias desde ya.

**Comment by FGarridoV** [comment]
Podrías llegar eventualmente con todo el lab si quieres. Lo que dice el avance parcial es una estimación en base a la cantidad de trabajo.

**Comment by CataWied** [comment]
Tengo una duda de la ponderación de esta segunda entrega parcial. Si, en los laboratorios anteriores la entrega parcial es el 30%, cada entrega parcial queda con 15% y 15%? O aumentó la ponderación de la entrega parcial al ser dos semanas.
