### ISSUE TITLE
Limpieza y depuración

### ISSUE THREAD

**Issue by paulavonbrand** [IIC2115/Syllabus#161]
Hola ! tengo entendido de que en la M2 solo debemos limpiar y depurar haciendo 5 resoluciones de conflicto. Pero es necesario limpiar toooooda la base??, es decir, eliminar TODOS los nan q existan en ella, para luego poder entrenar el modelo? Tenía entendido que sí, ya que le pregunte al profe, pero varios compañeros me han dicho que no es así y estoy bien complicada

**Comment by FGarridoV** [comment]
Lo importante es que dejes la base limpia para tu trabajo posterior. En particular para la misión, te pedimos 5 ideas diferentes y bien aplicadas a las columnas para limpiarlas. Pero para el trabajo y que te funcione bien el resto, debes limpiar todo lo que tu necesites que este limpio.

**Comment by paulavonbrand** [comment]
Oka gracias!! todo lo que necesito que este limpio == toda la base??

**Comment by pcseisdedos** [comment]
Depende si ocupas o no todas las columnas.

Saludos,
Pablo 😁👍
