### ISSUE TITLE
Duda M6 y M7

### ISSUE THREAD

**Issue by Mcarriagada** [IIC2115/Syllabus#162]
Hola, no me queda claro en la M6 de que la fecha-hora despacho es desde el minuto 0 (prácticamente, no se en que influye esto a la hora de programar). Tampoco entiendo por qué en la M7 al principio se pide determinar las variaciones de velocidad en la trayectoria de un bus, pero lo que se explica después según yo no tiene relación con eso, y de hecho, en el output esperado no se pide esto.

**Comment by FGarridoV** [comment]
En la M6, se espera una gráfica de la trayectoria en km vs min. Para esto, considera la hora del despacho como el minuto 0. Es decir, si el despacho fuera a las 12-03-2019 23:44 y una primera medición el 12-03-2019 23:54, entonces, en el eje de los minutos sería:

| Datetime  | Minuto |
| ------------- | ------------- |
| 12-03-2019 23:44  | 0  |
| 12-03-2019 23:54 | 10 |

PD. En esta pregunta el bonus vale 0.5 pts.

En la M7, se refiere a determinar las variaciones de la velocidad respecto a un un bus que recorre a velocidad constante igual a la media de la velocidad del servicio. El grafico con la trayectoria real y la trayectoria a velocidad constante es lo que se pide.
