### ISSUE TITLE
L04 Visualización de datos

### ISSUE THREAD

**Issue by jtjara1** [IIC2115/Syllabus#162]
Hola, en la misión 3 me piden visualizar distintos datos y relacionarlos. Debe haber alguna cantidad mínima de variables por grafico? porque en mis gráficos solo estoy relacionando 2. En segundo lugar, quiero preguntar si la visualización de datos debe ser por año o puede ser cualquiera, mientras tenga su respectivo análisis? Esto lo pregunto porque yo estoy trabajando con mis df separadas por año, por lo que si quisiera visualizar todos los años, tendría que hacer un copy paste para cada año. 
Espero que se hayan entendido las preguntas.

**Comment by jtjara1** [comment]
Agradecería que me respondieran porque durante el fin de semana no se puede preguntar :c

**Comment by pcseisdedos** [comment]
Hola, la idea es que la visualización sea útil para el trabajo que están haciendo, si crees que es útil agregar varias variables por gráfico o separar por año puedes hacerlo.

Saludos,
Pablo 😁👍
