### ISSUE TITLE
M7

### ISSUE THREAD

**Issue by vgrivera** [IIC2115/Syllabus#163]
Hola 

En la M7 tengo que llamar a la M6? si es así se graficaría el de la M6 (en la M7) y por tanto tendría que agregar un input para que se grafique o no la curva? 
Mi duda es: En la M7 tengo que llamar a la M6? o a la M5 y volver a obtener los tiempos en minutos y las distancias, nuevamente?

Gracias!

**Comment by FGarridoV** [comment]
La idea es que si pudes usar métodos de otras misiones, los uses. Si los haces lo suficientemente genéricos puedes facilitarte el trabajo en misiones posteriores.

En particular, en la misión 7 te pido dos curvas y una de ellas es la que resulta de la misión 6.

Saludos,
Francisco

**Comment by arielczerny** [comment]
@FGarridoV si es que no me acomoda mucho llamar a la misión anterior, puedo hacerlas independientes?

Saludos!
