### ISSUE TITLE
Input M5

### ISSUE THREAD

**Issue by Sbaicardi** [IIC2115/Syllabus#165]
Hola! No me queda claro qué representa el número de la expedición que se recibe de input, no entiendo a qué se refiere con "número de expedición desde la primera presente en los datos para ese servicio sentido".

Gracias!

**Comment by cmujicai** [comment]
En esta misma pregunta, el nuevo "dataframe" creado tiene que tener SOLO la columna de emisiones gps para ese filtro dado ó tiene que contener todas las columnas originales (obviamente que sus filas cumplan con el filtro)??

**Comment by asnunez1** [comment]
Hola! tengo la misma duda que @Sbaicardi. Por favor si pudieran aclarar que tipo de input esperan con 'número de la expedición' (desde la primera en los datos)? cual sería un ejemplo de ese input ?

**Comment by isabelladahdal** [comment]
Hola! tengo la misma duda

**Comment by FGarridoV** [comment]
El filtro debe realizarse por line_code, direction y número de expedición.

número de expedición: Considera todas las expediciones de un servicio sentido. La expedición N será la n-ésima expedición desde la primera que se tenga registro (para ese servicio sentido).

------
Los que entendieron que era "expedition_id", no está incorrecto, solo les falta determinar una parte:

Su actual función es:
```
def misionActual(line_code, direction, expedition id):
      # Su código
```

Lo que deben hacer es:
```
def mision6(line_code, direction, n):
     # método que determine el expedition_id de la n-ésima expedicion
     # Luego usan su función con la exp_id que determinaron
     misionActual(line_code, direction, expedition id)
```
