### ISSUE TITLE
Error al instalar pyrematch

### ISSUE THREAD

**Issue by FranciscaSepulveda** [IIC2115/Syllabus#165]
Al instalar me sale esto
![image](https://user-images.githubusercontent.com/69482467/99420869-7ffaef80-28dc-11eb-82db-f9a5f7b9aaed.png)
Al importar me sale esto
![image](https://user-images.githubusercontent.com/69482467/99420362-e2072500-28db-11eb-9b33-7298461b4797.png)

Hola. Ya instalé en mi ordenador geopandas, osmnx, networkx y las librerías relacionadas a webscrapping. Sin embargo, al momento de instalar al librería de pyrematch e importarla me sale el siguiente error ImportError: DLL load failed: No se puede encontrar el módulo especificado. He buscado en la web y no logro encontrar algo relacionado a solucionar este problema al importar esta librería.

**Comment by pcseisdedos** [comment]
Hola Francisca,
Puedes darnos más detalles sobre el problema? qué sistema operativo tienes? tienes más de una versión de python en el computador?

Saludos,
Pablo 😁👍

**Comment by FranciscaSepulveda** [comment]
En primer lugar puse en la consola de jupyter !pip install pyrematch. Luego me arrojo lo que esta en la primera imagen. Luego hice import pyrematch as re y me arroja el error de la segunda imagen. Entonces no puedo importar el modulo en mi computador.

Tengo en mi computador instalado python 3.7.3 (no tengo ni pycharm, anaconda ni otra versión instalada). Mi notebook tiene sistema operativo de 64 bits.

**Comment by FranciscaSepulveda** [comment]
Aún no lo soluciono :(

**Comment by FGarridoV** [comment]
Vamos a ver con los desarrolladores de la librería y te comentamos.

**Comment by nicovsj** [comment]
Hola @FranciscaSepulveda, 

Soy uno de los desarrolladores de la librería pyrematch. Estamos mirando actualmente este problema para dar una solución general quizás en una versión actualizada. Dicho eso, te quiero pedir que por favor ejecutes lo siguiente desde la consola de jupyter y nos entregues el output:
 
```python
from distutils.util import get_platform
import site
import os.path
import re

print("Platform:", get_platform())
libpaths = site.getsitepackages()
libpaths.append(site.USER_SITE)
for libpath in libpaths:
    print("Search in:", libpath)
    for dirpath, dirnames, filenames in os.walk(os.path.join(libpath)):
        if(re.search("pyrematch", dirpath)):
            print("Found dirname:", dirpath)
            print(*dirnames, sep='\n')
            print(*filenames, sep='\n')

```
Quedo atento a tu respuesta.
Saludos!

**Comment by FernandaNavarroE** [comment]
Hola!! tuve el mismo problema que la compañera de más arriba, y mi computador tiene la misma características, a diferencia que mi python es la versión 3.7.8.
Ejecuté el código que entregaron y me entregó el siguiente output:
Platform: win-amd64
Search in: C:\Program Files\Python37
Search in: C:\Program Files\Python37\lib\site-packages
Search in: C:\Users\ferbe\AppData\Roaming\Python\Python37\site-packages
Found dirname: C:\Users\ferbe\AppData\Roaming\Python\Python37\site-packages\pyrematch
__pycache__
rematch.py
rematchlib.py
simple-test.py
test_basic_operation.py
_rematch.pyd
__init__.py
Found dirname: C:\Users\ferbe\AppData\Roaming\Python\Python37\site-packages\pyrematch\__pycache__

rematch.cpython-37.pyc
rematchlib.cpython-37.pyc
simple-test.cpython-37.pyc
test_basic_operation.cpython-37.pyc
__init__.cpython-37.pyc
Found dirname: C:\Users\ferbe\AppData\Roaming\Python\Python37\site-packages\pyrematch-0.1.3.dist-info

INSTALLER
METADATA
RECORD
top_level.txt
WHEEL

Saludos!!

**Comment by nicovsj** [comment]
Hola @FernandaNavarroE, muchas gracias por la información. El problema lo estamos investigando, sin embargo por mientras puedes intentar arreglarlo si con un explorador de archivos accedes a 

`C:\Users\ferbe\AppData\Roaming\Python\Python37\site-packages\pyrematch`

Y cambias el nombre del archivo de `rematch.pyd` a `_rematch.pyd`. Me parece que ese es el problema.

Mil disculpas por el bug. Somos nuevos dando soporte a varios sistemas operativos y este tipo de cosas puede ocurrir en algunas plataformas. Cuando quede arreglado el error en una versión nueva daremos aviso.

**Comment by FranciscaSepulveda** [comment]
Hola, despúes de intentar diversas formas de solucionar mi problema, opte por borrar python y todo lo relacionado a este. Posterior a eso, volvi a instalarlo y me corrió la librería pyrematch. La verdad que desconozco porque al inicio me arrojaba el problema mencionado más arriba, pero finalmente me resultó. Así que les agradezco su ayuda.

**Comment by Ferandadiaz** [comment]
Hola, a mi también me aparece ese error al importar y al ejecutar el código dado me entrega esto:
Platform: win-amd64
Search in: C:\ProgramData\Anaconda3
Found dirname: C:\ProgramData\Anaconda3\Lib\site-packages\pyrematch
__pycache__
rematch.py
rematchlib.py
simple-test.py
test_basic_operation.py
_rematch.pyd
__init__.py
Found dirname: C:\ProgramData\Anaconda3\Lib\site-packages\pyrematch\__pycache__

rematch.cpython-38.pyc
rematchlib.cpython-38.pyc
simple-test.cpython-38.pyc
test_basic_operation.cpython-38.pyc
__init__.cpython-38.pyc
Found dirname: C:\ProgramData\Anaconda3\Lib\site-packages\pyrematch-0.1.3.dist-info

INSTALLER
METADATA
RECORD
top_level.txt
WHEEL
Search in: C:\ProgramData\Anaconda3\lib\site-packages
Found dirname: C:\ProgramData\Anaconda3\lib\site-packages\pyrematch
__pycache__
rematch.py
rematchlib.py
simple-test.py
test_basic_operation.py
_rematch.pyd
__init__.py
Found dirname: C:\ProgramData\Anaconda3\lib\site-packages\pyrematch\__pycache__

rematch.cpython-38.pyc
rematchlib.cpython-38.pyc
simple-test.cpython-38.pyc
test_basic_operation.cpython-38.pyc
__init__.cpython-38.pyc
Found dirname: C:\ProgramData\Anaconda3\lib\site-packages\pyrematch-0.1.3.dist-info

INSTALLER
METADATA
RECORD
top_level.txt
WHEEL
Search in: C:\Users\feris\AppData\Roaming\Python\Python38\site-packages

**Comment by nicovsj** [comment]
Hola @Ferandadiaz, al parecer es el mismo problema que tenía @FernandaNavarroE. He tenido problemas para solucionarlo dado que no he podido reproducir el error en mi computador con Windows. Me serviría mucho si (en tu caso) accedes con un explorador de archivos a:

`C:\ProgramData\Anaconda3\Lib\site-packages\pyrematch`

y a 

`C:\ProgramData\Anaconda3\lib\site-packages\pyrematch`. 

Y en ambos directorios, cambias el nombre del archivo `rematch.pyd` a `_rematch.pyd`. Si se te soluciona (o si no) me comentas por acá por favor.

Gracias!

**Comment by FernandaNavarroE** [comment]
Holaa, yo denuevo!! Hice el cambio de nombre en el explorador de archivos y me sale el siguiente error al intentar importar la librería:

ImportError: cannot import name 'rematch' from 'pyrematch' (C:\Users\ferbe\AppData\Roaming\Python\Python37\site-packages\pyrematch\__init__.py)

Agradecería que me ayuden para poder avanzar con mi tarea!
Saludos!

**Comment by pcseisdedos** [comment]
@FernandaNavarroE puedes ocupar colab para seguir avanzando mientras los desarrolladores encuentran la solución al problema. Para instalar la librería en colab basta ejecutar `!pip install pyrematch`

Saludos,
Pablo 😁👍
