### ISSUE TITLE
Sugerencia

### ISSUE THREAD

**Issue by kdcarreno** [IIC2115/Syllabus#166]
Profesores, 

Para futuros cursos podrían considerar no hacer preguntas/misiones que dependan de la anterior. En este lab M6 y M7 dependen de M5 y considero que no mide si realmente se usar la librería o la lógica de saber cómo hacerlo.

slds

**Comment by halobel** [comment]
Hola @kdcarreno , gracias por la sugerencia. Lo tendremos en consideración.
Saludos

**Comment by arielczerny** [comment]
@halobel podríamos hacer las misiones independientes si así nos acomoda más?
