### ISSUE TITLE
Error para instalar geopandas en mac

### ISSUE THREAD

**Issue by Giovinco24** [IIC2115/Syllabus#167]
Hola! Estaba instalando geo pnadas y todas los paquetes necesarios y no me tiraba ningun error, pero cuando hice lo del video de meterme  python desde el terminal e importar pandas me tiraba error. Despues puse pip3 unistall pandas y lo trate de instalar denuevo y me tira este error.

Giovanni@Air-de-Giovanni ~ % pip3 uninstall geopandas
Found existing installation: geopandas 0.8.1
Uninstalling geopandas-0.8.1:
  Would remove:
    /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/geopandas-0.8.1.dist-info/*
    /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/geopandas/*
Proceed (y/n)? y
  Successfully uninstalled geopandas-0.8.1
Giovanni@Air-de-Giovanni ~ % pip3 install geopandas
Collecting geopandas
  Using cached geopandas-0.8.1-py2.py3-none-any.whl (962 kB)
Requirement already satisfied: shapely in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from geopandas) (1.7.1)
Requirement already satisfied: pandas>=0.23.0 in /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages (from geopandas) (1.1.4)
ERROR: Package 'pandas' requires a different Python: 3.6.0 not in '>=3.6.1'

**Comment by FGarridoV** [comment]
Al parecer es un problema con pandas, no con geopandas. Como pandas no funciona, entonces geopandas no se puede instalar. Veo que es un problema de compatibilidad de librerías con tu versión de python. Quizás sea bueno que actualices python a la versión 3.7 (mínimo) y pruebes instalar pandas, y luego geopandas.
