### ISSUE TITLE
M9

### ISSUE THREAD

**Issue by stlara** [IIC2115/Syllabus#167]
No me queda claro si para esta misión hay que incorporar las nuevas columnas sobre el dataframe original, o sobre el de la misión 8.

**Comment by Sabarriga** [comment]
A mí hoy en la clase el profe me dijo que bastaba hacerlo sobre el de la misión 8

**Comment by FGarridoV** [comment]
sip, puedes hacerlo sobre la M8.

**Comment by ValentinaNavarro** [comment]
Hola,

No me queda claro en esta mision, cuando piden la hora de termino de la expedición, se refieran a hora tipo Hora:Minutos:Segundos, o solo a la hora como un entero H. 

Gracias!

**Comment by isabelladahdal** [comment]
Hola! para hacer la parte de travel time, intento hacer una funcion lambda haciendo los respectivos cambios de formato, pero me aparece un error en la columna de "dispatch_time" porque me aparecen datos que están en el formato "%Y-%m-%d %H:%M:%S.%f" Intenté cambiarle el formato a la columna pero como son pocos datos los que me aparecen en este formato me tira error ¿Cómo se puede usar una condicional dentro de la función lambda, en donde se comparen formatos? (Si es que este valor tiene tal formato, entonces le aplico esta transformación?)
