### ISSUE TITLE
Error al instar osmnx

### ISSUE THREAD

**Issue by Ferandadiaz** [IIC2115/Syllabus#168]
hola trato de instalar la libreria osmnx y me sale este error
![image](https://user-images.githubusercontent.com/69482563/99848275-3fa7a580-2b58-11eb-88f0-3f4d342bd913.png)
A que se puede deber?

**Comment by pcseisdedos** [comment]
Hola, por lo que dice ahí la versión de numpy que tienes no es compatible, te recomiendo actualizarla y ver que pasa. En cuanto al tema del acceso denegado, intentaste ocupar la opción que te muestra el error?

Saludos,
Pablo 😁👍

**Comment by FGarridoV** [comment]
para que no tengas el error de acceso, procura ejecutar todas las instalaciones en la cmd de administrador (mostrada en los videos).
