### ISSUE TITLE
M8

### ISSUE THREAD

**Issue by mblejeune** [IIC2115/Syllabus#168]
En enunciado dice:

> con la ayuda de la función loc filtre los datos para obtener solo la u ́ltima emisión GPS de cada expedición 

¿Puedo usar otra función que me entrega lo pedido o debo usar loc?, específicamente usar groupBy. Gracias!

**Comment by FGarridoV** [comment]
Puedes usar groupBy su lo deseas.

saludos

**Comment by mblejeune** [comment]
Gracias !
