### ISSUE TITLE
Cantidad de personas por generación

### ISSUE THREAD

**Issue by memadrid** [IIC2115/Syllabus#17]
Para el requisito cantidad de personas por generación, ¿los cónyuges se cuentan como parte de la generación de esa familia? ¿y este requisito se aplica a todos los árboles existentes en el momento, o se especificará para que familia se debe utilizar?

**Comment by fnquinteros** [comment]
Hola! Los cónyuges no se cuentan y se debe especificar una familia en particular (como input) para realizar la consulta. Durante el día modificaremos el enunciado y mandaremos un aviso por siding indicando los cambios.

Saludos!
