### ISSUE TITLE
Uso del CMD: configurar comandos

### ISSUE THREAD

**Issue by alagoshurtado** [IIC2115/Syllabus#17]
En mi computador tengo muchos ramos ordenados, por lo que la carpeta de IIC2115 está metida dentro de muchas otras y cada vez que quiero hacer pull/push debo escribir una dirección enorme en el CMD. ¿Existe alguna forma de configurar un comando que me lleve directamente a la carpeta? Es la única que voy a usar por este medio este semestre, por lo que me ahorraría mucho tiempo poder hacer algo así.
Gracias!

**Comment by FGarridoV** [comment]
Los path son relativos a tu ubicación. Por tanto te recomiendo posicionarte en tu carpeta iic2115 antes de realizar el commit.
