### ISSUE TITLE
Unicidad de títulos de películas

### ISSUE THREAD

**Issue by manalvarezc** [IIC2115/Syllabus#17]
Hola!
¿Se puede asumir que los títulos de películas no se repiten?
Gracias

**Comment by pcseisdedos** [comment]
Puedes asumir que los títulos de películas son únicos.

Saludos,
Pablo 😁👍

**Comment by nencinav** [comment]
Pude notar que hay peliculas diferentes con el mismo nombre, por el ejemplo , hay 3  peliculas llamadas "The Fan". Si creo un diccionario y pongo de key el nombre asumiendo que los titulos son unicos, se sobreescribirían, por tanto no lo podría asumir. ¿Que hago en ese caso?

**Comment by pcseisdedos** [comment]
Puedes asignarles un ID.

Saludos,
Pablo 😁👍
