### ISSUE TITLE
Duda retornos y prints

### ISSUE THREAD

**Issue by jorgee02** [IIC2115/Syllabus#17]
Hola!

Tengo la duda de si es que puedo crear funciones que retornen lo pedido en forma de instancias, y en la celda correspondiente yo haga la correcta impresión de los nombres, por ejemplo. 

En concreto, en "descendiente más lejano", me es muy cómodo retornar la instancia de la persona (porque esa función la uso en otras partes que me conviene hacerlo así), y tenía pensado que cuando en el Jupyter responda en celda, ponga str(respuesta) y así se visualice bien.

Estoy atento!

**Comment by RonaldoSosa** [comment]
Hola. Recuerda que en el enunciado se establece que las estructuras de datos para almacenar información y los mecanismos para responder las consultas deben ser modelados mediante POO. Con esto, se espera que no usen funciones "sueltas", sino que ordenen su código en clases y trabajen con métodos de cada clase, tanto para estructurar sus datos como para resolver las consultas.

**Comment by Elpartyrock617** [comment]
quiere decir que si definimos una función especifica para cada consulta solicitada y no usamos clases estaría malo?
