### ISSUE TITLE
Cambio de vialidad

### ISSUE THREAD

**Issue by mjfresard** [IIC2115/Syllabus#17]
En el caso de que vaya en una autopista y llegue a un cruce (me quedan por ejemplo 4 celdas por recorrer), y luego del cruce paso a un camino en que la velocidad es de 2 celdas por turno. ¿Avanzo las 2 celdas que admite esa vialidad o avanzo las 4 celdas restantes luego del cruce?

**Comment by Jamidd** [comment]
Avanza las 2 celdas que admite la nueva vialidad. 
En todo caso, con este tipo de preguntas puedes decidir tu lo que consideres mas lógico y dejarlo explicitado en el README.

Jaime Middleton
