### ISSUE TITLE
Instalar geopandas desde Anaconda

### ISSUE THREAD

**Issue by ConsueloAraya15** [IIC2115/Syllabus#170]
Hola!
Tengo problemas para instalar geopandas con anaconda, al correr el comando conda install -c conda-forge geopandas, me tira error cuando dice solving environment 
![imagen](https://user-images.githubusercontent.com/69482574/99887063-0d617b00-2c20-11eb-9f5b-c9fc90ad5d3c.png)

**Comment by FGarridoV** [comment]
Para los que tengan este error, podrían hacer dos cosas:
- Desinstalar anaconda e instalar python normal
- Usar Google Colab
