### ISSUE TITLE
M12 L09

### ISSUE THREAD

**Issue by ccgarcia** [IIC2115/Syllabus#170]
Para el modelo de predicción el output pedido es solo el rendimiento del modelo?? (utilizando los modelos de predicción que se describen en el capitulo 5 de las clases)

**Comment by FGarridoV** [comment]
U otro que encuentres apropiado! Es importante que dejes tus iteraciones en el notebook (ordenadas). Tal como se realiza en la materia. Quizás variando el modelo o las variables para la predicción
