### ISSUE TITLE
M8 comando tail

### ISSUE THREAD

**Issue by isalvador95** [IIC2115/Syllabus#171]
Hola, usando la combinación Group by y tail pude sacar lo pedido para la misión 8, pero me queda la duda de si me entrega efectivamente un Dataframe o una serie de datos, conceptualmente me queda la duda de si aplican para lo mismo y además si ambos me ayudan a trabajar las próximas misiones o debo buscar una forma distinta. 
Adjunto foto del formato que entrega un data frame en misión anterior y el que me entrega en esta misión. 
![Captura de pantalla 2019-06-04 a la(s) 17 28 41](https://user-images.githubusercontent.com/30678736/58916974-25bf9c00-86f3-11e9-91b4-9f92ca44f6be.png)
![Captura de pantalla 2019-06-04 a la(s) 17 28 51](https://user-images.githubusercontent.com/30678736/58916975-25bf9c00-86f3-11e9-92c2-8ba9f377e6d2.png)

**Comment by pcseisdedos** [comment]
Hola! para ver el tipo de una variable puedes usar `type(var)`, un [DataFrame](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.html) en pandas es una clase que sirve para almacenar datos y trabajar sobre ellos, las [Series](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.html) son básicamente una columna de un DataFrame, pues es un arreglo unidimensional, para produnfizar en la diferencia puedes ver [aquí](https://stackoverflow.com/questions/26047209/what-is-the-difference-between-a-pandas-series-and-a-single-column-dataframe), debes fijarte bien en el formato de input y output de cada misión para cumplir lo pedido.
