### ISSUE TITLE
Misión 1, letra a)

### ISSUE THREAD

**Issue by FernandaNavarroE** [IIC2115/Syllabus#171]
Holaa!! llevo bastante rato intentando abrir el archivo json y me sale el siguiente error:

Expecting value: line 7 column 1 (char 6)

a qué se deberá?? 

Saludos!!

**Comment by FGarridoV** [comment]
Cómo lo estas abriendo? Tu error indica que hay un error en la linea 7 (primer elemento), que el tipo no coincide.
