### ISSUE TITLE
M8 y M10

### ISSUE THREAD

**Issue by vgrivera** [IIC2115/Syllabus#172]
Hola,
Respecto a la M8, es requisito respetar el orden de las columnas pedidas en el enunciado? Porque mi dataframe resultante muestra el orden en el que están en la original.

Respecto a la M10, tengo que definir manualmente la distribución de horario (rango de dos hrs) para cada día?

Gracias

**Comment by FGarridoV** [comment]
No lo consideraría como requisito. Pero creo que es algo fácil de buscar en google.
