### ISSUE TITLE
Misión 1c

### ISSUE THREAD

**Issue by GonzaGM** [IIC2115/Syllabus#172]
Hola!

Tengo una consulta respecto a la creación del método solicitado, se nos especifica que se debe crear una nueva columna con el tiempo de viaje desde una zona dada (la que se ingresa como parámetro al método) hacia el resto de zonas.  Sin embargo, ocurre que la información de zonas (columna) solo se encuentra disponible para el archivo json y no para el csv de tiempos de viaje. Entonces, lo correcto sería determinar los tiempos entre pares origen-destino? (que esos si se encuentran en ambos dataframes entregados) y no verlo por zonas?

Sumado a lo anterior, para el csv de tiempos de viaje se cuentan con 2 promedios:  _mean_travel_time_ y _geometric_mean_travel_time_. ¿Cual corresponde utilizar?

Saludos!

**Comment by FGarridoV** [comment]
@GonzaGM Si, hazlo respecto a los id de los pares Origen Destino. Es decir, recibes un id (el de origen) y retornas una DF con los tiempos de viaje desde ese id a todos los destinos.

Respecto a tu pregunta de los promedios, uno corresponde a la media aritmética de los tiempos de viaje, mientas que el otro es la media geométrica. Puedes usar el que quieras, justificando por qué uno y no el otro.

**Comment by Giovinco24** [comment]
Hola! Tengo un problema uniendo los dataframes, porque como recibo un id de origen al unirlos me queda un geodataframe con que tiene el mismo valor de ID en todas las filas, entonces la geometria es las misma para todo el geodataframe siendo esta la geometria del ID de origen.

**Comment by FGarridoV** [comment]
Es la revés, tus geometrías deben ser las de destino. El id de origen es solo para saber que columna de tiempo escoger. Por tanto para cada geometría agregas el tiempo de ir desde la zona de origen dada a esa geometría de zona de destino.
