### ISSUE TITLE
Histograma

### ISSUE THREAD

**Issue by aaguzman11** [IIC2115/Syllabus#173]
Hola! Tengo una duda con los histogramas.
Lo que pasa, es que efectivamente el dataframe y la columna que quiero analizar existen, pero no se me genera el histograma.. para algunas columnas me las crea al instante y otras nunca las genera.

¿Qué podría estar pasando?

Muchas gracias!

**Comment by FGarridoV** [comment]
Quizás son columnas string y no numéricas
