### ISSUE TITLE
Misión 11

### ISSUE THREAD

**Issue by aaguzman11** [IIC2115/Syllabus#174]
Hola, tengo una duda de enunciado con respecto al rango de 2 horas que indican. ¿Este rango de horas se refiere a la hora del despacho o tiempo total de viajes?

Gracias!

**Comment by stlara** [comment]
Tengo una duda similar, ya que viendo algunas líneas, todas tienen tiempo de viajes menores a 2 horas, por lo que todas las expediciones estarían en un solo rango

**Comment by FGarridoV** [comment]
Criterio de ustedes. Sean consistentes.
