### ISSUE TITLE
Mision 10

### ISSUE THREAD

**Issue by rjvergarai** [IIC2115/Syllabus#175]
Tengo una duda con respecto al enunciado. Primero: ¿Se pide entregar el día de la semana con mayor cantidad de despachos sin contar Sábados ni Domingos? Y luego, ¿dentro de ese día el horario con más despachos? ¿O el horario (de dos horas) con más despachos es independiente de la pregunta anterior (día de la semana con más despachos)? 

Creo que puede haber más de una interpretación. ¿Se podrá dejar explicado en el ReadMe lo que entendimos? Ya que muchos compañeros pueden ya tener lista esta misión.

Gracias

**Comment by eljaker** [comment]
A mi también me costó un poco entenderlo y creo que puede tener más de una interpretación.. Está bien dejarlo explicado en el Readme supongo o no?

**Comment by FGarridoV** [comment]
Las últimas preguntas del lab están con esa intención. No están enfocadas en el resultado mismo. Sino que evaluar cómo abordan una solicitud. Por lo tanto, es valido hacer supuesto. Hay más de una forma de responder a la misma interrogante. Lo importante es que justifiquen sus acciones y tengan criterio a la hora de responder. Comentarios y readme son clave.
