### ISSUE TITLE
Mision 1 c) : Método de misión uno debe ser para alguna hora de agregación especifica?

### ISSUE THREAD

**Issue by Popper** [IIC2115/Syllabus#175]
En la Misión, pide crear columna nueva con el tiempo de viaje para cada destino, 
se debe agregar solo un tiempo para cada destino a una hora especifica(que el método requiera el "DataFrame" el "GeoDF", el "origen" y la "hora" ) ;
o agregar un tiempo general,ya que las siguientes misiones pide velocidad en un horario especifico, por lo que creo que no sería bueno perder la hora de agregación.

Saludos

**Comment by FGarridoV** [comment]
Puedes adaptar el método de la misión 1 como deseas. La idea es que te sirva para las misiones siguientes. En ese caso, si quieres que tu método reciba más inputs, o por ejemplo agregue los tiempos de viaje para periodos específicos. Puedes hacerlo.

**Comment by Popper** [comment]
ok, muchas gracias!
