### ISSUE TITLE
Misión 2 b)

### ISSUE THREAD

**Issue by romidonghi** [IIC2115/Syllabus#176]
Hola en esta parte de la misión entonces no es válido utilizar las velocidades en los arcos que vienen dadas por osmnx y rellenar de alguna forma las velocidades faltantes (por ejemplo por la media, mediana, etc)? 
Si la respuesta es no, entonces está permitido ocupar la libreria sklearn?

Quedo atenta, gracias!

**Comment by FGarridoV** [comment]
Puedes usarla de forma combinada, pero tu objetivo es usar los tiempos que entrega Uber para rellenar los arcos. Es posible usar sklearn si lo deseas, siempre y cuando el llenado de información de velocidades en arcos de la red utilice los datos de Uber.
