### ISSUE TITLE
Duda M2 a)

### ISSUE THREAD

**Issue by joseecourt** [IIC2115/Syllabus#177]
Hola! No entiendo mucho lo que hay que hacer en la misión 2a, no me queda claro a qué se refiere con vialidad :(
Gracias!

**Comment by FGarridoV** [comment]
La vialidad se refieres a la red vial de una ciudad. En clases vimos como se pueden obtener para ciudades o para zonas específicas.

**Comment by joseecourt** [comment]
Yaa, muchas gracias!
