### ISSUE TITLE
M12 y M13

### ISSUE THREAD

**Issue by asnunez1** [IIC2115/Syllabus#177]
Hola,
Con respecto a las M12 y M13, tengo que asumir que ustedes van a correr nuestro código con la base de datos modificada? O van a probar con exactamente la misma base de datos que tenemos disponible nosotros?

Porque, por ejemplo, en la parte de **limpieza y depuración de datos**, hago el análisis de que: **como no hay valores faltantes, no es necesario completar valores faltantes (por lo tanto no lo hago)**, y también estoy haciendo hartos comentarios y análisis específicos de los datos.

Por lo que: ¿Tengo que hacerlo de forma más 'general'? o está bien lo que estoy haciendo? Gracias!

**Comment by Jamidd** [comment]
Todo lo que sea análisis tiene que ser con una de las bases de datos que les dimos. Puede ser con la mediana o la grande (no la pequeña). 
Dejen un comentario de que BD usaron. 

Jaime Middleton.
