### ISSUE TITLE
M12 error en sklearn

### ISSUE THREAD

**Issue by vnramirez** [IIC2115/Syllabus#178]
Estimados,

Cuando intento correr la modelación, especialmente en la parte de calcular la eficiencia del modelo predictivo, Python me arroja lo siguiente:

Unknown label type: 'continuous'

Buscando en internet, me sale que en general se soluciona cuando uno pasa sus variables categóricas a números usando LabelEncoder, tal como en la materia del curso. Yo hago ese procedimiento y aún así me tira el error. Qué podrá ser? De hecho corroboro con un df.dtypes que todos mis datos estén como int32 y float64 antes de correr el modelo.

Saludos y gracias de antemano.

**Comment by vdiglesias** [comment]
Hola! tengo el mismo problema, lo pudiste resolver? @vnramirez

**Comment by vnramirez** [comment]
@vdiglesias sí. Los modelos predictivos sólo permiten tener como variable dependiente ("Y" de la regresión) a variables del tipo int32. Yo estaba intentando predecir un float64, por eso me tiraba el error!

**Comment by vdiglesias** [comment]
Gracias!!
