### ISSUE TITLE
Misión 2b

### ISSUE THREAD

**Issue by alejoeyzaguirre** [IIC2115/Syllabus#178]
Hola! Ando súper perdido en como partir la Misión 2b, si bien entiendo perfectamente lo que hay que hacer, no tengo ni la menor idea sobre cómo partir.
Feliz si pueden dar más pistas o criterios posibles a utilizar para resolverla. 
Cualquier ayuda legal se agradece!

**Comment by FGarridoV** [comment]
Tu tienes información de tiempos de viaje entre zonas. La idea es que inventes una lógica (puedes partir por una muy sencilla) que permita traspasar esa información a los arcos de la red. Te sugiero revises la materia o la documentación de osmnx que tiene funciones  para hacer cosas en la red.
