### ISSUE TITLE
Como eliminar un archivo que cree en mi repositorio de github [git]

### ISSUE THREAD

**Issue by FernandoSMG** [IIC2115/Syllabus#18]
Cree archivos en mi repositorio de github que quiero eliminar, al realizar git status en la consola de Git me aparece el siguiente mensaje 
![image](https://user-images.githubusercontent.com/48451029/91107768-14d6af80-e644-11ea-9c4c-c19230696c9d.png)

Cual es el comando para eliminar archivos en github?

**Comment by FGarridoV** [comment]
Git rm pathDelArchivo

**Comment by FernandoSMG** [comment]
Gracias!
