### ISSUE TITLE
Nombres de actores extraños

### ISSUE THREAD

**Issue by TomasFuenzalida** [IIC2115/Syllabus#18]
al tomar todos los actores y actrices de las películas, aparecen actores como:
- "."
- "and"
- "(voice)"
- "("

Para efectos del punto 3 de la Misión 3, ¿consideramos dichos "actores", o por inspección visual podemos decidir cuales son los 5 actores o actrices con trayectorias mas largas (mostrando anteriormente el como se obtuvieron obviamente y cuales se descartan)?

**Comment by IvoVuskovic97** [comment]
adhiero a la pregunta

**Comment by mavega8** [comment]
tengo la misma duda, sera un error de la base de datos?

**Comment by pcseisdedos** [comment]
Hola, pueden descartarlos de acuerdo a su criterio.

Saludos,
Pablo 😁👍
