### ISSUE TITLE
P3 : torneos incompletos

### ISSUE THREAD

**Issue by cristorcs** [IIC2115/Syllabus#18]
mi pregunta es si el numero de partidos que nos entrega la entrada esta reestringido o no, me explico, el "k" es un entero ? de esta forma el numero de equipos posibles serian en potencia de 2 (2,4,8,16...) o pueden haber por ejemplo 10 equipos.
de antemano muchas gracias.

**Comment by pcseisdedos** [comment]
Hola, K es entero, no puede haber 10 equipos.

Saludos,
Pablo 😁👍
