### ISSUE TITLE
Recordatorio Estructura del código A1

### ISSUE THREAD

**Issue by RonaldoSosa** [IIC2115/Syllabus#18]
En el enunciado se establece que las estructuras de datos para almacenar información y los mecanismos para responder las consultas deben ser modelados mediante POO. Con esto, se espera que no usen funciones "sueltas", sino que ordenen su código en clases y trabajen con métodos de cada clase, tanto para estructurar sus datos como para resolver las consultas. Ojo que esto se puede hacer de muchas maneras, lo importante es demostrar un manejo de POO.

**Comment by SebaMartinezM** [comment]
Para responder las diferentes consultas mayormente utilicé clases, sin embargo, también usé pequeñas funciones auxiliares (para printear, o hacer más evidentes algunos procesos). Esto se puede hacer? o debe ser todo resuelto utilizando unicamente funciones de clases?

**Comment by RonaldoSosa** [comment]
Hola. Como se indica en el enunciado tanto las estructuras de datos utilizadas para almacenar la información, como los mecanismos utilizados para responder las consultas, deben ser modelados mediante POO. De esta consulta se espera que la persona que se desea agregar, ahora forme parte de dicha estructura que almacene la información, de la manera en la cual ustedes la hayan modelado usando POO.
