### ISSUE TITLE
Error cuando trato de instalar pyrematch

### ISSUE THREAD

**Issue by jekipreos** [IIC2115/Syllabus#180]
Hola! Cuando trato de instalar la libreria pyrematch me sale el siguiente error:

ERROR: Could not find a version that satisfies the requirement pyrematch (from versions: none)
ERROR: No matching distribution found for pyrematch

Lo googlie pero no logro encontrar o entender algo que me ayude

Muchas gracias de antemano

**Comment by pcseisdedos** [comment]
Seguramente tiene que ver con la versión de python que estás ocupando, prueba con

* python3 -m pip install pyrematch
* pip3 install pyrematch
* py -m pip install pyrematch

Saludos,
Pablo 😁👍

**Comment by jekipreos** [comment]
Probe con todo eso y no me funciona :(

Lei que requiere de python mayor a 3.5, pero tengo el 3.6.8 asi que no entiendo que puede ser...

**Comment by nicovsj** [comment]
Hola @jekipreos,

Ejecuta lo siguiente desde Python:
```python
from distutils.util import get_platform
print("Platform:", get_platform())
```
Y me dices que te sale.

**Comment by jekipreos** [comment]
Hola!
Me sale "Platform: macosx-10.9-x86_64"

**Comment by nicovsj** [comment]
Ok, no esperaba problemas en esa plataforma. Voy a revisar eso (soy desarrollador de pyrematch). 

Por mientras te recomiendo (si es posible) que instales una versión de Python más nueva para ver si se arregla el problema. Sé que en macOS 10.9 con python 3.7 pyrematch fue testeado y funcionó. Cualquier cosa me avisas por esta issue.

Saludos!

**Comment by jekipreos** [comment]
Perdón molestar de nuevo! Desinstalé la versión de python que tenía (3.6) e instalé la 3.7 pero me sale el mismo error cuando trato de instalar pyrematch y ahora también urllib2.

Como la actividad de mañana se va a tratar de esto estoy medio preocupado jajaja

Saludos

**Comment by nicovsj** [comment]
@jekipreos subí una versión nueva de pyrematch, podrías ver si te resulta instalar ahora. Sin embargo que no te funcione urlib2 me hace pensar que hay un problema con tu instalación de Python. 

[En otra issue recomendaron instalar pyrematch en Google Colab](https://github.com/IIC2115/Syllabus/issues/165#issuecomment-735404747), para que lo tengas en cuenta.

**Comment by jekipreos** [comment]
Ahora me resulto!! Muchas gracias!! Aunque sigue sin poder instalarse urllib2 pero ya bacan que haya podido instalar pyrematch
