### ISSUE TITLE
M2b) Linkear IDs

### ISSUE THREAD

**Issue by clementeramirez** [IIC2115/Syllabus#181]
Hola! queria preguntar como se puede linkear los ids de los dataframes de los tiempos de viaje de la M1 y el que se crea con la vialidad en la M2a), dado a que son distintos formatos.
Muchas gracias, Clemente

**Comment by clementeramirez** [comment]
En que medida estan los mean_travel_time? y en que medida resultan los length de los arcos creados a partir de un geodataframe?

**Comment by FGarridoV** [comment]
> Hola! queria preguntar como se puede linkear los ids de los dataframes de los tiempos de viaje de la M1 y el que se crea con la vialidad en la M2a), dado a que son distintos formatos.
> Muchas gracias, Clemente

Eso es lo que buscamos, tu tienes tiempos de viaje entre zonas (un id para cada par) y debes traspasar esa información a los arcos. Puedes usar cualquier idea que consideres apropiada. No hay una única forma de hacerlo, la metodología es personal, lo
Importante es que tenga alguna justificación.

Los length de los arcos están en metros y los tiempos de viaje entre zona de uber están en segundos
