### ISSUE TITLE
geo refereciable M3

### ISSUE THREAD

**Issue by ddibattista** [IIC2115/Syllabus#182]
En la M3, cuando nos dicen que tenemos que sacar información que sea, de alguna manera, geo referenciable se refiere a que tiene que tener coordenadas? O simplemente que lo podamos asociar de alguna forma a los GeoDataFrames que tenemos?
Muchas gracias

**Comment by FGarridoV** [comment]
Puede tener coordenadas, o puedes georreferenciarlo de alguna otra forma.
