### ISSUE TITLE
[colab] [osmnx] [no funciona]

### ISSUE THREAD

**Issue by dilanlopeg** [IIC2115/Syllabus#183]
hola, hoy durante la mañana intente trabajar usando osmnx y no funciona, tira este error:
cannot import name '_png'
al parecer esta caido, que pasa si para la hora de sesion de trabajo sigue caido? yo tuve que trabajar en colab porque estuve mucho tiempo intentando instalar geopandas en mi pc, y cuando lo logre no me funcionaba pq al parecer mi pc no lo soportaba y reiniciaba el kernel cuando queria plotear cosas elaboradas.

**Comment by pcseisdedos** [comment]
¿Estás seguro que es problema de osmnx? Probablemente es en un plot y el problema real sea de matplotlib, seguramente osmnx requiere una versión distinta de matplotlib a la que viene instalada en colab, instalando la versión correcta no debieras tener problemas.

Saludos,
Pablo 😁👍

**Comment by dilanlopeg** [comment]
hola pablo :( puede ser que sea el plot, el problema es que es exactamente el mismo codigo que estaba usando ayer (material de clases y ayudantia) y funcionaba, pero hoy no, cuando intento usar plot con geopandas tmbn me tira el mismo error:
ImportError: cannot import name '_png'
como lo puedo arreglar? Uwu

**Comment by dilanlopeg** [comment]
el problema era matplot, lo pude solucionar con esto: pip install matplotlib==3.1.3

**Comment by rosariopenalabbe** [comment]
Hola, a mi me esta tirando error desde el import osmnx as ox, si pueden saber como arreglarlo sería de mucha ayuda, ya que llevo todo el día con esto

**Comment by Jamidd** [comment]
Hola Rosario,
que error te tira?
Jaime.

**Comment by rosariopenalabbe** [comment]
AttributeError: module 'matplotlib' has no attribute 'get_data_path'
esto en el import que se cayó hace un rato, antes eran otros cuándo intenté hacer la mision 2A

**Comment by Jamidd** [comment]
Esto es en collab??  o local??

**Comment by rosariopenalabbe** [comment]
en jupyter

**Comment by Jamidd** [comment]
Intenta desinstalar matplotlib (pip3 uninstall matplotlib) y reinstalarlo (pip3 install matplotlib==3.1.3).
Jaime

**Comment by rosariopenalabbe** [comment]
Hola! me dice que el matplotlib 3.1.3 es incompatible con el osmnx :(

**Comment by Jamidd** [comment]
Entonces intenta:
pip3 uninstall matplotlib 
pip3 install matplotlib

**Comment by rosariopenalabbe** [comment]
Sigue sin funcinarme :(
cuando importo osmnx me sale AttributeError: module 'matplotlib' has no attribute 'get_data_path'

**Comment by Jamidd** [comment]
mandame un mail y lo vemos manhana. jamiddleton@uc.cl

**Comment by rosariopenalabbe** [comment]
Gracias profe!
