### ISSUE TITLE
Reinicio del kernel con método overlay

### ISSUE THREAD

**Issue by FernandaNavarroE** [IIC2115/Syllabus#184]
Holaa!! estaba intentando implementar el método overlay, pero cada vez que corro el código, se me reinicia el kernel. He buscado en google por qué ocurre, pero no he encontrado nada :((

Saludos!!

**Comment by pcseisdedos** [comment]
Hola, revisa [este comentario](https://github.com/IIC2115/Syllabus/issues/169#issuecomment-734234092)

Saludos,
Pablo 😁👍
