### ISSUE TITLE
M2 a)

### ISSUE THREAD

**Issue by faaceituno** [IIC2115/Syllabus#185]
Hola, cuando importo los datos de el archivo areas_urbanas.shp y obtengo la geometria de "Santiago", intento obtener las redes a partir del poligono usando osmnx.graph_from_polygon y me tira un error que no he encontrado como evitarlo.

Este error es: Invalid projection: +proj=utm +zone=57941 +ellps=WGS84 +datum=WGS84 +units=m +no_defs +type=crs: (Internal Proj Error: proj_create: Error -35 (invalid UTM zone number))

**Comment by pcseisdedos** [comment]
Hola,
osmnx trabaja con el epsg 4326, tienes que cambiar el del geodataframe antes de ocupar sus métodos. O bien, modificar el default_crs de osmnx.

Saludos,
Pablo 😁👍

**Comment by rosariopenalabbe** [comment]
Holaaa, yo estoy con el mismo problema, y ya lo pase a 4326 y no se me ha arreglado :(

**Comment by Jamidd** [comment]
Antes del graph_from_polygon, intenten pasar la geometría a una projeccción de lat/long `ox.projection.project_gdf(...., to_latlong=True)`, con eso debería funcionarles.

**Comment by VicenteScholl** [comment]
Podrias explicar ese código porfa, no lo entendí y tampoco caché donde tiene que ir el nombre de mi multiploygon

**Comment by Jamidd** [comment]
Ahí está la documentación de la función:
https://osmnx.readthedocs.io/en/stable/osmnx.html#module-osmnx.projection

Saludos,
Jaime.

**Comment by faaceituno** [comment]
Yo lo pude solucionar tranformando el epsg del geodataframe con gdf.to_crs(epsg=4326) y luego a partir del gdf sacarle el poligono y usar graph_from_polygon
