### ISSUE TITLE
error "cannot set using a list-like indexer with a different length than the value"

### ISSUE THREAD

**Issue by acdelgado1** [IIC2115/Syllabus#186]
Hola! estoy tratando de hacer df.apply con una función a todas las filas del dataframe y me tira ese error y no sé por qué, también antes dice "

TypeError: '0              0
1              1
2              2
3              3
4              4
           ...  
143747    143747
143748    143748
143749    143749
143750    143750
143751    143751
Name: index, Length: 143752, dtype: int64' is an invalid key

No entiendo es como que los indices están mal pero no se por qué :(

**Comment by acdelgado1** [comment]
(la función para una linea si funciona)

**Comment by Jamidd** [comment]
Por casualidad estas usando un diccionario dentro de tu función?? 

Jaime.

**Comment by acdelgado1** [comment]
No, ninguno

**Comment by Jamidd** [comment]
Estas haciendo un for iterando por el dataframe?

Jaime.
