### ISSUE TITLE
Mision 3 pd.read_html

### ISSUE THREAD

**Issue by Giovinco24** [IIC2115/Syllabus#187]
Hola
Para la misión 3 puedo utilizar pd.read_html(link) o tengo que hacer lo que se vio en ayudantia?

**Comment by Giovinco24** [comment]
Que pasa si tengo datos solo para santiago urbano (provincia de santiago)

**Comment by Jamidd** [comment]
La idea es evaluar web-scrapping con las técnicas vistas en clases.
Respecto a los datos, la idea es que sean parte de santiago para usarlos después en la M4.

**Comment by clementeramirez** [comment]
Hola, la funcion pd.read_html si se vio en clases en vivo pero no esta en los jupyter notebook, se puede ocupar igual?
gracias

**Comment by nicifuentes** [comment]
me sumo a la pregunta de clemente, podemos usar pd.read_html?

**Comment by Giovinco24** [comment]
@Jamidd no me quedo ninguna duda clara, como dicen mis compañeros en clases vimos ese metodo por eso quiero saber si es valido. Con respecto a los datos, todos son de santiago urbano (provincia de stgo) porque en la RM hay otras provincias como chacabuco y melipilla, pero no encuentro datos para las comunas de las otras provincias. Igualmente, creo que RED solo esta dentro de la provincia de stgo.

**Comment by Jamidd** [comment]
Hola,
- **No** se puede usar pd.read_html, ya que no es parte de lo que se quiere evaluar en la misión.
- Los datos tienen que estar dentro del polígono obtenido en la misión 2. 

Saludos,
Jaime.
