### ISSUE TITLE
M3 leer tabla

### ISSUE THREAD

**Issue by rosariopenalabbe** [IIC2115/Syllabus#188]
Hola!, en la pagina que estoy viendo los datos están en tabla, pero la función salta todos las tablas (no estan como imagenes tampoco). Tienen alguna recomendación para esto?

**Comment by JaviOrtizH** [comment]
+1

**Comment by pcseisdedos** [comment]
Tendría que ver mas detalles para poder ayudarte, a priori no tengo claro lo que pueda ser.

Sube un .ipynb a tu repo con eso para que lo pueda revisar.

Saludos,
Pablo 😁👍
