### ISSUE TITLE
Pyrematch en Colab

### ISSUE THREAD

**Issue by lucianobucarey** [IIC2115/Syllabus#189]
Podrían mandar el código para instalar correctamente Pyrematch en Colab por favor? al parecer varios compañeros han tenido problemas con la instalación y está la preocupación para que funcione correctamente mañana para la actividad. Muchas gracias ! :D

**Comment by pcseisdedos** [comment]
Intentaste con lo que puse en [este comentario](https://github.com/IIC2115/Syllabus/issues/165#issuecomment-735404747)? A mi me funciona en colab sin problemas.

Quedo atento,
Pablo 😁👍

**Comment by lucianobucarey** [comment]
Gracias me funciono perfect !
