### ISSUE TITLE
Duda "Agregar Persona"

### ISSUE THREAD

**Issue by jorgee02** [IIC2115/Syllabus#19]
Hola! Tengo la siguiente duda en esta consulta:

Agregar persona: dados los datos de una persona, se debe agregar la persona al sistema. Esto implica
actualizar la estructura utilizada para almacenar la informaci´on, ubicando correctamente en ella a la
nueva persona. Si la persona a agregar no esta conectada a ninguna familia, se creara una nueva
familia, donde su único miembro es la persona agregada.

Mi duda entra en la última oración. Para mi, eso que se dice es consecuencia directa de que cada vez que se agregue una persona, se añada correctamente su padre y madre, de ser el caso.

Se refiere a eso? O debe haber un atributo, por ejemplo, que guarde realmente las diferentes familias. Porque considero que no es necesario para añadir una persona.

Estoy atento!

**Comment by RonaldoSosa** [comment]
Hola. Como se indica en el enunciado tanto las estructuras de datos utilizadas para almacenar la información, como los mecanismos utilizados para responder las consultas, deben ser modelados mediante POO. De esta consulta se espera que la persona que se desea agregar, ahora forme parte de dicha estructura que almacena la información, de la manera en la cual ustedes la hayan modelado, usando POO.

**Comment by Fopazov** [comment]
Me sumo a la pregunta. Para guardar las relaciones entre personas, **no** tengo un atributo dentro de mi grafo que contenga **instancias de personas**. Solo los ruts y sus relaciones (padre, madre). En los casos pertinentes, tengo métodos que, una vez finalizado el proceso de filtro, instancian a las personas (por medio de sus ruts) y las retornan (así como lo piden las consultas, que se retornen las PERSONAS). ¿Sería necesario cambiar la estructura de mi código? (pregunto porque la última consulta habla de la creación de familias)
