### ISSUE TITLE
Formato personas.json

### ISSUE THREAD

**Issue by shiflix** [IIC2115/Syllabus#19]
Creo que hay un error en el archivo personas.json:
},
"12928618-1": {
  "nombre": "Justin",
  "apellido": "Carrillo",
  "genero": "m",
  "rut padre": "16446564-2",
  "rut madre": "14543256-k"
},
"16346436-7":{
  "nombre": "Manuela",
  "apellido": "Vincenzi",
  "genero": "f",
  "rut padre": null,
  "rut madre": null

La persona Manuela Vincenzi no tiene un espacio a continuacion del rut , por lo que sería "16346436-7":{ en lugar de "16346436-7": {  como todos los demás individuos. Se trata de un error en el formato?

Lucas

**Comment by Hernan4444** [comment]
Hola, esto no es un error del formato, dentro del formato JSON, los espacio (o saltos de línea) no importan. En este [link](https://www.json.org/) puedes encontrar más información respecto a este formato.

Saludos ✌️
