### ISSUE TITLE
A1, Mision 3, punto 4: ¿Para considerarse como reparto el cast de una película debe contener más de un actor?

### ISSUE THREAD

**Issue by jbraunb** [IIC2115/Syllabus#19]
Hay muchas películas con solo un actor como reparto, ¿para resolver el punto 4 de la misión debemos considerar como reparto más de un actor?

**Comment by pcseisdedos** [comment]
Un reparto deben tener 2 o mas actores, el profesor lo aclaró en discord y actualizó el enunciado ayer.

Saludos,
Pablo 😁👍

**Comment by jbraunb** [comment]
Muchas gracias!

**Comment by BryanAscencio** [comment]
con respecto a esto mismo, si en una pelicula se encuentra el reparto que mas se repite pero ademas de ellos hay otro actor mas, cuenta esa pelicula para el contador, o en las peliculas solo debe tener ese exacto reparto de actores?

**Comment by pcseisdedos** [comment]
@BryanAscencio si cuenta, basta con que el conjunto de actores que más se repite sea un subconjunto del reparto de una película.

Saludos,
Pablo 😁👍
