### ISSUE TITLE
Dirección en intersecciones 

### ISSUE THREAD

**Issue by bombanex** [IIC2115/Syllabus#19]
Me quedo la duda de que si un viaje se encuentra con una intersección, Este puede volver por el camino que venia? o solo puede elegir entre doblar a la izq o der (si ese fuera el caso) pero no volver?

**Comment by FGarridoV** [comment]
Como dice en el enunciado, las entidades no pueden volver a pasar por la misma celda. De este modo, la via por la que venían queda descartada de la elección.

Saludos,
Francisco
