### ISSUE TITLE
En la materia de clases hay dos versiones de comandos

### ISSUE THREAD

**Issue by paulavonbrand** [IIC2115/Syllabus#19]
Hola!! En la materia de "colas" se puede importar deque, pero aun asi los metodos como .enqueue o .dequeue me tiran error
![image](https://user-images.githubusercontent.com/68405224/91243605-59cc1600-e718-11ea-9a28-5d1d180927a0.png)

**Comment by pcseisdedos** [comment]
Hola @paulavonbrand, disculpa la demora. enqueue y dequeue son los nombres genéricos, para la implementación en python puedes ver la tabla que aparece en los contenidos.
![image](https://user-images.githubusercontent.com/18387808/91493744-bdc01d00-e885-11ea-8160-f42a29f64f4b.png)

Saludos,
Pablo 😁👍
