### ISSUE TITLE
M3 funcion or en pyrematch

### ISSUE THREAD

**Issue by Giovinco24** [IIC2115/Syllabus#191]
Hola! 

Estaba trabajando sacando los datos de una pagina y necesito hacer un or porque mi patrón no es siempre el mismo (números de 2 y 3 dígitos) . Adicionalmente, necesito saber como puedo seleccionar los datos que solo cumplan exactamente el patrón. Finalmente, hasta que punto puedo editar los datos que saco de la pagina, por ejemplo, si saco los valores de una comuna después puedo rellenar a mano los nombres de la comuna?

**Comment by pcseisdedos** [comment]
Hola,
Todas las preguntas que haces sobre pyrematch están en la materia del curso, te recomiendo revisarlo y si quedas con dudas vuelves a preguntar.

Respecto a lo otro, rellenar a mano no es válido, la información la tienes que sacar de una página web.

Saludos,
Pablo 😁👍

**Comment by Giovinco24** [comment]
Gracias pablo, pero viendo el vídeo no me quedaba claro cual era el comando or. Igualmente, me queda otra duda sobre el uso de or porque en mi caso tengo números con decimales y otros no. Entonces, al usar or los números con decimales se guardan dos veces pq también cumplen la condición.

**Comment by Giovinco24** [comment]
por ejemplo si tengo 50 y  45,1 el comando me retorna 50 45 y 45,1

**Comment by pcseisdedos** [comment]
pyrematch encuentra todos los matches para un patrón, no solo el primero. Es así por construcción, pudes buscar patrones únicos o hacerlo de otra forma.

Saludos,
Pablo 😁👍
