### ISSUE TITLE
M2B caminos superpuestos

### ISSUE THREAD

**Issue by rscheelv** [IIC2115/Syllabus#193]
Hola, cómo considero las lineas que quedan superpuestas? ya que para la misma ruta y mismo horario hay diferentes tiempos

**Comment by pcseisdedos** [comment]
La metodología y supuestos que ocupen queda a criterio de ustedes. Preocúpate de explicitar las decisiones que tomes y de justificarlas debidamente.

Saludos,
Pablo 😁👍
