### ISSUE TITLE
Problema al leer el shape de paradas

### ISSUE THREAD

**Issue by vnramirez** [IIC2115/Syllabus#194]
No había tenido este problema sino hasta el final del laboratorio.
El nombre de la comuna para aquellas cuyo nombre tiene una tilde (Maipú, por ejemplo) me aparecen como MAIP?. Intenté agregar encoding='utf-8' cuando hago el read.file pero no funciona.
Qué puedo hacer? Es importante para poder hacer un par de merges que necesito al final, y como tienen ese ? entremedio nunca hace el match con la key que le entrego.

Saludos y gracias!

**Comment by pcseisdedos** [comment]
Hola @vnramirez, revisa la issue #188 
Saludos,
Pablo.
