### ISSUE TITLE
L05 plazo de entrega

### ISSUE THREAD

**Issue by miflores1** [IIC2115/Syllabus#194]
No estoy seguro de si otros compañeros tendrán el mismo problema que yo pero siento que no voy a ser capas de terminar el laboratorio en el plazo que hay, tengo varias otros trabajos que consumen bastante tiempo pero ninguno mas que este laboratorio por lo que me gustaría preguntar si es posible obtener un par de días mas para realizar el laboratorio de antemano muchas gracias por su comprensión

**Comment by VicenteScholl** [comment]
x2

**Comment by Jisepulveda1** [comment]
x3

**Comment by fmundurraga** [comment]
x4

**Comment by sregonesi** [comment]
x5

**Comment by paulavonbrand** [comment]
siento lo mismo:( onda un di mas estaría bacan que se acumularon todas las entregas para este domingoo:(

**Comment by cdsoza** [comment]
x7

**Comment by pipequiroz** [comment]
x8

**Comment by paulavonbrand** [comment]
o igual tengo la sensación de que el puntaje esta como medio raro distribuido, y por cosas muy dificil es de hacer castigan mucho en puntaje:(

**Comment by martinchino77** [comment]
Me sumo a lo de Paula y @miflores1, encuentro que esta demasiado difícil alcanzar a terminar el lab a tiempo, considerando que es fin de semestre y esta bastante duro en mi caso, con hartas cosas mas en los otros ramos, como cierres de proyectos, ultimas tareas y los exámenes que parten esta semana que viene me están complicando todo muchísimo mas y generando mas presión en el stress de fin de año y este año que a sido super especial....

Por otro lado, encuentro que el puntaje esta acomplejándonos mas, ya que varios estamos super complicados con la 2b que es todo el laboratorio a fin de cuentas. Feliz si pudieran ayudarnos con algo al respecto o guiarnos un poco mas en como se subdividirá o como, de tal forma de hacerlo mas amigable.

**Comment by halobel** [comment]
Hola a todos, acabo de enviar un aviso extendiendo el plazo de entrega del L05 hasta el martes. Con respecto a la asignación de puntaje, esta no se modificará, ya que apunta a que pongan el mayor esfuerzo en las partes más relevantes del laboratorio. No tiene ningún sentido pedagógico reducir este puntaje para darle uno mayor a las partes menos relevantes.

**Comment by Nsanhueza7** [comment]
@halobel Profesor, creo que a lo que se apuntaba con el tema del puntaje es que 3.3 pts de 6 dependen de solo la pregunta 2b (sin ella no se puede hacer la 4).
Respecto a la misma pregunta, llevo desde el lunes de la semana pasada estancado, podría dar algún tip sobre algo útil para utilizar en la pregunta? De antemano muchas gracias.

**Comment by clementeramirez** [comment]
Me sumo a lo de @Nsanhueza7 tambien llevo mucho tiempo y sin resultados

**Comment by martinchino77** [comment]
Gracias @halobel por dar más plazo, ayudara significativamente para descomprimir un poco y lograr una mejor entrega. 
Con respecto a lo del puntaje, quizás me explique mal. Me refería a lo mismo que Nicolas Sanhueza, si es que pudiese dar un tip para poder por lo menos dejar algo decente y no quedar con algo pesimo. Es por eso, que al decir que se subdividiera el ptje me referia a que la misma pregunta 2b como que se dijera como se distribuyen esos 2,3 ptos como en "pequeñas partes" de la pregunta, de esta forma darse cuenta que al lograr cierta cosa o cierto desarrollo se esta logrando una parte del puntaje o el ptje total.

**Comment by VicenteScholl** [comment]
Apoyo la propuesta de Martin!
