### ISSUE TITLE
Uso de data.today() P5

### ISSUE THREAD

**Issue by emapazvaldes** [IIC2115/Syllabus#195]
profe las fechas se pueden generar usando la libreria date?
Porque como en la pagina sale como hoy, mañana, sabado. poder hacer date.today() e ir sumando dias dependiendo de cuantos pronosticos hay.
GRACIAS!!

**Comment by pcseisdedos** [comment]
Si puedes usar la librería date para eso.

Saludos,
Pablo 😁👍
