### ISSUE TITLE
P05 manipulación de listas

### ISSUE THREAD

**Issue by jtjara1** [IIC2115/Syllabus#196]
puedo manipular listas manualmente? Obtuve el html y luego de aplicar filtros (con pyrematch), conseguí una lista que me indica la humedad en cada dia. Resulta que en la página web, se repite el pronostico del primer dia, por lo que mi lista de humedades tiene un valor repetido. Ej: humedades =[jueves3:20,jueves3:20, vienres4:25,sabado5:23....]. Puedo eliminar ese valor manualmente? A su vez, puedo manipular cada elemento de la lista manualmente para cambiarle el formato (ej: poner el signo% a cada elemento y agregar fecha)?

**Comment by pcseisdedos** [comment]
Puedes extraer el registro repetido, y también puedes cambiar el formato para la visualización.

Saludos,
Pablo 😁👍

**Comment by jtjara1** [comment]
Muchas gracias. Me simplificó caleta esto jajaja
