### ISSUE TITLE
P05 Cantidad de días distintos por página

### ISSUE THREAD

**Issue by JaviOrtizH** [IIC2115/Syllabus#197]
Hola,

Qué tengo que hacer si una página me muestra 7 días y la otra 15? Muestro ambas hasta los 7 y luego de eso muestro las de la página que me muestra 15?

Muchas Gracias!

**Comment by pcseisdedos** [comment]
Basta con que muestres los primeros 7 días para la que te muestra 15.

Saludos,
Pablo 😁👍

**Comment by sregonesi** [comment]
> Basta con que muestres los primeros 7 días para la que te muestra 15.
> 
> Saludos,
> Pablo 😁👍

Hola, a mi me pasa algo similar una de mis paginas tiene información para un mes y la otra para 13 dias, muestro la misma cantidad de dias para ambas paginas?.
Saludos

**Comment by JaviOrtizH** [comment]
> Basta con que muestres los primeros 7 días para la que te muestra 15.
> 
> Saludos,
> Pablo 😁👍

Super muchas gracias!

**Comment by pcseisdedos** [comment]
@sregonesi El enunciado dice:

> NOTA: Si N es más grande que los días que se pueden obtener hacia el futuro de los sitios elegidos, entonces obtenga los datos hasta la última fecha común a los dos sitios web.

Y ya lo respondí recién en esta misma issue, no entiendo qué cosa no te queda clara.
