### ISSUE TITLE
P05 uso de material de clases

### ISSUE THREAD

**Issue by CristobalUrzua** [IIC2115/Syllabus#198]
Hola!

Me gustaría saber si puedo utilizar el material del notebook 03 - Web Scrapping para realizar mi actividad.
Concretamente me gustaría sbaer si puedo copiar este pedazo de código y utilizarlo.
import urllib.request as net
import ssl

class WebDownloader:
    
    def __init__(self, link):
        self.user_agent = 'Mozilla/5.0 (Windows; U; Windows NT 5.1; en-US; rv:1.9.0.7) Gecko/2009021910 Firefox/3.0.7'
        self.url =  link
        
        
    def getHtmlAsString(self):
        headers = {'User-Agent':self.user_agent}
        request= net.Request(self.url,None,headers)
        gcontext = ssl.SSLContext()
        response = net.urlopen(request,context=gcontext)
        return response.read().decode('utf-8')
    
wd = WebDownloader('https://www.prensadigital.cl/valor-utm-unidad-tributaria-mensual.html')
sourceCode = wd.getHtmlAsString()
print(sourceCode)

Si es así, ¿Cómo puedo citarlo?

Gracias

**Comment by pcseisdedos** [comment]
Si puedes ocuparlo, basta con que lo cites indicando que lo sacaste del material y con el link.

Saludos,
Pablo 😁👍
