### ISSUE TITLE
[REGEX][p05]

### ISSUE THREAD

**Issue by dilanlopeg** [IIC2115/Syllabus#199]
hola, como puedo encontrar elementos que contengaan un % ?? intento poner pattern = "%" pero se me cae

**Comment by pcseisdedos** [comment]
Debe ser otro el problema, lo acabo de intentar y funciona correctamente, revisa bien el código.

![image](https://user-images.githubusercontent.com/18387808/101092689-cae15c00-3598-11eb-985d-3d8ae8f03295.png)
Saludos,
Pablo 😁👍
