### ISSUE TITLE
Tasa entrada/salida vagon 

### ISSUE THREAD

**Issue by JJCollado** [IIC2115/Syllabus#2]
Buenas, tengo una duda para la tasa de entrada y salida de los vagones, esta en el enunciado es de 25 pasajeros/segundo esto aquí es por puerta de cada vagón o el casa total de un tren con 10 vagones, ya que si es para el primer caso descrito seria irreal, por el hecho que esto no sucede en la vida real y los 200 pasajeros que hay en el vagón podrían bajarse sin problema de el y también podrían subir los 200 de su capacidad en los 30 segundos que el tren esta parado en la estación. Con que valor trabajamos 2,5 pax/seg o 25 pax/seg? Espero su respuesta y muchas gracias.

**Comment by FranciscoDev** [comment]
En efecto es un valor poco real. Pero es 25 pax/seg por puerta

Saludos
