### ISSUE TITLE
Duda ejercicio formativo 1

### ISSUE THREAD

**Issue by raimundo8** [IIC2115/Syllabus#2]
Hola que tal? , esperando que estés super , te quería consultar con respecto al tema de la probabilidad p dada por enunciado, la verdad tal vez me estoy enredando mucho con la lógica detrás de esa probabilidad, pero no se si entenderlo como que a fin de cuentas llegan una cantidad  X de personas a  cada una de las N filas , es decir , tengo como una cantidad aleatoria de personas, o sino mas bien, se refiere a que tengo una probabilidad diferente para cada votante que llega a mi local de votación en una de las N filas? y  que por ende, la persona, vota en la fila con mayor probabilidad a partir de valores aleatorios de p para cada fila?

de antemano muchas gracias 
saludos!

**Comment by nfalvarado** [comment]
Hola Raimundo, es solamente un modelo aleatorio para distribuir en las mesas.
