### ISSUE TITLE
Tiempo de los turnos

### ISSUE THREAD

**Issue by DanteZM** [IIC2115/Syllabus#2]
Quisiera saber que se entiende por turno, ya que no me queda claro por el enunciado. ¿se refiere a una cierta cantidad de segundos que yo debo definir?, ¿se refiere al tiempo en que transcurre la siguiente generación de viajes? ¿o a otra cosa?

Muchas gracias de antemano.

**Comment by FGarridoV** [comment]
Un turno es un momento donde ocurren los eventos. Es decir, en un turno pueden generarse viajes y/o realizarse los movimientos de las entidades. Esos cambios generan un nuevo estado de la ciudad. Luego, se puede ejecutar otro turno.

Es decir en cada turno debes movilizar todas las entidades de la ciudad según sus velocidades y preocuparte de generar viajes donde corresponda.

Saludos,
Francisco

**Comment by FelipeUlloan** [comment]
la cantidad de turnos la ingresa el usuario al programa o nosotros debemos definir una cantidad por defecto?

**Comment by FGarridoV** [comment]
la cantidad de turnos debe quedar paramétrica

Saludos,
Francisco
