### ISSUE TITLE
consulta uso de librerías

### ISSUE THREAD

**Issue by catasibisa** [IIC2115/Syllabus#20]
Para las consultas estuve investigando harto y encontré  la librería itemgetter. La puedo usar?? La verdad me ayudó mucho para el conteo rápido de los "5 más" o los "3 mejores#...

**Comment by pcseisdedos** [comment]
Hola, Si. Puedes ocupar itemgetter para eso.

Saludos,
Pablo 😁👍

**Comment by iavasquez1** [comment]
@pcseisdedos Respecto a la misma pregunta estuve revisando que hay una estructura de datos distintas a la que hemos visto que me permite hacer de manera mas eficiente la parte 4 de la misión 3, ¿la puedo usar o tiene que usarse estrictamente lo visto en los contenidos hasta el momento?

**Comment by pcseisdedos** [comment]
@iavasquez1 cual?

**Comment by pcseisdedos** [comment]
@iavasquez1 si los pueden usar, los sets se ven en el [capítulo 2](https://github.com/IIC2115/Syllabus/blob/main/Material%20de%20clases/Cap%C3%ADtulo%202/Parte%20a/03%20-%20Sets.ipynb) y los frozensets son solo una extensión a estos con ciertas particularidades (como dicts con defaultdicts).

Saludos,
Pablo 😁👍
