### ISSUE TITLE
Personas más jovenes

### ISSUE THREAD

**Issue by memadrid** [IIC2115/Syllabus#20]
Hola :) Una consulta, el requerimiento Personas más jovenes dice: "Dado un numero entero k, se debe retornar a las k personas de mayor rut", sin embargo, estaba leyendo los datos y a veces pasa que los hijos tienen un rut menor que el de los padres. Entonces, aunque puedo retornar los rut mayores, no necesariamente corresponderán a las personas más jóvenes. ¿Se trata de un error?

**Comment by fnquinteros** [comment]
Hola! No, no se trata de un error. Los ruts son aleatorios, ni siquiera son válidos, así que es normal que ocurra lo que dices 😅. Sólo retorna las personas con mayor rut y estará bien 👍.

Saludos!

**Comment by memadrid** [comment]
Ahh, ok, gracias :) Otra consulta, ¿comparo los ruts hasta el dígito antes del guión? Es que como a veces aparece la k...

**Comment by fnquinteros** [comment]
No está especificado, así que queda a tu criterio qué hacer con el último dígito (lo puedes ignorar o considerar la k mayor que 9 o menor que 0, etc... 😅). Recuerda especificar de alguna forma tu decisión (un comentario o en el Readme).

Saludos!
