### ISSUE TITLE
Archivo README

### ISSUE THREAD

**Issue by bombanex** [IIC2115/Syllabus#20]
Se puede hacer el archivo README en un archivo de texto .txt o tiene que ser .md. De ser asi: Como se hace un archivo de ese tipo?

**Comment by FGarridoV** [comment]
Los comando para trabajar en un markdown (md) los puedes encontrar acá o en alguna página de google. [Link](https://support.zendesk.com/hc/es/articles/203691016-Uso-de-Markdown-para-el-formato-de-texto)

Basta con cambiar la extensión. textEdit de mac los entiende. Para windows googlea algun programa para ello, si no usa los comando directamente en notepad.

Saludos,
Francisco
