### ISSUE TITLE
Duda Antepasado en común relacion padre hijo

### ISSUE THREAD

**Issue by PabloLaporte** [IIC2115/Syllabus#20]
Me surgio una duda en esta consulta, en el caso que se pregunte un padre y un hijo el antepasado comun es el padre o el abuelo?, ya que el padre no es antepasado de si mismo pero si es comun con el hijo

**Comment by RonaldoSosa** [comment]
Hola. Esa consulta se refiere a un antepasado en común, tal y como dices uno mismo no podría ser antepasado de si mismo por lo que en el caso que mencionas el antepasado en común más cercano sería el abuelo.
