### ISSUE TITLE
return self

### ISSUE THREAD

**Issue by dilanlopeg** [IIC2115/Syllabus#20]
hola, en el codigo de la materia sobre arboles hay una parte del codigo en la clase arbol que no entiendo, ¿para que sirve return self?
    def __repr__(self):
        # Para visualizar el arbol redefinimos el método __repr__ para recorrer recursivamente
        # todos los nodos del árbol.
        
        def recorrer_arbol(raiz):
            for hijo in raiz.hijos.values():
                self.ret += "id-nodo: {} -> id_padre: {} -> valor: {}\n".format(hijo.id_nodo, hijo.id_padre, hijo.valor)
                recorrer_arbol(hijo)
                
            **return self**

        self.ret = 'RAIZ:\nroot-id: {} -> valor: {}\n\nHIJOS:\n'.format(self.id_nodo, self.valor)
        recorrer_arbol(self)        
        return self.ret

**Comment by pcseisdedos** [comment]
Hola @dilanlopeg disculpa la demora, en lo que indicas lo que se hace es sobreescribir el repr para que se imprima información personalizada al imprimir un objeto de la estructura de datos creada (el Arbol), recorrer_arbol lo que hace es agregar los hijos a este print, sin embargo, concuerdo contigo en que el `return self` no aporta mayor utilidad en este caso, puesto que no se guarda esa información en ninguna parte ni se utiliza, lo importante es que se actualiza self.ret al llamar a recorrer_arbol, según yo al eliminar `return self` debiera seguir funcionando correctamente, prueba y cuéntame como te va.

Saludos,
Pablo 😁👍

**Comment by VicenteScholl** [comment]
en el mismo código comentado, ¿qué es self.ret? ¿de donde sale?

**Comment by Jamidd** [comment]
@VicenteScholl 
self.ret es simplemente una variable de instancia.
ahí la definen => `self.ret = 'RAIZ:\nroot-id: {} -> valor: {}\n\nHIJOS:\n'.format(self.id_nodo, self.valor)`
saludos,
Jaime

**Comment by VicenteScholl** [comment]
Perfect ya entendi, gracias!
