### ISSUE TITLE
P03 Pregunta 1 y 2

### ISSUE THREAD

**Issue by smdiban** [IIC2115/Syllabus#200]
Hola, no entiendo bien la diferencia entre la pregunta 1 y la 2. Para la pregunta 1 me piden mostrar la variable meteorológica que yo elegí para los días siguientes, y para la pregunta 2 debo mostrar solo un valor por día? Si es así, cuál sería ese valor?

**Comment by pcseisdedos** [comment]
Hola, revisa #202 

Saludos,
Pablo 😁👍
