### ISSUE TITLE
P05 duda instrucción

### ISSUE THREAD

**Issue by CristobalUrzua** [IIC2115/Syllabus#202]
Hola, no entiendo muy bien esta instrucción:

2. Agregar por cada día la variable meteorológica obtenida de los dos sitios web, entregando un solo valor
por día. (0.5 puntos)

Mi duda también es que: Para una única ciudad vamos a obtener datos de dos páginas distintas. ¿Cuáles datos debemos utilizar para mostrar? ¿O mostramos tanto los datos de la página 1 y página 2?

**Comment by pcseisdedos** [comment]
Deben agregar los datos de ambas páginas en uno solo de alguna forma (ej:promedio).

Saludos,
Pablo 😁👍

**Comment by jtjara1** [comment]
Pablo, con respecto a lo anterior:
La agregación se hace al momento de printear la prediccion final? Es decir, al momento de retornar pred_meteo

**Comment by pcseisdedos** [comment]
`pred meteo(ciudad, N)` debe realizar las 3 cosas, pueden desagregar en otras funciones que hagan una parte y luego lo juntan. En este caso es en la pregunta 2.

Saludos,
Pablo 😁👍

**Comment by jtjara1** [comment]
Aahh entonces pred deberia retornarme 3 cosas, donde 2 son la predicción segun una pagina y la tercera que sea el promedio?
