### ISSUE TITLE
P05: imprimir "elegantemente los datos"

### ISSUE THREAD

**Issue by jphiribarren** [IIC2115/Syllabus#204]
Hola!
Quería saber a qué se refieren específicamente con imprimir elegantemente las predicciones, ¿se refieren a que esté ordenado y claro? ¿o algo más?

**Comment by jtjara1** [comment]
Me sumo a la pregunta. Es valido si imprimo una lista que muestre fecha,variable y link? adjunto foto para mostrar como se vería en el notebook. Encuentro que se ve bien así y ordenado.

![print](https://user-images.githubusercontent.com/69482268/101097664-58747a00-35a0-11eb-9642-2f299256ecd0.PNG)

**Comment by alagoshurtado** [comment]
Me sumo a la pregunta. Se puede usar una librería que no vimos en el curso (tabulate) para mostrar los datos?

**Comment by pcseisdedos** [comment]
Se refiere a que esté ordenado y claro, el ejemplo de @jtjara1 es suficiente. Pueden usar tabulate o crear un dataframe para que se vea mejor aún si lo desean.

Saludos,
Pablo 😁👍
