### ISSUE TITLE
M3 procesamiento de datos.

### ISSUE THREAD

**Issue by FernandaNavarroE** [IIC2115/Syllabus#209]
Hola!! el procesamiento de los datos luego de obtener estos si o si debe ser a través de expresiones regulares? o es una forma de hacerlo y se pueden utilizar otros arreglos como slice en listas y cosas de ese estilo? Considerando que la información ya fue obtenida con webscrapping.

 Saludos!!

**Comment by pcseisdedos** [comment]
Hola,
Revisa #192 

Saludos,
Pablo 😁👍
