### ISSUE TITLE
Subir tarea a github

### ISSUE THREAD

**Issue by mblejeune** [IIC2115/Syllabus#21]
Hola! subí una actualización de mi tarea a github pero al momento de ingresar desde github a mi carpeta L01, aunque me aparece el commit que yo hice al actualizarla, si yo quiero ingresar a mi .ypynb que es el código de mi tarea me sale "Sorry, something went wrong. Reload?", y lo intenté desde distintos navegadores, ¿como puedo revisar que mi tarea se subió bien con mis actualizaciones?

Gracias!

**Comment by Jamidd** [comment]
Puede ser que la extensión no es correcta, los notebooks son ".ipynb" y no ".ypynb". No se si será un typo de tu issue. Avisame.

Jaime Middleton

**Comment by mblejeune** [comment]
@Jamidd lo escribi mal! jajaj está subido como .ipynb, pero me sale ese mensaje de error :( porque subi el archivo en el que estoy trabajando desde jupyter

**Comment by Jamidd** [comment]
No te preocupe por el error de GitHub.

Jaime Middleton
