### ISSUE TITLE
Entrega actividad

### ISSUE THREAD

**Issue by vmunozgarachena** [IIC2115/Syllabus#21]
Hola! no entiendo en que parte se debe entregar el archivo creado, que en el repositorio personal no encuentro ninguna carpeta donde subirlo.

**Comment by RonaldoSosa** [comment]
Hola. La carpeta en la que debe estar el archivo creado deben crearlas ustedes mismos, y subirla al repositorio. Recordar que el nombre del archivo debe ser "A1.ipynb" y el de la carpeta "A1".
