### ISSUE TITLE
comprensión de comandos material de estudio

### ISSUE THREAD

**Issue by dilanlopeg** [IIC2115/Syllabus#21]
hola, es necesario comprender profundamente los comandos que estan en la materia de estudio (como por ej. el arbol) o simplemente sirve aprender su uso?

**Comment by pcseisdedos** [comment]
Debieran entender el trasfondo de la materia, no les pedimos que memoricen sintaxis o algo por el estilo, porque pueden buscar información en google para eso. En caso que encuentren en la materia alguna cosa de sintaxis que no logren entender buscando en google pueden preguntarlo en las issues.

Saludos,
Pablo 😁👍
