### ISSUE TITLE
A1, Misión 3: ¿Qué significa los datos necesarios para generar la solución?

### ISSUE THREAD

**Issue by jbraunb** [IIC2115/Syllabus#21]
¿Qué significa que la función requiera los datos necesarios para generar la solución?
A modo de ejemplo: 
¿debemos empaquetar la misión 1, 2 y 3 para que una sola función Encontrar_5_generos_populares(.,.,.,.) cargue los datos de la base de datos entregue la respuesta?
¿O consideramos que ya se cargaron los datos (misién 2) en forma de las clases (misión 1) y se creo por ejemplo una lista con instancias. Luego Encontrar_5_generos_populares() requerirá solo aquella lista?

**Comment by pcseisdedos** [comment]
Hola, Para las consultas considera que ya creaste las instancias.

Saludos,
Pablo 😁👍

**Comment by jbraunb** [comment]
Muchas gracias!
