### ISSUE TITLE
M2b L05

### ISSUE THREAD

**Issue by Nsanhueza7** [IIC2115/Syllabus#210]
Existe algún tip para esta pregunta? Es la que más vale del lab y literalmente llevo más de una semana sin lograr determinar si un linestring está contenido en cierto polygon o no. ¿Alguna bibliografía recomendada con esta información?

De ante mano muchas gracias.

**Comment by dilanlopeg** [comment]
me summo a esto, no pueden dar algo para guiarnos?

**Comment by Jamidd** [comment]
Hola,
la verdad es que el mejor tip que te puedo dar es que veas las clases 1 y 2 para hacer la 2b. En estas dos clases está el 95% de lo que necesitas para hacer esta misión. 

Saludos,
Jaime.
