### ISSUE TITLE
M2b “Metodología propia”

### ISSUE THREAD

**Issue by sitauscant** [IIC2115/Syllabus#211]
Hola!

En la misión 2b se pide definir una metodología, ¿esto quiere decir una función? Porque para resolverlo utilicé muchos pasos y los expliqué en celdas, podría dejarlo así o lo uno todo a una función?

Saludos

**Comment by pcseisdedos** [comment]
No es necesario que sea una función, pero por temas de orden es recomendable hacerlo así. De todas formas mientras quede claro no debiera haber problemas, ocupa celdas en markdown para poder explicarlo bien.

Saludos,
Pablo 😁👍
