### ISSUE TITLE
M3 

### ISSUE THREAD

**Issue by jahernandez2** [IIC2115/Syllabus#212]
Hola! tengo una duda, cuando obtengo la información de mi nodo en una lista (con soup.findall(node)) existe alguna restricción para después procesar aquella informacion y buscar lo que me sirve? Hasta el momento estoy asumiendo que no hay problema para procesar la informacion como quiera. Saludos.

**Comment by jahernandez2** [comment]
Y otra duda con esta mision, algunos nombres de comunas no me aparecen completos por sus caracteres especiales (Maipú me sale como Maip por el tilde en la u y Ñuñoa no me aparece simplemente). Mi pregunta es si puedo incorporarlos por mi cuenta aquellos caracteres que faltan. Saludos.

**Comment by Jamidd** [comment]
La idea es que usen lo mas posible las librerías que les mostramos. Si hacen algo con listas, que se podría haber hecho con las librerías enseñadas va a estar malo. Si llegan a un punto donde la información esta sumamente fácil de obtener con un split o algo por el estilo, entonces estaría OK. 

El objetivo del laboratorio es evaluar su uso de las librerías enseñadas. En general, usen su criterio y demuestren que se manejan con estas. 

Saludos, 
Jaime.
