### ISSUE TITLE
Duda M3 Dead Kernel

### ISSUE THREAD

**Issue by joaquinnavarro1** [IIC2115/Syllabus#214]
Hola!! tengo un problema con la M3. Utilicé regex101.com para obtener el patrón que me sirve para sacar la info que necesito del string. El problema es que al momento de ejecutarlo me tira el error de: Dead Kernel. A que se podría deber esto?

**Comment by pcseisdedos** [comment]
Al usar pyrematch se reinicia el kernel frente a algunos errores, revisa bien que el patrón está ok y que las variables que obtienes existen en el patrón.

Saludos,
Pablo 😁👍

**Comment by joaquinnavarro1** [comment]
mmm esque ni siquiera estoy tratando de correr un patrón muy complicado, por ejemplo, si trato de usar el patrón: [0-9,]+  también se me muere el kernel :(

**Comment by pcseisdedos** [comment]
Podrías replicar el error con un ejemplo sencillo? Así lo puedes publicar aquí y lo comentamos.

**Comment by joaquinnavarro1** [comment]
Por ejemplo al tratar de correr el patrón :  [a-zA-Z´\s]+   me tira error
![Captura de pantalla 2020-12-07 152329](https://user-images.githubusercontent.com/69482507/101389507-4cd6cb00-38a0-11eb-9072-6d78f962fbaa.png)

**Comment by pcseisdedos** [comment]
El problema es que en la cuarta linea le pides al match la variable text pero esta no la incorporaste en el patrón.

Saludos,
Pablo 😁👍

**Comment by joaquinnavarro1** [comment]
oohhh! ya cache! muchisimas gracias!!
