### ISSUE TITLE
Duda M2b cantidad de arcos

### ISSUE THREAD

**Issue by jahernandez2** [IIC2115/Syllabus#215]
Hola, en la M2b de menciona que "Defina una metodología propia que permita incorporar a la vialidad las velocidades presentes en arcos de la red vial", hay alguna cantidad de arcos que deben estar cubiertos (mas o menos) para completar esta misión?

**Comment by pcseisdedos** [comment]
No hay una cantidad mínima de arcos a cubrir de por si, es verdad que la ciudad de Santiago es muy grande y dependiendo de la metodología que ocupen puede que se vuelva realmente muy difícil de trabajar para todos los arcos. Por lo tanto, pueden incorporar las velocidades solo a un subconjunto de los arcos. Ahora bien, más que apuntar a la cantidad de arcos que eligen yo creo que es relevante **cuales** eligen. Como siempre, justifiquen su elección.

Saludos,
Pablo 😁👍
