### ISSUE TITLE
Aprobación del curso

### ISSUE THREAD

**Issue by paulavonbrand** [IIC2115/Syllabus#216]
Hola!! Lo leí recién en el syllabus, pero quería preguntar para asegurarme.
Para aprobar el curso se debe tener la nota de los labs sobre 3.95 y aparte hay que tener también la nota de las actividades sobre 3.95?
Y para las notas de los labs siempre es el puntaje obtenido según el enunciado más 1 punto base?
Muchas gracias:)

**Comment by pcseisdedos** [comment]
Paula, tal como tu lo mencionas esa información está en el Syllabus.

Respecto a tu otra pregunta, no siempre la nota se calcula así, hubo un laboratorio que permitía tener 7 puntos pero la nota máxima era un 7,5 (no un 8). Además, en el laboratorio 4 dimos un bonus de 5 décimas por entregar dentro del plazo inicial a quienes llenaron el formulario y obtuvieron nota 4 o superior. De todas formas, las notas de los laboratorios están calculadas tanto en SIDING como en las issues de sus repositorios privados.

Saludos,
Pablo 😁👍
