### ISSUE TITLE
M1 lugar de los archivos (entrega)

### ISSUE THREAD

**Issue by rosariopenalabbe** [IIC2115/Syllabus#217]
Hola, en la mision 1 hay que abrir archivos que estan en diferentes carpetas. Yo movi algunos y los cambie de carpetas, en la entrega tengo que llamar al archivo en la carpeta original que esta o da lo mismo?.
Muchas gracias

**Comment by pcseisdedos** [comment]
Lo ideal es trabajar con path relativo a la carpeta actual y no mover los archivos de lugar.

Saludos,
Pablo 😁👍
