### ISSUE TITLE
Celdas de comentarios en colab

### ISSUE THREAD

**Issue by Giovinco24** [IIC2115/Syllabus#219]
Hola, cuando descargo mi cuaderno de colab en .py pasa que las celdas de comentarios no queda con un # y quedan entre comillas triples. Tengo que cambiar el .py para que queden con #  o las comillas triples también funcionan.

**Comment by pcseisdedos** [comment]
Las puedes dejar con triple comillas, es otra forma de comentar código.

Saludos,
Pablo 😁👍
