### ISSUE TITLE
Imprimir eventos

### ISSUE THREAD

**Issue by bombanex** [IIC2115/Syllabus#22]
A que se refiere con que hay que imprimir en cada turno los eventos generados?
Decir cuantos viajes y de que tipo se generaron? Cantidad de personas de cada uno? Cada movimiento?

**Comment by bombanex** [comment]
Sigo con la duda. Espero la respuesta

**Comment by ardelriog** [comment]
Tenía la misma duda y hablé con un ayudante. Me dijo que es como hacer un print para explicitar la generación de viajes, tipo "se genera un viaje en auto con 3 personas en la casilla (2,0)" o algo de ese estilo, supongo que igual podría estar bien hacer un total del turno.
De todas formas dijo que se dejara explicado en el README la forma en que se entrega esa información.

**Comment by Jamidd** [comment]
Básicamente es lo que dijo @ardelriog.
En general este tipo de cosas dejalas a tu criterio y mecionalo en el README. En todos los trabajos van a existir decisiones del programador, mientras las menciones después en el README no hay problema.
