### ISSUE TITLE
Formatos y cálculo de tiempos L02

### ISSUE THREAD

**Issue by FGarridoV** [IIC2115/Syllabus#22]
El formato debe ser el siguiente:

**L02.py**
```python
# Las librerías que utilicen (pondrá ejemplos)
import random
import datetime

# solucion P1a
def numero_espadas(mapa):
    # Aca programan su solucion al P1a
    return min_espadas # Debe ser un entero

# solution P2a
def ruta_de_jaime(origen, destino, mapa):
    # Aca programan su solucion al P2a
    return ruta_minima # Debe ser una tupla con una lista y un entero

# solution P2b
def motor_lobel(prefijos, historico):
    # Aca programan su solucion al P2b
    return recomendaciones # Debe ser una lista de strings

# solution P3a
def traduccion(mensaje, estructura):
    # Aca programan su solucion al P3a
    return respuesta # Debe ser una tupla de tuplas

# Pueden agregar correspondientemente otras funciones (def) que le ayuden a solucionar sus problemas. Por ejemplo, si para el problema P1a desea definir una función que haga algo, entonces debe estar definida antes de ser utilizada.





```

**Comment by Jamidd** [comment]
Para que todos tengamos el mismo estándar para medir el tiempo de las funciones. Para la revisión se medirá el tiempo de la siguiente manera. 
```
import time

def funcion():
	for i in range(1000000):
		print(i, 'Francisco es un buen profe.')

inicio = time.time()
funcion()
tiempo = time.time() - inicio

print(f'la funcion se demoro un total de {tiempo} segundos')
```

**Comment by Jamidd** [comment]
**IMPORTANTE**
el código para medir el tiempo es solo para que ustedes prueben el tiempo. El entregable **SOLO** debe contener las funciones con los nombres específicos, no debe contener código "suelto".

**Comment by alagoshurtado** [comment]
Hola! Podemos definir clases que van a ser ocupadas en nuestras funciones? Si es así, las subimos al mismo L02.py antes de definir nuestras funciones?

**Comment by pcseisdedos** [comment]
@alagoshurtado puedes definir funciones y clases auxiliares si quieres (las que debes incluir también en el .py), incluso es recomendado hacerlo para ordenar mejor el código. Lo importante es que exista una función con el nombre específico señalado arriba y que reciba y retorne lo que corresponda.

Saludos,
Pablo 😁👍

**Comment by alagoshurtado** [comment]
y debo importar esas funciones auxiliares dentro de mi función? O ustedes van a importar automáticamente todas las funciones y clases de mi archivo.py?

**Comment by pcseisdedos** [comment]
No, basta con que estén en el .py todas las funciones y clases que ocupes, luego nosotros las importamos.

Saludos,
Pablo 😁👍
