### ISSUE TITLE
Consulta input

### ISSUE THREAD

**Issue by plourido** [IIC2115/Syllabus#22]
Holaaa. Espero que se encuentren bien. Les escribo para preguntarles al momento de hacer una consulta por ejemplo encontrar los descendientes de un rut. Eso se realiza mediante input del usuario?

**Comment by RonaldoSosa** [comment]
Hola. Las consultas deben ir junto con una explicación del proceso que permite resolverlas, en dicha explicación debiesen indicar como se esperaría recibir los inputs para que se resuelva la consulta.
