### ISSUE TITLE
A1: Mision 1

### ISSUE THREAD

**Issue by RockyInDaHouse** [IIC2115/Syllabus#22]
Con respecto a la indicación "No está permitido incluir información agregada en las entidades, es decir, valores calculados que no se encuentran descritos de manera explícita en la base de datos", ¿esto está referido a los atributos?  ¿Puedo generar valores calculados como resultado de un método creado en una clase?

**Comment by halobel** [comment]
Hola, la idea de esta restricción es que no hagan cálculos asociados a las consultas al momento de cargar los datos inicialmente. El objetivo es que esos cálculos se hagan exclusivamente en las consultas, por lo que si esos métodos solo los usas cuando ejecutas las consultas y no en la carga de datos, no hay ningún problema.
Saludos

**Comment by ianmiquel** [comment]
Si defino un método en la misión 1 pero lo llamo en la misión 3 para resolver una consulta (ejemplo: objeto.resolver_consulta() ) ¿Ese método se estaría ejecutando sólo cuando lo llamo o estaría "haciendo cálculos asociados a las consultas" previamente, por escribirlo al inicio?
Saludos
