### ISSUE TITLE
Duda notas

### ISSUE THREAD

**Issue by jahernandez2** [IIC2115/Syllabus#220]
Hola! Quería saber cuanto estarán listas las notas y las recorrecciones pendientes? Mas o menos. 
Saludos.

**Comment by pcseisdedos** [comment]
Hola, las recorrecciones del laboratorio 3 las subiré mañana. Las de L04 y P04 durante la semana junto con las notas de la P05. Finalmente, las notas del L05 debieran estar a más tardar este fin de semana.

Saludos,
Pablo 😁👍
