### ISSUE TITLE
Librerías permitidas

### ISSUE THREAD

**Issue by Milena2021** [IIC2115/Syllabus#23]
Hola!
¿Hay alguna restricción respecto de las librerías que se pueden utilizar para el Laboratorio?

**Comment by fnquinteros** [comment]
Hola! Creo que es más fácil que pregunten si pueden usar alguna en particular jajaja. Tienes una en mente?

**Comment by Milena2021** [comment]
mmmm json?

**Comment by fnquinteros** [comment]
Es la idea que la ocupen 😁 saludos!
