### ISSUE TITLE
Problema 1 a): ¿Cómo es el Input "mapa" ?

### ISSUE THREAD

**Issue by JaviOrtizH** [IIC2115/Syllabus#23]
Hola! 

Queria saber si es que el input mapa para la pregunta 1a) lleva comillas como especifica la tarea (mapa = 'fGgJjJhEdDiHaGcAbCdG') o si es solo las letras tipo (mapa = fGgJjJhEdDiHaGcAbCdG) o será un archivo??

 Muchas gracias!!

**Comment by pcseisdedos** [comment]
Hola!
Recibe un string y retorna un int.

Saludos,
Pablo 😁👍
