### ISSUE TITLE
Duda misión 2 

### ISSUE THREAD

**Issue by vichoro25** [IIC2115/Syllabus#23]
Hola, en la misión 2 tengo una duda porque siento que el enunciado es demasiado abierto. Se nos pide extraer las entidades del archivo y cargarlas en objetos para luego almacenarlas en estructuras de datos que nosotros consideremos adecuadas en base a la modelación que se hizo de las entidades en la misión 1?

**Comment by pcseisdedos** [comment]
Si, se pide extraer la información del archivo movies.json, crear instancias de las clases diseñadas en la misión 1 con esta información, y guardar dichos objetos en estructuras de datos que consideren convenientes.

Saludos,
Pablo 😁👍

**Comment by RockyInDaHouse** [comment]
En base a esta misma pregunta, puede ser que dentro de mi objeto se guarden las entidades en estructuras de datos determinadas? O que mi objeto en sí conste de una lista de entidades por ejemplo?

**Comment by pcseisdedos** [comment]
Creo que te refieres a ocupar composición. Esto está permitido, incluso se recomienda en el enunciado.

Saludos,
Pablo 😁👍
