### ISSUE TITLE
funcion agregar persona

### ISSUE THREAD

**Issue by rpmalonnek** [IIC2115/Syllabus#24]
para agregar una persona al arbol/grafo cúal será el input de la función? será de un diccionario como los del archivo personas.json ?

**Comment by fjgonzalez5** [comment]
Cuando te refiera a que permitamos "pasar esos datos por input al programa", significa que tenemos que preguntar los atributos de la persona? O podriamos simplemente entregarle un diccionario con datos de la persona (de la misma manera que el archivo personas.json)  y que la funcion utilice esa informacion.

**Comment by fnquinteros** [comment]
La consulta consiste en preguntar al usuario los datos de la persona a agregar y luego crear dicha persona y agregarla al árbol que corresponda. A eso me refiero, que el usuario debe ser capaz de ingresar los datos por input y ustedes deben manejarlos como quieran para crear el nuevo objeto y colocarlo en el árbol, se entiende?

**Comment by fjgonzalez5** [comment]
Si! Perfecto, gracias
