### ISSUE TITLE
Función 4

### ISSUE THREAD

**Issue by nencinav** [IIC2115/Syllabus#24]
Al correr el código respectivo a la cuarta función de la misión 3 de la actividad, este toma alrededor de 12 minutos. ¿Esto es influyente para esta entrega o debo optimizarlo más?, en caso de esta última, ¿Cuanto es el tiempo esperado o límite para cada función?

**Comment by pcseisdedos** [comment]
Hola, a pesar de que la eficiencia no es el foco de esta actividad, si los tiempos de ejecución no son razonables (de un orden de 30 segundos), quiere decir que hay algo que estás haciendo mal, por lo que debes revisarlo

Saludos,
Pablo 😁👍
