### ISSUE TITLE
Uso de librerias externas para la tarea

### ISSUE THREAD

**Issue by ddibattista** [IIC2115/Syllabus#24]
Hola, se puede usar alguna librería para los ejercicios de la tarea?
Por ejemplo usar Networkx para el problema 2 a), y usar su metodo de A*

**Comment by JaviOrtizH** [comment]
Me sumo a la pregunta, podriamos crear un grafo usando Networkx?

**Comment by Jamidd** [comment]
Hola, se puede ocupar NetworkX pero no se pueden llamar a ningún algoritmo implementado por esta, en caso contrario se evaluará con nota 1 la pregunta. Si quieren usarlo tendría que ser únicamente para almacenar la estructura. 
Saludos,
Jaime.

**Comment by sitauscant** [comment]
Hola! Se puede ocupar las librerías numpy y heapq?

**Comment by pcseisdedos** [comment]
@sitauscant Si, pueden usarlas para el A*

Saludos,
Pablo 😁👍

**Comment by FranciscaUlloa** [comment]
Holaa! puedo importar estas librerias para la pregunta 2B?
- from random import sample, randint
- from typing import Tuple

**Comment by pcseisdedos** [comment]
@FranciscaUlloa Si se puede.

Saludos,
Pablo 😁👍
