### ISSUE TITLE
Finalización en el desplazamiento

### ISSUE THREAD

**Issue by ccornejon** [IIC2115/Syllabus#24]
Tengo una duda con respecto a lo que pasa una vez que se genera un viaje, de acuerdo a la velocidad me moveré cierta cantidad de celdas, que pasa con las personas una vez que se finaliza el desplazamiento, ¿se quedan ahí? ¿ entran a algún edificio o hogar? 
Considerando que la condición para generar viaje un viaje es que mi celda sea de vialidad y este en un borde o que este en una edificación que colinde con una celda de vialidad, entonces, si las personas quedan en una celda de vialidad ¿no podrán moverse a otro lugar en otro turno, es decir, se quedaran ahí hasta el final de la simulación?

Gracias,

**Comment by FGarridoV** [comment]
Los viajes finalizan una vez que llegan al borde. Debes contabilizar en dicha celda los viajes finalizados.

saludos
