### ISSUE TITLE
Ver tarea en GitHub

### ISSUE THREAD

**Issue by Sbaicardi** [IIC2115/Syllabus#25]
Hola! Cuando subo la tarea a mi repositorio en GitHub y luego voy al repositorio, la tarea efectivamente aparece ahí, pero si trato de abrirla para verla solo me aparece la información sobre la cantidad de líneas y el tamaño del archivo; más abajo donde debería verse el desarrollo de mi código no aparece nada. Me di cuenta que me pasa exactamente lo mismo si desde el Syllabus ingreso a la carpeta "material de clases"; si trato de abrir cualquiera de los archivos .ipynb me aparece la misma información sobre cantidad de líneas y tamaño del archivo pero nada más. Me gustaría saber a qué se debe esto y si puedo solucionarlo, ya que me preocupa que al subir mi tarea esta no se pueda luego revisar.
Gracias!

**Comment by Jamidd** [comment]
Puede ser un problema de GitHub. Si quieres asegurarte de que está todo ok podrías clonar tu repo en otra carpeta y probar que todo funciona. 
Sino, googlea el problema, de seguro a alguien mas le ha pasado. 

Jaime Middleton
