### ISSUE TITLE
Video enunciado y orden espadas P1

### ISSUE THREAD

**Issue by rscheelv** [IIC2115/Syllabus#25]
Hola! quiero consultar si subirán el video de la revisión de enunciado del jueves, porque hay una parte que no recuerdo de una de las preguntas (si es que en la P1 las espadas se van recogiendo de forma lineal o no). gracias de antemano

**Comment by pcseisdedos** [comment]
¡Hola! Tienes toda la razón, no hemos publicado el video todavía, lo vamos a gestionar para subirlo lo antes posible. Hoy en la sesión de trabajo puedes aprovechar de resolver tus dudas.

No se si entiendo tu pregunta bien, las espadas las vas encontrando en un orden pero no necesariamente tienes que ocuparlas en ese orden (recuerda que puedes comprar espadas), lo que si está prohibido es ocupar una espada que todavía no encuentras.

Saludos,
Pablo 😁👍

**Comment by rscheelv** [comment]
Perfecto! sí respondiste a mi pregunta, gracias!

**Comment by pcseisdedos** [comment]
Es mejor no cerrar issues porque la información puede ser útil para el resto, nosotros nos encargaremos de cerrarlas en su momento.
