### ISSUE TITLE
Consulta sobre los 5 actores con la trayectoria más larga

### ISSUE THREAD

**Issue by iavasquez1** [IIC2115/Syllabus#25]
En el enunciado en la misión 3 parte 3 no queda muy claro cuando se menciona la trayectoria más larga. ¿Esta considera cuantas veces ha actuado considerando todas las peliculas o se considera también el intervalo en el que está preparando también alguna película o podemos suponer que en el mismo año que se lanzó la película se prepara la pelicula?.  De antemano muchas gracias!

**Comment by CesarSoteloUc** [comment]
Tengo la misma duda si es la diferencia entre la primera y ultima película o la cantidad que ha estado activo según los años Ej
actor A hace películas en 1990,1992.1992,1997,2000, Ahí su trayectoria seria de 10 años o solo tomando los años activos siendo que no se repita(4 años ya que 1992 se repite)

**Comment by pcseisdedos** [comment]
Hola, la trayectoria es el tiempo que lleva actuando, por lo tanto sería el tiempo desde su primera película, hasta la última.

Saludos,
Pablo 😁👍
