### ISSUE TITLE
Problema con importación de Librerías, Python y Jupyter

### ISSUE THREAD

**Issue by facumiranda149** [IIC2115/Syllabus#26]
Hola, el otro día comencé a hacer una tarea de otro ramo, y quise utilizar Jupyter Notebook para hacerla, al poner "jupyter notebook" en terminal no abría y me tiraba error. Tuve que instalarlo e instalarlo otra vez, fue raro.
Una vez que logré eso, para hacer mi código debía importar "numpy" y "Matplotlib", las cuales las tenía instaladas y con su versión más reciente en el computador y no había caso, me salía en el error " No module named '*' ". Finalmente tuve que hacer mi tarea en Colab :(.
Creo que lo que cambió es que ahora mi terminal (de mac) sale "zsh". Alguien sabe que puedo hacer para solucionar el problema? Gracias!

**Comment by FGarridoV** [comment]
Si, cuando utilizas ZSH la instalación de jupyter es diferente y no queda lineada al comando "jupyter notebook"
Para eso te recomiendo que veas este video: [LINK VIDEO](https://www.youtube.com/watch?v=FxHoi_ZRV4s).

En el video explico cómo instalar jupyter cuando tienes una consola de tipo ZSH.

Saludos,
Francisco
