### ISSUE TITLE
Duda sobre eficiencia

### ISSUE THREAD

**Issue by javiernavarretet** [IIC2115/Syllabus#26]
Hola es que mi código se demora mucho en correr y quiero saber si es que descuentan si el programa se demora mucho tiempo o si el requisito es llegar a las soluciones independiente del tiempo?

**Comment by pcseisdedos** [comment]
Hola, a pesar de que la eficiencia no es el foco de esta actividad, si los tiempos de ejecución no son razonables (de un orden de 30 segundos), quiere decir que hay algo que estás haciendo mal, por lo que debes revisarlo

Saludos,
Pablo 😁👍
