### ISSUE TITLE
Mostrar familia

### ISSUE THREAD

**Issue by lucazul** [IIC2115/Syllabus#26]
En la consulta mostrar familia es necesario imprimir una representación gráfica del árbol genealógico o basta con imprimir líneas de strings del tipo:

Los hijos de Juan Carrillo y María Carrillo son : {a, b, c}
Los hijos de ...

**Comment by fnquinteros** [comment]
Hola! Deben imprimir una representación del árbol. Si buscas en Google como imprimir un árbol hay código que te puede ser muy útil.

Saludos!
