### ISSUE TITLE
problema con subirlo

### ISSUE THREAD

**Issue by tmoreno1** [IIC2115/Syllabus#26]
Hago lo mismo para subirlo al repositorio y me dice:

$ git add https://github.com/IIC2115/repositorio-2019-1-tmoreno1.git
fatal: pathspec 'https://github.com/IIC2115/repositorio-2019-1-tmoreno1.git' did not match any files

que puede ser??

**Comment by Jamidd** [comment]
Honestamente no estoy seguro que puede ser.
Para hacerlo rápido, lo más fácil es:
- copiar todos tus archivos de tu repo a otra carpeta 
- borrar la carpeta de tu repo en tu pc
- volver a clonar tu repo (git clone)
- pegar todos los archivos que guardaste
- git add .
- git commit -m ".."
- git push

Jaime Middleton
