### ISSUE TITLE
Antepasado común

### ISSUE THREAD

**Issue by memadrid** [IIC2115/Syllabus#27]
Hola, tengo una consulta.. en la función antepasado común, si le doy los rut de un padre y un hijo, ¿qué me debe retornar? ¿el padre como antepasado común? ¿ el abuelo? ¿con qué distancia?

¿Y si le doy el rut de un nieto y un abuelo (raíz de la familia)? ¿es el abuelo o digo que no tienen antepasados en común? 

Gracias :)

**Comment by fagomez2** [comment]
Hola Michelle! Como regla general, alguien nunca es antepasado de sí mismo. Por tanto, el padre y el hijo tienen como antepasado en común al abuelo. El nieto y el abuelo tienen como antepasado en común al padre del abuelo.
Sobre las distancias, deberías calcularlas como con cualquier otro parentezco, esto es el número de pasos en que llegas desde uno al otro pasando por el antepasado. En el caso del padre y el hijo, la distancia es 3 si quieres pasar por el antepasado común más cercano.
Saludos!
