### ISSUE TITLE
Resultados consultas

### ISSUE THREAD

**Issue by sofiaify** [IIC2115/Syllabus#27]
Hola! ¿existe la posibilidad de que nos entreguen los resultados de las consultas para poder comparar y ver si lo estamos haciendo bien?
Saludos

**Comment by halobel** [comment]
Hola, no consideramos entregar los resultados de las consultas para las evaluaciones de este curso, antes de que estas se entreguen. Tanto el desarrollo como el correcto resultado son importantes, por lo que tal como en la mayoría de los cursos, publicaremos una pauta con el código después de la entrega.
Saludos
