### ISSUE TITLE
Cantidad de turnos

### ISSUE THREAD

**Issue by mblejeune** [IIC2115/Syllabus#27]
Hola! Es necesario que el usuario ingrese la cantidad de turnos a realizar? Porque yo lo tengo hecho de la forma en que la cantidad de turnos está determinada por la función exponencial teniendo como el max de turnos el número maximo que me entrega este en alguna de las casillas dentro de la matriz

**Comment by Jamidd** [comment]
En el enunciado sale:
La generación de eventos en la simulación terminará una vez que se hayan cumplido t turnos, donde
t es una constante predefinida, **entregada** a la simulación.

Jaime Middleton
