### ISSUE TITLE
Tamaños y tiempos en L02 (+ data pregunta 2b)

### ISSUE THREAD

**Issue by FGarridoV** [IIC2115/Syllabus#27]
Estimados,

Como se indica en el enunciado del L02, parte del puntaje de cada problema es por la correctitud y tiempo de ejecución. Se evaluara cada problema con 3 tamaños diferentes, y en cada tamaño se evaluará la correctitud y tiempo de ejecución como se indica a continuación:

1. **Tamaño pequeño**: Cada pregunta se ejecutará con varios *inputs* pequeños
     - Correctitud: Debes tener todas las ejecuciones correctas para obtener este puntaje, sino, se obtienen 0 puntos.
     - Tiempo: El promedio del tiempo de solución de todas las soluciones debe ser menor o igual a 1.5 segundos (solo si todas fueron correctas) y el tiempo de cada solución debe ser menor a 2 segundos, si no, se obtienen 0 puntos.
1. **Tamaño mediano**: Cada pregunta se ejecutará con varios *inputs* medianos
     - Correctitud: Debes tener todas las ejecuciones correctas para obtener este puntaje, sino, se obtienen 0 puntos.
     - Tiempo: El promedio del tiempo de solución de todas las soluciones debe ser menor o igual a 1.5 segundos (solo si todas fueron correctas) y el tiempo de cada solución debe ser menor a 2 segundos, si no, se obtienen 0 puntos.
1. **Tamaño grande**: Cada pregunta se ejecutará con varios *inputs* grandes
     - Correctitud: Debes tener todas las ejecuciones correctas para obtener este puntaje, sino, se obtienen 0 puntos.
     - Tiempo: El promedio del tiempo de solución de todas las soluciones debe ser menor o igual a 1.5 segundos (solo si todas fueron correctas) y el tiempo de cada solución debe ser menor a 2 segundos, si no, se obtienen 0 puntos.

**Les recuerdo mirar esta issue #22, que tiene información de como pueden medir los tiempos (en Google Colab) y el formato de entrega del .py**

A continuación se detallan los tamaños de *input* por problema:

## Problema 1
**1. Pequeño:** 
```python
len(mapa) = 20
```
**2. Mediano:**
```python
 len(mapa) = 10000
```
**3. Grande:** 
```python
len(mapa) = 200000
```

## Problema 2a
**1. Pequeño:** 
```python
len(mapa) = 10
len(mapa[0]) = 10
```
**2. Mediano:**
```python
len(mapa) = 50
len(mapa[0]) = 50
```
**3. Grande:** 
```python
len(mapa) = 100
len(mapa[0]) = 100
```

## Problema 2b
**1. Pequeño:** 
```python
len(prefijos) = 5
len(historico) = 20
```
**2. Mediano:**
```python
len(prefijos) = 100
len(historico) = 250
```
**3. Grande:** 
```python
len(prefijos) = 3000
len(historico) = 5000
```

### Problema 3
**1. Pequeño:** 
```python
len(mensaje) = 8
len(estructura) = 3 # La estructura tendrá un máximo de 10 letras diferentes
```
**2. Mediano:**
```python
len(mensaje) = 10
len(estructura) = 5 # La estructura tendrá un máximo de 10 letras diferentes
```
**3. Grande:** 
```python
len(mensaje) = 15
len(estructura) = 11 # La estructura tendrá un máximo de 10 letras diferentes
```

Cualquier consulta, no duden en escribir comentando esta issue

**Comment by Jamidd** [comment]
Adentro de la carpeta Laboratorios cree la carpeta L02-2b con un archivo txt y un script de python con una función que les entrega la información necesaria para probar el problema 2b de la tarea.

**Comment by clementeramirez** [comment]
hola! en la pregunta 2b, si entregan un prefijo vacio, retornamos la frase mas repetida de los historicos, aunque esta ya se haya retornado para otro prefijo? por ejemplo, si mi base de historicos es: historico = [(5, 'llama'), (6, 'llamar'), (12, 'llueve'), (4, 'llueve hoy'), (7, 'es'), (5, 'estructura'), (2, 'estas'), (6, 'estas aca')] y mis prefijos son: prefijos = ['llam', 'est', 'llu', '']
debe retonar ['llamar', 'estas aca', 'llueve', 'llueve'] o ['llamar', 'estas aca', 'llueve', 'llueve hoy']?

**Comment by paulavonbrand** [comment]
Hola @Jamidd sobre el archivo que subiste, si mi código funciona con eso esta ok? El input como txt es como será corregido despúes? estoy un poco perdida acerca de ello.Gracias!

**Comment by Jamidd** [comment]
La información la tenemos en un .txt para que sea mas fácil de manejar, sin embargo ustedes tienen que aceptar una lista como se menciona en el enunciado. Por eso les dimos la función que lee el archivo y genera la lista con la información. Mientras tu código funcione con lo que retorna la función que les entregamos esta todo ok. 
PD. tenemos hasta 100.000 datos para el histórico, así que les recomiendo fuertemente implementar el trie y no irse por la fuerza bruta.

**Comment by BereVF** [comment]
Hola! @Jamidd @FGarridoV  una duda; si en algún tamaño no se cumple la correctitud o el tiempo, entonces en este ítem (tiempo y correctitud, 50%), toda la pregunta tendrá 0 puntos, o solo se quitará un puntaje parcial?
Graciasss!

**Comment by martincrasemann** [comment]
Hola
Una pregunta respecto a los tamaños de los inputs de la pregunta 3. Aqui ponen que el input más grande que probaran es de len(mensaje)=15 pero en los ejemplos que han subido todos los mensajes tienen len mayor a 20. ¿Esto influye en algo?¿Hay algo que este entendiendo mal?

**Comment by pcseisdedos** [comment]
@BereVF cada pregunta y tamaño tiene su puntaje asociado (los puntajes de los tres tamaños sumados corresponden al 50%), son independientes entre si, y se evalúan de forma binaria, es decir, si no se cumple alguno de los criterios se asigna 0 puntos en esa pregunta-tamaño, pero no en toda la pregunta. Por ejemplo, podrías tener los puntajes de los tamaños pequeño y mediano de la pregunta 1 pero no el grande si en ese no se cumple alguno de los criterios.

En esta tabla se muestran los puntajes correspondientes
| Pregunta |	Tamaño          | Puntaje |
| :-: | :-:| :--------: |
| 1   | Pequeño   |  0.16     | 
| 1   | Mediano   |  0.16     | 
| 1   | Grande     |  0.17     | 
| 2a | Pequeño   |  0.25     | 
| 2a | Mediano   |  0.25     | 
| 2a | Grande     |  0.25     | 
| 2b | Pequeño  |  0.25     | 
| 2b | Mediano  |  0.25     | 
| 2b | Grande    |  0.25     | 
| 3   | Pequeño  |  0.33     | 
| 3   | Mediano  |  0.33     | 
| 3   | Grande    |  0.34     | 

@martincrasemann el criterio del tiempo se evaluará respecto a lo que se publicó [aquí](https://github.com/IIC2115/Syllabus/issues/27#issue-690688973), los inputs de ejemplo son solo para que ustedes puedan probar sus soluciones.

Saludos,
Pablo 😁👍
