### ISSUE TITLE
Problema administrativo con Github

### ISSUE THREAD

**Issue by vgrivera** [IIC2115/Syllabus#28]
Al parecer el lunes pasado subí mal el archivo al repositorio y acabo de ver que tengo una subcarpeta dentro de mi repositorio. Mi archivo del día lunes quedo dentro de la carpeta L01 con nombre Untitled.ipynb
¿Está bien tener esa subcarpeta dentro de mi repositorio ? Estuve mucho tiempo intentando eliminarla (lo hice en la carpeta de mi computador, sin embargo sigue existiendo en github). 

Gracias

**Comment by Jamidd** [comment]
En el enunciado sale que la entrega es:
• Lugar: repositorio privado en GitHub. Recuerde incluir todo en una carpeta de nombre L01.

Jaime Middleton
