### ISSUE TITLE
Duda sobre las funciones de la M3

### ISSUE THREAD

**Issue by Tomas-GrayD** [IIC2115/Syllabus#28]
Existe la posibilidad de responder las consultas sin llamar a los objetos creados en la M2? sino hacerlo de forma independiente,  creando funciones que utilizen estructuras de datos tales como diccionarios, listas, tuplas, lo digo porque para alguien puede que le resulte resulte mucho conveniente hacerlo de esa manera, ya que al relacionar las misiones puede que haya mas errores y/o problemas. 

Saludos.

**Comment by pcseisdedos** [comment]
No, el objetivo de la actividad apunta directamente a eso.

Saludos,
Pablo 😁👍
