### ISSUE TITLE
output backtracking

### ISSUE THREAD

**Issue by clementeramirez** [IIC2115/Syllabus#28]
Hola, en el problema de backtracking, con el input de 'elaguaeselaguaeselpez'  y con la estructura 'A B B C', mi codigo retorna en el output (('A', 'e'), ('B', 'laguaese'), ('C', 'lpez')), que revisandolo igual seria valido para lo que se pide. Esto estaría mal? Porque el output de ejemplo es ((’A’, ’el’), (’B’, ’aguaesel’), (’C’, ’pez’))
Muchas gracias

**Comment by Jamidd** [comment]
Mientras la recombinación del patrón con la información que entregue tu función sea correcto, no hay problema. Muchas veces hay mas de una opción para cada patrón. 
Ejemplo: 
con la frase 'hola' y patrón 'ABC' tenemos las opciones:
h-o-la
ho-l-a
h-ol-a
