### ISSUE TITLE
Consulta T1: M1

### ISSUE THREAD

**Issue by plourido** [IIC2115/Syllabus#29]
Estimados, junto con saludarlos y desearle una buena tarde, les escribo ya que tengo una pequeña confusión respecto a la definición de servicio en el contexto de la tarea
Muchas gracias

**Comment by RonaldoSosa** [comment]
Hola. El servicio en el contexto de la tarea se refiere al número de la línea del bus, el cual estaría determinado por el line_id. Sin embargo, en los datos proporcionados podrán observar que siempre se repite el mismo valor en todas las filas, esto fue un error con los datos y ya ha sido reportado, en la brevedad se subirán datos que tendrán distintos valores de line_id(servicios).

**Comment by RonaldoSosa** [comment]
Hola. Ya se subió la base de datos y el enunciado también se actualizo.
