### ISSUE TITLE
A1: duda de los resultados

### ISSUE THREAD

**Issue by rafuenz** [IIC2115/Syllabus#29]
¿Los resultados deben ser impresos en algún formato?, es decir, si van dentro de una lista, diccionario, tupla, etc. ¿O deben ser impresos como un string?

**Comment by pcseisdedos** [comment]
Deben ser impresos de forma en que se logre visualizar y entender fácilmente el resultado de la consulta. No se especifica un formato en particular, por lo que eres libre de elegir.

Saludos,
Pablo 😁👍
