### ISSUE TITLE
Github

### ISSUE THREAD

**Issue by kdcarreno** [IIC2115/Syllabus#29]
Cómo puedo encontrar rápido el repositorio donde subo mis archivos? Hasta ahora si voy al icono de mi user (arriba a la derecha) y luego hago click en "tus repositorios" me sale todo vacío. He estado entrando desde el link de mail para compartir y ahí recien puedo ver mis archivos.

**Comment by fagomez2** [comment]
Hola Karla! En "Your profile" > Overview te saldrá información de los últimos repositorios que has editado. Además, puedes clicker "Star" en tus repositorios para marcarlos como favoritos, esa es otra forma de encontrarlos rápidamente.
Saludos!
