### ISSUE TITLE
Descendiente más lejano [Lab02]

### ISSUE THREAD

**Issue by javierpenafiel** [IIC2115/Syllabus#29]
Hola! En la consulta descendiente más lejano, si pregunto a alguien que no es papa, pero su hermano tiene un hijo (es decir, la persona del rut dado tiene un sobrino), este cuenta como descendiente más lejano o no?

**Comment by fagomez2** [comment]
Hola Javier! Hay dos formas de pensarlo:
1. Descendiente es alguien que se encuentra en un nivel inferior al mío en el árbol de la familia. Si lo piensas de esta forma, un sobrino podría ser el descendiente más lejano
2. Descendiente es alguien a quien puedo llegar con una línea recta hacia abajo desde mí, como hijos, nietos, bisnietos, etc. En este caso, el sobrino no contaría como descendiente más lejano

Lo importante en esta pregunta es que decidas un criterio y lo especifiques en el README. Mientras seas consistente con lo que definiste no habrá ningún problema.

Saludos!
