### ISSUE TITLE
Duda con las clases y turnos

### ISSUE THREAD

**Issue by jlcasanova2** [IIC2115/Syllabus#3]
Cuando en la simulacion vaya recorriendo la matriz de la ciudad, no se me ocurre como decir que la celda que tenga valor 0 por ejemplo, se le asigne la clase que corresponde al Hogar

Y por ejemplo en un turno, se generan viajes del hogar, y esos se trasladan en el modo en el mismo turno, o debo esperar un turno para que se muevan?

Gracias

**Comment by FGarridoV** [comment]
No entiendo bien a qué te refieres con "simulación recorriendo la ciudad", la simulación es el proceso de turnos donde se mueven las entidades por la ciudad. No es necesaria una asignación directa de una clase a una celda, lo que necesitas hacer es tener conocimiento cuáles son las celdas hogar, dado que en cada turno necesitas saber si generan viajes o no.

respecto a tu segunda pregunta, si, el momento que se genera el viaje aparece la entidad en la vialidad correspondiente. A partir del siguiente turno se comienza a mover.

Saludos,
Francisco

**Comment by FGarridoV** [comment]
No es mala idea. Por ejemplo tener una colección o lista de objetos hogar/oficina/vialidad que sean la ciudad. A lo que me referia con asignación directa es que no es necesario asignar un número a una clase, sino que basta con tener la clase.

saludos,
Francisco
