### ISSUE TITLE
Duda 2a. Algoritmo de A* (LAB2)

### ISSUE THREAD

**Issue by VicenteDelRio** [IIC2115/Syllabus#30]
Hola
Hay algo que todavía no tengo muy claro.
Para seleccionar la casilla a la que nos movemos lo hacemos eligiendo el f de menor valor.
Y tenemos f=g+h
En el ejemplo del laboratorio se mueve del (1,2) al (2,1), pero por lo que tengo entendido se debería mover al (1,1) porque:
(2,1)--> g=8     h=8(Manhattan)  h=5,8(euclidiana)  f=16 o 13,8
(1,1)-->g=2      h=9(Manhattan)  h=6,4(euclidiana)  f=11 o 8,4
En ambos casos el f del (1,1) sería menor.
Pero se que no tiene sentido que se mueva para el (1,1) porque de hecho después baja al (2,1).
Por lo que ¿En que parte estoy fallando? O por cuanto se debe ponderar el valor de h
Saludos

**Comment by Jamidd** [comment]
Hay un par de detalles:
- el output es la solución optima, no el orden con el que fue revisando los nodos. (8 < 2+7)
- existen MUCHAS heurísticas, no solo distancia Euclidiana y Manhattan. 
Saludos, 
Jaime.

**Comment by Leda7** [comment]
aun no entiendo mucho esto, porque a mi me ocurre que al analizar los vecinos, el que mas le conviene es el (1,1) porque como se dice mas arriba es el que tiene menor f.

**Comment by pcseisdedos** [comment]
Disculpa por la demora, se nos pasó tu mensaje. Tal como indica Jaime, les recomiendo probar con distintas heurísticas.

Saludos,
Pablo 😁👍
