### ISSUE TITLE
Agregar personas - guardar en el sistema

### ISSUE THREAD

**Issue by fjgonzalez5** [IIC2115/Syllabus#30]
Al agregar una persona, quedandose esta en una familia, o creando una familia nueva, esta familia actualizada o familia nueva debe quedar guardada en el sistema? O podriamos usar un grafo auxiliar que solo sirva para demostrar que se agrego o no a la familia.

**Comment by fnquinteros** [comment]
No es necesario que se mantenga guardada en el sistema. Basta con que al agregarla quede en el grafo/árbol, cosa que si, por ejemplo, yo pidiera imprimir el árbol, la nueva persona aparezca en él. Si igualmente quieres agregarla al archivo .json y que se mantenga en el sistema , bienvenido sea jajaj 👍
