### ISSUE TITLE
Problema al subir la tarea

### ISSUE THREAD

**Issue by niherrera** [IIC2115/Syllabus#30]
Cuando subo el archivo a la plataforma de Git hub se crea automáticamente una carpeta que se llama igual que el archivo.checkpoints. ¿Qué puedo hacer para que no aparezca?

**Comment by fagomez2** [comment]
Hola! ¿Cómo lo estás subiendo? Me interesa, no me había pasado que se te genera un archivo automáticamente.

Para futuras referencias, puedes crear un archivo llamado **.gitignore** para ignorar archivos y que no se suban junto con el resto de tus archivos importantes. Te dejo un link que te puede servir:
https://swcarpentry.github.io/git-novice-es/06-ignore/
