### ISSUE TITLE
Restricciones de información agregada y métodos en clases

### ISSUE THREAD

**Issue by ianmiquel** [IIC2115/Syllabus#30]
Entiendo que en las clases que creemos no puedo incluir, por ejemplo, un diccionario que guarde información procesada de una función, y por ende no podemos llamar después de nuestro objeto dicho diccionario. Sin embargo, ¿puedo crear diccionarios, listas, etc. en los **métodos** pertenecientes a estas clases, y que dichos métodos sólo retornen información? tipo actores.mas_populares() retorna los actores mas populares

**Comment by halobel** [comment]
Hola, por favor revisa la respuesta a la [issue 22](https://github.com/IIC2115/Syllabus/issues/22#issuecomment-815181078).
Saludos
