### ISSUE TITLE
Tarea1: M3

### ISSUE THREAD

**Issue by Mariaignacia22** [IIC2115/Syllabus#30]
la distancia recorrida se refiere a ''la foto del kilometraje que marca el bus'' o la distancia desde el punto de origen

**Comment by RonaldoSosa** [comment]
Hola. La distancia recorrida, refiriéndose a lo dicho en la descripción para la columna  distance_kms, se refiere a los kilómetros que ha recorrido el bus desde su despacho hasta el instante de la medición GPS. Por ejemplo digamos que una medición tiene un gps_time de 2018-07-31 20:02:02, un dispatch_time de 2018-07-31 20:01:32 y un distance_kms de 0.6318157221232613. Esto indica que ha recorrido 0.6318157221232613 kms desde 2018-07-31 20:01:32 hasta 2018-07-31 20:02:02.

**Comment by Mariaignacia22** [comment]
Entonces la distancia recorrida solo podría ir aumentando? Si encuentro casos en los que disminuya, lo asumo error del dataframe? Por último, cuál sería la diferencia con total_kms?

**Comment by mbertin1** [comment]
Se puede usar la libreria datetime  para manejar los tiempos??

**Comment by RonaldoSosa** [comment]
Dada su definición la distancia recorrida solo podría ir aumentando, no debiese haber casos en los que disminuya. Con esto me refiero a que por ejemplo, digamos de que se tienen dos mediciones, llamémoslas "M1" y "M2" ambas con el mismo expedition_id, pero el gsp_time de "M2" es mayor que el de "M1" en ese caso el valor de distance_kms de "M2" debiese ser mayor que el de "M1". Con respecto a total_kms este último se refiere al total de kilómetros que el bus debiese de recorrer en su totalidad durante la expedición.
