### ISSUE TITLE
Descendiente más lejano

### ISSUE THREAD

**Issue by gevicencio** [IIC2115/Syllabus#31]
Hola, para descendiente más lejano, si le doy el rut de un cónyuge la función debería retornar algo? o la función solo aplica para los familiares que posean el mismo apellido?

**Comment by fagomez2** [comment]
Hola Gonzalo! Creo que lo mejor es que respondas con un "la persona no tiene descendientes registrados" o algún otro mensaje de ese estilo. 

La función está pensada para preguntar por descendientes de alguna de las familias principales, pero igual deberías responder algo en caso de que se pregunte por un cónyuge o por alguien que no tiene descendientes.

Saludos!
