### ISSUE TITLE
No entiendo bien PseudoCódigo de A* en material de clases

### ISSUE THREAD

**Issue by Popper** [IIC2115/Syllabus#31]
hola.
En la parte donde código empieza a compara las funciones g de los vecinos.(despues del else)
NO entiendo cuál es la diferencia entre las dos primeras condicionales ("if ","elif") ,  ya que hacen lo mismo solo cambia condición de donde se encuentra vecino. Pero por lo que yo entendí los vecinos que estaban en la cola cerrada no se actualizaba la función g

![pseudo codigo](https://user-images.githubusercontent.com/69559146/92152756-32004080-edf1-11ea-8288-3d4cc468ef34.png)

**Comment by Jamidd** [comment]
Otro posible pseudocodigo puede ser:
```
cerrado = lista vacia
abierto = lista con el primer nodo (nodo_de_inicio)

mientras abierto no este vació:
	nodo = nodo perteneciente a la lista abierto con el menor valor de F

	agrega nodo a cerrado

	si nodo es el objetivo:
		terminamos

	para cada nodo_vecino en los vecinos de nodo:

		si nuevo valor de g menor a valor antiguo:
			actualizamos actualizamos valor de g
			padre de nodo_vecino es nodo

			si nodo_vecino no esta en abierto:

				si nodo_vecino esta en cerrado:
					sacarlo de cerrado

				agregar nodo_vecino a abierto
```

Si sigues sin entenderlo, responde a la issue y lo vemos. 
Saludos, 
Jaime

**Comment by VicenteScholl** [comment]
a que se refieren con lista abierta y lista cerrada? que representan?

**Comment by carlos-bertoglio** [comment]
Hola! yo no entendí el pseudocódigo y me basé en un pseudocódigo de un ppt del ramo flujo en redes que hice el semestre pasado, es válido?

**Comment by pcseisdedos** [comment]
@VicenteScholl disculpa por la demora, se nos pasó tu comentario. La idea es la misma que en Dijkstra (con nodos abiertos y cerrados).

@carlos-bertoglio Si, en Flujo en Redes lo vemos con un concepto de incumbente, pero en esencia es lo mismo.

Saludos,
Pablo 😁👍

**Comment by pcseisdedos** [comment]
La lista cerrada es para los nodos que ya has visitado, cosa de no hacerlo de nuevo. La lista abierta es la de los que tienes que visitar, pero no todos los del mapa, sino los que podrías visitar en el siguiente paso (los vecinos de los ya visitados).

Saludos,
Pablo 😁👍
