### ISSUE TITLE
Problema con la librerías game y arcade

### ISSUE THREAD

**Issue by sidiaz2** [IIC2115/Syllabus#31]
Hola, la librería me tira a mi y a varios compañeros más el siguiente error

/anaconda3/lib/python3.7/site-packages/pyglet/gl/cocoa.py in attach(self, canvas)
    287         # The NSView instance should be attached to a nondeferred window before calling
    288         # setView, otherwise you get an "invalid drawable" message.
--> 289         self._nscontext.setView_(canvas.nsview)
    290         self._nscontext.view().setWantsBestResolutionOpenGLSurface_(1)
    291         self.set_current()

AttributeError: 'NoneType' object has no attribute 'setView_'

no me deja avanzar y un ayudante me dijo que borrara anaconda por el tema de la versión de python, pero no creo que sea la solución.

Qué puedo hacer?

**Comment by FGarridoV** [comment]
Estamos trabajando en este error, esperamos hoy tener una solución.

Saludos,
Francisco

**Comment by vnramirez** [comment]
Vale la pena ir definiendo todas las clases con sus métodos y todo si no
sabemos bien como funciona lo de game arcade? O mejor esperamos a que sea
arreglado?

Gracias.

**Comment by halobel** [comment]
Sigue trabajando en las clases de todas maneras. La parte gráfica es realmente muy poco código, por lo que el grueso del trabajo lo puedes hacer si tenerla.
