### ISSUE TITLE
A1, duda acerca del uso de herencia 

### ISSUE THREAD

**Issue by Javiera205** [IIC2115/Syllabus#31]
¿Es obligación usar herencia para la actividad o es solamente una recomendación?

**Comment by pcseisdedos** [comment]
Debes modelar las clases aplicando la materia del curso. Si crees que la mejor forma de hacerlo es sin ocupar herencia, entonces hazlo de esa forma, mientras esté bien modelado no debieras tener problemas.

Saludos,
Pablo 😁👍
