### ISSUE TITLE
T1: M10

### ISSUE THREAD

**Issue by plourido** [IIC2115/Syllabus#31]
Hola, buenas noches, espero que se encuentren bien. Les escribo ya que no entiendo mucho lo que me preguntan en la M10. Me podrían dar un poco mas de detalle por favor. Muchas gracias

**Comment by RonaldoSosa** [comment]
Hola. En que aspecto de la misión 10 tienes dudas?

**Comment by jorgee02** [comment]
Hola, existe algún número estimado de features para agrupar?
Pienso hacerlo con 2 variables que estimo relevantes, y así podría graficarlo en 2D. Soy consciente de que pueden ser 3, por ejemplo, y hacerlo en 3D. Por ahí va mi duda. 
Saludos

**Comment by RonaldoSosa** [comment]
Hola. No existe un número estimado de features, sin embargo, debes considerar que el número de features puede afectar a la precisión de la agrupación y la eficiencia del algoritmo de agrupación, una recomendación sería que probarán con distintos números de features que estimen relevantes hasta conseguir un resultado con el que estén satisfechos. Si te preocupa la dimensionalidad de tus gráficos, hay técnicas de reducción de dimensionalidad para facilitar la visualización que provee sklearn.
