### ISSUE TITLE
Problema librería arcade

### ISSUE THREAD

**Issue by icandrade** [IIC2115/Syllabus#32]
Hola,

Seguí las instrucciones de reinstalar jupyter y aún sigo teniendo inconvenientes con la librería. Me aparece el error `NoSuchConfigException`. Para verificar si el error no era específicamente de jupyter, decidí correr el código directamente del `cmd` y sigo teniendo el mismo error.

Espero puedan responder a la brevedad, muchas gracias.

Saludos

**Comment by Jamidd** [comment]
Como ayer se dijo en clases, la librería tiene unos errores. Cuando esté funcionando se les avisará. Pueden avanzar sin problemas en su código sin tener la librería, ya que esta es solo para "mostrarlo bonito" al final. 

Jaime Middleton

**Comment by sidiaz2** [comment]
Pucha, yo creo que al contrario, es súper difícil avanzar sin la librería porque podemos escribir muchas líneas de código que no vamos a saber si están funcionando (además de considerar que la mayoría estamos con 40 créditos más). ¿Tienen un estimado de cuándo estará disponible la librería y cuánto van a correr la entrega? Gracias.

**Comment by Jamidd** [comment]
No necesitas que esté la libreria para ver si tu juego funciona. Puedes imprimir tu matriz de juego en cada integración y revisar que está funcionando bien. 
Lo único que hace la libreria es poder visualizar "bonita" la tarea. 

Jaime Middleton

**Comment by roaastudillo** [comment]
Dado que todavía no se arregla este problema, ¿ya se movió el plazo de entrega de la tarea, o sigue fija para el jueves?

Saludos :)

**Comment by jlcasanova2** [comment]
pregunto lo mismo que @roaastudillo ya que como no pude importar game.py tengo que definir varias cosas del tablero por mi mismo, y tampoco sería la idea que defina todo y luego tenga que redefinir todas las clases si es que se arregla el archivo game.py

Saludos

**Comment by Jamidd** [comment]
No te puedo confirmar que van a dar mas tiempo. Sin embargo, si estas haciendo bien la tarea, al agregar la librería "game.py" no deberías cambiar nada de tu código y solo agregar unas pocas lineas.

**Comment by sidiaz2** [comment]
En ese caso podrían considerar no tener que utilizar la librería? Ha dado puros problemas, y ya pasó la mitad del tiempo de la entrega, estamos en semana de pruebas y no podemos estar pendientes a que lo arreglen contra el tiempo

**Comment by halobel** [comment]
Como mencioné durante la sesión del lunes, desde el momento en que arreglemos el problema comenzará a correr el tiempo de entrega. Por lo tanto no es necesario que te preocupes del plazo, o que estés pendiente de un arreglo contra el tiempo. Solo basta que hagas "watch" de las issues para poder estar al tanto de las novedades.
