### ISSUE TITLE
Función Mostrar Familia

### ISSUE THREAD

**Issue by camallea** [IIC2115/Syllabus#32]
Hola! Tengo una duda para imprimir la representación gráfica de esto. Mi duda es, por ejemplo, para la familia Carrillo, ¿está bien imprimirlo así? (Asumiendo que ----- es un Tab)

Daniel
Maria
------Justin
------Rhonda
 -----Jessica
Manuela
Justin
------April
------James
------Jose
------Steven
Roberto
Rhonda
-----Jon
-----Leslie

O debe ser tipo: 
Daniel
Maria
-----Justin
-----Manuela
---------------April
---------------James
---------------Jose
---------------Steven

Porque se entendería que Manuela también sería hija de Daniel y Maria. 

Quedo atenta!
Gracias

**Comment by fagomez2** [comment]
Hola Carolina! Creo que tu segunda opción es mejor porque se observan más fácilmente las jerarquías, en este caso, el hecho de que April, James, Jose y Steven son nietos de Daniel y María.

En general, mientras se pueda ver el árbol con las jerarquías de forma ordenada, va a estar bien.

Saludos!

**Comment by nmcarvajalcortes** [comment]
Hola Felipe,
Es que en el enunciado dice que hay que agregar a los cónyuges, pero si usamos la segunda opción, se entiende que Manuela es hija de Daniel y María, siendo de que ellos solo tienen un hijo, Justin, y Manuela es la cónyuge de Justin.

**Comment by fnquinteros** [comment]
Agrega al árbol los apellidos o la inicial para dejar claro de qué familia son :+1:

Saludos!
