### ISSUE TITLE
Actualización de valor g en A* (Problema 2a, L02)

### ISSUE THREAD

**Issue by JaviOrtizH** [IIC2115/Syllabus#32]
Hola!

Tengo una duda acerca de la actualización del valor g del nodo en el que estamos, ya que tendríamos un valor para g en este nodo (nodo actual, 1), y luego si voy a un nodo vecino (2) en el que subo de altura, la energía consumida sería h2 - h1 + 1 (como dice el enunciado), pero al valor de g (que sería la energía consumida hasta 1) ahora sería la energía consumida hasta 1 más lo mencionado antes? (esto es h2 - h1 + 1 )

Gracias!!

**Comment by Jamidd** [comment]
En A* hay tres valores importantes para cada nodo. Está G(nodo) que es el costo mínimo con el que haz logrado llegar a ese nodo desde el inicio, esta H(nodo) que es tu heurística desde ese nodo (AKA. tu mejor estimación, SIN SOBRESTIMAR, de cuanto te va a costa llegar al nodo final) y F(nodo) que es igual a G(nodo) + H(nodo). Por lo que si estas en un nodo `n_1` y te mueves a un nodo vecino `n_2`, nos queda que `G(n_2) = min(G(n_2), G(n_1) + energia_para_ir_de(n_1, n_2))`. 
Saludos. 
Jaime

**Comment by JaviOrtizH** [comment]
Super muchas gracias!
