### ISSUE TITLE
T1: M8

### ISSUE THREAD

**Issue by plourido** [IIC2115/Syllabus#32]
Hola, buenos días, espero que se encuentren bien. Les escribo ya que tengo una duda en la M8 de la tarea. Ya logro graficar los tiempos en días de semanas pero mi duda surge al momento de como saber la distribución de  los tiempos de viaje en días laborales. A simple vista no se ve un gráfico de una distribución conocida
Muchas gracias
Que tengan buen fin de semana

**Comment by mbertin1** [comment]
Al hablar de rango de dos horas se refiere a que este grafico es de 0 a dos horas?? O se refiere a que hay que separar de a bloques de 2 horas los tiempos. Creo que debe ser la primera porque los tiempos de viaje no son muy largos pero es para confirmar

**Comment by RonaldoSosa** [comment]
Hola @plourido . Respecto a lo que preguntas no se esperaría que los gráficos tengan una forma de una distribución conocida, por ejemplo distribución normal u otra. Se esperaría que logren generar un gráfico y en base a este den una explicación del motivo que sean así.

**Comment by RonaldoSosa** [comment]
Hola @mbertin1 . La idea es que agrupen las horas del día en bloques de a dos horas.

**Comment by Josefinafp** [comment]
Hola! En esta pregunta se debe calcular el gráfico para los días de semana agregados (promedio para lunes a viernes) para cada intervalo, o se debe mostrar el promedio de cada día para cada intervalo? Tengo la misma pregunta para el fin de semana.
