### ISSUE TITLE
Reparto repetido actores

### ISSUE THREAD

**Issue by vichoro25** [IIC2115/Syllabus#33]
Tengo una duda sobre la última consulta, cuando nos piden el reparto de actores que más se repite es el conjunto de actores en su totalidad? Por ejemplo, si tengo el reparto de actores actor1, actor2 y actor3, estos tres tienen que repetirse en conjunto en otras películas o también las posibles combinaciones entre ellos, por ejemplo las siguientes combinaciones también contarían como reparto de actores: actor1 y actor2, actor1 y actor3, actor2 y actor3.

**Comment by pcseisdedos** [comment]
Debe repetirse el reparto completo.

Saludos,
Pablo 😁👍
