### ISSUE TITLE
Problemas al printear en editor de texto

### ISSUE THREAD

**Issue by iasantibanez** [IIC2115/Syllabus#33]
hola, con mi compañero tenemos el siguiente problema printear la función mostrar_familia() desde un editor de texto (Notepad++ y atom);

  File "C:\Users\XXX\AppData\Local\Programs\Python\Python37-32\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u250c' in position 18: character maps to <undefined>

mientras que usando el IDE Shell de Python , anda ok:
![captura](https://user-images.githubusercontent.com/42156288/45259974-a8f3d180-b3af-11e8-8deb-2b53a343bdbe.PNG)

he tratado de solucionar dicho problema (pero aun no lo logro), por otro lado esto puede afectarnos a la hora de la corrección?

Gracias de antemano

**Comment by fnquinteros** [comment]
No te preocupes por eso 😊. 

Saludos!
