### ISSUE TITLE
Error libreria

### ISSUE THREAD

**Issue by ccgarcia** [IIC2115/Syllabus#33]
Instalé el modulo arcade y al correr las lineas:
miJuego = game.LostGame()
miJuego.setup()
me abre una pestaña en blanco que no responde y que al cerrarla se reinicia Jupyter

**Comment by rastasoldat** [comment]
Me pasa el mismo error. Trate usar la librería arcade usando python directo y usando spyder y pasa lo mismo.

**Comment by ccgarcia** [comment]
Lograste solucionar ese problema??

**Comment by Jamidd** [comment]
Revisar #32 

Jaime Middleton
