### ISSUE TITLE
T1: M4

### ISSUE THREAD

**Issue by Fopazov** [IIC2115/Syllabus#33]
Me surgió una duda. Para la construcción del gráfico con la velocidad media, ¿se debe calcular la media de las velocidades instantáneas del recorrido en cuestión o usar la distancia que se alcanza una vez que pasa todo el tiempo (distancia máxima / tiempo final)?

**Comment by Fopazov** [comment]
O se debería usar la distancia total que el bus debería recorrer?

**Comment by RonaldoSosa** [comment]
Hola. Debiesen de calcular la velocidad media como (distancia recorrida)/(tiempo de viaje).

**Comment by Fopazov** [comment]
gracias
