### ISSUE TITLE
Formato Entrega

### ISSUE THREAD

**Issue by pmiquelv** [IIC2115/Syllabus#34]
El formato de entrega pide solo un archivo .py y otro .ipyng, para poder mantener mejor orden dentro del código, se pueden entregar 2 archivos .py y 2 arvhivos .ipyng?? Uno con las funciones y otro con el "Run" o la consola misma.

**Comment by fagomez2** [comment]
Hola Pedro! La idea de los archivos `.ipynb` es que separes por celdas y de esa forma mantienes el código ordenado dentro de un mismo archivo, por lo tanto, no necesitas tener varios archivos e importar uno en el otro (de hecho, ni siquiera estoy seguro de que esto sea posible).

Con respecto a los `.py`, lo que dices es una buena prácitca, pero por simplicidad les pedimos que hagan todo en un solo archivo (además, recuerda que el `.ipynb` debe ser igual al `.py`).

Saludos!
