### ISSUE TITLE
problema con Librería Arcade

### ISSUE THREAD

**Issue by ekuncars** [IIC2115/Syllabus#34]
Al tratar de correr las líneas vistas hoy en clases, me sale este problema:

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-75-c4d540b27e35> in <module>()
      1 import random
      2 import math
----> 3 import game
      4 import arcade
      5 

~\Documents\...
      1 import random
----> 2 import arcade
      3 import time
      4 
      5 #Parametros

ModuleNotFoundError: No module named 'arcade'

Hay alguna solución?

**Comment by pcseisdedos** [comment]
@ekuncars Ese error significa que no tienes instalada la librería arcade, debes ocupar los comandos que salen en el enunciado en la cmd.
`pip3 install arcade`
`python3 -m pip install arcade`
Si no funciona ninguno de esos dos prueba con 
`py -m pip install arcade`

**Comment by FGarridoV** [comment]
@ekuncars Prueba cerrar jupyter y volver a abrirlo si es que te sige saliendo el error.
