### ISSUE TITLE
Calculo energia gastada L02 2a)

### ISSUE THREAD

**Issue by faaceituno** [IIC2115/Syllabus#34]
Tengo una duda respecto al calculo de la energia gastada del caballo, ya que en el ejemplo dado dice en la salida que el total consumido es 45, sin embargo, solo con pasar desde  el nodo (2, 1) al  (3, 1) donde las alturas son 2 y 46 respectivamente, ya se gastan 45 de energía, es esto un error en el output o estoy entendiendo mal el problema?

**Comment by pcseisdedos** [comment]
Hola, creo que estás confundiendo distintas celdas en el mapa. La celda (2,1) tiene altura 9 y la (3,1) 18, quizás con esta imagen te queda más claro.

![image](https://user-images.githubusercontent.com/18387808/92413144-149ae180-f125-11ea-94f0-8c4fbc10f5cf.png)

Las filas comienzan en 0 en la arriba y aumentan hacia abajo, las colunmas comienzan en 0 arriba y aumentan hacia la derecha, en las tuplas el primer elemento es la fila y el segundo la columna, espero que te sirva. Cualquier duda me avisas.

Saludos,
Pablo 😁👍

**Comment by faaceituno** [comment]
Ya lo entendí, muchas gracias

**Comment by felipediaz08** [comment]
> Hola, creo que estás confundiendo distintas celdas en el mapa. La celda (2,1) tiene altura 9 y la (3,1) 18, quizás con esta imagen te queda más claro.
> 
> ![image](https://user-images.githubusercontent.com/18387808/92413144-149ae180-f125-11ea-94f0-8c4fbc10f5cf.png)
> 
> Las filas comienzan en 0 en la arriba y aumentan hacia abajo, las colunmas comienzan en 0 a la izquierda y aumentan hacia la derecha, en las tuplas el primer elemento es la fila y el segundo la columna, espero que te sirva. Cualquier duda me avisas.
> 
> Saludos,
> Pablo 😁👍

Hola, tengo una duda en este mapa, porque el penultimo paso lo da de la altura 20 a la 19 y luego al destino y no al 1 que esta al lado?

**Comment by pcseisdedos** [comment]
Porque el objetivo es encontrar la ruta óptima del origen al destino.

Saludos,
Pablo 😁👍
