### ISSUE TITLE
¿Qué hacer en caso de empate?

### ISSUE THREAD

**Issue by galvarado1** [IIC2115/Syllabus#35]
En la misión 3 podría darse el caso en que por ejemplo haya un empate por el quinto género más popular. Si fuese así, ¿es necesario que el código lo tome en cuenta? ¿o basta con imprimir cualquiera de los que empata?

**Comment by pcseisdedos** [comment]
Hola, queda a criterio de ustedes.

Saludos,
Pablo 😁👍
