### ISSUE TITLE
T1:M6

### ISSUE THREAD

**Issue by Mariaignacia22** [IIC2115/Syllabus#35]
Hola, en la misión 6 tengo una duda lo que se pide es una agregación a la base de datos original y después obtener un dataframe con esas columnas, mi duda va mas si es por medición de gps o es como la misión 5 que se obtiene solo una fila por expedición y a eso se le agrega lo que preguntan en la 6

**Comment by RonaldoSosa** [comment]
Hola. Puedes trabajarlo como estimes conveniente, con esto me refiero a editar la base de datos original o hacer una copia del Dataframe de tu base de datos original y editar dicha copia, lo importante es que se genere un nuevo Dataframe con las especificaciones mencionadas en el enunciado. Generalmente es recomendable editar la copia para que así en futuras misiones no tengas que filtrar más cosas pero depende de cada uno
