### ISSUE TITLE
Mostrar_familia 

### ISSUE THREAD

**Issue by gevicencio** [IIC2115/Syllabus#35]
Hola, para la función mostrar familia, puedo imprimir el árbol con los ruts y no los nombres? esto porque  hay nombres que se repiten y usando los ruts elimino posibles confusiones. Gracias

**Comment by gevicencio** [comment]
@fnquinteros

**Comment by fnquinteros** [comment]
Hola! Sí, también es válido, pero pon también el nombre para facilitar la visualización de las personas en el árbol o, si es que no se repiten en conjunto, pon el nombre y apellido en vez del rut. 

Saludos!
