### ISSUE TITLE
Categorías de bandos

### ISSUE THREAD

**Issue by vgrivera** [IIC2115/Syllabus#35]
Si cada bando es de 3 categorías: Atacantes, Defensores y Jefes, ¿Debo representar a cada categoría con un icono PNG distinto (dado que tienen distintas habilidades)? o uso un mismo icono para las tres categorías (y que por tanto, la diferenciación se encuentre implícita)?

**Comment by pcseisdedos** [comment]
@vgrivera Es mejor que sean imágenes distintas entre personajes y equipos (serían 10 en total o 12 si haces el personaje extra), puedes usar colores distintos para diferenciar equipos.
