### ISSUE TITLE
Duda especialización

### ISSUE THREAD

**Issue by isalvador95** [IIC2115/Syllabus#36]
En el enunciado dice que dentro de las categorías de personajes (jefe, atacantes y defensores) existen categorías de especialización, lo que me deja la duda de si, por ejemplo, el atacante 2 es más especializado que el atacante 1,  éste además de tener la habilidad que habla el enunciado, contiene la habilidad del atacante 1 o solo es más especializado porque su habilidad es más bacán? Esto también aplica para defensor 1 y 2.

**Comment by FGarridoV** [comment]
Si pensamos en  un arbol de jerarquia, atacante 1 es igual a atacante 2. Es decir, no hay diferencia en entre ellos más que su propia habilidad.

Saudos,
Francisco
