### ISSUE TITLE
Agregar persona 

### ISSUE THREAD

**Issue by memadrid** [IIC2115/Syllabus#36]
¿Se pueden agregar personas con ruts de padres que no existen en el sistema, o no lo deberíamos permitir?

**Comment by memadrid** [comment]
¿Pero en ese caso los padres no serían null? Ya lo había hecho de la otra manera ):

**Comment by fagomez2** [comment]
Ahh toda la razón, me confundí. Queda a tu criterio decidir qué hacer en ese caso. Recuerda especificarlo en el README!
