### ISSUE TITLE
T1: M9

### ISSUE THREAD

**Issue by mbertin1** [IIC2115/Syllabus#36]

**Comment by mbertin1** [comment]
Hola! Quisiera saber que tan buena debe ser la precision del modelo ya que llevo mucho tiempo intentando mejorar el modelo y el error no es gigantesco pero no deja de ser importante

**Comment by RonaldoSosa** [comment]
Hola. No hay algo así como un una precisión mínima establecida por sí decirlo, sin embargo, en tú análisis podrías mencionar la razón por la que crees que tú modelo presenta dicho error.
