### ISSUE TITLE
Duda sobre código en el .ipynb de Grafos

### ISSUE THREAD

**Issue by VicenteScholl** [IIC2115/Syllabus#37]
Hola, me podrían explicar porfa la parte del código que dice:

-   visited, stack = list(), [start]

- visited, queue = list(), [start]

No cacho por qué son 2 cosas separadas por una coma y tampoco cacho para que sirve el [start]

![pantallazo duda](https://user-images.githubusercontent.com/69535870/92660700-549ec780-f2d1-11ea-9ccf-ef3886732581.jpg)

**Comment by pcseisdedos** [comment]
hola @VicenteScholl, la sintaxis de separar por comas es propia de una tupla, en terminos simples te sirve para asignar valores a multiples variables en una sola linea, en visited se guarda una lista vacía y en stack una lista (que será trabajada como un stack) con el primer elemento (llamado start), esta representa los nodos que falta por visitar mientras que la otra los ya visitados.
Start corresponde al elemento desde el que quieres comenzar a recorrer el grafo, puedes entederlo como el nodo padre o nodo de inicio. 

Espero haberlo aclarado, si te quedan más dudas dime.

Saludos,
Pablo 😁👍
