### ISSUE TITLE
Not module name game

### ISSUE THREAD

**Issue by bombanex** [IIC2115/Syllabus#37]
Despues de muchos videos logre instalar arcade, pero ahora tengo problemas al instalar game. me sale: Not module name game.

**Comment by fagomez2** [comment]
Hola! ¿Cómo estás usando el archivo? Revisa que **game.py** esté en la misma carpeta en la que está tu código. Además revisa que estés importando adecuadamente el archivo antes de usarlo. Si sigue saliendo el mismo error vuelve a escribir por aquí. Buena suerte!

**Comment by ekuncars** [comment]
Hola! ya he realizado el tutorial de instalación dos veces y sigo teniendo el mismo error de "Not module name game." siendo que está en la misma carpeta dentro de mi repositorio. Hay algo que pueda hacer?
