### ISSUE TITLE
T1 

### ISSUE THREAD

**Issue by MariaJoseSilva** [IIC2115/Syllabus#37]
Hola!
Tengo algunas preguntas sobre la Tarea 1

1. Se puede utilizar la librería _**datetime**_ para manejar las fechas?

2. Para la M6
- total_mean_speed, que refiere a la velocidad media, esto medido en km/min para ser consistente con las unidades de medida de las otras columnas? 
- podemos asumir que la hora de la última medición es la hora de término de una expedición?

3. Para la M9
en el bonus piden que también se estime la varianza, a qué se refiere esta varianza? 

Muchas gracias!

**Comment by RonaldoSosa** [comment]
Hola. Respondiendo tus preguntas en el mismo orden:

1. Pueden utilizar las librerías y herramientas que estimen convenientes.
2. En el mismo orden de las preguntas:
    -  Lo ideal sería que fuesen consistentes.
    -  Sí, pueden asumir eso.
3. Se refiere a la varianza del tiempo de viaje.
