### ISSUE TITLE
Programación Consola

### ISSUE THREAD

**Issue by cristobalwelch** [IIC2115/Syllabus#38]
Para programar la consola, podemos usar Errors y Exceptions para evitar que se caiga?

**Comment by fnquinteros** [comment]
Hola! Sí, pero con 2 condiciones:

* En el manejo de errores deben especificar la Excepción que están enfrentando (nada de Except Exception: o Except: a secas). 

* No debe estar todo el código o una porción substancial de código metido en el try except statement (solo la parte en que es necesario manejar el error). 

Te recomiendo que si el manejo de input es simple utilices ifs, que es menos engorroso. :sweat_smile:

Saludos!
