### ISSUE TITLE
Estructura del árbol. Pregunta 2b

### ISSUE THREAD

**Issue by ConsueloAraya15** [IIC2115/Syllabus#38]
Hola a todos!
Mi consulta es si la estructura de mi árbol puede ser mediante el uso de diccionarios

**Comment by Jamidd** [comment]
Hola, puedes armar el árbol como encuentres conveniente. Solo piensa bien como lo vas a definir, igual, siempre tienes como último recurso a POO y todas las facilidades que te entrega. 
Éxito con la tarea. 
Jaime.

**Comment by FranciscaUlloa** [comment]
Hola! puede ser que mi manera de ejecutar el código para esta pregunta no sea como se muestra en el ejemplo? 
En mi código sí hay que poner el historico y el prefijo pero no se lee como motor_lobel(prefijos,historicos), sino como motor_lobel(rama,prefijo)

**Comment by pcseisdedos** [comment]
El formato del input y el output debe cumplir con lo que se establece en el enunciado y  en #22 . El nombre de los parámetros no es relevante pero el orden en que se reciben y su estructura que tienen si lo son. Recuerda que parte del puntaje (50%) se asigna mediante un script que evalúa de forma binaria sus respuestas si se cumplen los 3 criterios (correctitud, tiempo promedio y tiempo límite) simultaneamente, por eso el formato es sumamente importante.

Saludos,
Pablo 😁👍
