### ISSUE TITLE
Consulta Github y Google Drive

### ISSUE THREAD

**Issue by lucianobucarey** [IIC2115/Syllabus#39]
Hola!

Existe algún inconveniente para subir una carpeta a Github que tengo almacenada en Google Drive File Stream en mi computador? o esto puede generar algún inconveniente cuando suba el laboratorio o algo así ?

**Comment by pcseisdedos** [comment]
No creo que tengas problema, pero te recomiendo intentarlo antes para que lo puedas verificar.

Saludos,
Pablo 😁👍
