### ISSUE TITLE
Reclamos sobre el ramo

### ISSUE THREAD

**Issue by bombanex** [IIC2115/Syllabus#39]
Estimados,
Tengo algunas quejas sobre el ramo:

1.- En el verano había un programa del ramo que decía que tendríamos 3 tareas en grupos de a 4. Tenia pensado cambiar el ramo por otro ya que me habían dicho que demandaba mucho tiempo debido a que tenia tareas semana por medio, pero al ver ese programa no lo cambie. Llegando a clases me topo con la sorpresa de que habían modificado completamente el programa y ahora, en vez de tener menos tareas que el semestre anterior tendríamos el doble y ademas estas serian de trabajo individual. 
Esperaba por ultimo que estas tareas fueran cortas, pero de nuevo no estaba en lo correcto. Preguntándole a compañeros que habían tomado el ramo otros semestre me dijeron que las tareas que nos han mandado están a la altura de las que les mandaban a ellos.
Ademas, viendo el programa del ramo Programación Avanzada, que siempre se a visto como un ramo mucho mas exigente, dice que tienen 3 laboratorios en el semestre.

2.- Por otro lado, se supone que el ramo es de 10 créditos. Si sumo las horas de estudio para las clases, las clases mismas y las horas semanales programando la tarea me da un total de al menos 16 horas. Ya con eso estamos pasados los 10 créditos y para rematar, estas 16 horas las distribuyen en 4 días a la semana ya que no nos dan mas plazo para entregar las tareas. Por favor piensen que este no es nuestro único ramo y que muchas veces vamos a tener pruebas y trabajos durante la semana, por lo que nos vamos a tener que ver obligados a elegir entre hacer el laboratorio o estudiar para la o las pruebas. 

3.- Por ultimo, no entiendo como un ramo de programación lo hacen en una sala como la A7, no hay espacio ni para el computador sobre el escritorio y con suerte hay enchufes para conectarlos. Se que esto no lo ven ustedes, pero podrían pedir un cambio de sala si es posible.

Espero su comprensión.

**Comment by Mcarriagada** [comment]
X2, estoy de acuerdo en todo lo mencionado. Considero que las horas requeridas para el cursos son muchas más de los 10 créditos dispuestos y además, no todos programamos al mismo ritmo. También encuentro que la sala es bastante mala para poder programar, esto igual debería ser tomado encuenta.
Finalmente, creo que la extensión de las tareas no es acorde al tiempo que tenemos para desarrollarlas, no siempre vamos a contar con esos 3 días para poder trabajar en los laboratorios

**Comment by eljaker** [comment]
Con todo respeto creo que @bombanex tiene razón, en mi caso al menos es muy complicado poder hacer una buena tarea considerando el tiempo que se da y que tengo I1 mañana y el jueves. A muchos les podría pasar algo parecido en semanas venideras.
El tema es que no sabemos exactamente a lo que nos enfrentamos (en cuanto a carga semanal) hasta tener solo 3-4 días para resolverlo.

**Comment by rjvergarai** [comment]
Comparto lo que dice @bombanex, creo que son reclamos bastante razonables. Espero que se pueda hacer algo al respecto, porque como dice @eljaker a muchos compañeros les puede pasar que tengan pruebas en la semana, lo que dificulta bastante el trabajo en sólo 4 días.

**Comment by stlara** [comment]
Comparto el sentimiento de mis compañeros. A modo de ejemplo, la semana pasada le dediqué al rededor de 20 horas a este ramo, el tema es que todos tenemos otras obligaciones. Considero que existe un problema entre "el largo" de la tarea y el plazo para entregarla. Creo que soluciones pueden estar en torno a realizar tareas más cortas, o una cantidad menor de tareas (a la del programa) con un plazo mayor. Creo que muchos nos hemos visto sobrepasados con la cantidad de horas necesarias para realizar las tareas, por lo que pienso que sería correcto reconsiderar la forma de evaluación.

**Comment by cmujicai** [comment]
Totalmente de acuerdo con lo comentado por mis compañeros. Agregar además que el método de aprendizaje es válido, pero debería tener un mayor apoyo por parte del equipo docente. Por que una cosa es leer y estudiar el material de clases y otra cosa es entender y "madurar" lo estudiado.

**Comment by asnunez1** [comment]
Estoy de acuerdo con todo lo que se ha comentado anteriormente, espero se planteen la relación entre la extensión de las tareas versus el tiempo que nos dan para entregarla (un poco más de 3 días)
Creo que a la mayoría nos está tomando más de 10 horas programar las tareas (en mi caso fueron 20).
Y también consideren que en ese acotado tiempo en la semana tenemos obligaciones con los otros ramos. Por ejemplo: Yo la próxima semana tengo 3 interrogaciones seguidas, donde claramente no alcanzo a hacer la tarea.
Me parece bien que hayan replanteado el trabajo individual, pero creo que deberían o aumentar el plazo de entrega o acortar las tareas.

**Comment by mblejeune** [comment]
Estoy de acuerdo también con mis compañeros, primero que nada las horas utilizadas para estudiar los contenidos y también practicarlos (trabajo personal, que por lo tanto si son temas que nunca hemos visto toman mucho más tiempo a que si fueran explicados en algún tiempo de la clase aunque sea como introducción), luego están las tareas que para lograr leerlas, entenderlas e intentar darle forma en la mente de cómo se partirá haciendo toma mucho más que 10 minutos, ya que por ejemplo, la tarea 1 del ramo el enunciado estaba bastante enredado para lograr entenderlo en clases con el tiempo que se nos dio al principio de clase para luego hacer un buen avance, en este caso recién al llegar a mi casa y leer calmadamente la tarea logro formarme una idea en mi cabeza sobre lo que pedían para recién ahí poder comenzar a hacerla, y dado que a partir de esto solo se tienen 3 días para entregarla, 3 días en los que tenemos clases, y en estas podemos tener semana a semana controles, pruebas o trabajos, no da para terminar la tarea completamente. Además, creo que cada uno tomó el curso sabiendo lo que nos podía usar en nuestro tiempo, pero el que está usando actualmente no es lo que se cree para este ramo, ya que si fuera una tarea con una extensión menor o extensión de acuerdo al tiempo que se tiene para entregar (considerando que no es lo único que tenemos que hacer) podríamos avanzarla y entregarla en su totalidad.
Espero que escuchen nuestras preocupaciones y se haga algo al respecto, al menos un debate para ver donde está el problema y solucionarlo. Gracias

**Comment by Sbaicardi** [comment]
Estoy totalmente de acuerdo con todo lo que se ha planteado. Creo que definitivamente el tiempo que se está dando para los laboratorios no es suficiente para todo el trabajo que implican. Es muy difícil planificarse en tan solo 4 días y no podemos anticiparnos tampoco porque no sabemos cómo será cada laboratorio hasta el lunes. Además, creo que no se debe olvidar que la mayoría de nuestras interrogaciones en la universidad son a las 18:30 hrs, lo que hace que esos días el tiempo sea aún más escaso. En una semana que se tienen por ejemplo 2 interrogaciones entre lunes y jueves, el tiempo que queda disponible para hacer el laboratorio es muy poco (sin considerar que además se necesita tiempo para estudiar para esas pruebas u otros ramos también). Por otra parte, pienso que dar tan poco tiempo no es beneficioso para el aprendizaje, ya que no se alcanza a madurar bien la tarea. Generalmente para programar se necesita tiempo para entender lo que se pide, pensar después en una forma de resolverlo y luego comenzar a probar con el código. Muchas veces pasa que lo que uno pensó en un principio no funciona y se debe pensar en otra forma de hacerlo, o no se está escribiendo bien el código y hay que buscar información al respecto, etc. Todo este proceso toma tiempo que ahora mismo no estamos teniendo. Creo que sería muy bueno que se reconsideraran los plazos que se entregan para hacer cada laboratorio, o bien, reconsiderar su extensión para que estos efectivamente se puedan realizar en tan pocos días.

**Comment by mzrojas** [comment]
Estoy completamente de acuerdo con lo comentado. Creo que si bien es eficiente estudiar nosotros la materia antes, sería bueno tener un repaso breve de ésta al iniciar la clase para ver si se entendió todo bien. Además, creo que es necesario que se reconsideren los plazos; que se dé más tiempo para los laboratorios o bien que estos sean más breves. Esto tomando en cuenta que aunque destinemos harto tiempo para aprender de este ramo, el tiempo se hace poco con otros ramos. Como se ha dicho, no alcanzamos a asimilar los contenidos de un laboratorio en 4 días, tomando en cuenta que muchos de nosotros podemos no haber programado hace varios años y por más que queramos aprender, nos demoraremos muchas más horas en lograr que funcione. Por último, creo también, que se agradecería un montón un cambio de sala, ya que es muy incómoda para usar el computador y poder concentrarse. Espero que se consideren nuestras opiniones. Desde ya gracias!

**Comment by antoniacatalina** [comment]
Estoy muy de acuerdo con todo lo planteado por mis compañeros. Creo que es necesario que haya alguna instancia en donde se nos enseñe sobre la materia, nuestra base de programación fue intro a la progra y la mayoría lo hizo hace un par de años ya. El material que se sube no basta para que podamos entregar una tarea decente. Además, mencionar que se dijo que los laboratorios serían más cortos porque solo tendríamos 3 días y algo, cosa que no se está cumpliendo. Tenemos 4 ramos más en los cuales rendir y se hace imposible con este tipo de laboratorios. Sobre todo para los que tenemos ies entre los lunes y jueves. Espero se pueda hacer algo al respecto para que todos podamos aprender de la mejor manera en un ramo tan útil como debería ser este.

**Comment by halobel** [comment]
Con el resto del cuerpo docente, apreciamos mucho que estén opinando sobre los aspectos del curso que creen que necesitan mejoras o correcciones. Puede que no estemos de acuerdo en todo, pero para nosotros es muy valioso tener este feedback antes de la encuesta de medio semestre, así que considero muy bueno que esto se mantenga. 
Dicho esto, voy a tratar de responder a todos los comentarios que han hecho en esta issue, y si se me queda algo por favor me avisan. 
Creo que la principal queja/comentario está relacionada con el tiempo que le han tenido que dedicar a los laboratorios. Esto es algo que ocurre todos los semestres con este curso, y tiene un motivo muy claro: para programar bien es necesario hacer un gran esfuerzo inicial para "soltar la mano". Después de las primeras 3-4 semanas, la carga del curso se reduce, ya que el énfasis del curso cambia a utilizar la programación como una herramienta, más que programar todo desde cero. 
En relación a la dificultad de los laboratorios, es importante que tengan claro que este es un curso exigente, donde se busca que adquieran conocimientos avanzados de programación, fundamentales para cualquier ingeniero moderno. En vista de eso, no tenemos planificado disminuir la dificultad de los laboratorios. Entendemos que para muchos programar no es una prioridad, y la última vez que lo hicieron fue hace bastante tiempo atrás, pero las competencias que debe desarrollar el curso son claras y años de experiencia en cursos de programación indican que este esquema es muy efectivo para lograrlas.
Ahora, con respecto al tiempo que tienen para hacer los labs, eso es otro tema y es perfectamente discutible. Lógicamente es responsabilidad nuestra regular la extensión de los laboratorios para que no tengan que dedicar más de 10 horas a la semana, y muchos de estos reclamos creo que se explican porque para el L01 le dedicaron mucho más que eso, comprimido en un par de días. Ya mencioné que esta es una situación puntual que se da al principio del curso, pero a pesar de eso, cambiaremos esta política para el L03 y daremos hasta el domingo previo al siguiente lab para entregarlo. Si eso funciona mejor, mantendremos el esquema
Con respecto a la sala, este es un problema gigantesco y que por el futuro cercano no tiene solución. Este no es el lugar para explicarlo, pero en resumidas cuentas, por un lado la Escuela no tiene los recursos para que existan más secciones del curso, y por otro lado no existen salas adecuadas para recibir un curso de este tamaño con esta metodología. No quisiera ahondar más sobre este problema por esta vía, pero no tengo ningún problema en aclararlo más durante alguna de las sesiones, si es que les interesa.
El tema del programa es algo distinto. Lamentablemente la universidad no ha sido capaz de ofrecer un sistema para mantener los programas actualizados, a pesar de que nosotros enviamos los programas todos los semestres a la DiPre. El programa que estaba en verano, cuando no se había escrito ni siquiera un aviso en el Siding, es el antiguo y no tiene que ver mucho con lo que es ahora el curso. Esto pasa con todos los cursos de la Escuela, por lo que no debiese ser sorpresa para nadie. Además, dado que esta es la cuarta vez que se da el curso en este formato, y que el material de todos los semestres anteriores está disponible, creo que no costaba mucho revisar un poco más para tener claro el formato del curso.
Finalmente, en relación al L02 y el desastre de la librería, deremos un aviso más tarde, pero para adelantarles un poco como viene la mano, el plazo de entrega se correrá para la próxima semana, por lo que el L03 comenzará el lunes 8.

**Comment by kdcarreno** [comment]
A pesar mover la fecha de esta entrega se mantendrán 13 labs? Es un detalle no menor, ya que de 13 se borran 2. Asumo que en caso de reducir los labs, también bajarán las instancias de eliminación y aunque pueda sonar mediocre los labs eliminados entran dentro de la planificación de (mi) semestre.

**Comment by FcaCanales** [comment]
hola ! a mi me gustaría que se usara el módulo del día jueves. Quizá se podría generar una instancia para avanzar en la tarea o comprender mejor los conceptos, con el apoyo de nuestros compañeros y ayudantes. Lo que sería completamente opcional para el alumno.

**Comment by halobel** [comment]
Hola, con respecto a lo primero no tenemos claridad si aún quedarán 12 ó 13 labs, y tampoco con respecto a cuantos se eliminan. Es probable que esto último sigue igual, pero no es posible confirmarlo aún.
En relación a los jueves, coincido 100% en que sería ideal usarlo, pero tenemos el problema de la carga de trabajo para los ayudantes, por lo que, al menos por ahora, el horario de los días jueves será usado esporádicamente.
