### ISSUE TITLE
Archivo txt para parte a

### ISSUE THREAD

**Issue by AlexandraOvalle** [IIC2115/Syllabus#39]
Estaba revisando los contenidos para el lunes, pero no está el archivo que se usa de ejemplo. Lo pueden subir? por favor.

**Comment by pcseisdedos** [comment]
Hola, si te refieres a [stacks-texto.txt](https://github.com/IIC2115/Syllabus/blob/main/Material%20de%20clases/Cap%C3%ADtulo%202/Parte%20a/stacks-texto.txt) lo acabo de subir. Gracias por avisar.

Saludos,
Pablo 😁👍
