### ISSUE TITLE
Parte 2g Laboratorio 7

### ISSUE THREAD

**Issue by Gerardogrt** [IIC2115/Syllabus#39]
Hola, la pregunta 2g, dice "Encuentre el porcentaje de asientos vendidos para cada clase en los 10 aviones m ́as utilizados, comparado con la capacidad total del avi ́on.", pero en la data, solo hay 9 aviones distintos, por lo que usare solo esos 9 aviones. ¿Esta correcto?

**Comment by pcseisdedos** [comment]
Hola, revisa bien, probablemente estás buscando por modelo en lugar de por avión.

Saludos,
Pablo
