### ISSUE TITLE
T1: M9

### ISSUE THREAD

**Issue by Fopazov** [IIC2115/Syllabus#39]
Esperando que estén bien, quería resolver unas dudas:
- ¿Estaría bien entrenar un modelo con todos los datos (todos los servicios y rangos horarios) y testearlo con esos mismos datos, para luego realizar una predicción con un data_frame filtrando por servicio y rango horario?
- ¿Para presentar la predicción (del df_filtrado) basta con imprimirla? (son muchos resultados distintos ya que consideré variables que pueden cambiar para cada expedición) ¿O es mejor sacar un promedio del vector predicho?

**Comment by RonaldoSosa** [comment]
Hola. Respondiendo a tus preguntas en orden:

- Si te refieres a que tu set de entrenamiento sean todos los datos y luego testear con los mismos datos el modelo resultante, eso sería incorrecto, ya que el modelo solo estaría "aprendiendo todas las respuestas" y no los patrones necesarios para realizar una adecuada predicción.
- Si solo sería necesario imprimir los resultados. De cualquier modo confirmaré esto con el profesor. También no olvidar que junto con los resultados es necesario incluir un análisis de estos y procedimiento completo de preparación de los datos, además del entrenamiento del modelo predictivo.
