### ISSUE TITLE
Problema con Git

### ISSUE THREAD

**Issue by vjariztia** [IIC2115/Syllabus#4]
Estimados, 

Junto con saludar me dirijo a ustedes con la intención de buscar alguna solución al problema que me surge cuando quiero abrir el código que mi compañero subió al repositorio privado. 
El error que me aparece es el siguiente:
" Error loading notebook"

Unreadable Notebook_ C:\Users\vjari\Desktop\Programacion\L01-jfmorenosm-vjariztia\clases.ipynb
NotJSONError('Notebook does not appear to be JSON: \'{\\n "cells": [\\n {\\n "cell_type": "c....',)

Saludos

**Comment by Hernan4444** [comment]
Hola, el error está en que ambos intentaron hacer cambios en el mismo archivo sin hacer `pull` como corresponde. Esto provocó que dentro del archivo, ambas versiones se combinaran (`merge` en terminos de git). Te recomiendo que tu compañero copie su archivo que está bueno con otro nombre, lo pushee y ahí hagas `pull`. De este modo tendrás el archivo bueno.
