### ISSUE TITLE
duda funcion distribucion uniforme

### ISSUE THREAD

**Issue by jlcasanova2** [IIC2115/Syllabus#4]
Estaba usando la funcion de distribucion uniforme de la libreria comodoro y me arroja un numero racional (con decimales) y en el enunciado dice que para determinar el nivel de ocupacion de los modos debe ser números enteros, entonces nos encargamos nosotros de llevar el numero a un numero entero?? Lo aproximamos o truncamos??

De antemano gracias

**Comment by FGarridoV** [comment]
Exacto! y ten la precaución que te arroje todas las opciones que buscas. Esto porque al usar las funciones ceiling o floor podrías perder una de las opciones si es que no analizas los resultados posibles.

Saludos,
Francisco

**Comment by VedranRazmilic** [comment]
Uno puede importar random y usar randint() para esa ocasión o es preferible usar la función de comodoro?

Saludos!
