### ISSUE TITLE
jupyter en windows

### ISSUE THREAD

**Issue by clementeramirez** [IIC2115/Syllabus#4]
hola, instale jupyter y todo bien, pero cuando lo quiero abrir escrbiendo "jupyter notebook" en el cmd, me sale un mensaje que dice C:\Users\sole\Desktop>jupyter notebook
"jupyter" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.

muchas gracias

**Comment by FGarridoV** [comment]
@clementeramirez Si pudiste solucionarlo, podrías comentarlo. Así ayudas a otros compañeros que tengan el mismo problema. Sino avísame, pero bastaría agregar jupyter al PATH. Busca como agregar rutas al PATH en windows.

**Comment by clementeramirez** [comment]
perdon. lo solucione con este link: https://living-sun.com/es/python/715587-running-jupyter-via-command-line-on-windows-python-jupyter-notebook-jupyter.html
por si a alguien le sirve

**Comment by cnarvez** [comment]
> @clementeramirez Si pudiste solucionarlo, podrías comentarlo. Así ayudas a otros compañeros que tengan el mismo problema. Sino avísame, pero bastaría agregar jupyter al PATH. Busca como agregar rutas al PATH en windows.

Pucha me apareció el mismo problema, me podrían explicar cómo determinar la ruta de jupyter para poder agregarla a PATH?

**Comment by paulavonbrand** [comment]
Hola!! Al seguir el tutorial "IIC2115 - Instalación de Python y Jupyter" estoy en el punto de usar el Simbolo del sistema CMD pero al poner pip freeze, al igual que en el tutorial, no me parecen nada. En el video menciona que debiese aparecer una lista de las librerias con su respectiva version, pero no me aparece ninguna. ¿eso es porque no tengo ninguna instalada? jajaj

Además al descargar jupyter notebook me aparecen muchos avisos de warning:
![2020-08-12 (1)](https://user-images.githubusercontent.com/68405224/90058963-7005bb00-dcb0-11ea-8e15-582f89b0ec88.png)

Y después como que no me aparece de nuevo la posibilidad de poder escribir algo más.

**Comment by paulavonbrand** [comment]
hice lo quemenciono un compañero para resolver lo del warning (https://github.com/IIC2115/Syllabus/issues/8#issuecomment-672267016 ) 
![2020-08-12 (2)](https://user-images.githubusercontent.com/68405224/90059619-76e0fd80-dcb1-11ea-854a-5400f3275fcd.png)
y ahora solo aparece esto: ¿esta ok?

**Comment by paulavonbrand** [comment]
> Hola!! Al seguir el tutorial "IIC2115 - Instalación de Python y Jupyter" estoy en el punto de usar el Simbolo del sistema CMD pero al poner pip freeze, al igual que en el tutorial, no me parecen nada. En el video menciona que debiese aparecer una lista de las librerias con su respectiva version, pero no me aparece ninguna. ¿eso es porque no tengo ninguna instalada? jajaj
> 
> Además al descargar jupyter notebook me aparecen muchos avisos de warning:
> ![2020-08-12 (1)](https://user-images.githubusercontent.com/68405224/90058963-7005bb00-dcb0-11ea-8e15-582f89b0ec88.png)
> 
> Y después como que no me aparece de nuevo la posibilidad de poder escribir algo más.

hice lo que menciono un compañero para resolver lo del warning, y me aparece el siguiente warning: y además si escribo solo "jupyter notebook despues no se me abre la pestaña que en el video mencionan que se debiese abrir"
![2020-08-12 (3)](https://user-images.githubusercontent.com/68405224/90060051-1f8f5d00-dcb2-11ea-928f-fd2b69d0df61.png)
¿Que debo hacer?

**Comment by FGarridoV** [comment]
Escribiste "jupyer" en vez de "jupyter". Eso debe ser.

**Comment by paulavonbrand** [comment]
> Escribiste "jupyer" en vez de "jupyter". Eso debe ser.

la segunda vez lo escribi bien!! jaja

**Comment by FGarridoV** [comment]
Cierto jaja. Mira, eso es justamente lo que escribió tu compañero. Debes agregar Jupyter al PATH y luego reiniciar para que los efectos ocurran.

Saludos

**Comment by paulavonbrand** [comment]
Ahi funciono! Gracias.
¿Ahora siempre que quiera abrirlo tendre que poner "python -m notebook" en vez de "jupyter notebook"? No se _arregla_ esto?

**Comment by FGarridoV** [comment]
mmm debería funcionarte jupyter notebook, ahora que ya esta en el PATH, prueba "pip Install jupyter notebook" y luego ve si te funciona "jupyter notebook"

**Comment by clementeramirez** [comment]
yo trate con eso, pero no me funciono. me dice "requierement already satisfied", y cuando pongo jupyter notebook me dice esto:
![image](https://user-images.githubusercontent.com/69482444/90071416-85381500-dcc3-11ea-9b14-89179029c521.png)
igual ocupando python -m notebook funciona

**Comment by FGarridoV** [comment]
@paulavonbrand y @clementeramirez,  Hay que crear un alias que apunte a ese comando. De lo que estuve leyendo, en algunas versiones de Mac OS también cambio el comando al que indican. Es otra forma de abrirlo. 

SI quiere aventurarse a cambiarlo podrían probar:
`pip install --upgrade --force-reinstall jupyter`

Pero si ya les funciona, yo lo dejaría así.

Saludos!

**Comment by AlexandraOvalle** [comment]
Tengo el mismo problema con las infinitas líneas de warning, y nada de lo que han puesto lo soluciona, he buscado en google y nada, existe otra manera de instalar jupyter notebook?

**Comment by FGarridoV** [comment]
@AlexandraOvalle Se me traspapeló esta issue. Estas segura que al instalar Python seleccionaste la opción "ADD TO PATH"? Si estas segura, entonces busca "Instalar Anaconda" en windows. Este programar se instala de forma convencional (como otro programas). Esa opción no debería fallar, pero trata de usarla solo si estas segura que seguiste bien los demás pasos.
