### ISSUE TITLE
sobre uso de habilidad

### ISSUE THREAD

**Issue by kdcarreno** [IIC2115/Syllabus#40]
Sólo el atacante 1 y el jefe pueden "matar" otra pieza ?

si tengo un defensa y al moverse "pisa" a otra pieza, la mata? O lo dejo como supuesto en README ?

**Comment by idmdvan** [comment]
Hola, 

1. Sí, solo Atacante 1 y Jefe tienen la habilidad de atacar.
2. Ninguna ficha debería "pisar" a otra. Es decir, no debería haber más de una ficha por celda.

Nos vemos, 
DM.

**Comment by kdcarreno** [comment]
y para mover una pieza, puedo saltar a otra? Pensando en el caso del movimiento en línea recta.

**Comment by idmdvan** [comment]
“Saltar” sí se puede, no está prohibido en el enunciado. Éxitos!

**Comment by kdcarreno** [comment]
Solo para corroborar, cuando el jefe usa la habilidad del atacante 1 si tendría la opción de moverse 2 celdas en línea recta? Porque en el caso de moverse es solamente 1 celda en cualquier dirección

**Comment by halobel** [comment]
Exacto, en ese caso podría.
