### ISSUE TITLE
Pregunta sobre modelos de predicción:

### ISSUE THREAD

**Issue by Fopazov** [IIC2115/Syllabus#40]
- Si uno entrena y testea un modelo con datos estandarizados (Scaler), ¿se puede realizar un "predict" para todos los datos (los de entrenamiento y testeo con los cuales se entreno al modelo) pero "no escalados" (matriz de "features" no escalada)?  ¿o también se tendría que estandarizar?

**Comment by RonaldoSosa** [comment]
Hola. El modelo si sería capaz de realizar dicha predicción, sin embargo, debes de tener en cuenta que dado que estandarizaste los datos para entrenarlos el modelo habría aprendido los patrones para los datos estandarizados por ende los resultados podrían no ser muy precisos, lo recomendable es que los datos con los que testeas el modelo tengan la misma estandarización que los datos con los que entrenaste el modelo.
