### ISSUE TITLE
Consulta respecto a listas ligadas

### ISSUE THREAD

**Issue by iavasquez1** [IIC2115/Syllabus#40]
En la materia de Listas Ligadas no me quedó muy claro por qué cuando definen la cola para la primera lista ligada la definen como self.cola = self.cabeza, ¿Es debido a que en este caso, al haber un elemento representa a lo mismo?. De antemano muchas gracias!
![Duda](https://user-images.githubusercontent.com/17599169/114432571-d835d500-9b8e-11eb-82be-c84751f548d8.png)

**Comment by pcseisdedos** [comment]
Eso ocurre cuando se agrega el primer elemento a la lista ligada, por lo que la cabeza y la cola hacen referencia al mismo nodo (es una lista ligada de largo 1).

Saludos,
Pablo 😁👍
