### ISSUE TITLE
P02- ayuda

### ISSUE THREAD

**Issue by paulavonbrand** [IIC2115/Syllabus#40]
Hola!! hay manera de obtener ayuda vía voz? como en sería en clases presenciales como "ir a su oficina"?
Mi codigo me tira el error: **maximum recursion depth exceeded in comparison**
No cacho porque si antes funcionaba bien jaja y busque en google y parece q no es tan dificil de arreglar, y hay que ponerle como un límite manualmente con: **sys.setrecursionlimit**
pero intenté y no funciona:((

gracias:)

**Comment by Jamidd** [comment]
En cuanto a "ir a la oficina", si necesitas hablar con los profesores por algún tema personal, puedes mandarles un email y coordinar una reunión. Sin embargo, si es por materia, la idea es que utilices instancias como la de recién para preguntar.

En cuanto al recursion limit, efectivamente se "soluciona" con el sys.setrecursionlimit. Sin embargo esto no elimina el limite, solo lo mueve. Esto es para evitar el error llamado "StackOverflow", si quieres saber mas revisa esto https://stackoverflow.com/questions/214741/what-is-a-stackoverflowerror. 

En las tareas y labs no deberían haber ocasiones en donde necesites cambiar el largo del stack (aka. limite de recusión), y lo mas probable es que tengas un problema de implementación o de como pensaste la solución. Mini tip, VS Code te permite poner break-points para ir viendo como se va ejecutado el código en tiempo real. Quizás te pueda ayudar a ver en donde esta el error. https://code.visualstudio.com/docs/editor/debugging

Mucho éxito y happy hacking,
Jaime.

**Comment by paulavonbrand** [comment]
Gracias!!!
Esque utilice una función recursiva para la actividad b) , y al tratar de usarla como en la función principal (la función simplificar_red), se me está haciendo como un loop infinito al parecer o algo así, y no se como eliminarlo, porque no le encuentro el problema, y además antes funcionaba perfectt

**Comment by paulavonbrand** [comment]
Hola!! el archivo .py solo dejo los imports, definiciones de las funciones y nada más? si puse comentarios con # da igual cierto?

**Comment by pcseisdedos** [comment]
@paulavonbrand respecto a lo primero, necesitaría mayor detalle. En cuanto a lo segundo, en el .py debes dejar los imports y definiciones de funciones solamente, los comentarios con # no influyen (puedes dejarlos o quitarlos). En el .ipynb puedes dejar la función que lee el archivo si quieres.

Saludos,
Pablo 😁👍
