### ISSUE TITLE
Duda enunciado

### ISSUE THREAD

**Issue by jsgalleguillos** [IIC2115/Syllabus#41]
En el enunciado sale que "Un turno esta compuesto por un movimiento, y opcionalmente seguido de una habilidad, para cada una de las piezas del jugador." 
Esto se refiere a que muevo una pieza de cada equipo por turno o que muevo las 5 piezas de cada equipo por turno?

**Comment by Jamidd** [comment]
En el enunciado sale: "El juego se desenvuelve en turnos intercalados entre ambos jugadores. Un turno esta compuesto por un movimiento, y opcionalmente seguido de una habilidad, **para cada una de las piezas del jugador**. "

Mueves las 5 piezas.

Jaime Middleton
