### ISSUE TITLE
lista de función familia con más generaciones

### ISSUE THREAD

**Issue by nmcarvajalcortes** [IIC2115/Syllabus#41]
Para la función familia con más generaciones, se pide una lista con todos los integrantes de la familia,. ¿Puedo imprimir el árbol genealógico en vez de una lista? Así aprovecho la función mostrar familia

**Comment by fagomez2** [comment]
Hola Nicolás! Sí, puedes imprimir el árbol en lugar de hacer la lista. Bien pensado!
Saludos.
