### ISSUE TITLE
Consulta sobre ejercicio 2 de taller 2a

### ISSUE THREAD

**Issue by iavasquez1** [IIC2115/Syllabus#41]
En el ejercicio de los grafos, para poder resolverlo ¿no se puede crear objetos que representen los nodos y funciones que expresen su comportamiento? o todo lo que se implemente solamente pueden ser variables que esten dentro de la función y no se pueden hacer instancias de objetos ni comportamiento de ellos?
De antemano muchas gracias!

**Comment by pcseisdedos** [comment]
Pueden crear estructuras de datos propias (con clases) y también pueden ocupar estructuras de datos existentes para representar el grafo. Queda a criterio de ustedes.

Saludos,
Pablo 😁👍
