### ISSUE TITLE
T1: M8

### ISSUE THREAD

**Issue by SebaMartinezM** [IIC2115/Syllabus#41]
Hola buenos días, en la misión 8 me surgió una pregunta. Pasa que en esta misión se piden comparar los tiempos de viaje en días laborales vs en el fin de semana, sin embargo, al ver la base de datos "mediciones_gps_2" todos los despachos en "dispatch_time" ocurren en solo 2 días, 13-08-2018 y 14-08-2018 que corresponden a un Lunes y Martes respectivamente. Por esto me surge la pregunta de como realizar esta parte si solo se tiene información de estos 2 días y no ocurre ningún despacho el fin de semana. Agradecería que me aclaren esta consulta, quizás lo entendí mal.

**Comment by RonaldoSosa** [comment]
Hola. En el enunciado hay un link ha una base de datos más grandes, ahí hay mediciones en los fines de semana.

**Comment by RonaldoSosa** [comment]
Hola. Dado que en mediciones_gps2.csv no presenta mediciones para los fines de semana debiesen de usar el archivo más grande para probar está misión, lo importante es que su función retorne lo solicitado en el enunciado. A lo que voy es que la base de datos entregada es para que prueben si sus funciones cumplen lo solicitado.

**Comment by RonaldoSosa** [comment]
No es necesario que sea uno solo, es decir, si algunas ya las dejaste con respecto a la base de datos mediciones_gps_2.csv está bien y si dejas la de esta misión respecto a la otra base de datos también estaría bien.
