### ISSUE TITLE
Duda P02 - retorno de funciones

### ISSUE THREAD

**Issue by Nsanhueza7** [IIC2115/Syllabus#41]
Estimado cuerpo docente,
Para la función de los sensores Bluetooth, ¿Es necesario retornar una lista de tuplas? 
Mi duda radica en que sé que esos nodos serán Bluetooth por la condición que implementé en mi función, pero más adelante necesito calcular todos los pares de nodos obtenidos en (a) y es mucho más útil (al menos de la forma que lo estoy viendo) haber retornado una lista con los nombres de los nodos (Ej: ['A','B'....]) para poder calcular todas las combinaciones.
Cuando retorno la solución final la retorno de la forma: [['nodoBluetooth1','nodoBluetooth2','nodoBluetooth3',...],[(arco 1), (arco2), (arco3),...]] siendo (arco i) de la forma mostrada en el enunciado.

Saludos

**Comment by Jamidd** [comment]
- En el enunciado no sale nada de que tienen que retornar un lista de tuplas. 
`(a) Cree una función que retorne el subconjunto de nodos de la red original que solo poseen sensores Bluetooth (Regla 1 de construcción de la red simplificada). (0.5 puntos)`. Ergo, tiene sentido retornar (Ej: ['A','B'....]).
- Se ve bien el retorno final. 

Éxito y happy hacking.
El jinete.

**Comment by pelayouc** [comment]
para el retorno final puede quedar así [['B', 'D', 'I'], [('B', 'D'), ('D', 'B'), ('D', 'I')]]?

**Comment by pelayouc** [comment]
o debe tener el 1 correspondiente a bluetooth?

**Comment by pcseisdedos** [comment]
@pelayouc debe tener el 1 correspondiente al bluetooth.
 
Saludos,
Pablo 😁👍

**Comment by romidonghi** [comment]
y puedo retornar dos cosas? 
Una de la lista de tuplas y otra que es una lista solo con las letras de los nodos? porque despues en otra función me sirve eso

Saludos.

**Comment by pcseisdedos** [comment]
No es relevante como trabajan con las funciones intermedias, lo que si debe cumplirse es el formato de la función simplificar_red(), que **recibe y retorna una red**, que cumple lo siguiente.
1. Un nodo está representado por una tupla de dos elementos (nombre, tiene sensor), donde nombre es el
nombre del nodo como texto y tiene sensor es una variable binaria que vale 1 si el nodo tiene un sensor
Bluetooth y 0 si no.
1. Un arco esta representado por una tupla de dos elementos (nodo origen, nodo destino), donde nodo origen
es el nombre del nodo de origen y nodo destino es el nombre del nodo de destino.
1. Una red queda determinada por una lista con dos elementos, el primero es una lista de nodos y el segundo una lista de arcos. 

Saludos,
Pablo 😁👍

**Comment by Ignacio-Ortiz** [comment]
¿Al final entonces se debe retornar algo de este tipo? [[('A', 1), ... , ('T', 1)],  [('A', 'G'), ... , ('R', 'T')]] ¿o me equivoco?

**Comment by Jamidd** [comment]
Si, debe contener el uno de que son bluetooth.
Sorry, mala mia antes. Ya la corregí.

Saludos,
El Jinete.

**Comment by FranciscaSepulveda** [comment]
Una duda... en la resolución del problema implemente clases para crear los nodos y el grafo. Pueden usarse cierto?
Otra duda... en mi retorno de lista simplificada la lista de nodos con sensores está compuesta por nodos de la clase nodo y se representan con el formato pedido. Esta bien esto o debo convertirlos a tupla("letra_nodo",1) para el output?

**Comment by Jamidd** [comment]
- si
- el output tiene que ser como se pidió en el enunciado. De la forma: [[('A', 1), ... , ('T', 1)], [('A', 'G'), ... , ('R', 'T')]] 

Saludos,
El Jinete.
