### ISSUE TITLE
Antepasado en común

### ISSUE THREAD

**Issue by ravielr** [IIC2115/Syllabus#42]
Hola! Tengo una consulta acerca de esta función:
Si se está buscando la relación entre un abuelo y su nieto ¿el antepasado en común sería el mismo abuelo? y si es así ¿la distancia entre ambos sería de dos?

**Comment by fagomez2** [comment]
Hola Rodrigo! Revisa la issue #27, creo que estás repitiendo la pregunta que se hizo allí.
Saludos!
