### ISSUE TITLE
[GitHub] Duda Deprecation Notice

### ISSUE THREAD

**Issue by FernandoSMG** [IIC2115/Syllabus#42]
Me enviaron un mail desde Github indicando lo siguiente:

Hi @FernandoSMG,

You recently used a password to access the repository at IIC2115/iic2115-2021-1-FernandoSMG with git using git/2.30.2.windows.1.

Basic authentication using a password to Git is deprecated and will soon no longer work. Visit https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/ for more information around suggested workarounds and removal dates.

Cuando realizo commits me piden usuario y clave en cada ocasion, ya configure mi usuario y mail según las instrucciones del curso, me gustaria saber como proceder.

Muchas gracias

**Comment by pcseisdedos** [comment]
Hola Fernando, por lo que veo ahí mismo te indican los pasos a seguir, intentaste con eso?

Saludos,
Pablo 😁👍
