### ISSUE TITLE
Duda codigo final

### ISSUE THREAD

**Issue by ccgarcia** [IIC2115/Syllabus#42]
en el código final tengo que crear un escenario del juego o tengo que hacer que el usuario vaya realizando los movimientos que el quiera??

**Comment by Jamidd** [comment]
Depende si buscas el bonus o no. Está en el enunciado.  

Jaime Middleton

**Comment by pcseisdedos** [comment]
@ccgarcia Complementando la aclaración de Jaime, todo el juego debe ser automático, es decir, el usuario no debe ingresar inputs. El bonus corresponde a realizar una estrategia automática.
Pablo
