### ISSUE TITLE
DUDA P02

### ISSUE THREAD

**Issue by dilanlopeg** [IIC2115/Syllabus#42]
hola, la funcion final 
simplificar_red(red) 
recibira una red en formato .txt?

**Comment by BereVF** [comment]
Holaaa, tengo la misma duda: el input que va en la función simplificar_red(red), "red" debería ser .txt y dentro de mi función usar la que nos dieron para **transformarlo**; o debo **asumir que el input vendrá como lo explica el enunciado** (como una lista de sublistas de tuplas )?

**Comment by pcseisdedos** [comment]
La función simplificar_red(), recibe y retorna una red, que cumple lo siguiente:
1. Un nodo está representado por una tupla de dos elementos (nombre, tiene sensor), donde nombre es el
nombre del nodo como texto y tiene sensor es una variable binaria que vale 1 si el nodo tiene un sensor
Bluetooth y 0 si no.
1. Un arco esta representado por una tupla de dos elementos (nodo origen, nodo destino), donde nodo origen
es el nombre del nodo de origen y nodo destino es el nombre del nodo de destino.
1. Una red queda determinada por una lista con dos elementos, el primero es una lista de nodos y el segundo una lista de arcos.

Saludos,
Pablo 😁👍

**Comment by FGarridoV** [comment]
Como dice @pcseisdedos ustedes solo trabajan con variables. La parte del txt es solo para que uds prueben sus códigos. Pero no tiene nada que ver con la entrega. Como dice en el enunciado el input del método simplificar_red(red_original) recibe una red en el formato de red original y retorna una red simplificada.
