### ISSUE TITLE
Problemas librería y dudas sprites

### ISSUE THREAD

**Issue by VedranRazmilic** [IIC2115/Syllabus#43]
He instalado y desintalado la librería arcade, la instalé a través de pycharm también, y siempre que la corro me lanza el error NoSuchConfigException. Todo esto pese a haber descargado jupyter con anaconda. No sé qué puede estar causando esto. ¿Qué podría hacer para arreglarlo o qué lo puede estar causando?

Por otro lado ¿los sprites tienen que ser fijos y solo para las piezas o se espera que haya sprites para las habilidades, para los movimientos de las piezas y todo eso?

**Comment by pcseisdedos** [comment]
Hola @VedranRazmilic, para tu primera consulta revisa #32 respecto al segundo punto se espera que cada pieza tenga una imagen distinta pero no es necesario que los ataques o movimientos tengan alguna animación u otra imagen, revisa #35 si tienes mas dudas
Pablo

**Comment by FGarridoV** [comment]
@VedranRazmilic Revisa mi último comentario en #46
