### ISSUE TITLE
T1:M8

### ISSUE THREAD

**Issue by plourido** [IIC2115/Syllabus#43]
Hola buenas noches. Les escribo ya que tengo una duda si los gráficos que debo retornar deben ser por día?
Muchas gracias

**Comment by RonaldoSosa** [comment]
Hola. Puedes distribuir tus gráficos como mejor te acomode, es decir, un gráfico para todos los días laborales y otro para los fines de semana o un gráfico para cada día, etc. Lo importante es mostrar los solicitado en el enunciado.
