### ISSUE TITLE
Lista de funcion familia con mas generaciones

### ISSUE THREAD

**Issue by agrudsky95** [IIC2115/Syllabus#43]
Hola,
La lista que debe retornar es una con los nombres de cada miembro, o los ruts de cada miembro o el diccionario completo de cada miembro (rut nombre apellido genero rut mama y rut papa)?
Saludos

**Comment by fagomez2** [comment]
Hola Andrés! Queda a criterio tuyo. Te sugeriría colocar los nombres y si quieres ocupar los ruts para los casos de personas del mismo nombre (te serviría, por ejemplo, para diferenciar padres de hijos que se llaman igual).
Saludos!
