### ISSUE TITLE
No entiendo algo del formato de la pregunta 2b del laboratorio. 

### ISSUE THREAD

**Issue by jtjara1** [IIC2115/Syllabus#44]
Hola! para la 2B, sale que se puede hacer con árboles. ¿Esto es una sugerencia o una obligación? Lo pregunto porque no definí ninguna estructura de árbol (lo hice con puras listas y slice de string). Sin embargo, mis outputs son correctos (si los comparo con los ejemplos), salvo el tercer caso (el de 5000x3000), que se demora 10 segundos.  
Gracias de antemano!

**Comment by Jamidd** [comment]
Hola, efectivamente se puede hacer usando solamente listas y slices, pero esto implica un impacto enorme en rendimiento. Ponte un caso donde tengas todos los prefijos sean solamente la letra "T". Vas a tener que buscar casi todas las entradas y compararlas entre si (va a ser muuuy lento).
El trie es una estructura que te permite hacer este tipo de búsquedas muy eficientemente.
En definitiva, lo que hiciste no esta mal, pero no hay posibilidad de que obtengas todo el puntaje.
Saludos.
Jaime

**Comment by pcseisdedos** [comment]
Para acceder a todo el puntaje del item "contenidos y mecanismos" se debe aplicar la materia señalada, no es una simple recomendación. En este caso la materia corresponde a árboles, usar trie es opcional pero ayuda bastante.

Saludos,
Pablo 😁
