### ISSUE TITLE
T1 Advertencias gráficos

### ISSUE THREAD

**Issue by AndreaJalil** [IIC2115/Syllabus#44]
Hola, quería preguntar si se puede utilizar la librería warnings para suprimir las advertencias que se generan al correr el código, puesto que al graficar salen muchas. De antemano muchas gracias

**Comment by jorgee02** [comment]
Me sumo a la pregunta

**Comment by RonaldoSosa** [comment]
Hola. Pueden utilizar las librerías que estimen convenientes. Sin embargo, ¿podrían decir cuáles son las advertencias que les aparecen?

**Comment by jorgee02** [comment]
A mi por lo menos me salen siempre que hago slicing o no uso loc, y sale varias veces así que termina siendo medio molesto

**Comment by RonaldoSosa** [comment]
Vale, ese tipo de advertencias se debe a que generalmente es mejor usar loc o iloc, dependiendo de lo que necesites, en lugar de slicing por temas de eficiencia y precisión al trabajar con los datos.
