### ISSUE TITLE
Error "Unexpected token < in JSON at position 1746." en mi actividad 1

### ISSUE THREAD

**Issue by pafuenzalidaw** [IIC2115/Syllabus#44]
Volví a abrir mi ipynb de la actividad 1 porque necesitaba una función que tenía ahí y note que me arrojaba el error Unexpected token < in JSON at position 1746. No sé como arreglarlo ni sé si se va apoder correr mi tarea para la corrección ¿Qué puedo hacer' La única opción viable que se me ocurre es descargar como txt mi tarea y trapazarla a mano.

**Comment by pcseisdedos** [comment]
No entendí bien el problema, pero cuando publiquemos las actividades te recomiendo enviarnos un mail si tienes dudas al respecto. Revisé tu repo y hiciste un cambio a la actividad 1, pero fue después de que se recolectó, por lo que no debiera afectar.

Saludos,
Pablo 😁👍
