### ISSUE TITLE
Quitar pieza

### ISSUE THREAD

**Issue by josefinabravo** [IIC2115/Syllabus#45]
Tengo duda sobre si el método quitar_pieza sirve únicamente para eliminar una pieza para siempre o si para cada movimiento tengo que quitarla y luego usar mover_pieza.

**Comment by fagomez2** [comment]
Es lo primero que dices. Con `mover_pieza()` basta, no necesitas eliminarla cada vez. Cuando quieras retirarla del tablero ahí ocupa `quitar_pieza()`
