### ISSUE TITLE
Creación del mapa de la fonda.

### ISSUE THREAD

**Issue by memadrid** [IIC2115/Syllabus#45]
¿Cuál es el método de obtención del mapa? ¿se entregará un archivo de texto?  Si es así, ¿se abre sólo con el nombre?

**Comment by fnquinteros** [comment]
Hola! Debe ser una variable que contenga a la lista de listas de strings. No debes manejar ningún tipo de input como archivo, solo debes preocuparte que el mapa tenga el mismo formato presentado en los ejemplos :+1:

Saludos!

**Comment by memadrid** [comment]
¿Pero cómo sé qué valor corresponde a cada una de las coordenadas? ¿se decide arbitrariamente, lo ingresará el ayudante por teclado?

**Comment by oaleiva** [comment]
no me queda claro, ¿nosotros lo dejamos con un mapa a nuestro criterio y ustedes lo cambiaran directo del código para corregir entonces?

y otra duda, ¿tampoco se debe manejar inputs para elegir el tipo de búsqueda? y si es así ¿como se elige?
