### ISSUE TITLE
Lab 1: Ejercicio 1

### ISSUE THREAD

**Issue by ValentinaGutz** [IIC2115/Syllabus#45]
Hola! En el input de combinaciones, se puede asumir que las tuplas serán de 2 elementos? La otra duda que tengo es que si 0 combina con 10 y con 7 por ejemplo en el input debiera salir como una tupla de 3 elementos o {(0,10),(0,7)}?
Saludos

**Comment by pcseisdedos** [comment]
Hola! Disculpa por la demora,  las tuplas son de 2 elementos solamente según lo descrito en el enunciado, sin embargo, esto no significa que no pueda existir una combinación entre 3 o más líneas, para eso basta incluir más tuplas, en tu ejemplo se muestra una opción.

Saludos,
Pablo 😁👍
