### ISSUE TITLE
Issue sobre entrega exitosa de la actividad

### ISSUE THREAD

**Issue by FranciscaSepulveda** [IIC2115/Syllabus#46]
Hola, tengo una duda muy pequeña. Para la entrega de las actividades me debería llegar al momento del cierre del buzón una issue a mi repositorio personal que me indique que fue recibida correctamente la actividad?. Esta duda me surgió, ya que ayer a las 23:59 no me llegó la issue confirmando como si había ocurrido con el L01.

**Comment by pcseisdedos** [comment]
Hola! Eso no es 100% automático, lo publiqué para el laboratorio 1 porque varios tenían dudas al respecto. Lo puedo hacer para esta actividad igual, pero más tarde o quizás mañana.

Saludos,
Pablo 😁👍
