### ISSUE TITLE
Tutorial para la solución de la librería 

### ISSUE THREAD

**Issue by FGarridoV** [IIC2115/Syllabus#46]
Estimados,

Después de varias pruebas y búsqueda por la web, se puede concluir que los errores que presenta la librería se deben a la instalación de Python que tienen en sus computadores y un conflicto que genera Anaconda. Me preocupé de hacer funcionar la librería en computadores "nuevos" que no tenían Python con una instalación desde cero y me funcionaron sin problemas. A continuación voy a describir paso a paso lo que deben hacer para solucionar el problema para windows y mac.

#### 1.1) Desinstalación de Anaconda

Anaconda realiza ciertos cambios en el computador que evita que ciertas librerías no funcionen correctamente. Para eliminarlo, primero debemos localizar una carpeta que se llama **Anaconda3**. 

Dependiendo de dónde hayan instalado el programa, debiera estar en **ProgramData** o en su **carpeta de usuario** (recuerden habilitar el poder ver archivos ocultos). Una vez localizada, copien la ruta del archivo y vayan a esa dirección por **cmd** en ingresen a Scripts en modo administrador. Por ejemplo, si estuviera en ProgramData, sería:

`cd "C:\ProgramData\Anaconda3\Scripts"` (con comillas)

Para habilitar **cmd** en modo administrador, escriban *cmd* en la barra de inicio, y con click derecho sobre el command prompt ejecutenla como administrador.
![Untitled](https://user-images.githubusercontent.com/29065260/55009848-fa695400-4fc1-11e9-8b29-01e97c92b6b2.png)

Una vez ahí, van a ejecutar los siguientes comandos, uno por uno.

`conda install anaconda-clean`
`anaconda-clean --yes`

Cuando hayan finalizado vayan a **Panel de Control > Programas**, busquen Anaconda y lo desinstalan. Además, si hay alguna versión de Python de Anaconda también deben desinstalarla de acá.

#### 1.2) Verificando la versión de Python

Primero deben verificar si tienen una versión de Python (3.6 o superior) instalada en el sistema (No la de Anaconda). Para saberlo, vayan a *Panel de Control > Programas*  y busquen un ícono como el de a continuación.

![captura windows](https://user-images.githubusercontent.com/29065260/55006076-e7538580-4fbb-11e9-97ae-7f1202c439ff.PNG)

Si no tienen esos iconos, entonces hemos encontrado parte del problema, hay que instalar Python. Por otro lado, si te aparecen esos iconos vamos a desinstalar Python de todos modos (haciendo click derecho), luego lo volveremos a instalar.

#### 1.3) Descarga correcta de Python

Python se debe instalar de la página oficial:

- [Link para Windows 64 bits](https://www.python.org/ftp/python/3.7.3/python-3.7.3-amd64.exe)
- [Link para Windows 32 bits](https://www.python.org/ftp/python/3.7.3/python-3.7.3.exe)

Si no sabes qué arquitectura tienes (32 o 64 bits) entra en *Panel de Control > Sistema*

#### 1.4) Instalación de Python

Deben seguir al pie de la letra lo siguiente.  Hacer click en agregar python al PATH (ver imagen) y luego en customize installation.
![windows2](https://user-images.githubusercontent.com/29065260/55007579-677aea80-4fbe-11e9-97e8-05d45564778f.PNG)

Deben tener todos con check en esta nueva ventana
![3](https://user-images.githubusercontent.com/29065260/55007936-04d61e80-4fbf-11e9-85bb-ab8b35a41a1f.PNG)

Y finalmente deben marcar que es para todos los usuarios. Recuerden el link donde Python nos ha quedado instalado, este caso: *C:\Program Files\Python37\*. Este link no debe editarlo, al hacer click en "todos los usuarios" cambia solo.
![4](https://user-images.githubusercontent.com/29065260/55008022-23d4b080-4fbf-11e9-8c13-8f59c055b221.PNG)

#### 1.5) Instalación de Arcade

Ahora que ya contamos con una versión de Python en el systema, vamos a hacer lo siguiente. Abrir CMD con permisos de administrador (como vimos antes).

Una vez abierto ejecuten con el link que debíamos recordar arriba y agregando "\Scripts", esto queda:

`cd "C:\Program Files\Python37\Scripts"` (va con comillas)
y luego
`pip install arcade`

Ya fue instalado arcade para esa versión en específico, si ejecutamos por consola, la librería game.py ya debe funcionar.

Recuerden instalar Jupyter Notebook. *Sin cerrar cmd*, ejecutamos:
`pip install jupyter notebook`

Como instalaron Jupyter desde esta versión de python, entonces ahora va a trabajar directamente con ella.

Para abrir un jupyter notebook, basta que tipiemos en la consola:

`jupyter notebook`

Ahora ya deberías poder funcionar la librería.

#### 2.1) Desinstalación de Anaconda

Anaconda realiza ciertos cambios en el computador que evita que ciertas librerías no funcionen correctamente. Para eliminarlo, debemos ejecutar por Terminal lo siguiente (uno por uno):

`conda install anaconda-clean`
`anaconda-clean --yes`

Cuando hayan finalizado ejecuten el siguiente comando, que va a desinstalar la carpeta de anaconda.

`rm -rf ~/anaconda3`

Además borren un archivo nuevo que va a aparecer en su home (carpeta con su nombre, que en mac se puede usar ~). Debería llamarse *.anaconda_backup/<timestamp>*

Finalmente, deben borrar dos lineas del *bash*, para abrirlo escriban una por una:

` cd ~/`
`open .bash_profile`

Se abrirá un archivo y deben borrar la siguientes líneas:

```
# added by Anaconda3 5.2.0 installer
export PATH="/Users/SU_USER_NAME/anaconda3/bin:$PATH"
```

#### 2.3) Descarga correcta de Python

Python se debe instalar de la página oficial:

- [Link para macOS 32 bits](https://www.python.org/ftp/python/3.7.3/python-3.7.3-macosx10.6.pkg)
- [Link para macOS 64 bits](https://www.python.org/ftp/python/3.7.3/python-3.7.3-macosx10.9.pkg)

Para instalarlo basta que sigan la instalación normalmente.

#### 2.4) Instalación de Arcade

Ahora que ya contamos con una versión de Python en el sistema, vamos a hacer lo siguiente. Abrir Terminal y ejecutar:

`python37 -m pip3 install PyObjC arcade` (si no funciona, probar con pip en vez de pip3)
`python37 -m pip3 install jupyter notebook` (probarlo con el pip que funcionó arriba) 

Y listo, ya pueden arrancar un nuevo jupyter notebook tipeando

`jupyter notebook`

y la librería les debería funcionar

**Comment by cmujicai** [comment]
Yo no instale python con Anaconda, tengo versión python 3.7.. y además instale python de la página oficial y tal como siguen los pasos en las instrucciones. Así todo la librería no corre,

saludos

**Comment by cmujicai** [comment]
Para asegurarme acabo de hacer todo Paso a Paso. Desinstale todo e instale todo nuevamente. El error que me genera es el mismo (ver abajo). Quedo atento a la solución.
""
Traceback (most recent call last):
  File "C:/Users/usuario/Desktop/L02/L02.py", line 3, in <module>
    miJuego = game.LostGame()
  File "C:\Users\usuario\Desktop\L02\game.py", line 39, in __init__
    super().__init__(SCREEN_WIDTH, SCREEN_HEIGHT, SCREEN_TITLE)
  File "C:\Program Files\Python37\lib\site-packages\arcade\application.py", line 53, in __init__
    resizable=resizable, config=config)
  File "C:\Program Files\Python37\lib\site-packages\pyglet\window\win32\__init__.py", line 137, in __init__
    super(Win32Window, self).__init__(*args, **kwargs)
  File "C:\Program Files\Python37\lib\site-packages\pyglet\window\__init__.py", line 592, in __init__
    config = screen.get_best_config(config)
  File "C:\Program Files\Python37\lib\site-packages\pyglet\canvas\base.py", line 197, in get_best_config
    raise window.NoSuchConfigException()
pyglet.window.NoSuchConfigException

""

**Comment by FGarridoV** [comment]
Tu computador al parecer no tiene una configuración de pantalla. En la librería game.py hay un método super().

Que pide dos campos extra opcionales:
Resizable=False y config.

Este último, su valor por defecto get_best_config() te genera el error. 

En la página 11 de este articulo te muestran como manejarlo y crear un config específico. (Articulo)[https://media.readthedocs.org/pdf/pyglet/latest/pyglet.pdf]

Me cuentas como te va!

Saludos,
Francisco

**Comment by mcromero1** [comment]
¿Como puedo hacerlo si no me aparece la carpeta que debería aparecer en mac, después del código rm -rf ~/anaconda3?¿sigo con lo demás o se podría llamar de otra forma aunque no me aparece ninguna carpeta nueva en el home?.
Saludos

**Comment by asnunez1** [comment]
Hola! Seguí todas las instrucciones del tutorial y todo se instaló perfectamente en el terminal, pero aún así la librería no me funciona.

Me aparece el siguiente error: AttributeError: 'NoneType' object has no attribute 'setView_'
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-7-15735f272d5f> in <module>
      2 import arcade
      3 
----> 4 window = game.LostGame()
      5 window.setup()
      6 window.poner_pieza("player1.png",4,8,1)

~/Desktop/repositorio-2019-1-asnunez1/L02/game.py in __init__(self)
     37 
     38     def __init__(self):
---> 39         super().__init__(SCREEN_WIDTH, SCREEN_HEIGHT, SCREEN_TITLE)
     40         self.sprites_list = None
     41         self.background = None

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/arcade/application.py in __init__(self, width, height, title, fullscreen, resizable, update_rate, antialiasing)
     51 
     52         super().__init__(width=width, height=height, caption=title,
---> 53                          resizable=resizable, config=config)
     54 
     55         if antialiasing:

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyglet/window/__init__.py in __init__(self, width, height, caption, resizable, style, fullscreen, visible, vsync, display, screen, config, context, mode)
    641         from pyglet import app
    642         app.windows.add(self)
--> 643         self._create()
    644 
    645         self.switch_to()

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/arcade/monkey_patch_pyglet.py in _create(self)
     79         # Create a canvas with the view as its drawable and attach context to it.
     80         self.canvas = CocoaCanvas(self.display, self.screen, self._nsview)
---> 81         self.context.attach(self.canvas)
     82 
     83         # Configure the window.

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyglet/gl/cocoa.py in attach(self, canvas)
    287         # The NSView instance should be attached to a nondeferred window before calling
    288         # setView, otherwise you get an "invalid drawable" message.
--> 289         self._nscontext.setView_(canvas.nsview)
    290         self._nscontext.view().setWantsBestResolutionOpenGLSurface_(1)
    291         self.set_current()

AttributeError: 'NoneType' object has no attribute 'setView_'

**Comment by asnunez1** [comment]
Hola! seguí todas las instrucciones del tutorial y todo se instaló perfectamente, pero aún no corre la librería.
Me aparece el siguiente error -> AttributeError: 'NoneType' object has no attribute 'setView_' 
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-7-15735f272d5f> in <module>
      2 import arcade
----> 4 window = game.LostGame()
      5 window.setup()
      6 window.poner_pieza("player1.png",4,8,1)

~/Desktop/repositorio-2019-1-asnunez1/L02/game.py in __init__(self)
     38     def __init__(self):
---> 39         super().__init__(SCREEN_WIDTH, SCREEN_HEIGHT, SCREEN_TITLE)
     40         self.sprites_list = None
     41         self.background = None

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/arcade/application.py in __init__(self, width, height, title, fullscreen, resizable, update_rate, antialiasing)
     51 
     52         super().__init__(width=width, height=height, caption=title,
---> 53                          resizable=resizable, config=config)
     55         if antialiasing:

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyglet/window/__init__.py in __init__(self, width, height, caption, resizable, style, fullscreen, visible, vsync, display, screen, config, context, mode)
    641         from pyglet import app
    642         app.windows.add(self)
--> 643         self._create()
    645         self.switch_to()

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/arcade/monkey_patch_pyglet.py in _create(self)
     79         # Create a canvas with the view as its drawable and attach context to it.
     80         self.canvas = CocoaCanvas(self.display, self.screen, self._nsview)
---> 81         self.context.attach(self.canvas)
     83         # Configure the window.

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyglet/gl/cocoa.py in attach(self, canvas)
    287         # The NSView instance should be attached to a nondeferred window before calling
    288         # setView, otherwise you get an "invalid drawable" message.
--> 289         self._nscontext.setView_(canvas.nsview)
    290         self._nscontext.view().setWantsBestResolutionOpenGLSurface_(1)
    291         self.set_current()
AttributeError: 'NoneType' object has no attribute 'setView_'

**Comment by asnunez1** [comment]
Hola! seguí todas las instrucciones del tutorial y todo se instaló perfectamente, pero aún no corre la librería.
Me aparece el siguiente error: AttributeError: 'NoneType' object has no attribute 'setView_' 

AttributeError                            Traceback (most recent call last)
<ipython-input-7-15735f272d5f> in <module>
      2 import arcade
----> 4 window = game.LostGame()
      5 window.setup()
      6 window.poner_pieza("player1.png",4,8,1)

~/Desktop/repositorio-2019-1-asnunez1/L02/game.py in __init__(self)
     38     def __init__(self):
---> 39         super().__init__(SCREEN_WIDTH, SCREEN_HEIGHT, SCREEN_TITLE)
     40         self.sprites_list = None
     41         self.background = None

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/arcade/application.py in __init__(self, width, height, title, fullscreen, resizable, update_rate, antialiasing)
     51 
     52         super().__init__(width=width, height=height, caption=title,
---> 53                          resizable=resizable, config=config)
     55         if antialiasing:

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyglet/window/__init__.py in __init__(self, width, height, caption, resizable, style, fullscreen, visible, vsync, display, screen, config, context, mode)
    641         from pyglet import app
    642         app.windows.add(self)
--> 643         self._create()
    645         self.switch_to()

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/arcade/monkey_patch_pyglet.py in _create(self)
     79         # Create a canvas with the view as its drawable and attach context to it.
     80         self.canvas = CocoaCanvas(self.display, self.screen, self._nsview)
---> 81         self.context.attach(self.canvas)
     83         # Configure the window.

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/pyglet/gl/cocoa.py in attach(self, canvas)
    287         # The NSView instance should be attached to a nondeferred window before calling
    288         # setView, otherwise you get an "invalid drawable" message.
--> 289         self._nscontext.setView_(canvas.nsview)
    290         self._nscontext.view().setWantsBestResolutionOpenGLSurface_(1)
    291         self.set_current()
AttributeError: 'NoneType' object has no attribute 'setView_'

**Comment by javiolivas** [comment]
Hice todo lo del tutorial y tampoco me aparecía la carpeta que tiene que aparecer de anaconda en mac. Segui con los pasos siguientes pero al final aun me sigue arrojando el mismo error AttributeError: 'NoneType' object has no attribute 'setView_'.

**Comment by javiprado** [comment]
Hola,
Seguí todos los pasos y sigue sin funcionar, pero me tira este error en arcade:

GLException                               Traceback (most recent call last)
<ipython-input-3-180af0a4a03a> in <module>
     61 juego.mover_pieza(0,2,4) 
     62 juego.fin_del_juego()
---> 63 arcade.run()
     64 
     65 

c:\program files\python37\lib\site-packages\arcade\window_commands.py in run()
    243     commands on the main program.
    244     """
--> 245     pyglet.app.run()
    246 
    247 

c:\program files\python37\lib\site-packages\pyglet\app\__init__.py in run()
    140 
    141     """
--> 142     event_loop.run()
    143 
    144 

c:\program files\python37\lib\site-packages\pyglet\app\base.py in run(self)
    173             self._run_estimated()
    174         else:
--> 175             self._run()
    176 
    177         self.is_running = False

c:\program files\python37\lib\site-packages\pyglet\app\base.py in _run(self)
    185         platform_event_loop = app.platform_event_loop
    186         while not self.has_exit:
--> 187             timeout = self.idle()
    188             platform_event_loop.step(timeout)
    189 

c:\program files\python37\lib\site-packages\pyglet\app\base.py in idle(self)
    312             if redraw_all or (window._legacy_invalid and window.invalid):
    313                 window.switch_to()
--> 314                 window.dispatch_event('on_draw')
    315                 window.flip()
    316                 window._legacy_invalid = False

c:\program files\python37\lib\site-packages\pyglet\window\__init__.py in dispatch_event(self, *args)
   1311     def dispatch_event(self, *args):
   1312         if not self._enable_event_queue or self._allow_dispatch_event:
-> 1313             if EventDispatcher.dispatch_event(self, *args) != False:
   1314                 self._legacy_invalid = True
   1315         else:

c:\program files\python37\lib\site-packages\pyglet\event.py in dispatch_event(self, event_type, *args)
    368         if handler is not None:
    369             try:
--> 370                 if handler(*args):
    371                     return EVENT_HANDLED
    372             except TypeError as exception:

e:\progra\repositorio-2019-1-javiprado\L02\game.py in on_draw(self)
     58     def on_draw(self):
     59         arcade.start_render()
---> 60         arcade.draw_texture_rectangle(SCREEN_WIDTH // 2, (SCREEN_HEIGHT // 2)+15, SCREEN_WIDTH, SCREEN_HEIGHT-30, self.background)
     61         self.sprites_list.draw()
     62         output = f"{self.current_text}"

c:\program files\python37\lib\site-packages\arcade\draw_commands.py in draw_texture_rectangle(center_x, center_y, width, height, texture, angle, alpha, repeat_count_x, repeat_count_y)
   1262     texture.draw(center_x, center_y, width,
   1263                  height, angle, alpha,
-> 1264                  repeat_count_x, repeat_count_y)
   1265 
   1266 

c:\program files\python37\lib\site-packages\arcade\draw_commands.py in draw(self, center_x, center_y, width, height, angle, alpha, transparent, repeat_count_x, repeat_count_y)
    184         self._sprite.angle = angle
    185 
--> 186         self._sprite_list.draw()
    187 
    188 

c:\program files\python37\lib\site-packages\arcade\sprite_list.py in draw(self)
    557         # gl.glTexParameterf(gl.GL_TEXTURE_2D, gl.GL_TEXTURE_MAG_FILTER, gl.GL_NEAREST)
    558 
--> 559         with self.vao:
    560             self.program['Texture'] = self.texture_id
    561             self.program['Projection'] = get_projection().flatten()

c:\program files\python37\lib\site-packages\arcade\shader.py in __enter__(self)
    455 
    456     def __enter__(self):
--> 457         glBindVertexArray(self.vao)
    458         glUseProgram(self.program)
    459 

c:\program files\python37\lib\site-packages\pyglet\gl\lib.py in errcheck(result, func, arguments)
    103         if error:
    104             msg = ctypes.cast(gl.gluErrorString(error), ctypes.c_char_p).value
--> 105             raise GLException(msg)
    106         return result
    107 

GLException: b'operaci\xf3n no v\xe1lida'


¿Qué puedo hacer? :(

**Comment by gonzaloriveros** [comment]
Yo tengo el mismo problema que @asnunez1 a diferencia de que no pude seguir el tutorial porque mi terminal (en mac) no reconoce los comandos conda y anaconda.

**Comment by simonerenard** [comment]
Hola! A mi tampoco me funciona en mi mac :(

Siguiendo los pasos del tutorial no pude poner textualmente el comando "anaconda-clean --yes" ya que estaba a ingresar un [y/n], asumí que poner y era decirle yes, pero por lo que vi después solamente se me descargaron archivos y cosas. 

No me apareció ninguna carpeta en el home. El ícono de anaconda me sigue apareciendo en el computador (y eso que ya lo reinicié) y ahora cuando trato de correr el archivo se me abre el Python Launcher y se me queda pegado el programa.

No sé si lo hice mal o si las instrucciones a lo mejor no funcionan en mis versiones que tengo en el computador.

Gracias por su tiempo!

**Comment by vnramirez** [comment]
No me funciona hacer el primer comando que hay que hacer en cmd administrador. Al parecer no puedo acceder a la fuente de la descarga.
Estoy con el internet de mi casa, por lo que no debería tener ningún tipo de bloqueo...

C:\Users\vicen\Anaconda3\Scripts>conda install anaconda-clean
Solving environment: failed

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.anaconda.com/pkgs/free/win-64/repodata.json.bz2>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

If your current network has https://www.anaconda.com blocked, please file
a support request with your network engineering team.

SSLError(MaxRetryError('HTTPSConnectionPool(host=\'repo.anaconda.com\', port=443): Max retries exceeded with url: /pkgs/free/win-64/repodata.json.bz2 (Caused by SSLError("Can\'t connect to HTTPS URL because the SSL module is not available."))'))

Gracias

**Comment by cmujicai** [comment]
@FGarridoV Me leí la página 11 del artículo que mandaste. Sé que ahí te explican el problema pero no entendí muy bien como resolverlo, me podrías ayudar? Quieres que modifique el game.py??? Realmente no entendí muy bien

**Comment by FelipeUlloan** [comment]
Hice lo que indicaron en el tutorial, desinstalé python y lo volví a instalar con el link correspondiente a 64 bits de mac, y ahora cuando intento instalar cualquier librería me tira el error de -bash: python37: command not found, intenté con py y tampoco lo reconoce.
Que puedo hacer?

**Comment by ValentinaNavarro** [comment]
Hola! me pasa lo mismo que @FelipeUlloan 

Al intentar hacer el paso 2.4) de la instalación para mac el terminal me devuelve el error : -bash: python37: command not found

Por un momento pensé que había instalado mal la nueva version de python pero revise y efectivamente tengo la 3.7.3. 
ayuda!

**Comment by FGarridoV** [comment]
@cmujicai y para los que tienen el error de **pyglet.window.NoSuchConfigException**. Si ya hicieron el tutorial, deben reiniciar el kernel cada vez que inician el juego nuevo. Así desaparecen las cosas que Jupyter deja cargadas de la corrida anterior.

saludos,
Francisco

**Comment by asnunez1** [comment]
@FelipeUlloan me pasaba lo mismo. En la parte de "python37 -m pip3 install PyObjC arcade" hay que poner python3.7  y funciona

**Comment by cmujicai** [comment]
@FGarridoV No entiendo a que te refieres. Ya no sirve entonces el artículo que me mandaste? Es otro el problema? Por favor ayuda, ya que llevo mucho tiempo perdido intentando de hacer funcionar la libreria. Quedo atento a la respuesta

**Comment by cmujicai** [comment]
@FGarridoV Además a que te refieres con "reiniciar el kernel"???

**Comment by vnramirez** [comment]
@cmujicai en la barrita de arriba de Jupyter hay un símbolo como de actualizar (a la izquierda del símbolo stop). Eso reinicia el kernel!

**Comment by Mcarriagada** [comment]
Hola, al seguir el tutorial en la parte 1.1 (desintalación de anaconda) me señala el siguiente error.

C:\Users\Mati Arriagada\Anaconda3\Scripts>conda install anaconda-clean
Collecting package metadata: failed

CondaHTTPError: HTTP 000 CONNECTION FAILED for url <https://repo.anaconda.com/pkgs/free/noarch/repodata.json.bz2>
Elapsed: -

An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

If your current network has https://www.anaconda.com blocked, please file
a support request with your network engineering team.

SSLError(MaxRetryError('HTTPSConnectionPool(host=\'repo.anaconda.com\', port=443): Max retries exceeded with url: /pkgs/free/noarch/repodata.json.bz2 (Caused by SSLError("Can\'t connect to HTTPS URL because the SSL module is not available."))'))

**Comment by vnramirez** [comment]
Haz los mismos pasos pero desde Anaconda prompt, es la consola de anaconda.
A mi me pasaba lo mismo!

**Comment by niherrera** [comment]
En el último paso para eliminar anaconda no me salen textuales las lineas que tengo que borrar del bash. El  mensaje que me sale es el siguiente

# Setting PATH for Python 3.4
# The orginal version is saved in .bash_profile.pysave
PATH="/Library/Frameworks/Python.framework/Versions/3.4/bin:${PATH}"
export PATH

# Setting PATH for Python 3.7
# The original version is saved in .bash_profile.pysave
PATH="/Library/Frameworks/Python.framework/Versions/3.7/bin:${PATH}"
export PATH
# added by Anaconda3 2018.12 installer
# >>> conda init >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$(CONDA_REPORT_ERRORS=false '/anaconda3/bin/conda' shell.bash hook 2> /dev/null)"
if [ $? -eq 0 ]; then
    \eval "$__conda_setup"
else
    if [ -f "/anaconda3/etc/profile.d/conda.sh" ]; then
        . "/anaconda3/etc/profile.d/conda.sh"
        CONDA_CHANGEPS1=false conda activate base
    else
        \export PATH="/anaconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda init <<<

**Comment by VivancoF** [comment]
@FGarridoV buenas tardes. Instale python 3.7 (64bit) y me aparece nuevamente este error el correr este codigo:
import arcade
import game

window = game.LostGame()
window.setup()
window.poner_pieza('player1.png',4,8,1) #posicion y escala
window.poner_pieza('player2.png',4,8,1)

arcade.run()

Resultado:
NoSuchConfigException                     Traceback (most recent call last)
<ipython-input-3-5e8a928b9085> in <module>()
      2 import game
      3 
----> 4 window = game.LostGame()
      5 window.setup()
      6 window.poner_pieza('player1.png',4,8,1) #posicion y escala
.
.
.
~\Anaconda3\lib\site-packages\pyglet\canvas\base.py in get_best_config(self, template)
    195             configs = self.get_matching_configs(template)
    196         if not configs:
--> 197             raise window.NoSuchConfigException()
    198         return configs[0]
    199 

NoSuchConfigException:

**Comment by FelipeUlloan** [comment]
hice nuevamente todo el tutorial para mac, pude instalar las librerias de arcade, pero al momento de ejecutar, me entrega el mismo error  :(
AttributeError: 'NoneType' object has no attribute 'setView_'

**Comment by ValentinaNavarro** [comment]
Hola, nuevamente me paso lo mismo que a @FelipeUlloan 
nose si en alguna parte de todos los comentarios que han escrito ya solucionaron esto, si no.. ayuda!

**Comment by FernandoSMG** [comment]
@vnramirez vicho no me deja usar Anaconda Promt como administrador, solo el CMD normal de Windows y me aparece el mismo error que a @Mcarriagada , como iniciaste Anaconda Promt como admin?

**Comment by FcaCanales** [comment]
Hola ! hice todos los pasos pero ahora me apareció un problema distinto al inicial:
para instalar el arcade con la primera y tercera opción que proponen en el enunciado, me sale error de sintaxis(_con pip3 install arcade_ y con _python3 -m pip install arcade_)
y con la segunda opcion (_pip install arcade_) me sale que tengo que reiniciar el kernel. Antes de leer el comentario de @vnramirez, lo cerre y lo volví a abrir, reinicie el pc y despues reinicie el kernel como dijo. Luego intenté las 3 opciones de nuevo, y los mismos errores :(

**Comment by josefinabravo** [comment]
Ejecutando "python37 -m pip3 install PyObjC arcade" no me reconoce python37 (ni python3.7) como comando. Al intentar no usar esta parte y solo escribir "pip3 install PyObjC arcade" me sale otro tipo de error. ¿Cómo puedo realizar esta parte de las instrucciones?

**Comment by cdpoblete** [comment]
Hola! Pude realizar el tutorial sin ningún problema pero me sigue tirando el error que a varios de acá. He intentado arreglarlo de todas las formas pero sigue apareciendo lo mismo. El error es el siguiente: 

---------------------------------------------------------------------------
ContextException                          Traceback (most recent call last)
<ipython-input-2-5a284f7c81c0> in <module>
      2 import arcade
      3 
----> 4 window = game.LostGame()
      5 window.setup()
      6 window.poner_pieza("player1.png",4,8,1)

~\Documents\Powi\UC\Programación como herramienta para la Ingeniería\repositorio-2019-1-cdpoblete\L02\game.py in __init__(self)
     37 
     38     def __init__(self):
---> 39         super().__init__(SCREEN_WIDTH, SCREEN_HEIGHT, SCREEN_TITLE)
     40         self.sprites_list = None
     41         self.background = None

c:\program files\python37\lib\site-packages\arcade\application.py in __init__(self, width, height, title, fullscreen, resizable, update_rate, antialiasing)
     51 
     52         super().__init__(width=width, height=height, caption=title,
---> 53                          resizable=resizable, config=config)
     54 
     55         if antialiasing:

c:\program files\python37\lib\site-packages\pyglet\window\win32\__init__.py in __init__(self, *args, **kwargs)
    135                     self._event_handlers[message] = func
    136 
--> 137         super(Win32Window, self).__init__(*args, **kwargs)
    138 
    139     def _recreate(self, changes):

c:\program files\python37\lib\site-packages\pyglet\window\__init__.py in __init__(self, width, height, caption, resizable, style, fullscreen, visible, vsync, display, screen, config, context, mode)
    641         from pyglet import app
    642         app.windows.add(self)
--> 643         self._create()
    644 
    645         self.switch_to()

c:\program files\python37\lib\site-packages\pyglet\window\win32\__init__.py in _create(self)
    265         if not self._wgl_context:
    266             self.canvas = Win32Canvas(self.display, self._view_hwnd, self._dc)
--> 267             self.context.attach(self.canvas)
    268             self._wgl_context = self.context._context
    269 

c:\program files\python37\lib\site-packages\pyglet\gl\win32.py in attach(self, canvas)
    289         self.config._set_pixel_format(canvas)
    290         self._context = wglext_arb.wglCreateContextAttribsARB(canvas.hdc, share, attribs)
--> 291         super(Win32ARBContext, self).attach(canvas)

c:\program files\python37\lib\site-packages\pyglet\gl\win32.py in attach(self, canvas)
    236                 raise RuntimeError('Share context has no canvas.')
    237             if not wgl.wglShareLists(share._context, self._context):
--> 238                 raise gl.ContextException('Unable to share contexts.')
    239 
    240     def set_current(self):

ContextException: Unable to share contexts.

**Comment by FelipeUlloan** [comment]
Estimados profesores,
Actualmente sigo sin poder hacer uso de las librerías y de momento me encuentro programando sin siquiera poder considerarlo, es decir, solo a base de printeos y listas con posiciones. Tengo miedo a que esto no sea lo que finalmente se esperaba de esta tarea pues lo único que he importando como librería es random. No utilizo ni arcade, ni game.
He realizado 2 veces los tutoriales para mac y la verdad me he rendido a intentar solucionar el error.Por honor al tiempo y debido a que la próxima semana tengo 6 obligaciones académicas entre tareas, pruebas y laboratorios he avanzado con lo que tenia nada más a mi alcance.
Dicho esto, implica un descuento en la nota el no hacer uso de game ni arcade? pues mi programa pretende realizar todo por debajo y no mostrar nada cuando se corra.
Espero puedan considerar lo frustrante que fue y es para todos quienes aun no podemos solucionar el error :(

**Comment by mairiondo** [comment]
Hola, trate de ejecutar los 2 comandos para desinstalar anaconda desde el Anaconda Prompt. Pude ejecutar el primero, pero al tratar de ejecutar el 2do me sale este error:

(base) C:\Users\mairi\Anaconda3\Scripts>anaconda-clean --yes
Backup directory: C:\Users\mairi\.anaconda_backup\2019-03-30T104358
Error: Unable to move C:\Users\mairi\.ipython

a qué se debe?

**Comment by mairiondo** [comment]
Al tratar de correr el juego, con el siguiente código:
w=game.LostGame()
w.setup()
w.mostrar_texto("hola")
w.fin_del_juego()
w.run()

Me aparece el siguiente error:
AttributeError                            Traceback (most recent call last)
<ipython-input-1-fe51c51075a8> in <module>
   1231 w.mostrar_texto("hola")
   1232 w.fin_del_juego()
-> 1233 w.run()
   1234 

AttributeError: 'LostGame' object has no attribute 'run'

A que se debe este error?
