### ISSUE TITLE
Enunciado Tarea 2

### ISSUE THREAD

**Issue by BenjaminIbanez** [IIC2115/Syllabus#47]
Buenas Tardes:
Cuando van a subir el enunciado de la tarea 2 o donde se encuentra, ya que, segun el programa del curso, el enunciado iba a estar subido el dia martes 24.

Saludos Cordiales.
Benjamin Ibañez

**Comment by RonaldoSosa** [comment]
Hola. El profesor me comunica que la tarea debería de estar publicada entre hoy en la noche o mañana, tendrán unas 3 semanas. El profesor detallará más esto cuando publique la tarea.
