### ISSUE TITLE
Pregunta 3. Traduccion

### ISSUE THREAD

**Issue by sregonesi** [IIC2115/Syllabus#47]
Hola, tengo una duda del ejemplo que dan para traducir en la pregunta 3, "elaguaeselaguaeselpez", "A B B C". A mi parecer tiene dos posibles traducciones(traduccion 1: ((’A’, ’el’), (’B’, ’aguaesel’), (’C’, ’pez’)). Traduccion 2: ((’A’, ’e’), (’B’, ’laguaese’), (’C’, ’lpez’)), de ser asi se consideran las dos como correctas o solo la que aparece en el enunciado?. o hay que leer el mensaje de izquierda a derecha?.
saludos

**Comment by Jamidd** [comment]
Puede que exista mas de una posibilidad de dividir el string. Si sigue el patrón pedido y al juntarlo queda igual al original esta correcto. 

Saludos.
Jaime
