### ISSUE TITLE
Tarea 2: OpenStreetMap

### ISSUE THREAD

**Issue by Fopazov** [IIC2115/Syllabus#48]
Buenas noches, me surgió una duda. ¿Debemos desgargar los datos de openstreetmap desde internet (.osm) o se solicita utilizar la librería osmnx?
Gracias de antemano

**Comment by RonaldoSosa** [comment]
Hola. Como se indica en el enunciado deben utilizar y combinar los datos de la Actividad 4, Tarea 1 y OpenStreetMap. Esto último se refieren a que trabajen de forma similar a como se pedía para la actividad 4 y que fue desarrollada en la ayudantía 9.
