### ISSUE TITLE
TAREA3

### ISSUE THREAD

**Issue by gevicencio** [IIC2115/Syllabus#48]
se espera que cuando se encuentren los caminos óptimos cada amigo coma mas o menos la misma cantidad de calorías? o sólo es necesario que no quede comida al finalizar todo?

**Comment by fnquinteros** [comment]
Hola! En primer lugar, te pido que seas un poco más descriptivo con los títulos de tus issues, para que les sea más fácil a los demás encontrar las respuestas a sus preguntas si ya fueron hechas.

Ahora la respuesta a tu pregunta: no se espera nada sobre la proporción de calorías que consumió cada compañero, solo que realicen los algoritmos que describimos y pedimos de forma correcta y que al finalizar todo no quede comida en el tablero.

Saludos!

**Comment by nmcarvajalcortes** [comment]
Hola!!

Un ejemplo, si hay 2 amigos y la lista de comidas en el mapa son:

6 empanadas (3600)
1 anticuchos (300 calorías)
7 choripanes (3500)
3 terremotos (600 calorías)

Se cumple que hay 4000*m (m = número de amigos) calorías en el mapa, pero si uno de ellos utilizando rutas mínimas se come primero 6 empanadas y luego 1 anticucho, habrá consumido 3900 calorías y al final de la simulación aún quedarán productos en el mapa porque depende del orden en que alcancen los alimentos.

¿Qué hago en esta situación?
