### ISSUE TITLE
Output Problema 3, Laboratorio 1

### ISSUE THREAD

**Issue by jbraunb** [IIC2115/Syllabus#48]
Estoy partiendo el ejercicio 3 y no entiendo la nota entregada para el ejemplo.

Sume las ponderaciones de cada evaluación realizada y las dividi por la ponderación total, creo que esta operación debería entregar la nota final, si la nota de cada evaluación realizada es 1 y las de las no realizadas es 0. Pero este numero me entrega un numero diferente al output.

¿Estoy calculando mal la ponderación o hay un error?

PD: El código entregado tiene un error ya que la función llama a la variable evaluaciones y solo existe evals.

**Comment by pcseisdedos** [comment]
Hola! la `nota final ponderada` se calcula como la suma de la ponderación de cada evaluación multiplicado por su nota, dividido por la suma de las ponderaciones. Tal como se muestra aquí: 

![CodeCogsEqn (1)](https://user-images.githubusercontent.com/18387808/117208635-5d459000-adc3-11eb-90d9-dc362c576fe1.gif)


El valor obtenido se debe redondear a 2 cifras después de la coma. En el caso del ejemplo del enunciado el valor correcto debiera ser `0.94` en lugar de 0.96. Lo actualicé junto con el error de tipeo que comentaste.

Saludos,
Pablo 😁👍

**Comment by jbraunb** [comment]
Perfecto!! ahi me calza!

Gracias!
