### ISSUE TITLE
Python Not Responding y reinicio del kernel al ejecutar el código

### ISSUE THREAD

**Issue by vnramirez** [IIC2115/Syllabus#48]
Hola,

Hice el nuevo tutorial para reinstalar todo y al parecer funcionó. Al menos la desinstalación e instalación fue sin problemas.
Luego intenté correr mi código (y también el que nos mostró Francisco el lunes) y me sigue pasando lo mismo. Al correrlo por primera vez, se me abre una ventanita de Python que se llama Juego Perdido, pero abre (Not Responding) siempre. Al cerrarla, se finaliza el proceso de Python, tira error en la consola de Jupyter y tira el mensaje de que el kernel debe reiniciarse porque colapsó.

A alguien más le pasa? Alguien pudo correr algo básico usando arcade y game?

Gracias

**Comment by FGarridoV** [comment]
Probaste reinciar el PC? Si te abre la ventana, entonces ya tienes resulto el error de la librería. Me suena a que el problema puede ser que están usándose los recursos en otro proceso.

**Comment by vnramirez** [comment]
@FGarridoV  Sí!

Intenté correrlo si mi lógica (un while que se podría llegar a demorar un poco), y lo que me pasa ahora es que efectivamente se me abre una ventanita con Juego Perdido pero en blanco, no se ve nada de lo que pasa. Luego de unos 3 segundos, la ventanita se cierra y se termina de ejectutar el módulo de Juypter correctamente (al menos ya no me tira error ni me dice que kernel is dead).
El problema es que nunca he podido ver nada gráficamente!

**Comment by vnramirez** [comment]
Creo que ya caché lo que pasa.
La ventanita aparece como Not Responding hasta que el código termina de ejecutarse. En mi caso, es cuando mi "condición" se cumple. Recién ahí me empieza a mostrar la parte gráfica y las piezas moverse. 
Como que ejecuta todos los turnos que necesita (eventualmente muchos) y recién al final te muestra lo que pasó en todos esos turnos.
Es así?

**Comment by FGarridoV** [comment]
Si, como se mencionó en clases, la librería no sirve para resolver el problema. Es solo para que al final muestre la animación de lo que ya resolviste. Como si de un video se tratase.
