### ISSUE TITLE
Problema al crear el archivo en 04 - "Acceso a bases de datos" (Error!  * is not UTF-8 encoded)

### ISSUE THREAD

**Issue by romidonghi** [IIC2115/Syllabus#48]
Hola, en la parte 04 sobre SQL + python del capitulo 3 cuando abro el archivo que se creó con la nueva tabla me aparece Error!  * is not UTF-8 encoded. Saving disabled. See console for more details.
Intenté buscar el error en google pero no logré encontrar la forma de arreglarlo. 
![Captura de Pantalla 2020-09-29 a la(s) 22 58 35](https://user-images.githubusercontent.com/69482280/94635008-fe0d2380-02a7-11eb-9bbe-eff0123857cb.png)

**Comment by pcseisdedos** [comment]
Hola,
Disculpa la demora, seguramente la base de datos está en un formato que no soporta jupyter, para visualizarla puedes hacerlo directamente con SQL.

Saludos,
Pablo 😁👍

**Comment by jaraya4** [comment]
Hay que descargar SQLite entonces?

**Comment by pcseisdedos** [comment]
Existen programas como SQLite para visualizar, pero también pueden hacerlo con una consulta SQL desde la librería vista en el curso.

Saludos,
Pablo 😁👍
