### ISSUE TITLE
Tarea 2: preguntas sobre enunciado 

### ISSUE THREAD

**Issue by Fopazov** [IIC2115/Syllabus#49]
- M1: "incluyendo dentro de esta su **recorrido** en la columna geometry". ¿A qué se refiere con recorrido en este caso? ¿a la posición del bus en el momento determinado según las mediciones gps? 
- M2: en base a un **análisis de las posiciones de los buses durante las expediciones**, identificar paraderos. No entiendo como se podrían identificar paraderos a partir de las posiciones de los buses. ¿La idea es obtener con Openstreetmap? 
- M3: ¿cuáles serían los posibles medios de transporte además de bus y metro? 
Gracias de antemano

**Comment by mbertin1** [comment]
Sobre la misma pregunta del recorrido... se espera que se tenga un dataframe que para cada medicion se tenga su punto en geometry. O que se tenga una linea que una estos puntos para cada expedicion o linea??

**Comment by RonaldoSosa** [comment]
Hola @mbertin1. Para decidir qué tipo usar debes de tener en cuenta las características de cada uno y ver cuál  es el más apropiado:
- POINT: Representa un único punto en el espacio
- LINESTRING: Representa una secuencia ordenada de puntos conectados por segmentos de línea recta
- POLYGON: Representa una región cerrada en el plano, definida por una secuencia de coordenadas de vértices que se conectan en una secuencia cerrada

**Comment by Fopazov** [comment]
Entonces, ¿1 recorrido estaría asociado a 1 línea de servicio? (logré graficar cada medición gps, pero no distingo entre líneas de servicio: C02, C02C....)

**Comment by Fopazov** [comment]
Con respecto a los paraderos, el método para identificar paraderos es arbitrario? (siempre que tenga sentido)

**Comment by RonaldoSosa** [comment]
Hola @Fopazov. Respondiendo en orden a tus preguntas:
- Un recorrido estaría asociado a un bus por así decirlo. Recuerda que para la Tarea 1 se dio la siguiente definición para la columna expedition_id "identificador interno de la expedición asociada a la medición GPS. Una expedición
corresponde a la realización de un recorrido por un bus".
- No hay una norma estipulada para identificar los paraderos, sin embargo, como dices se espera que la manera en la que lo hagan tenga sentido, sería de ayuda si explicasen en un comentario la lógica empleada para identificarlo.
