### ISSUE TITLE
Prioridad búsqueda de comida

### ISSUE THREAD

**Issue by memadrid** [IIC2115/Syllabus#49]
El enunciado dice: "Debes priorizar las comidas que se encuentren más cercanas" . ¿Cuál es el criterio que debería usar para elegir la comida más cercana? ¿sólo la distancia de Manhattan, o la distancia efectiva más corta (es decir, considerando los obstáculos)?

**Comment by Hernan4444** [comment]
Hola, basta con que utilices una heurística admisible para calcular la distancia. Tanto Manhattan como distancia euclideana son heurísticas aceptadas.

Saludos ✌️

**Comment by fjgonzalez5** [comment]
Pero si por ejemplo una comida se encuentra detrás de un obstáculo, la heurística deja de ser certera, no? Porque debería rodear el obstáculo. Por ejemplo un caso así:
_ _ E
_ X _
_ X _
C X P
La persona P, si hace una heuristica, le diria que el alimento mas cercano es C, pero en realidad es E. ¿Qué hacemos en este caso?

**Comment by Hernan4444** [comment]
Queda a tu criterio, puedes usar más de una heuristica o utilizar la distancias antes indicadas pero revisando obstáculos, también puedes usar backtracking para encontrar el camino más corto, etc. Hay varias alternativas y queda a tu criterio cual usar 👍 

Saludos ✌️
