### ISSUE TITLE
L03 numero de variables de la tabla city

### ISSUE THREAD

**Issue by Leda7** [IIC2115/Syllabus#49]
Hola, es que al ver la cantidad de columnas que tiene la tabla city me aparecen 21 no 20 como dice el enunciado eso esta bien? Gracias.

**Comment by pcseisdedos** [comment]
Puede que sea un error de tipeo simplemente, pero no creo que sea relevante.

Saludos,
Pablo 😁👍

**Comment by Jisepulveda1** [comment]
Pero si es un error de tipeo que hago con la variable que me sobra?
Como se cual variable es cual.
Para la tabla eco en el enunciado salen 19 variables pero en la tabla aparecen 21 columnas.

**Comment by pcseisdedos** [comment]
Si su pergunta es respecto a que en la base de datos hay más columnas que las listadas, en el enunciado se especifica que "considere solo las siguientes columnas (ignore otro tipo de columnas)".

Saludos,
Pablo 😁👍

**Comment by Jisepulveda1** [comment]
Claro, pero debo asumir que las columnas sobrantes son las ultimas?

**Comment by FGarridoV** [comment]
No necesariamente, el orden de columnas y filas en una BD no tiene relevancia. Lo importante es que solo consideres las columnas que están en el anunciado.
