### ISSUE TITLE
Laboratorio 1: Duda sobre el problema 3

### ISSUE THREAD

**Issue by ricardomerino99** [IIC2115/Syllabus#49]
Hola, en la pregunta tres se pueden realizar evaluaciones a partir del día 0? O hay que partir del día 1?
Considerando que se pueden realizar las evaluaciones hasta el día menor o igual al limite, si puedo comenzar resolviendo evaluaciones desde el día 0 que es lo que me parece lógico (porque el input contiene los días que faltan para la entrega) puedo obtener una nota máxima de 0.98 con el input del enunciado, mientras que si lo hago partiendo del día 1 obtengo 0.94 (como el enunciado). Por otro lado, veo que el problema puede tener múltiples respuestas ya que para el 0.94 que obtuve, realice las mismas evaluaciones que la respuesta del enunciado pero en distinto orden, y revise manualmente que la respuesta también fuera valida.

**Comment by pcseisdedos** [comment]
Hola, se parte del día 1. Respecto a lo otro, es verdad que puede haber múltiples soluciones, pero basta con que entreguen una correcta.

Saludos,
Pablo 😁👍
