### ISSUE TITLE
Problemas en mac después de seguir los pasos del tutorial

### ISSUE THREAD

**Issue by sidiaz2** [IIC2115/Syllabus#49]
Hola. Luego de seguir todos los pasos del tutorial para desinstalar Anaconda de Mac, instalar Python nuevamente, instalar Arcade, sigo obteniendo el mismo error. 

En primer lugar, al importar Arcade, me dice: 
FFmpeg binaries could not be loaded.

Luego, al intentar realizar game.LostGame() y window.setup(), me tira el error:
AttributeError: 'NoneType' object has no attribute 'setView_'

El cual es el mismo error que me tiraba al principio. A alguien le ocurre lo mismo? Alguna idea de cómo solucionarlo? Gracias.

**Comment by sidiaz2** [comment]
Cambio la pregunta: alguien en mac pudo correr la librería efectivamente?

**Comment by ValentinaNavarro** [comment]
Hola!! 
me pasa exactamente lo mismo, aun no puedo correr nada :(

**Comment by arielczerny** [comment]
Hola! Me pasa exactamente lo mismo.. Realice todos los pasos y aún asi no me corre la interfaz gráfica. Tengo el error de _setView_..

**Comment by arbanados** [comment]
Lo mismo por aca.....

**Comment by FelipeUlloan** [comment]
no conocen a nadie con mac que le pueda correr la visualización?? Todos con el SetView? :(

**Comment by FGarridoV** [comment]
Estimados,

Si quieren les puedo adelantar que estamos probando ver si la raíz del problema en los computadores Mac es un recurso gráfico que instala **Xcode**. Si quieren pueden tratar e instalar este programa y verificar. O pueden esperar a mañana por la mañana que sabremos si es esa la causa del problema setView para que lo instalen por seguridad.

Los que deseen probar, deben instalarlo desde la App Store de macOS y seguir la instalación por defecto. 

Saludos,
Francisco
