### ISSUE TITLE
Uso de Git

### ISSUE THREAD

**Issue by FranciscaSepulveda** [IIC2115/Syllabus#5]
Ayer me descargué Git pero no se como descargar el repositorio y a la vez ir actualizándolo a medida que se sube el material. Habrá por casualidad algún vídeo explicativo de como usar Git?

**Comment by FGarridoV** [comment]
Si ya instalaste git, y viste el video de CMD entonces:
- Con la ayuda del terminal posiciónate en la carpeta que quieres descargarlo
- Escribe en la consola lo siguiente: `git clone https://github.com/IIC2115/Syllabus.git`
Espera que termine,  y ya tendrás la carpeta descargada en la carpeta seleccionada.

Para actualizarla:
- Posiciónate dentro de la carpeta Syllabus (con la consola)
- Ejecuta `git pull`

Evita modificar las cosas dentro de la carpeta syllabus para que no tengas problemas de sincronización. Lo que te recomiendo es que una vez clonada, copies los archivos, los trabajes fuera de syllabus. Si te tira cualquier error. Borra la carpeta syllabus y vuelve a clonarla.

**Comment by pcseisdedos** [comment]
¡Hola!
El profesor Francisco explicó eso en la [consolidación del capítulo 1](https://youtu.be/Xy_UMYjQwiw). Si tienes dudas sobre algún paso dime para poder ayudarte.

Yo te recomiendo clonar el syllabus y hacer git pull cuando quieras actualizar los archivos.

Saludos,
Pablo 😁👍

**Comment by FranciscaSepulveda** [comment]
Muchas gracias! He logrado descargarlo y me queda claro como actualizarlo

**Comment by romidonghi** [comment]
Hola tengo un problema al clonar la carpeta, seguí los pasos que dijo el profesor pero me sale error.  Adjunto foto de mi consola
![Captura de Pantalla 2020-08-12 a la(s) 15 47 23](https://user-images.githubusercontent.com/69482280/90060811-44d09b00-dcb3-11ea-8dea-e8d209fe8189.png)

**Comment by paulavonbrand** [comment]
Al descargar git, tengo  que elegir algo diferente a lo que esta predeterminado? ¿o solo le doy next a todo?

**Comment by FGarridoV** [comment]
@romidonghi Instalaste git?
@paulavonbrand Todo lo que esta por defecto

**Comment by romidonghi** [comment]
@FGarridoV si lo tenia instalado, lo borré y volví a instalar y funcionó. A lo mejor había quedado mal instalado. Gracias !

**Comment by Giovinco24** [comment]
Tengo que descargar el git con Xcode?

**Comment by FGarridoV** [comment]
@Giovinco24 Dado que tienes Mac OS, prueba escribir git en la terminal. Si te dice, que no existe el comando, entonces instala git del link de la clase o instalando Xcode. Pero puede que al escribir git en la terminal, te pregunte si quieres descargarlo.
