### ISSUE TITLE
Función comodoro.ruta

### ISSUE THREAD

**Issue by jsgalleguillos** [IIC2115/Syllabus#5]
Estimado,
En el enunciado se propone una preferencia al momento de elegir una ruta (arriba, abajo, izquierda, derecha). Sin embargo, la función comodoro.ruta no respeta dichas preferencias (al ejecutar el ejemplo del enunciado entrega uno de los valores True, pero de forma aleatoria).  Gracias

**Comment by isalvador95** [comment]
+1 a esto, si la función no entrega la misma preferencia que el enunciado, cuál es el fin de esa función?

**Comment by bombanex** [comment]
Por lo que entendí a función sirve para cuando ya estas en la vía en un modo y te enfrentas a una intersección.
Lo que esta predefinido es para cuando se genera un viaje en una edificación. Según el enunciado el viaje debe ingresar a la via segun la preferencia arriba, abajo, izq, derecha. Pero esto es solo cuando se genera, o sea cuando aun no esta en algun espacio de la red vial

**Comment by FGarridoV** [comment]
Exacto!, como menciona @bombanex las preferencias de dirección son solo para la generación de viajes. La función comodoro.ruta sirve para tomar una decisión en ruta. 

Saludos,
Francisco
