### ISSUE TITLE
¿Qué es lo que se evalúa en la A1?

### ISSUE THREAD

**Issue by dani-sschlack** [IIC2115/Syllabus#5]
Hola!, me preguntaba si lo que entrará para la primera Actividad serán solo los contenidos del Capitulo 1 (Parte a y b) o evaluarán otros contenidos, es decir, si subirán nuevo contenido por estos días que será evaluado.

**Comment by pcseisdedos** [comment]
En las actividades se evalúa el contenido de ese capítulo (parte a y b) no hay más materia.

Saludos,
Pablo 😁👍
