### ISSUE TITLE
Probelma NoSuchConfigException 

### ISSUE THREAD

**Issue by cmujicai** [IIC2115/Syllabus#50]
Ya realicé todo recomendado. Hice todo el manual de instrucciones y me sigue apareciendo el mismo error (lo corra por jupyter o desde python). Leí el articulo que mando @FGarridoV  pero no entendí si tenía que realizar un cambio en la librería game.py. Por otro lado, reinicié el kernel en jupyter e intente correr nuevamente y no pasa nada, me sigue tirando el mismo error "NoSuchConfigException ". Por favor encontrar la solución.

**Comment by gjalliende** [comment]
A mi me pasa lo mismo, he seguido todos los pasos varias veces y probado con dos computadores distintos. Con el artículo que subieron tampoco me queda claro que es lo que deberíamos hacer. Por favor si pudieran dar alguna solución alternativa, o dar algún módulo de ayuda para resolver este tipo de problemas sería ideal. De antemano muchas gracias.
