### ISSUE TITLE
Region es diferente en tabla city y eco

### ISSUE THREAD

**Issue by xayovaniniz** [IIC2115/Syllabus#50]
En la tabla city, la región de Santiago de Chile, por ejemplo, es South America, pero en la tabla Eco, la region es Latin America. ¿Hay un error, nosotros tenemos que decidir cual de las 2 regiones tomamos o la división por región es diferente para los países y ciudades?

Gracias!

**Comment by pcseisdedos** [comment]
Las bases de datos son reales y fueron obtenidas de lugares distintos, por lo tanto es posible que se den este u otro tipo de problemas. Ustedes deben decidir como abordarlo, siempre dejando claros los supuestos y decisiones que tomen.

Saludos,
Pablo 😁👍
