### ISSUE TITLE
Laboratorio 1, Parte II Misión 1. Uso de librería

### ISSUE THREAD

**Issue by CristobalPreuss** [IIC2115/Syllabus#51]
Hola, para trabajar con la información obtenida de wikipedia es posible ocupar la librería wikipediaapi en vez de la librería wikipedia?

**Comment by pcseisdedos** [comment]
Hola, no se puede ocupar. En el enunciado se especifican las librerías que deben ocupar (Beautiful Soup y REMatch)

Saludos,
Pablo 😁👍
