### ISSUE TITLE
Duda sobre habilidad 

### ISSUE THREAD

**Issue by Sbaicardi** [IIC2115/Syllabus#51]
Cuando una de las piezas se encuentra en una posición que le permite atacar a otra enemiga, pero  hay más de 1 pieza enemiga que puede atacar ¿debe elegir atacar solo a 1 o puede atacar a más de 1? 
Gracias!

**Comment by pcseisdedos** [comment]
@Sbaicardi en un turno cada pieza puede usar máximo 1 habilidad, por lo tanto no puedes atacar a 2 enemigos con la misma pieza en un turno, queda a criterio de ustedes la forma de elegir que pieza atacar.
Pablo
