### ISSUE TITLE
Como se descarga lo que usó el profe hans para poder ver las bases a la izquierda?

### ISSUE THREAD

**Issue by paulavonbrand** [IIC2115/Syllabus#51]
y es más recomendado eso que jupyter? y como se descarga? gracias!!

**Comment by pcseisdedos** [comment]
Hola, Si te refieres a jupyter lab puedes instalarlo con pip (pip install jupyterlab en la cmd).

Puedes ocupar el que te acomode, también pueden usar colab.

Saludos,
Pablo 😁👍
