### ISSUE TITLE
Plazo T2

### ISSUE THREAD

**Issue by Fopazov** [IIC2115/Syllabus#51]
Buenas noches, esperando que estén bien, me gustaría saber si podrían extender el plazo de entrega de la tarea. Si mal no recuerdo subieron tarde el enunciado (acorde al programa), y personalmente contaba con esos días "iniciales" para avanzar. Me corrijen si me equivoco. 
Gracias de antemano

**Comment by Fopazov** [comment]
corrigen*

**Comment by RonaldoSosa** [comment]
Hola @Fopazov. Se lo comente al profesor y me comunica que verá si es posible dar un poco más tiempo para la tarea.

**Comment by Fopazov** [comment]
yaa gracias. Sería de mucha ayuda, aunque sean unos pocos días.

**Comment by mbertin1** [comment]
Finalmente va a haber mas plazo??
