### ISSUE TITLE
Tarea 2 M1

### ISSUE THREAD

**Issue by mbertin1** [IIC2115/Syllabus#52]
Hola! Quería preguntar por lo que hay que graficar en esta mision. Se espera que se grafiquen las lineas como C01 etc con puntos??? O que otra cosa?

Pd: puede ser que hay algunas mediciones que esten erroneas? Porque por ejemplo en la C01 hay una que su gps va a cualquier parte. Que se hace con esa??

**Comment by RonaldoSosa** [comment]
Hola @mbertin1. Se esperaría que se grafiquen los recorridos de los buses, se esperaría un resultado similar al del ejercicio del capítulo 5 que fue desarrollada en la ayudantía 9. ¿Respecto a lo último que mencionas a que te refieres con erróneas que la posición en la que se encuentran (latitud, longitud) están demasiado distanciadas de la medición anterior? Podrías ser más específico con esta pregunta?

**Comment by mbertin1** [comment]
Sobre lo primero, estoy confundido, el geodataframe debe ser de los puntos del gps o debe ser de cada uno de los recorridos?

Con lo segundo a lo que voy es que si usas la base de datos completa (la del link) hay unos datos específicamente de la C01 que se encuentran fuera del tipico trayecto. ¿Que se hacen con esos?

**Comment by RonaldoSosa** [comment]
Hola @mbertin1. Respondiendo en el mismo orden de tus preguntas:
- Ten en cuenta que los recorridos estan hechos en base a las distintas mediciones GPS, algo a recalcar en este punto es que no es necesario que el Geodataframe sea respecto a todas las mediciones, sino que sería suficiente con algunas que generen el mismo recorrido.
- Podrías graficar el recorrido de igual forma, ya que este cuenta con las características necesarias para hacerlo, si encuentras extraño el comportamiento podrías dejar un comentario acerca de esto y decir la razón por la que tu recorrido tiene esa forma.
