### ISSUE TITLE
Duda misión 2 Lab 1 parte b

### ISSUE THREAD

**Issue by manalvarezc** [IIC2115/Syllabus#52]
Hola! 
Para responder las distintas consultas, se espera que la consulta de SQL entregue la respuesta de inmediato o podemos trabajar con, por ejemplo, la lista que entrega una consulta y después con algoritmo y código encontrar la respuesta?

Por otro lado, para entregar la respuesta se debe seguir algún formato? Se debe imprimir, o dejar como lista, tupla, etc?

Y se pueden ocupar comandos de SQL que no aparezcan en el material del curso como, por ejemplo, RANK()?

Gracias.

**Comment by pcseisdedos** [comment]
Hola, responderé tus dudas en orden:
1. Las consultas se deben responder en su totalidad ocupando sqlite3, no se puede combinar con Python.
1. El formato de esta parte es libre, pero debe ser lo suficientemente claro como para que se entienda fácilmente.
1. Si pueden ocupar comandos que no salgan en la materia, incluso es recomendable que busquen por su cuenta para aprender más. La única restricción es que deben ser soportados por sqlite3.

Saludos,
Pablo 😁👍
