### ISSUE TITLE
Información repetida en tablas M1

### ISSUE THREAD

**Issue by imleaplaza** [IIC2115/Syllabus#52]
Hola, tengo una duda sobre la M1, cuando dice que no puede haber info repetida, se refiere a que en cada tabla no haya datos repetidos? La pregunta va en realidad a que si se puede compartir info entre tablas, es decir, que en dos tablas distintas se use el mismo dato?

**Comment by FGarridoV** [comment]
En general, el propósito de crear más de una tabla es justamente evitar la redundacia de información. Es decir, que es preferible que no ocurre. ¿Cómo haces eso? Debes definir bien cuales serán tus entidades, luego definir qué columnas son de cada entidad y separarlas en nuevas tablas. La idea es que en estas nuevas tablas no se repitan registros dentro de las filas y preferentemente no hayan columnas repetidas entre tablas. Digo preferentemente, porque puede darse que en casos sea mucho más conveniente que el registro este repetido. Por tanto si justificas tu acciones no deberías tener problemas. Se claro por qué estas haciendo las cosas de ese modo.
