### ISSUE TITLE
Forma de los mapas

### ISSUE THREAD

**Issue by nmcarvajalcortes** [IIC2115/Syllabus#52]
Hola!
¿Puedo asumir que todos los mapas son rectangulares? Es decir, que no hay uno como:

[[ ’C’,’-’, ’E’, ’X’ , ’-’, ’-’,’C’, ’X’, ’-’, ’C’, ’T’ , ’X’, ’-’] ,
[’C’,’X’, ’-’, ’G1 ’, ’-’, ’X’,’-’, ’-’, ’T’, ’X’]]

Gracias

**Comment by fnquinteros** [comment]
Hola! Sí, todos son rectangulares :+1:.

Saludos!
