### ISSUE TITLE
Duda habilidad defensa 2

### ISSUE THREAD

**Issue by mairiondo** [IIC2115/Syllabus#53]
La habilidad del defensa 2 solo se puede ocupar contra un atacante contrario? no contra jefe ni defensas?

Saludos

**Comment by FcaCanales** [comment]
Respecto a la parte en que sale que "se ataca al defensa que esta _al frente_" . Ese "al frente" es en funcion de alguna dirección aleatoria que escojo? seria como que se puede mover en todas direcciones?

**Comment by FGarridoV** [comment]
@mairiondo Por enunciado textual debiera ser solo atacantes, pero si consideraste cualquier pieza, también está bien. Aclara en el readme esos detalles.

@FcaCanales Piensa que el ataque es un empujón al borde del tablero. Por lo tanto, es en la dirección que tú puedes empujarlo derechamente a un borde (recuerda que si hay otra pieza llega hasta ahí). De este modo la dirección queda determinada

saludos

**Comment by Amanriquez11** [comment]
@FGarridoV Considerando que un tablero tiene 4 bordes, yo entiendo por el enunciado que solo se puede empujar hacia el borde de arriba o el de abajo , teniendo que definir cual es el borde de arriba y de abajo, ya que de lo contrario saldría que esta habilidad se puede ocupar cuando el enemigo esta a una celda de distancia sin contar las diagonales. Estoy en lo correcto ?

**Comment by eljaker** [comment]
Si mal no entiendo lo que dice @Amanriquez11, segun el enunciado, asumiendo que un equipo parte al sur del tablero y otro al norte, el defensa 2 del equipo que parte al sur puede empujar hacia el norte solamente y vice versa con el otro. O puede ser a cualquier borde estando a una celda de distancia sin contar diagonales? (Se entiende que en este segundo caso la posicion relativa de ambos define a que borde se empuja)

**Comment by halobel** [comment]
Exacto, se puede empujar en cualquier dirección que no sea las diagonales, a eso se refiere el enunciado con línea recta.

**Comment by arielczerny** [comment]
@halobel profe, en ese caso, si esta la ficha que ataca en el norte del tablero y la que es atacada en el sur, se puede empujar al este u oeste ó solo hacia el norte o sur, ó sólo hacia el sur?

**Comment by mblejeune** [comment]
@FGarridoV Hola! tengo una duda, me acabo de dar cuenta que para las habilidades no tomé en cuenta que tanto **atacante 2** como defensa 2 solo pueden usar su habilidad contra un atacante del equipo contrario, sino que pueden usarla contra todo el equipo contrario (siempre que se pueda) al igual que el defensa 1 y el atacante 1. ¿Puedo dejar esto así sin que se me vaya a bajar puntaje en la evaluación del laboratorio, pero explicarlo en el README, para que se sepa que yo lo hice así? Sé que ya dijiste que está bien hacerlo pero explicarlo para el defensa 2, pero quiero saber si también aplica para la habilidad del atacante 2. Muchas gracias!

**Comment by FGarridoV** [comment]
El readme es la forma de entregar aclaraciones cómo las que mencionas con el fin de agilizar y simplificar la corrección. El puntaje se va a calcular en base a las funcionalidades implementadas de enunciado y criterio.

saludos
