### ISSUE TITLE
Tarea 2 M3

### ISSUE THREAD

**Issue by faresdababneh** [IIC2115/Syllabus#53]
Hola! No sé si estoy entendiendo del todo bien lo que se pide, ¿Es lo mismo que se hizo en la actividad 5 cambiando los puntos por los que se pasa? De esta manera debería utilizar la base de datos que se nos dio para hacer la actividad 5 e imprimir un ejemplo de recorrido que yo elija arbitrariamente

Muchas gracias por el tiempo.

**Comment by RonaldoSosa** [comment]
Hola @faresdababneh. Es similar a lo que se pide para la A5, pero con inicio y fin arbitrario (la función debería ser capaz de recibir cualquier coordenada de inicio y fin en Santiago) pero no es necesario que uno de los modos sea el bus, puede ser auto particular, metro, caminata, bici, etc. Además, los puntos de combinación deben ser ahora elegidos por el algoritmo, no a mano como en la actividad.

**Comment by jorgee02** [comment]
Hola. Tengo la duda de si los modos de transporte quedan a criterio mio, o si se dejan como parámetro para quien ejecute la función. Por ejemplo, si elijo modos A, B y C para construir la función es suficiente? O la función debería estar preparada para soportar cualquiera que se le ingrese.
Saludos

**Comment by RonaldoSosa** [comment]
Hola @jorgee02. En efecto los modos de transporte quedan a criterio de cada uno.

**Comment by mnallark** [comment]
Se puede no incluir el bus o metro como uno de los metros de transporte? Por ejemplo, elegir caminata, bicicleta y auto.

**Comment by RonaldoSosa** [comment]
Hola @mnallark. Como dices no es necesario incluir el bus o metro, los medios de transporte quedan a criterio de cada uno.

**Comment by mbertin1** [comment]
Hola! Tengo una duda sobre la implementación de los 3 modos. En el enunciado se entiende que se deben usar 3 modos, pero lo que me pasa es que en general el programa puede preferir usar un modo mas que todos los otros y que solo se grafique un modo. Sobre esto, debo forzar a que se usen los 3? Y si es asi, pongo puntos arbitrarios para separar?

Y ultima pregunta, estos modos deben ser usados solo una vez?? O puedo usar auto, bici, auto,caminar, bici?

**Comment by RonaldoSosa** [comment]
Hola @mbertin1. Como se indica en el enunciado la restricción dada es que se usen 3 medios de transportes distintos, queda a criterio de cada uno el lugar del trayecto donde se hace el cambio de modo.
