### ISSUE TITLE
TAREA M1

### ISSUE THREAD

**Issue by flovillarreal** [IIC2115/Syllabus#54]
Hola! para la misión 1 de la tarea, con "identificando claramente cada uno de los recorridos", según que columna debemos agrupar los datos y crear las rutas? "expedition_id"? ya que me tiene confundida según que graficar, gracias.

**Comment by RonaldoSosa** [comment]
Hola @flovillarreal. Recuerda que para la tarea 1 se pidió graficar la trayectoria de una expedición y que esta última corresponde a la realización de un recorrido por un bus (y esto esta señalado por su identificador "expedition_id"), para la tarea 2 se está pidiendo que grafiques dicho recorrido sobre un mapa de la red vial de los sectores de Santiago.

**Comment by gmoran77** [comment]
Esta red vial es necesario que sea con Open Street Map??

**Comment by RonaldoSosa** [comment]
Hola @gmoran77. Como se indica en el enunciado se espera que logren el desarrollo de las misiones con las librerías vistas en el curso tales como Geopandas o osnmx, el uso de estas en conjunto se vío en las ayudantías pasadas.
