### ISSUE TITLE
Prioridad de comida

### ISSUE THREAD

**Issue by caaravena1** [IIC2115/Syllabus#54]
En el enunciado se dice que uno debe priorizar la comida más cercana y que se "debe ir rápido" por que otro  se lo puede comer.  
Nosotros teníamos pensado poner un "objetivo" para cada persona y si dos tenian el mismo objetivo que el que estaba más lejos buscaba otro. 
Eso es válido? o no?

**Comment by fnquinteros** [comment]
Hola! Sí, es una solución viable :+1:

Saludos!
