### ISSUE TITLE
Sobre los personajes no identificados

### ISSUE THREAD

**Issue by vnramirez** [IIC2115/Syllabus#54]
Hola!

Para el bonus de los personajes no identificados, tenemos que crear un nuevo atacante y un nuevo defensor con alguna nueva “gracia”, cierto? Alguna habilidad o movimiento distinto a lo que ya tenemos.
Entonces... los equipos ahora van a estar conformados por 7 piezas cada uno?

**Comment by FGarridoV** [comment]
Exacto!
