### ISSUE TITLE
Creación/modificación tablas L03

### ISSUE THREAD

**Issue by JaviOrtizH** [IIC2115/Syllabus#54]
Hola!

Quería saber si para el lab, si es que tengo una tabla ciudades (dentro de las nuevas tablas), basta con modificar la que ya existe o debo crear una nueva de tal manera que las tablas iniciales se mantengan?

Muchas gracias!

Javiera😄

**Comment by pcseisdedos** [comment]
Hola! En el enunciado se pide generar nuevas tablas.

Saludos,
Pablo 😁👍
