### ISSUE TITLE
Ejemplos de input y tiempos de demora.

### ISSUE THREAD

**Issue by cbishara** [IIC2115/Syllabus#54]
Buenas, es que cuando el profe leyó el enunciado en clases, me parece haber escuchado que iban a dar varios input de ejemplo para probar nuestros códigos, al igual que los respectivos tiempos de demora máximos, no se si escuché mal o ya los subieron y no los he visto. De antemano gracias.

**Comment by pcseisdedos** [comment]
Publicaremos un documento al respecto esta semana.

Saludos,
Pablo 😁👍
