### ISSUE TITLE
T2: DATOS

### ISSUE THREAD

**Issue by Valemalzamora** [IIC2115/Syllabus#55]
Hola! Se que se deben  utilizar los conjuntos de datos de la Actividad 4, Tarea 1 y OpenStreetMap, pero se podrían ocupar además más datos? Por ejemplo la carpeta de Paradas de la Actividad 5?

Gracias

**Comment by RonaldoSosa** [comment]
Hola @Valemalzamora. Se podrían utilizar, pero solo como referencia, ya que se tratan de datos distintos, por un lado, los datos de la Actividad 5 son los paraderos geolocalizados y los datos designados, los que mencionaste, para la Tarea 2 son mediciones GPS. La idea de la Tarea 2 es que logren localizar los paraderos a partir de estos últimos datos.
