### ISSUE TITLE
Puedo usar CountryCode como primary key?

### ISSUE THREAD

**Issue by Popper** [IIC2115/Syllabus#55]
Hola, me parece intuitivo usar el countryCode como PRIMARYKEY, pero si en la otra tabla que referencia a esa se repitiera "CHI" varias veces, estaría mal ?

**Comment by FGarridoV** [comment]
Recuerda que la Primary Key (PK) hace referencia a un identificador único de una entidad. Antes de definir cuales son tus PK, debes definir cuales son tus entidades. Luego, sabras decir que columnas son PK de tu entidad.

**Comment by Popper** [comment]
perfecto, y debería evitar que en una tabla se repita texto?

**Comment by FGarridoV** [comment]
Te recomiendo revisar lo que respondí en la Issue #52
