### ISSUE TITLE
mostrar_texto()

### ISSUE THREAD

**Issue by FcaCanales** [IIC2115/Syllabus#55]
Hola ! tengo una duda con la funcion mostrar_texto() de game
la tengo que usar para explicar todo lo del juego? algo asi como "se movió Atacante 1" "Atacante 1 decide atacar" "Atacante 1 no pudo atacar porque su rival estaba piedra" etc? 

gracias !! 💃

**Comment by FGarridoV** [comment]
Exacto, cosas de ese estilo! no es necesario que detalles nada más
