### ISSUE TITLE
Laboratorio 1, P1, uso de librería

### ISSUE THREAD

**Issue by IvoVuskovic97** [IIC2115/Syllabus#55]
hola, se puede ocupar la librería itertools?

**Comment by mavillafranca** [comment]
Aprovechando el issue, pregunto si se puede usar itertools para la parte IV

**Comment by pcseisdedos** [comment]
Pueden ocupar itertools en L1a.IV, pero tengan ojo con el orden de complejidad de sus métodos, porque en este laboratorio se evaluará el tiempo de ejecución.

Saludos,
Pablo 😁👍
