### ISSUE TITLE
Clases del día lunes

### ISSUE THREAD

**Issue by sidiaz2** [IIC2115/Syllabus#56]
Hola! Considerando el cambio de fecha, vamos a tener clases normales el lunes? Saludos

**Comment by vnramirez** [comment]
Me sumo a la pregunta de @sidiaz2. Además, habrá asistencia este lunes, dado los acontecimientos?

Gracias!

**Comment by halobel** [comment]
Por supuesto, el único cambio es la fecha de entrega del L02, y por lo tanto, que no deberán estudiar la materia nueva para este lunes. Todo el resto sigue igual, incluyendo la asistencia (y obviamente no se contabiliza avance).
