### ISSUE TITLE
Tarea 2 M1 

### ISSUE THREAD

**Issue by PabloLaporte** [IIC2115/Syllabus#56]
Hola!, podria hacer uso de la libreria shapely, es que no he encontrado manera de convertir puntos en linestrings sin esa libreria
from shapely.geometry import Point, LineString, shape
esas serian las funciones que me gustaria usar que encontre en este link https://stackoverflow.com/questions/51071365/convert-points-to-lines-geopandas

**Comment by RonaldoSosa** [comment]
Hola @PabloLaporte. No hay problema con que uses esa librería.
