### ISSUE TITLE
Datos inconsistentes en las tablas 

### ISSUE THREAD

**Issue by FernandaNavarroE** [IIC2115/Syllabus#56]
Hola!! Creando mis tablas me di cuenta que por ejemplo hay un región en particular que pertenece a tres continentes distintos, lo cual está incorrecto. Respecto a esto, ¿queda a nuestra criterio cómo solucionar este tipo de errores? 
Por otro lado, también me percaté que hay regiones que tienen nombres de continentes y viceversa, y tengo la misma de qué hacer con este tipo de casos.

Saludos!!!

**Comment by pcseisdedos** [comment]
Exacto, cualquier inconsistencia o error en las bases de datos debe ser manejado con el criterio de cada uno, dejando claros los supuestos y decisiones tomadas.

Saludos,
Pablo 😁👍
