### ISSUE TITLE
como veo <sqlite3.Cursor at 0x183f28cda40>

### ISSUE THREAD

**Issue by paulavonbrand** [IIC2115/Syllabus#57]
como hago para ver que tengo ? graciasss

**Comment by pcseisdedos** [comment]
Lo que hizo el execute se guarda en cursor, si solo haces print te muestra la dirección, pero es un iterable, por lo que puedes iterar sobre sus elementos y printearlos por separado. Otra opción es ocupar cursor.fetchall() que te retorna todo lo que contiene.

Saludos,
Pablo 😁👍
