### ISSUE TITLE
Estado actual del mapa

### ISSUE THREAD

**Issue by agrudsky95** [IIC2115/Syllabus#57]
Hola, no logro entender la siguiente frase:
 "Luego de cada episodio, se debe preguntar si se desea mostrar en pantalla el estado actual del mapa o sólo mostrar el estado final, imprimiéndolo de forma ordenada"
 Quiere decir que una vez que todos los amigos tienen su turno, debo preguntar si quieren ver el tablero turno por turno o una vez jugados todos los turnos?
O si quieren ver el mapa solo cuando se terminen los alimentos? En este ultimo caso entonces no seria necesario preguntar luego de cada episodio como dice el enunciado.

**Comment by diflores** [comment]
Hola,

La frase se refiere a que una vez que todos los amigos se movieron en el episodio, debes preguntar si se desea ver el mapa actual o imprimir el estado final una vez que se acaben todos los episodios.

**Comment by nmcarvajalcortes** [comment]
Hola!!

Tengo una duda respecto a este punto, 

¿Episodio es cuando todos los amigos se movieron un paso en el orden dado o por cada movimiento es un nuevo episodio?

Por otra parte, ¿imprimir el estado final es cuando uno de los amigos llego a la comida y hay que recalcular las rutas o cuando ya nadie sigue comiendo?

**Comment by diflores** [comment]
Hola,

Un episodio empieza cuando el primer amigo se mueve y termina cuando el último del grupo lo hace. 

El estado final del mapa ocurrirá cuando nadie siga comiendo.

¡Saludos!
