### ISSUE TITLE
Librería game.py simplista

### ISSUE THREAD

**Issue by FGarridoV** [IIC2115/Syllabus#57]
Estimados,

Para lo alumnos que no han podido solucionar el problema con la librería, hemos desarrollado una nueva librería *game.py* que funciona de la misma forma que la anterior. Ya se encuentra disponible en Syllabus.

Acá daré algunas instrucciones de su uso:

- Esta librería no requiere de la carpeta *sprites* para funcionar, dado que utiliza carácteres  ascii para representar los personajes (en vez de archivos png).

- Esta librería debe usarse exactamente de la misma forma que la librería *game.py*, es decir, deben inicializar un juego con el comando *game.LostGame()*, luego ejecutar *setup()*, poner sus piezas con *poner_pieza()* y luego hacer su juego con *mover_pieza()*/*quitar_pieza()*. Finalmente deben ejecutar *fin_del_juego()* y *run()* (Este último debe ejecutarse con el juego instanciado en vez de *arcade.run()* como eran antes). 

```
import game

window = game.LostGame()
window.setup()
window.poner_pieza('X',4,8,1)
window.poner_pieza('Y',5,3,1)
logica()
window.fin_del_juego()
window.run()
```

- El primer parámetro de *poner_pieza()* corresponde al símbolo que van a utilizar para cada personaje. Debe ser de largo uno. El último parámetro no significa nada en esta librería y **puede** ser omitido.

- Ustedes deben programar la lógica del juego

- Para usar carácteres novedosos pueden consultar esta [web](https://www.compart.com/en/unicode/category/So) y usar el código Unicode que se encuentra asociado 

por ejemplo, este símbolo
<img width="156" alt="Screen Shot 2019-03-30 at 16 18 26" src="https://user-images.githubusercontent.com/29065260/55280667-81426780-5307-11e9-9025-3024294fcc14.png">

puede ser utilizado con:
`window.poner_pieza(u'\u0F17',4,8,1)`

Saludos,
Éxito con su tarea
Francisco

**Comment by imena2** [comment]
Hola, ya no me tira error la libreria, pero en lugar de mostrar la interfaz me sale esto como output: <function arcade.window_commands.run()> (tengo mac)

**Comment by EliasSaleh** [comment]
Hola, ¿es normal que cada vez que use el tablero de la librería se imprima el tablero múltiples veces? Por ejemplo al hacer:

import game

window = game.LostGame()
window.setup()
window.poner_pieza(u'\u2368',4,8,1)
window.poner_pieza('Y',5,3,1)

window.fin_del_juego()
window.run()


print("----------------")

window.quitar_pieza(1)
window.run()

Se me imprimen 5 tableros (2 solo con la parte del código del ejemplo y 3 luego de quitar piezas).

Gracias!

**Comment by Mcarriagada** [comment]
Hola, esta librería me sigue dando error, no se que hacer la verdad.

OSError                                   Traceback (most recent call last)
<ipython-input-5-de183fb5b9c2> in <module>
      1 import game
----> 2 import arcade
      3 
      4 window = game.LostGame()
      5 window.setup()

~\AppData\Roaming\Python\Python37\site-packages\arcade\__init__.py in <module>
     15 from arcade import color
     16 from arcade import key
---> 17 from arcade.application import *
     18 from arcade.arcade_types import *
     19 from arcade.draw_commands import *

~\AppData\Roaming\Python\Python37\site-packages\arcade\application.py in <module>
      6 from numbers import Number
      7 
----> 8 from arcade.window_commands import set_viewport
      9 from arcade.window_commands import get_viewport
     10 from arcade.window_commands import set_window

~\AppData\Roaming\Python\Python37\site-packages\arcade\window_commands.py in <module>
     11 from arcade.monkey_patch_pyglet import *
     12 
---> 13 import numpy as np
     14 
     15 from numbers import Number

~\AppData\Roaming\Python\Python37\site-packages\numpy\__init__.py in <module>
    140     from . import _distributor_init
    141 
--> 142     from . import core
    143     from .core import *
    144     from . import compat

~\AppData\Roaming\Python\Python37\site-packages\numpy\core\__init__.py in <module>
     21             # NOTE: would it change behavior to load ALL
     22             # DLLs at this path vs. the name restriction?
---> 23             WinDLL(os.path.abspath(filename))
     24             DLL_filenames.append(filename)
     25     if len(DLL_filenames) > 1:

c:\program files\python37\lib\ctypes\__init__.py in __init__(self, name, mode, handle, use_errno, use_last_error)
    354 
    355         if handle is None:
--> 356             self._handle = _dlopen(self._name, mode)
    357         else:
    358             self._handle = handle

OSError: [WinError 193] %1 no es una aplicación Win32 válida

**Comment by Mcarriagada** [comment]
Ya solucione el error reiniciando el Kernel.

**Comment by FGarridoV** [comment]
Es porque estás usando mal la librería.

El comando **run()** se ejecuta solo una vez, cuando ya has ingresado todos los movimientos del juego. El método **run()** comienza mostrando el estado inicial del tablero, luego muestra el tablero por cada método **mover_pieza()** o **quitar_pieza()** utilizado y previamente instanceado. Finalmente muestra el estado final del tablero. 

Al igual que librería anterior, el método **mostrar_texto("texto")** se encarga de modificar el texto que muestra la siguiente impresión. A modo de ejemplo considera el siguiente código:

```
mostrar_texto("Se ha movido una pieza")
mover_pieza(...)
```

Cuando se ejecute run(), se va a mostrar el estado del tablero con el texto "Se ha movido una pieza" y el movimiento de pieza ejecutado.

Tu código tiene 2 ejecuciones de run() y un quitar_pieza(), lo que explica las 5 impresiones.

saludos y espero te haya quedado claro,
Francisco

**Comment by bombanex** [comment]
Me sigue arrojando el siguiente error:

<ipython-input-64-8768f2515bd3> in <module>
      2 import random
      3 
----> 4 window = game.LostGame()
      5 window.setup()
      6 window.poner_pieza('X',4,8,1)

~\Documents\1er Semestre 2019\Programacion como Herramienta para Ingenieros\repositorio-2019-1-bombanex\L02\game.py in __init__(self)
     37     def cargar_matriz(self):
     38         n=10
---> 39         grid = [' '] * n
     40         for i in range(n):
     41             grid[i] = [' '] * n

~\Anaconda3\lib\site-packages\arcade\application.py in __init__(self, width, height, title, fullscreen, resizable, update_rate, antialiasing)
     51 
     52         super().__init__(width=width, height=height, caption=title,
---> 53                          resizable=resizable, config=config)
     54 
     55         if antialiasing:

~\Anaconda3\lib\site-packages\pyglet\window\win32\__init__.py in __init__(self, *args, **kwargs)
    135                     self._event_handlers[message] = func
    136 
--> 137         super(Win32Window, self).__init__(*args, **kwargs)
    138 
    139     def _recreate(self, changes):

~\Anaconda3\lib\site-packages\pyglet\window\__init__.py in __init__(self, width, height, caption, resizable, style, fullscreen, visible, vsync, display, screen, config, context, mode)
    590 
    591         if not config.is_complete():
--> 592             config = screen.get_best_config(config)
    593 
    594         if not context:

~\Anaconda3\lib\site-packages\pyglet\canvas\base.py in get_best_config(self, template)
    195             configs = self.get_matching_configs(template)
    196         if not configs:
--> 197             raise window.NoSuchConfigException()
    198         return configs[0]
    199 

NoSuchConfigException:

**Comment by FGarridoV** [comment]
Esos métodos son la librería antigua. Procura moverla de la carpeta donde estes programado y dejar solo la nueva.

Saludos,
Francisco

**Comment by bombanex** [comment]
Revise las dos librerias  me aparece que la unica que tiene la funcion cargar_matriz() es la nueva y eso es lo que me esta causando el problema

**Comment by FGarridoV** [comment]
Estimado,

Prueba reinciando el kernel de jupyter, dado que en tu ejecución siguen existiendo ambas librerías.

saludos,
Francisco
