### ISSUE TITLE
¿qué pasa si hago un commit?

### ISSUE THREAD

**Issue by paulavonbrand** [IIC2115/Syllabus#58]
despues no puedo volver a abrir la tabla o algo asi? o de que sirve?

**Comment by pcseisdedos** [comment]
El commit se ocupa para finalizar una transacción, eso no impide que luego se comience otra.

Saludos,
Pablo 😁👍

**Comment by FGarridoV** [comment]
El commit solo lo utilizas cuando realizas modificaciones en la BD: Creación, Inserción, Eliminación o Edición. Con el commit te aseguras que los cambios se guarden, es lo mismo que apretar "Save" en un documento de Word. Cuando haces consultas (Querys) solo estas "viendo" la base de datos. Es como abrir un Word y no hacerle cambios, en ese caso no es necesario el uso de commit.

**Comment by paulavonbrand** [comment]
gracias!
