### ISSUE TITLE
Nuevo error con la libreria actualizada

### ISSUE THREAD

**Issue by simonerenard** [IIC2115/Syllabus#59]
Hola a todos,

Lamentablemente ahora me tira este error.... no se hay algún problema con la instancia de mis objetos o si las librerías no son compatibles con mi computador. 

(La matriz me cargó perfectamente, mi problema es con poner las piezas en la matriz)

Gracias!

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-24-0a3c4f1841b7> in <module>
      7 
      8 alpha = Atacante_1(0,3,3,0)
----> 9 miJuego.poner_pieza(u'\u03B1',3,3,1)
     10 beta = Atacante_2(1,8,6,0)
     11 miJuego.poner_pieza(u'\u03B2',8,6,1)

~/Documents/U/2019-1/Programacion/Tareas/repositorio-2019-1-simonerenard/L02/game.py in poner_pieza(self, ascii_char, posX, posY, escala)
     54         piece_sprite.X = posToCoordX(posX)
     55         piece_sprite.Y = posToCoordY(posY)
---> 56         self.sprites_list.append(piece_sprite)
     57 
     58     def mover_pieza(self, nPieza, posX, posY):

AttributeError: 'NoneType' object has no attribute 'append'

**Comment by halobel** [comment]
Hola, el error se genera pq no estás inicializando bien el objeto que representa al tablero gráfico. Revisa que estés efectivamente creando un objeto del tipo LostGame, y que posteriormente llames al método setup(), todo esto antes de poner las piezas.

**Comment by mblejeune** [comment]
@simonerenard  me pasó lo mismo! y revisé en el otro issue, intenta poner .setup() --> con los paréntesis al final, ahí me funcionó a mí! :D

**Comment by FcaCanales** [comment]
Hola! soy a la unica que todavia le tira error? 😭 
si lo corro, se me abre una ventana y el pc colapsa :( (la ventana no carga nunca y se me queda pegado el pc)
