### ISSUE TITLE
Duda input Lab 1, parte IV

### ISSUE THREAD

**Issue by mavillafranca** [IIC2115/Syllabus#59]
Hola, en la parte IV podemos asumir que se recibe como input unicamente tuplas compuestas por valores enteros?

Saludos

**Comment by pcseisdedos** [comment]
En el enunciado se especifica que son [números naturales](https://es.wikipedia.org/wiki/N%C3%BAmero_natural) (considerando el 0), por lo tanto están contenidos dentro de los enteros.

Saludos,
Pablo 😁👍
