### ISSUE TITLE
Hola!! como el próximo lunes es feriado, habrá una instancia de recuperación del lab?

### ISSUE THREAD

**Issue by paulavonbrand** [IIC2115/Syllabus#59]
Sería genial si pudiesen hacerlo, o correr el lab para tener más instancias para preguntar!! Al menos a mi me esta costando demasiado entender esta nueva materia

**Comment by FGarridoV** [comment]
Lamentablemente por temas de calendario y la matería que se nos avecina, no tenemos contemplado atrasar las entregas de Laboratorio. Pero recuerda que las issues de GitHub y la ayudantía de hoy serán instancias para que logren resolver sus dudas de la materia de Base de Datos. Como les dijimos en la lectura de enunciado, si avanzan de forma paulatina las consultas, no van a tener problemas de tiempo.

**Comment by paulavonbrand** [comment]
Gracias profe!! Entonces el próximo jueves supongo que sólo tendremos la actividad P03 (?)

**Comment by FGarridoV** [comment]
Exacto!
