### ISSUE TITLE
Distribucion Exponencial

### ISSUE THREAD

**Issue by bombanex** [IIC2115/Syllabus#6]
Para generar viajes los viajes se utiliza esta función, pero rara vez arroja números enteros. Yo lo que estaba haciendo era tomarlos como fracción de viaje y multiplicar la fracción de viajes por el numero aleatorio de personas que me arrojaba el modo (también aleatorio), el cual muchas veces es un numero menor al mínimo permitido por el modo (al ser una fracción de este). Por ejemplo si generaba 0,5 viajes en un hogar y luego me arrojaba que el viaje era en caminata, tendría 0,5 personas caminando.
Esta bien hacerlo así o debo pasarlo desde el principio a números enteros?
Ademas si tengo mas de un viaje generado en una edificación en un turno debo buscar el modo aleatorio para cada uno de los viajes generados o le asigno el mismo modo a todos los viajes?

**Comment by FGarridoV** [comment]
Primero que todo, las funciones exponencial y uniforme son continuas (no discretas) por eso arrojan números irracionales. Lo que debes hacer, es usarlas adecuadamente para lograr los objetivos solicitados en el enunciado.

Recuerda que si la llegada de entidades distribuyen poisson, entonces los tiempos entre llegada distribuyen exponencial. Es decir, para cada "punto de generación de viajes" puedes conocer los tiempos entre generaciones. Para ello puedes definirlo a priori o ir construyéndolo a medida avanza la simulación. En este caso los turnos son discretos, por lo que las entidades que lleguen en 2,3; 2,8; 2,9 estarían llegando en el mismo turno.

Para todas las demás puedes simularlo con la distribución uniforme. Imagina que vas a modelar el lanzamiento de un dado (que puede estar cargado). Con una distribución uniforme basta para ello. 

Te recomiendo fuertemente googlear información al respecto. Buscan en wikipedia como trabajan estas distribuciones.

Saludos,
Francisco

**Comment by mblejeune** [comment]
@FGarridoV tengo una duda de este tema, pero con el enunciado, este dice: "Considere que se generan en promedio _1 viaje por turno en los terminales de camino_, 1 viaje cada 2 turnos en hogares y 1 viaje cada 3 turnos en oficinas." es decir, en cada turno tengo que ver si se generan aleatoriamente tanto viaje en camino y ver lo mismo en hogares y ver lo mismo en oficinas (con respectivas probabilidades), estoy en lo correcto? Y cuando se refiere a "1 viaje por turno en los terminales de camino" con camino se refiere a vialidad que incluye : camino, calle y autopista o solo camino ??? porque en ese caso no tengo un lambda para generar aleatoriamente en calle ni autopista. Gracias!

**Comment by FGarridoV** [comment]
Estas en lo correcto en ambas afirmaciones. Esos valores son los parametrós de las distribuciones exponencial que te indica en cuantos turnos más se genera un viaje. Respecto a tu segunda pregunta. ese valor es para todos los tipos de vias (no solo caminos). Error de nosotros en usar la misma palabra.

Saludos,
Francisco

**Comment by mblejeune** [comment]
@FGarridoV gracias! me surgió otra duda con respecto a esto mismo, si aleatoriamente se me debe generar un viaje en vialidad entonces se genera un viaje en camino, uno en calle y otro en autopista, a partir de esto mi código reconoce cuales celdas que sean camino, calle o autopista me sirven para generar un viaje, y de estas celdas que me sirvan puedo elegir con random en cual celda de camino hago el viaje ? porque puedo tener muchas opciones de celdas caminos para generarlo que me sirven

gracias otra vez!!

**Comment by vgrivera** [comment]
Aun me queda la duda si cada posible terminal de generacion tiene su propio "próximo tiempo" o si solo es un próximo tiempo de generacion para todos los caminos(calle,camino, autopista), otro para hogar y otro para oficina.

Gracias!!

**Comment by FGarridoV** [comment]
Cada punto de generación de viajes tiene su próximo tiempo.

Saludos,
Francisco

**Comment by josefinabravo** [comment]
Si es en promedio un viaje por turno en los terminales de camino ¿Significa que entre todos los terminales de camino tengo que crear un viaje en promedio por turno, o que por cada terminal de camino tengo que generar un viaje en promedio por turno?

**Comment by FGarridoV** [comment]
Lo segundo que indicas, por cada terminal de camino tengo que generar un viaje en promedio por turno.

Saludos,
Francisco

**Comment by arielczerny** [comment]
> Para generar viajes los viajes se utiliza esta función, pero rara vez arroja números enteros. Yo lo que estaba haciendo era tomarlos como fracción de viaje y multiplicar la fracción de viajes por el numero aleatorio de personas que me arrojaba el modo (también aleatorio), el cual muchas veces es un numero menor al mínimo permitido por el modo (al ser una fracción de este). Por ejemplo si generaba 0,5 viajes en un hogar y luego me arrojaba que el viaje era en caminata, tendría 0,5 personas caminando.
> Esta bien hacerlo así o debo pasarlo desde el principio a números enteros?
> Ademas si tengo mas de un viaje generado en una edificación en un turno debo buscar el modo aleatorio para cada uno de los viajes generados o le asigno el mismo modo a todos los viajes?

@bombanex, yo también considere que si se hacen por ejemplo, 0,3 viajes en bus de 24 personas, finalmente viajaran en bus 24 x 0,3 = 7,2 personas y eso pasarlo a entero. O simplemente si se generan 0,3 viajes por esa infraestructura redondeo a 0 generados?

**Comment by FGarridoV** [comment]
@arielczerny es imposible que se generen viajes irracionales. recuerda que la exponencial indica el tiempo entre llegadas. No la cantidad de viajes.

saludos,
Francisco
