### ISSUE TITLE
Consulta respecto a contenido de herencia y diagrama de clases

### ISSUE THREAD

**Issue by iavasquez1** [IIC2115/Syllabus#6]
Hola!, al leer el contenido de herencia no me queda muy claro cuando se realiza el for en la función buscar, en el que se menciona que se itera en el "self" que se refiere al objeto, sin embargo no me queda claro a que se refiere el self en este caso ya que se debiera referir al mismo objeto que en este caso es ContactList y no "list". Adjunto la imagen en donde aparece esta duda.
También no me queda claro en el ejemplo de los diagramas de clases a que se refieren las variables "ra" y "dec" en la clase "SeriesDeTiempo" que no se menciona que significan en la explicación. Adjunto imagen
De antemano muchas gracias!

![Consulta_herencia_y_polimorfismo](https://user-images.githubusercontent.com/17599169/111511879-e6c6d300-872d-11eb-8f77-2377bd4c2188.png)

![Duda_diagrama_de_clases](https://user-images.githubusercontent.com/17599169/111513355-7caf2d80-872f-11eb-81b4-1db92b835c36.png)

**Comment by pcseisdedos** [comment]
Hola, tal como dices self hace referencia a una instancia de la clase ContactList, esta hereda de list, por lo que conserva sus propiedades y además agrega el método buscar.

Respecto a tu segunda pregunta, la verdad no tiene mucha importancia lo que representan ra y dec, lo importante es que se entienda el formato para los diagramas.

Saludos,
Pablo 😁👍
