### ISSUE TITLE
Capacidad_tren

### ISSUE THREAD

**Issue by ravielr** [IIC2115/Syllabus#6]
Hola!

Quería saber qué tiempo debe imprimir la función capacidad_tren.
¿Es cuando el tren llega a la estación o cuando se va? # #

**Comment by jiechevarria** [comment]
La lista que nos entrega el usuario como argumento de la funcion capacidad_tren esta ordenada? Digo, nos da las estaciones en una lista de manera como dice el enunciado ["Tranca_Perro", "Nuestra_señora_Danielita",...........,"Hernando_de_Valdivia"]?

**Comment by Hernan4444** [comment]
Hola, en el enunciado no queda especificado que será una lista ordenada, por lo tanto no se puede asumir dicha cualidad. En caso de necesitarla ordenada, deberás crear una función que la ordene después de recibirla.

Saludos ✌️

**Comment by Jiallende** [comment]
La función: Capacidad_tren(estaciones) ,te tiene que imprimir solo una
 llegada de tren en un tiempo especifico,  o todas las llegadas de los
trenes a esa estación durante la simulación?
