### ISSUE TITLE
Capitulo 2

### ISSUE THREAD

**Issue by rsbarrosuc** [IIC2115/Syllabus#6]
Cuando suben la materia del Capitulo 2 parte a???

**Comment by halobel** [comment]
Hola, ya está todo el material del capítulo 2 arriba. Aproveché de incluir las slides que usaré en los resúmenes de materia (seguramente con algunos cambios leves), que pueden serles útiles para el estudio. Les recomiendo además ver los videos del semestre pasado sobre esta materia, en caso que necesiten profundizar más.
Saludos!
