### ISSUE TITLE
Creación de repositorios privados

### ISSUE THREAD

**Issue by FGarridoV** [IIC2115/Syllabus#6]
Estimados Alumnos,

Espero se encuentren bien con el inicio de semestre. Como les comentamos ayer en clases, les daremos las instrucciones para que puedan crear sus repositorios privados. Es importante que lo hagan antes de la clase del Jueves o no podrán seguir algunas instrucciones.

Para ello, deben hacer lo siguiente:

1. Primero que todo, deben crearse una cuenta en GitHub. Si ya tienen, omitan este paso.
2. Ingresen al siguiente [link](https://classroom.github.com/assignment-invitations/ed6bf0f33f0fdd92b3244aadf0fcad52). 
2. Si no están loggeados en GitHub, el link les pedirá que se loggeen. Si no, ya estarán con la sesión iniciada.
3. Al cargar la página va a aparecer una lista con los correos UC de todos ustedes. Búsquense en ella y seleccionen su correo. IMPORTANTE: Seleccionen cuidadosamente su correo y no el de un compañero, si no, van a generar un conflicto con la cuenta de su compañero.
4. Luego sigan el proceso de vinculación.

Su repositorio privado será creado y SOLO podrán acceder a él cuando se encuentren loggeados con su cuenta de GitHub. Si no lo hacen, les saldrá que la página no existe.

Luego del proceso, el link de su repositorio será:

**`http://www.github.com/IIC2115/IIC2115-2020-2-USER`** donde user es su usuario de GitHub.

Cualquier duda, escriban bajo este hilo.

Saludos,
Francisco

**Comment by caespinoza5** [comment]
¡Hola! Al clickear el link en el paso 2, me pidió autorización para vincular Github Classroom a mis repositorios. Al clickear "Authorize", se quedó en un loop recargando la página, hasta el punto que me apareció la ventana que muestro a continuación (que es lo que actualmente me aparece al momento de apretar el link).
![Untitled](https://user-images.githubusercontent.com/26394948/89912766-efb45c80-dbc0-11ea-928a-fdd11d555e44.png)

¿Qué puedo hacer? Cabe destacar que no me apareció la lista con los correos UC.

**Comment by FGarridoV** [comment]
Espera el tiempo que indica ahí. Si no funciona en una hora. Mándame un correo.

**Comment by pelayouc** [comment]
profe y después de esto debo clonarlo?

**Comment by FGarridoV** [comment]
> profe y después de esto debo clonarlo?
Si puedes entrar a la pagina de GitHub es suficiente. El jueves les mostraremos como usarlo.

**Comment by clementeramirez** [comment]
hola profe, deberia quedar asi? o hay que hacer algo mas?
![image](https://user-images.githubusercontent.com/69482444/89947094-f27b7580-dbf1-11ea-94da-81ca5b6a6e3b.png)

**Comment by FGarridoV** [comment]
Si, Perfecto!

**Comment by clementeramirez** [comment]
muchas gracias

**Comment by rosariopenalabbe** [comment]
Hola!, no me apareció nunca la lista ( no sé si es normal o no) y ya cree un repositorio privado pero no puedo ingresar con ese link al repositorio
![error](https://user-images.githubusercontent.com/65323304/90076154-ff20cc00-dccc-11ea-863a-d84cfbd3fccc.JPG)

**Comment by jaraya4** [comment]
Hay que dejarlo como el de clemente? o hay que hacer algo mas? porque no me deja crear repositorios ni subir archivos.

**Comment by pcseisdedos** [comment]
@jaraya4 En la sesión de hoy el profesor Francisco mostró como subir carpetas, actualizar y eliminar archivos en github. Te recomiendo ver el video cuando se publique en el syllabus y si tienes mas consultas te las podemos aclarar por este medio o en la sesión de discord el lunes.

Saludos,
Pablo 😁👍
