### ISSUE TITLE
Duda habilidad atacante 1

### ISSUE THREAD

**Issue by eljaker** [IIC2115/Syllabus#60]

**Comment by eljaker** [comment]
Hola, queria saber si el atacante 1 puede destruir si a un enemigo que se encuentre a una celda de distancia en linea recta. En el enunciado no se especifica del todo.

**Comment by idmdvan** [comment]
Hola, 

El enunciado dice que el atacante puede destruir si la ficha atacada está a una celda en diagonal **o**
a dos en línea recta. Es decir, si está a una celda de distancia en línea recta, no podrá destruirla.

Saludos.

**Comment by CataWied** [comment]
Otra pregunta sobre esta habilidad: cuando destruyo a otra ficha tomo su lugar (estilo ajedrez) o me quedo en la posicion desde donde ataque?

**Comment by FGarridoV** [comment]
Los movimientos son independientes de las habilidades. Si la habilidad no implica movimiento, entonces no se mueve.

**Comment by CataWied** [comment]
Esa era mi pregunta, la habilidad implica movimiento (me muevo 2 veces) o la elimino desde donde estoy?

**Comment by CataWied** [comment]
Es que en el issue #40 dijeron que si el jefe usa la habilidad del atacante 1, en ese caso avanza 2 casillas en un turno, es decir, al usar la habilidad se mueve. Pero en el enunciado no menciona que la habilidad misma implique que tomo la posicion de la ficha que elimine.
