### ISSUE TITLE
Duda output L1a P4

### ISSUE THREAD

**Issue by nencinav** [IIC2115/Syllabus#60]
Noté que en caso de no haber problemas con los ordenes de los nativos, se pide "printear" cada combinación posible en una linea diferente, sin embargo como el código que se ejecuta es dado, se "printeará" el return de la función ordenes_vacunacion. ¿Cómo hago para que el return de una funcion actúe como  "print(*posiciones, sep="\n")", que se usaba para printear de aquella forma? o ¿se puede printear como una lista de listas?

**Comment by pcseisdedos** [comment]
Hola, la verdad no entiendo bien a qué te refieres, en ambos casos se pide **retornar**, no printear.

Caso 1: Es posible generar ordenes de vacunación consistente, se debe **retornar una lista de listas de enteros**, donde cada una presenta un posible orden en que deben realizarse las vacunaciones y cada elemento de la lista representa a un nativo.

Caso 2: No existen ordenes posibles, su algoritmo debe **retornar una lista de enteros**, que contenga los  identificadores de los nativos que presentan inconsistencias en sus registros.

Saludos,
Pablo 😁👍

**Comment by nencinav** [comment]
En el caso 1, 
Copié el input del enunciado y retorne una lista de listas, lo que se muestra en la foto.

![Captura de Pantalla 2021-05-18 a la(s) 22 34 21](https://user-images.githubusercontent.com/80851830/118748086-335f8500-b829-11eb-8ae6-a80a2bc519db.png)

Pero en el enunciado dice que es de esta forma. 

![Captura de Pantalla 2021-05-18 a la(s) 22 36 16](https://user-images.githubusercontent.com/80851830/118748223-77528a00-b829-11eb-87e8-9e3a553b657e.png)

Como si printeara en lineas diferentes cada combinación. ¿Esto como lo hago dado el input o está bien lo que hice?

**Comment by pcseisdedos** [comment]
Está bien como lo hiciste, actualicé el enunciado porque el otuput no estaba representado como una lista de listas tal como se indicaba previamente, ahora quedó así:

![image](https://user-images.githubusercontent.com/18387808/118750120-c948df00-b82c-11eb-8a5f-8858de8b2091.png)

Gracias por hacerlo notar!

Saludos,
Pablo 😁👍

**Comment by pcseisdedos** [comment]
De todas formas si quieres que se vea más ordenado puedes poner un for dentro del bloque main, esto no causará problemas con la corrección automática dado que esa sección de código no se ejecuta al importar la tarea tal como hemos explicado anteriormente.

**Comment by gmasihy** [comment]
Hola :)  Me puedes confirmar si en definitiva está bien usar "print(resultado)" tal cual como sale en el enunciado, en vez de usar "print(*resultado,sep='\n')", a pesar que eso signifique que la lista de listas se entregue toda junta y no con saltos de linea como aparece en el output del enunciado?

**Comment by pcseisdedos** [comment]
Lo que importa es que la función retorne en el formato que corresponde. El print es opcional pero deseable para facilitar la corrección a los ayudantes. En mi opinión se ve mejor con el separador.

Saludos,
Pablo 😁👍
