### ISSUE TITLE
ordenamiento

### ISSUE THREAD

**Issue by rpmalonnek** [IIC2115/Syllabus#60]
para ordenar la lista de comidas encontradas, hay que hacerlo para cada amigo ? o del total de comidas encontradas en el tablero ? 
despues, esa lista ordenada se muestra al final del programa ?

**Comment by pmiquelv** [comment]
No entiendo el procedimiento del ordenamiento.

Primero se generan sublistas de forma equilibrada (entendido), pero luego dice que hay que ordenar estas sublistas usando el mismo algoritmo. No entiendo a que algoritmo se refiere (volver a generar sublistas para cada una de las sublistas¿?

Lo que tengo desarrollado es que se generen las n sublistas, y luego cada una de estas particularmente se ordene de forma ascendente, para finalmente juntarlas todas de manera que entregue una lista final ordenada.
