### ISSUE TITLE
Duda enunciado L03 Misión 3, d)

### ISSUE THREAD

**Issue by sitauscant** [IIC2115/Syllabus#60]
Hola!

No entiendo la parte que dice "Asumiendo que el uso de un lenguaje distribuye de manera homogénea en cada país", ¿se refiere a que todos los lenguajes de cada país se hablan en todas las ciudades homogéneamente? Tampoco veo de que sirve este supuesto en el ejercicio.

Gracias!

**Comment by FGarridoV** [comment]
Significa que en una ciudad de un país se cumplen las mismas proporciones que en el país.
