### ISSUE TITLE
Creación de tablas L1b

### ISSUE THREAD

**Issue by manalvarezc** [IIC2115/Syllabus#61]
Para la misión 0 del L1b, se pueden agregar tablas a las que se crearon en la pauta del Taller 3a, la de la ayudantía, como una que relacione géneros y actores, o se debe trabajar solamente con la base de la pauta?
Y a qué se refiere, en la misión 1, a que se evaluará según la cantidad de registros complementados? Cuales serán los criterios?

**Comment by pcseisdedos** [comment]
Ustedes son libres de utilizar la modelación que consideren conveniente. Pueden basarse en la ayudantía, pero recuerda que para usar código que no es tuyo debes citarlo siguiento las reglas descritas en #2.

Saludos,
Pablo 😁👍
