### ISSUE TITLE
Mostrar_texto()

### ISSUE THREAD

**Issue by bombanex** [IIC2115/Syllabus#62]
Tengo un problema con la función mostrar texto().
Esta solo almacena un texto por movimiento, por lo tanto si quiero imprimir que por ejemplo, el defensa se convirtió en piedra, esto no se muestra ya que no hay movimiento.
Que puedo hacer para imprimir que alguien fue convertido en piedra si es que no hay movimiento?

**Comment by jlcasanova2** [comment]
Creo que tendré luego el mismo problema (todavia no llego a eso), pero podriamos por ejemplo usar la funcion mover_pieza pero dando las mismas coordenadas que ya tiene la pieza, asi no se mueve, pero te deja imprimir el texto que vayas a poner en mostrar_texto()

**Comment by FGarridoV** [comment]
La solución de @jlcasanova2 es válida.

saludos,
Francisco
