### ISSUE TITLE
Laboratorio 1.a, pregunta 1

### ISSUE THREAD

**Issue by Tomas-GrayD** [IIC2115/Syllabus#62]
Que restriccion tienen que tener las lienas para ser pintadas con el color 0, 1, 2, etc?

**Comment by pcseisdedos** [comment]
Deben poder ser distinguidas por los cristaloides en todas las combinaciones existentes. Minimizando la cantidad de colores distintos utilizados.

Saludos,
Pablo 😁👍

**Comment by Tomas-GrayD** [comment]
Ok, pero 
1- en el caso de ejemplo que pusieron,  la linea 1 fue pintada con 0 porque combina con la 2 y la 3 directamente, la 2 fue pintada con 1 porque combina solo con una linea directamente que seria la 1 y la 3 por la misma razon? 
2- en el caso que todas las lineas puedan ir direcamente hacia todas se pintaria con un 0? 
saludos

**Comment by pcseisdedos** [comment]
Responderé de forma genérica ambas preguntas. Las líneas 1 y 2 se pueden pintar del mismo color porque los cristaloides no tienen forma de confundirlas, pero si la línea 0 se pintara del mismo color que alguna de las otras entonces si podría generar confusión. Una forma de asegurar que no habrá confusiones es pintar todas las líneas de colores distintos, pero se pide minimizar la cantidad de colores ocupados.

Saludos,
Pablo 😁👍

**Comment by Tomas-GrayD** [comment]
Ok, otra duda que mes surgio es si cada par de tuplas es una combinacion hacia lineas distintas o puede haber una combinacion hacia la misma linea?

Saludos

**Comment by pcseisdedos** [comment]
Solo hay combinación entre líneas distintas.

Saludos,
Pablo 😁👍
