### ISSUE TITLE
Impresión mapa

### ISSUE THREAD

**Issue by memadrid** [IIC2115/Syllabus#63]
El enunciado dice que: "es importante que el formato visual del mapa sea claro, entendible y mantenga correctamente el alineamiento de las y/o columnas." ¿Este debe ser igual al del ejemplo, o podemos usar otras cosas, como tablas para mantener el orden?

**Comment by diflores** [comment]
Hola,

No tiene por qué ser igual a los ejemplos, mientras cumplas con los
requisitos del mapa que mencionas: claro, entendible y que mantenga la
alineación de las filas y columnas.

¡Saludos!

**Comment by memadrid** [comment]
¿Puedo ocupar el módulo [PrettyTable](https://code.google.com/archive/p/prettytable/) para imprimir el mapa de forma más bonita? Aunque deba instalarse..
