### ISSUE TITLE
mover y poner_pieza()

### ISSUE THREAD

**Issue by kdcarreno** [IIC2115/Syllabus#63]
Hola, 
Al usar mover_pieza, la pieza me queda duplicada en la posición anterior y la nueva. Lo podría solucionar con quitar_pieza y poner_pieza, supongo que no es la idea. Ayuda?

También al poner_pieza me imprime un tablero por cada pieza que quiero poner, cómo puedo evitar esto?

**Comment by FGarridoV** [comment]
Debes reiniciar el kernel entre cada corrida. Eso pasa porque las instancias de la ejecución anterior siguen activas.

**Comment by FGarridoV** [comment]
Respecto a poner pieza, esta solo genera una única impresión con todas las posiciones. Estas deben ser ejecutadas luego de stup() y antes de cualquier movimiento.

**Comment by eljaker** [comment]
Tengo una duda acerca de la interfaz gráfica. (usando la librería simplista en MacOS)

Cada vez que quiero imprimir el tablero para mostrar lo que está sucediendo los comandos que utilizo son:

window.mover_pieza(...)
window.mostrar_texto(...)

El tema es que me imprime (en el siguiente orden):
-comienza el juego
-tablero

-comienza el juego 
-tablero (se movio el atacante 1)
*(aca debe estar el problema porque me imprime dos veces comienza el juego)

-texto de que se movio el atacante 1
-tablero (se movio el atacante 2)

-texto de que se movio el atacante 2
-...

Y así sucesivamente, en el fondo esta desfasado lo que muestra el tablero con lo que se imprime sobre el tablero. Si cambio el orden de window.mover_pieza y window.mostrar_texto por como estan definidos en el game.py no me corre el programa. Importa ese desfase o se puede obviar? No se me ocurre como solucionarlo ya que me tinca que tiene que ver con la librería nueva.
