### ISSUE TITLE
Variable IsLanguageOfficial tabla city

### ISSUE THREAD

**Issue by FernandaNavarroE** [IIC2115/Syllabus#63]
Hola!!! La variable IsLanguageOfficial de la tabla city, ¿es propia de cada país o de cada ciudad? a esto me refiero con que si un lenguaje puede ser oficial en una ciudad, pero no oficial en otra ciudad, o será o no será oficial respecto al país??

Espero haberme explicado bien sjdjd

Saludos!!!

**Comment by FGarridoV** [comment]
Si, te entendí. La Columna hace referencia a si el lenguaje es oficial o no en el país. Si no me equivoco, todas las ciudades de un mismo país deberían tener el mismo valor en esa columnas.

**Comment by pcseisdedos** [comment]
@FernandaNavarroE De todas formas puedes hacer una consulta para verificarlo si quieres salir de dudas.

Saludos,
Pablo 😁👍
