### ISSUE TITLE
Variable mapa - Respuesta Duda #45

### ISSUE THREAD

**Issue by memadrid** [IIC2115/Syllabus#64]
En la Issues #45 pregunté como obtener el mapa, y me dijeron que esta debía ser una variable (una lista de listas), ¿algo como: [[ 'E', '_', '_', '_', '_', 'X', 'C' ], ['_', '_', '_' , '_', 'E', 'X', '_' ]]? ¿Cómo ingresan esto ustedes? 
Pregunté en clases y me dijeron que podían pegarla al inicio del programa...¿estaría bien?
Además, asumo que el formato es el correcto, ¿verdad?

**Comment by iasantibanez** [comment]
según yo si, en nuestro caso usamos algo de este estilo antes de iniciar el programa:

lista = \
    [['E','_','_','_','_','X','C'],
    ['_','_','_','_','E','X','_'],
    ['X','X','X','X','_','X','_'],
    ['_','T','_','X','_','X','_'],
    ['_','_','_','X','_','X','_'],
    ['_','X','_','_','_','_','_'],
    ['_','X','_','_','_','_','C']]
