### ISSUE TITLE
L03-->M1-->Error (data type mismatch) en creación nuevas tablas

### ISSUE THREAD

**Issue by VicenteDelRio** [IIC2115/Syllabus#64]
Hola!
Al crear una nueva tabla me arroja el siguiente error:
"data type mismatch"
Por lo que busque es que al recibir todas las variables tipo TEXTO  me genera problema a pasarlas a tipo REAL en mi nueva tabla. Como lo puedo arreglar?
Saludos

**Comment by FGarridoV** [comment]
Este error ocurre cuando creas una base de datos y luego le tratas de insertar una fila de datos donde uno de los tipos no coincide. Probablemente, y según lo que indicas, debe ser el signo del decimal, verifica si esta con "coma" o con "punto".

**Comment by VicenteDelRio** [comment]
Lo acabo de revisar y esta todo ok. No será problema que no he arreglado mi base de datos? En cuanto a valores vacíos y repetidos? Tenía pensado hacerlo una vez creadas las tablas de entidades...

**Comment by FGarridoV** [comment]
Te recomiendo siempre buscar los tipos de errores en google. Ayuda muchísimo y aprendes de otras cosas que topas en tu búsqueda.
