### ISSUE TITLE
Duda habilidad Jefe

### ISSUE THREAD

**Issue by jlcasanova2** [IIC2115/Syllabus#64]
cuando hago la funcion de usar_habilidad para el Jefe, como tengo que llamar a las 4 otras clases, el valor del identificador de las piezas se me modifica, así que no encuentro como llamar solo a los metodos de las otras clases/piezas, sin llamar a las clases.
Gracias

**Comment by FGarridoV** [comment]
Trata de detallar un poco más para poder entender, no logro captar tu duda.
