### ISSUE TITLE
Output consulta 3 Lab1b

### ISSUE THREAD

**Issue by IvoVuskovic97** [IIC2115/Syllabus#64]
en la consulta "Construya un ranking descendente de popularidad de los generos, donde para cada uno se
muestren los 3 actores mas populares"

el output debe ser algo asi como por ej:

(Comedia, [Pedro, Juan, Diego])
ó
(Comedia, Pedro)
(Comedia, Juan)
(Comedia, Diego)

**Comment by pcseisdedos** [comment]
Creo que la opción`(Comedia, [Pedro, Juan, Diego])` se entiende mejor.

Saludos,
Pablo 😁👍
