### ISSUE TITLE
mover_pieza

### ISSUE THREAD

**Issue by fcanessa2** [IIC2115/Syllabus#65]
Hola! Estoy cambiando mi tarea a la librería simplificada pero me di cuenta que no me mueve las piezas. Hice un ejemplo chico para entender que pasaba:

import game

window = game.LostGame()
window.setup()
window.poner_pieza('Y',5,8,1)
window.mover_pieza('Y',1,1)
window.mostrar_texto("Y se mueve")
window.fin_del_juego()
window.run()

Comienza el juego
   -----------------------------------------
10 |   |   |   |   |   |   |   |   |   |   |
   -----------------------------------------
9  |   |   |   |   |   |   |   |   |   |   |
   -----------------------------------------
8  |   |   |   |   | Y |   |   |   |   |   |
   -----------------------------------------
7  |   |   |   |   |   |   |   |   |   |   |
   -----------------------------------------
6  |   |   |   |   |   |   |   |   |   |   |
   -----------------------------------------
5  |   |   |   |   |   |   |   |   |   |   |
   -----------------------------------------
4  |   |   |   |   |   |   |   |   |   |   |
   -----------------------------------------
3  |   |   |   |   |   |   |   |   |   |   |
   -----------------------------------------
2  |   |   |   |   |   |   |   |   |   |   |
   -----------------------------------------
1  |   |   |   |   |   |   |   |   |   |   |
   -----------------------------------------
     1   2   3   4   5   6   7   8   9   10

Y se mueve
   -----------------------------------------
10 |   |   |   |   |   |   |   |   |   |   |
   -----------------------------------------
9  |   |   |   |   |   |   |   |   |   |   |
   -----------------------------------------
8  |   |   |   |   | Y |   |   |   |   |   |
   -----------------------------------------
7  |   |   |   |   |   |   |   |   |   |   |
   -----------------------------------------
6  |   |   |   |   |   |   |   |   |   |   |
   -----------------------------------------
5  |   |   |   |   |   |   |   |   |   |   |
   -----------------------------------------
4  |   |   |   |   |   |   |   |   |   |   |
   -----------------------------------------
3  |   |   |   |   |   |   |   |   |   |   |
   -----------------------------------------
2  |   |   |   |   |   |   |   |   |   |   |
   -----------------------------------------
1  |   |   |   |   |   |   |   |   |   |   |
   -----------------------------------------
     1   2   3   4   5   6   7   8   9   10

Gracias!

**Comment by sidiaz2** [comment]
Hola! Creo que me pasaba lo mismo que a ti. Lo que pasa es que cuando ocupas window.poner_pieza(), el id que se le asigna a la pieza que creaste comienza en 0, y es en el orden en que pones las piezas en el tablero. De este modo, cuando pones window.mover_pieza(), deberías ocupar como referencia a la pieza 0.

**Comment by fcanessa2** [comment]
Funciono! Gracias!
