### ISSUE TITLE
L1b, Misión 0

### ISSUE THREAD

**Issue by jgfarias** [IIC2115/Syllabus#65]
Con respecto a la limpieza de la base, tengo que:
- crear y poblar las tablas que voy a usar, y hacer la limpieza sobre las tablas (usando ``sqlite``), o
- hacer la limpieza sobre el archivo ``movies.json`` (usando python sobre los diccionarios que tienen la información de cada película) y luego crear y poblar las tablas

Leyendo el enunciado me surgió esa duda respecto a como hacerlo.

Gracias!

**Comment by pcseisdedos** [comment]
Depende, puede que haya errores que al corregirlos puedas crear tablas de otra forma, por lo que tendrías que hacerlo antes de crearlas. Queda a criterio de ustedes cómo manejarlo.

Saludos,
Pablo 😁👍
