### ISSUE TITLE
Cambio de nombres columna region

### ISSUE THREAD

**Issue by acdelgado1** [IIC2115/Syllabus#66]
Hola! Como en eco hay menos regiones que en City, es válido cambiar todas las de City para que calcen con las de eco o estaría incorrecto porque son menos específicas?

**Comment by FGarridoV** [comment]
Mientras dejes justificados tus supuestos y uses SQL para ello, no hay problema. Recuerda que nosotros vamos a ejecutar tu tarea a partir de la base de de datos que nosotros subimos. Por tanto, tu punto de partida es siempre esa BD.
