### ISSUE TITLE
Juego infinito

### ISSUE THREAD

**Issue by arielczerny** [IIC2115/Syllabus#66]
Estimados,

Qué pasaría si todas las fichas que destruyen piezas de ambos equipos ya fueron eliminadas y quedan aún algunos defensores? Cómo lo hago para elegir un ganador?

**Comment by djhempel** [comment]
no se pueden destruir todas las con habilidades de ataque, porque en algún minuto va a quedar solo una de ataque que no puede ser destruida ni por defensores ni por atacante 2

**Comment by fagomez2** [comment]
Hola! Me parece que no es posible que quede una situación como la que describes. De todas formas, si llega a pasar alguna situación "rara", escribe en el readme cuál es la decisión que tomaste (puedes, por ejemplo, dejarlo en empate).

También queda a tu criterio qué hacer en otras situaciones especiales, por ejemplo, un equipo sin atacantes ni jefe no puede ganar, así que podrías hacer perder a ese equipo en cuanto no tenga opción de ganar la partida. 

Saludos!
