### ISSUE TITLE
Poner piezas iniciales

### ISSUE THREAD

**Issue by mblejeune** [IIC2115/Syllabus#67]
Hola! Al iniciar el juego debo poner las piezas en la matriz que se nos da, ¿es necesario que el equipo 1 parta al sur por ejemplo y el equipo 2 al norte? he leido issues como que alumnos asumen esto pero yo no lo lei en el enunciado, y hasta el momento los pongo en posiciones aleatorias que yo le doy (sin repetirse), gracias!

**Comment by fagomez2** [comment]
Hola! El enunciado dice textual:
> La posición inicial de las piezas queda a criterio de ustedes.

Así que estás bien. Recuerda escribirlo en el readme junto con otras suposiciones o decisiones importantes. Saludos!
