### ISSUE TITLE
Lab1a, pregunta 2: Palíndromos

### ISSUE THREAD

**Issue by ianmiquel** [IIC2115/Syllabus#67]
Hola, ¿Qué ocurre si la palabra evaluada es un palíndromo? ¿tenemos que filtrar que el código no cuente dos veces en todas las direcciones la palabra o se puede asumir que aparece dos veces?

**Comment by pcseisdedos** [comment]
No debiera afectar en el código la existencia de palíndromos (encontrar la misma palabra en ambas direcciones sería correcto), de todas formas, es poco probable que aparezcan en los inputs.

Saludos,
Pablo 😁👍
