### ISSUE TITLE
Problemas con quitar_pieza

### ISSUE THREAD

**Issue by josefinabravo** [IIC2115/Syllabus#68]
Hola! Al utilizar en mi código el comando "quitar_pieza(número de pieza a quitar)" no se me elimina la pieza, solo sale el mensaje que avisa que la eliminó. Me gustaría saber si que se debe utilizar quitar_pieza() de alguna forma en especial o si hay algo que pueda hacer que no cumpla su función.

**Comment by FGarridoV** [comment]
Es como dices, debes utilizar el número en que fue puesta la pieza en el tablero (poner_pieza) comenzando desde 0.
