### ISSUE TITLE
Uso de SQLiteStudio

### ISSUE THREAD

**Issue by JeanLabarthe** [IIC2115/Syllabus#68]
Hola, se puede usar QSLiteStudio para hacer cambios en la base de datos?
Como la app está recomendada en el Material de Clases me puse a ver que hacía y encontré que para modificar las tablas es mucho más rápido que hacerlo directamente con Python (ej: para cambiar los tipos de datos se necesitan 2 clicks)
Gracias

**Comment by pcseisdedos** [comment]
El tema es que nosotros vamos a ejecutar su tarea ocupando la base de datos original como punto de partida, si tu haces modificaciones que no están en tu código vamos a obtener resultados distintos.

Pueden ocupar otras herramientas como apoyo, pero en su entregable debe estar todo lo necesario para que la tarea se ejecute correctamente.

Saludos,
Pablo 😁👍
