### ISSUE TITLE
Pauta Taller 3B 

### ISSUE THREAD

**Issue by FernandoSMG** [IIC2115/Syllabus#69]
Hola podrian subir una pauta del taller del jueves pasado antes de la Actividad de mañana?

De antemano muchas gracias

**Comment by pcseisdedos** [comment]
Está disponible el [código](https://github.com/IIC2115/Syllabus/blob/main/Ayudant%C3%ADas/T3b/Ay_T3b.ipynb) y el [video](https://youtu.be/dFUTLExY-RI) de la ayudantía.

Saludos,
Pablo 😁👍
