### ISSUE TITLE
Entrega L02

### ISSUE THREAD

**Issue by simonerenard** [IIC2115/Syllabus#69]
Para subir la tarea tiene que tener de nombre L02 y en la carpeta solamente el código y el readme.txt cierto?

¿No tiene que estar ni el game.py ni los sprites? (yo usé la librería alternativa)

Gracias!

**Comment by pcseisdedos** [comment]
@simonerenard Tienes que subir un archivo `ipynb` junto con un `README.md`, en caso de usar la librería alternativa especifícalo en el `README` y no es necesario que subas sprites, si subes cualquier otro archivo en la carpeta `L02` de tu repositorio tendrás 5 décimas de descuento por formato tal como especifica el enunciado.
Pablo.

**Comment by pcseisdedos** [comment]
La extensión `.md` indica que el archivo corresponde a [Markdown Documentation](https://markdown-guide.readthedocs.io/en/latest/). Github reconoce los archivos con esa extensión y los muestra de mejor forma.

**Comment by simonerenard** [comment]
y si lo subo como txt me bajan puntos?

**Comment by simonerenard** [comment]
No puedo subir el nuevo md... 

No me deja actualizar el repositorio
