### ISSUE TITLE
Problema III - [LAB03]

### ISSUE THREAD

**Issue by javiprado** [IIC2115/Syllabus#70]
Hola!
No logro entender que es lo que piden en el problema 3 del laboratorio 03 con lo que sale en el enunciado. Lo podrían explicar de otra forma por favor?
Gracias de antemano!

**Comment by Jamidd** [comment]
Eso lo debería dejar mas claro.
https://youtu.be/feWxxns3EGk
Sorry la orientación.

Jaime Middleton

**Comment by javiprado** [comment]
Gracias, te pasaste! Ahora me queda claro :)

**Comment by kdcarreno** [comment]
Se incluye el 0 ?

**Comment by halobel** [comment]
Revisa el enunciado, ahí está especificado el intervalo.

**Comment by martinrafols** [comment]
pero todavía no me queda claro de donde sale la lista, si el input es un número solo! o está mal puesto en el pdf?
