### ISSUE TITLE
M1 error UNIQUE constraint failed: Ciudades.City

### ISSUE THREAD

**Issue by mfletelier** [IIC2115/Syllabus#70]
Hola! En la creación de tablas me aparece ese error ocupando DISTINCT y sin agregar datos que cambien. 
Como puedo solucionarlo?

**Comment by pcseisdedos** [comment]
Lo que pasa es que no se cumple la condicion de que la PK es única, el DISTINCT se ocupa para no repetir valores al hacer consultas, son cosas diferentes.

Saludos,
Pablo 😁👍
