### ISSUE TITLE
Problema II.a L03

### ISSUE THREAD

**Issue by isalvador95** [IIC2115/Syllabus#71]
El enunciado del problema habla de números enteros y dígitos. Solo para asegurarme, no se pueden utilizar números negativos entonces? dado que el 1 y -1 utilizan el mismo dígito.
Por otro lado, el 0 sí se incluye ?

**Comment by jlcasanova2** [comment]
siguiendo con las mismas preguntas, que pasa si se agrega un numero de más de un digito (ej: 10, 11...) o los strings que entran en la II.a seran tales que no sucedan esos casos

**Comment by FGarridoV** [comment]
@isalvador95 efectivamente, los números no pueden ser negativos dentro de la secuencia. Recuerda que esta busca represar un número, por lo que algo del estilo *122-23* no sería válido. El **0** si puede estar dentro de la secuencia.

**Comment by FGarridoV** [comment]
@jlcasanova2 si se pueden agregar número de más de un dígito, mientras se cumplan las reglas.

**Comment by ekuncars** [comment]
En el input de este problema, nos darán con qué  número partir? o eso lo tendría que ver el programa mismo?.
Lo pregunto porque en los ejemplos que nos dan en el enunciado, las secuencias de "+" y  "-" tienen una longitud inferior al output del sistema.
Por ejemplo:
![image](https://user-images.githubusercontent.com/48446230/55850893-51c00600-5b24-11e9-95aa-017c17f85644.png)

No se si el 1 del output lo dieron como input o lo dedujo el sistema.

**Comment by halobel** [comment]
Es parte del algoritmo elegir el número de inicio. La respuesta siempre debe tener un número más que la cantidad de símbolos de la entrada, ya que a partir de ese primer número, debe aumentar o disminuir la secuencia.

**Comment by Mcarriagada** [comment]
Me quedó una duda respecto a lo del número de inicio, yo podría hacer que mi número de inicio, por ejemplo, sea siempre el 1?
