### ISSUE TITLE
Librerías misión 1 lab 1b

### ISSUE THREAD

**Issue by manalvarezc** [IIC2115/Syllabus#71]
Hola!
En internet busqué una forma de obtener el código html de una página a través de python para utilizar BeautifulSoup, y esta forma ocupa la librería **requests** y la instalación del toolkit  **lxml**. Se puede utilizar esta librería (**requests**) y el **lxml** para la misión 1 del lab 1b? Estos se ocupan solo para la obtención del código html.
Gracias.

pd: por si acaso, dejo el link de la página https://j2logo.com/python/web-scraping-con-python-guia-inicio-beautifulsoup/

**Comment by pcseisdedos** [comment]
Hola, si puedes ocupar requests y lxml para esto. Es un complemento a bs4, a diferencia de las librerías wikipedia y wikipediaapi, que son un reemplazo, por lo que no se pueden ocupar.

Saludos,
Pablo 😁👍
