### ISSUE TITLE
Problema 1 (a) LAB03

### ISSUE THREAD

**Issue by cmujicai** [IIC2115/Syllabus#72]
Si bien las listas que se reciben esta ordenadas de menor a mayor, asumo que no hay numero repetidos en una misma lista?

**Comment by FGarridoV** [comment]
eso no debiera importar, podrían repetirse.

**Comment by cmujicai** [comment]
perfecto, y una pregunta de como quieren el output de la funcion. Si le entrego dos listas,
["A", "B"] y ["C", "D"], quieren que la función retorne ["C", "D"] o ["12", "13] ?? Gracias de ante mano

**Comment by halobel** [comment]
Tanto entrada como salida deben ir en hexa, por lo que sería el primer caso.

**Comment by eljaker** [comment]
Es valido que la salida (output) sea en hexa de esta forma: ['0x1', '0x2', '0x3', '0x6', '0x7', '0x7', '0x8', '0xa', '0xa'....] o solo es válido que sea así: ["1", "2", "3", "6", "7", "7, "8", "A", "A",...] ya que encontré una función que puede generar outputs hexadecimales de la primera forma.

**Comment by FGarridoV** [comment]
@eljaker  La segunda!

**Comment by KarinGolb** [comment]
La lista que nos entregan va a estar ordenada de menor a mayor? o es necesario ordenarla en nuestra función?

**Comment by aiiglesias** [comment]
Creo que el ejemplo entregado en el enunciado no esta bien ya que cuando llegue al 7 y elija el camino de suma máxima tomará la decisión de ir por la lista de arriba que suma más que la suma de abajo, sin embargo según el enunciado el algoritmo al llegar a 7 se irá por la lista de abajo.
