### ISSUE TITLE
Modificar base de datos

### ISSUE THREAD

**Issue by CabelloAlvaro** [IIC2115/Syllabus#73]
Previo al modelo, se pide armar la función dowload_app(app_name). Cada vez que es llamada se debe aumentar en 1 el número del atributo, pero este atributo está de la forma "1,000+", "5,000+".
Le sumo 1 y queda de la forma "1,001+"? Cual es la idea?

**Comment by Hernan4444** [comment]
La idea es que adapten el modelo para que pueda realizar exitosamente las consultas. Justamente cuando le sumas 1 puedes dejarlo como "1,001+" o simplemente como 1001, porque luego hay otras consultas que necesitan de ese dato.

**Comment by agrudsky95** [comment]
Hola, entonces podemos poner desde un principio que las installs son 1,000 sin el +?

**Comment by Hernan4444** [comment]
Si puedes .
Saludos ✌️
