### ISSUE TITLE
exceso de mails

### ISSUE THREAD

**Issue by kdcarreno** [IIC2115/Syllabus#73]
Es necesario cerrar los issues ? no existe una categoria archivar? A veces es absurda la cantidad de correos que llegan de esta página

**Comment by halobel** [comment]
Hola, sí, es necesario, porque a medida que avanza el curso la cantidad de issues crece bastante, por lo que se haría difícil buscar dentro de tantas.
Para evitar el problema, simplemente puedes crear un filtro en gmail, para que todos lo correos relacionados con el cierre de issues se borren o archiven, o se asignen a alguna etiqueta.
