### ISSUE TITLE
Dudas formato de entrega L1b

### ISSUE THREAD

**Issue by IvoVuskovic97** [IIC2115/Syllabus#73]
Hola, tengo dudas con respecto al formato de entrega

1. para el L1a igualmente deben estar los ejemplos en un bloque main  en el archivo py (solo que sin los print obviamente) , o solo basta con colocar todas las funciones?
2. para el L1b es necesario poner bloques main? y en el archivo py  e ipynb se pueden poner cosas con el metodo print?

de antemano gracias

**Comment by pcseisdedos** [comment]
Yo personalmente te recomiendo que te acostumbres a ocupar el bloque main para todas las ejecuciones y prints, es una buena práctica y no hace daño ni está de más.

Respecto a esta evaluación en particular, es muy importante que no haya ejecuciones ni prints en el L1a.py fuera de un bloque main. En el L1b.py da lo mismo si están o no.

Saludos,
Pablo 😁👍
