### ISSUE TITLE
Qué se pide exactamente en el Problema II a.?

### ISSUE THREAD

**Issue by vnramirez** [IIC2115/Syllabus#74]
Hola!

No me quedó claro con el enunciado, y con las issues quedé mas confundido todavía.

1) Se debe elegir la secuencia cuya suma de dígitos sea la menor? O cuyo número final (grande) sea el menor? En matemáticas hay sólo 10 dígitos (del 0 al 9), por lo que sólo se nos podrían entregar string de a lo más len = 9?

2) De considerar el 0, no estaría malo el ejemplo que se nos da en el enunciado?

3) Me confundí mucho cuando leí en un issue que se debían considerar números negativos...

Saludos y gracias de antemano.

**Comment by fagomez2** [comment]
Hola!
1. El número final debe ser el menor. La secuencia puede tener largo indefinido. Se te pide entregar el resultado para una secuencia válida. Por ejemplo, +++++++++++++++ (15 + seguidos) no sería una secuencia válida, en tanto que +-+-+-+-+-+-+-+-+-+- (+- de largo 20) sí lo es
2. El cero sí se considera (puede aparecer en tu secuencia), pero recuerda que poner un cero a la izquierda no sirve de nada (de hecho entregarías con menos dígitos de lo pedido)
3. ¿Cuál issue leíste? Me metí a revisar y solo hay una en donde @FGarridoV menciona que los números **no** pueden ser negativos dentro de la secuencia
Cualquier duda nos preguntas! Saludos

**Comment by vnramirez** [comment]
Gracias @fagomez2!

Cómo +-+-+-+-+-+-+-+-+-+- podría ser válida? Por ejemplo, si en algún momento de mi secuencia escribo un 1, eso me imposibilita poder escribir 11, 12, 13, ..., 21, 31, 41, etc... porque comparten el dígito 1. A eso voy!

Ejemplo para esa secuencia:

5463728190 y luego cómo sigo? el paso "obvio" sería escribir un 10, pero no debería porque ya tengo un 1 y un 0 en mi secuencia.

Saludos

**Comment by kdcarreno** [comment]
las instrucciones dicen que no se puede repetir los digitos. No podría ser válida una secuencia de 10 o más carácteres

**Comment by kdcarreno** [comment]
y de la segunda pregunta de vnramirez , el ejemplo dice  '++--+-+-' en caso de incluir al cero el resultado deberia ser 134206587 y no 125437698 como dice el enunciado.

**Comment by cmujicai** [comment]
@kdcarreno  Este numero 125437698 es más chico que 134206587. No se puede iniciar con cero por que se pide que el output sea un número entero. 

@fagomez2 Tampoco se como  +-+-+-+-+-+-+-+-+-+- podría ser valido, sin que se repitiese ningún dígito en el número que tiene que entregar el programa

**Comment by fagomez2** [comment]
Hola! Lamento el malentendido, me equivoqué con mi primera explicación. Olvidé el hecho de que no puedes repetir dígitos. En tal caso, las dos secuencias que di son inválidas. Les pedimos un resultado solo para secuencias válidas. Para el resto basta con que retornen algo como "No existen números válidos a generar".

**Comment by fagomez2** [comment]
Sobre el cero, la explicación de @cmujicai es correcta. el cero cuenta como uno de los dígitos a utilizar, pero no puedes empezar con él

**Comment by ekuncars** [comment]
Por qué no se puede empezar con el cero? si está considerado como dígito y es un número entero. Además, en el enunciado no explicitan que no se pueda empezar con él.

**Comment by vnramirez** [comment]
Según yo no se debería incluir el 0 como dígito. De lo contrario, la solución al ejemplo del enunciado debería ser 124306587.

**Comment by cmujicai** [comment]
No me había fijado en ese ejemplo, @fagomez2  que hacemos entonces? incluimos el cero? Por que de ser así, el ejemplo del enunciado estaría malo

**Comment by fagomez2** [comment]
@vnramirez tiene razón. Gracias por detectar ese error. Consideren que pueden ocupar el cero. Los profesores actualizarán el enunciado en breve

**Comment by vnramirez** [comment]
Quizás es mejor que no se considere el cero! Para no tener que modificar
las tareas de todos, o no?

**Comment by FGarridoV** [comment]
Desde el principio se dijo que se puede utilizar el 0 en la construcción de los números. Incluso el enunciado no niega el uso del cero. Solo que este no puede dar inicio al número dado que ahí no tendría valor.

**Comment by FGarridoV** [comment]
Actualizado el ejemplo,

Saludos

**Comment by mblejeune** [comment]
> Hola!
> 
> 1. El número final debe ser el menor. EDIT: como no hay repetidos, tienes razón con lo del largo del número. Se te pide entregar el resultado para una secuencia válida. Por ejemplo, +++++++++++++++ (15 + seguidos) no sería una secuencia válida, ni tampoco lo sería +-+-+-+-+-+-+-+-+-+- (+- de largo 20) porque no puedes repetir números
> 2. El cero sí se considera (puede aparecer en tu secuencia), pero recuerda que poner un cero a la izquierda no sirve de nada (de hecho entregarías con menos dígitos de lo pedido)
> 3. ¿Cuál issue leíste? Me metí a revisar y solo hay una en donde @FGarridoV menciona que los números **no** pueden ser negativos dentro de la secuencia
>    Cualquier duda nos preguntas! Saludos

@fagomez2  hola! como es posible que se cumpla con el largo del número que dice vnramirez si en esta issue https://github.com/IIC2115/Syllabus/issues/71 dice que se pueden agregar números de más de un dígito?

**Comment by FGarridoV** [comment]
Puedes agregar numeros de más de un dígito pero a la vez debes cumplir todos los requisitos y encontrar el mínimo.

**Comment by FelipeUlloan** [comment]
cuando se refiere a numero entero de menor valor, es la suma de los elementos de la lista? o es como que el numero se construye con cada elemento de la lista? es decir si la lista es [1,2,4,3,0,6,5,8,7], entonces el número sería 124.306.587? o 36?

**Comment by FelipeUlloan** [comment]
la secuencia no comenzaría en ningún caso con un "-" ?
