### ISSUE TITLE
Nueva base de datos

### ISSUE THREAD

**Issue by clementeramirez** [IIC2115/Syllabus#74]
Hola! Si ya habia trabajado con la base de datos que estaba antes y llevo harto, tengo que cambiar mi base de datos si o si? o puedo seguir trabajando con la de antes?

**Comment by Leda7** [comment]
Hola! A mi me paso lo mismo, inclusive hice mis consultas con mis tablas. También había filtrado mi base de datos eliminando errores, lo cual me llevo bastante tiempo.

**Comment by pcseisdedos** [comment]
Si ustedes arreglaron los mismos errores que jaime, no veo problema en que sigan ocupando la base de datos antigua. La idea de subir otra arreglada es facilitar su trabajo. Ahora bien, si trabajan con la base de datos antigua sin arreglar los errores creo que hay un problema.

Saludos,
Pablo 😁👍

**Comment by Leda7** [comment]
Con respecto a las tablas que subieron, al menos podría editarlas? para dejarla acorde a mis consultas? Como por ejemplo agregar una columna o quitarle?

**Comment by Jamidd** [comment]
Si te refieres a las tablas que no son 'city' o 'eco', puedes hacer lo que quieras con ellas, incluso borrarlas. Las importantes son 'city' y 'eco' de esas debes extraer la información. 

Saludos,
Jaime

**Comment by clementeramirez** [comment]
gracias!
