### ISSUE TITLE
modelo relacional

### ISSUE THREAD

**Issue by rpmalonnek** [IIC2115/Syllabus#74]
hola ! para las aplicaciones se debe considerar que pueden tener N generos o solo 1 ?

**Comment by Hernan4444** [comment]
Hola, en el enunciado se especifica bien la situación de los géneros con cada aplicación (en la sección de archivos entregados).

**Comment by cnurrutia** [comment]
Sobre el modelo relacional,
¿Las tablas deben cumplir las formas normales?

**Comment by Hernan4444** [comment]
No, no es materia pasada las formas normales, solo debes precuparte que sigas las restricciones del material de clases.
