### ISSUE TITLE
l1b mision 2

### ISSUE THREAD

**Issue by nencinav** [IIC2115/Syllabus#74]
Si el código me queda gigante, ¿Puedo crear variables en python que sean string para que quede mas ordenado?, como lo hacen en las pautas de años pasados.
Adjunto ejemplo del año pasado.

![Captura de Pantalla 2021-05-31 a la(s) 00 37 06](https://user-images.githubusercontent.com/80851830/120140337-56365580-c1a8-11eb-8464-555a2c5d8e4f.png)

**Comment by pcseisdedos** [comment]
Si se puede, siempre y cuando no se ocupe Python para resolver la consulta, solo para hacer consultas anidadas de la forma que planteas.

Saludos,
Pablo 😁👍
