### ISSUE TITLE
Crear tablas

### ISSUE THREAD

**Issue by shiflix** [IIC2115/Syllabus#75]
Primero creo una tabla usando el comando cursor.execute('CREATE TABLE t(...)') . El problema es que al ejecutar nuevamente el comando me dice "OperationalError: table t already exists"
Esto significa que siempre le debo cambiar el nombre a la tabla? Como puedo probar mi código para saber que funciona sin tener que siempre cambiar el nombre de la tabla?

Saludos,
Lucas

**Comment by CarlosCarvajalGallegos** [comment]
A ese codigo ponle cursor.execute("CREATE TABLE IF NOT EXISTS t(...)") y según yo se arregla (o por lo menos eso me salía en google). 
Ojalá te sirva!

**Comment by shiflix** [comment]
Gracias, voy a probarlo.
Eso no traería el problema de que nunca se crearía la tabla? ya que si la tabla t ya existe no la crearía o ejecutaría los cambios que le hago

Saludos, Lucas
