### ISSUE TITLE
Comando no reconocido T4a

### ISSUE THREAD

**Issue by ianmiquel** [IIC2115/Syllabus#75]
Hola, al correr el taller, me aparece el siguiente error en distintas ocasiones:
_"ls" no se reconoce como un comando interno o externo, programa o archivo por lotes ejecutable._
¿por qué ocurre esto?
Tengo instaladas las librerías que se piden y también los archivos de la EOD

**Comment by pcseisdedos** [comment]
Supongo que te refieres a los ejemplos, porque el taller todavía no lo publicamos. Lo que me parece raro es que pones "Is" en mayúsculas, quizás sea eso... Si no, puede que ya no exista en una versión más reciente de python.

Saludos,
Pablo 😁👍

**Comment by ianmiquel** [comment]
Que raro que se vea en mayúsculas, a mi se me muestra en minúsculas ls, en todo caso, lo solucioné pasándome a colab (estaba en VS). Por si alguien mas tiene ese problema.
Saludos!
