### ISSUE TITLE
duda implementacion de la materia

### ISSUE THREAD

**Issue by tmoreno1** [IIC2115/Syllabus#75]
Tanto para los stacks como para las colas, la idea es hacer los codigos con los "metodos basicos en el stack" o "implementacion en python" (tabla de las materias) ??

**Comment by FGarridoV** [comment]
La idea es que uses esa estructura de datos (colas o stacks) para resolver el problema. Esto gracias a la forma en que almacenan la información (FIFO o LIFO).

Saludos

**Comment by mtbobillier** [comment]
Hola! Tengo una duda, es necesario usar las recomendaciones de la materia? O puedo usar otra materia, igual del capítulo 2 para resolver los ejercicios? Por ejemplo, para el problema 3 puedo usar colas o stacks y no listas ligadas o árboles?

**Comment by vnramirez** [comment]
Ward a la pregunta de @mtbobillier
Algunos los resolví con materia del capítulo 2, pero no con lo que se recomendó.
Gracias!

**Comment by FGarridoV** [comment]
Si, mientras usen debidamente las estructuras, no hay problema
