### ISSUE TITLE
DataSet L03

### ISSUE THREAD

**Issue by Jamidd** [IIC2115/Syllabus#75]
Estimados, 
como algunos de ustedes comentaron, efectivamente hay algunos errores (tablas con información corrida en las columnas) en la base de datos que les entregamos. 
Les pedimos que descarguen la nueva base de datos. Esta se encuentra en el Syllabus y tiene por nombre "L03V2.db" .

Mucho éxito con el lab. 
Jaime Middleton

**Comment by JaviOrtizH** [comment]
Entonces, tenemos que editar esta base y subir esta?

**Comment by dilanlopeg** [comment]
Hola, me sumo a la duda de la compañera, debemos considerar como tablas
propuestas las nuevas tablas que aparecen en L03V2?

**Comment by Jamidd** [comment]
Las tablas originales "city" y "eco" son las que tienen información y son con las que deben empezar a trabajar. Las otras 4 tablas, son una posible propuesta de tablas que pueden replicar para la M1 y el resto del lab. No es necesario que usen estas tablas, incluso las pueden eliminar si lo desean. Insisto, las importantes son "eco" y "city", esas se mantienen. 
Saludos, 
Jaime

**Comment by paulavonbrand** [comment]
Hola! estoy media perdida, puedo hacer todo de 0 usando solo las tablas de L03V2? 
Al finalizar el lab hay que subir solo los .py y .ipynb o también las tablas?

**Comment by Jamidd** [comment]
- puedo hacer todo de 0 usando solo las tablas de L03V2?
  - Tienes que crear tu tus tablas, pero estas pueden tener la misma estructura que las 4 tablas nuevas.  
- Al finalizar el lab hay que subir solo los .py y .ipynb o también las tablas?
   - Tal como esta explicitado en el enunciado, deben subir el .py y el .ipynb. **NO** deben subir la base de datos. Su código debe ser tal que si lo corres leyendo ya sea "L03.bd" o "L03V2.db" imprima el resultado de todas las consultas. 

Cuando creas estar lista, ejecuta ”restart and run all” y revisa que entrega bien todas las consultas. Con eso deberías estar OK.
