### ISSUE TITLE
Tipo de dato de COUNT 

### ISSUE THREAD

**Issue by lcoronata** [IIC2115/Syllabus#76]
Si yo hago un SELECT COUNT y luego quiero manipular ese dato como hago para darle un tipo de dato? que si lo analizo con pragma table me dice que no tiene un tipo de dato por lo que no puedo darle restricciones

**Comment by Jamidd** [comment]
No entiendo muy bien tu pregunta, 
te refieres a hacer algo como 
`SELECT tipo, COUNT(cantidad) AS tot FROM aviones GROUP BY tipo ORDER BY tot DESC`
(aviones es una tabla inventada, pero asume que hay entradas con tipo de avión, cuantos han pasado en cierta fecha y la fecha)

**Comment by lcoronata** [comment]
Si hago un pragma table sobre una tabla que cree en base a un select count(), idp ... y lo agrupo en base al idp me pasa que la tabla resultante es así:

[(0, 'COUNT ()', '', 0, None, 0), (1, 'idp', 'TEXT', 0, None, 0)]

entonces como el count no tiene una categoría no lo puedo restringir en otro select

**Comment by FGarridoV** [comment]
Puedes asignar el count a una variable como indica @Jamidd
