### ISSUE TITLE
feedback positivo

### ISSUE THREAD

**Issue by tmoreno1** [IIC2115/Syllabus#76]
Me ayudo mucho para hacer la tarea que te digan la materia a utilizar en cada ejercicio. 
Me sirvió para la realización de la tarea y aprender mejor la materia especifica, y así no divagar en todas las materias (que es mucho).
Ojalá los siguientes laboratorios también hagan lo mismo!

**Comment by FGarridoV** [comment]
Por lo menos para los siguientes labs, mantendremos este formato!

gracias por comentarlo,
saludos

**Comment by kdcarreno** [comment]
@FGarridoV  En el lab 4 no están las sugerencias de EDD. Las van a subir ?

**Comment by FGarridoV** [comment]
No, deben usar la estructura que ustedes crean razonable para resolver el problema. El uso de estas será correcto si esta bien implementada y ayuda a encontrar la solución.

**Comment by kdcarreno** [comment]
En ese caso, podrían sugerir que **no** hacer o que sube mucho el tiempo de respuesta. Hasta este curso no he tenido la necesidad de fijarme en la eficiencia de un código.

eg para el problema 1: 3 for anidados **no**

**Comment by Mcarriagada** [comment]
En el enunciado sale que no se usa fuerza bruta, por lo tanto, si haces falta for estas haciendo fuerza bruta. Te lo estan diciendo implícitamente.

**Comment by halobel** [comment]
Por favor revisen esta [issue](https://github.com/IIC2115/Syllabus/issues/88#issuecomment-484559139) en relación al tema fuerza bruta.
Con respecto a las recomendaciones de estructuras, el primer lab de esta unidad fue pensado como introductorio, por lo que era importante acotar las estructuras que podían usar. Para este segundo lab, asumimos que ya tienen un conocimiento más acabado de las estructuras. Además, los problemas son más abiertos, por lo que pueden usar cualquier de las estructuras que crean convenientes, siempre que ayuden a evitar el uso de fuerza bruta en el problema.
