### ISSUE TITLE
NaN

### ISSUE THREAD

**Issue by jgmorales23** [IIC2115/Syllabus#76]
Hola, cuando dicen eliminar los NaN, se refiere al valor NaN de los comentario (dejandolo como vacio) o al comentario en si mismo, ya que hay muchos comentarios que no tienen ningun valor y todas sus columnas tienen NaN

Gracias

**Comment by fagomez2** [comment]
Hola Javier! De acuerdo al enunciado, tienes que eliminar el comentario en sí.
Saludos!
