### ISSUE TITLE
Laboratorio 1a - Pregunta II - Revisar letra dos veces

### ISSUE THREAD

**Issue by DanielCarrascoFalcon** [IIC2115/Syllabus#76]
Hola!
Una consulta, debo preocuparme de no volver a pasar por la misma posición dos veces o para efectos de este lab da lo mismo??
Me explico:
Supongamos una sopa
 X  X  T  A  C
 X  X  X  X  X
 X  X  X  X  X
 X  X  X  X  X
 X  X  X  X  X

Si busco la palabra TACA mi algoritmo la va a encontrar, puesto que al llecar a la letra C revisa todos los vecinos...
Se espera que manejemos estos caso o están permitidos?

Gracias!

**Comment by pcseisdedos** [comment]
Hola, no está permitido ocupar la misma posición dos o más veces para formar una palabra, por lo que TACA no estaría presente en este caso, debiera haber una A abajo de la A o de la C para que esté presente.

Saludos,
Pablo 😁👍
