### ISSUE TITLE
Uso de beautiful soup y rematch

### ISSUE THREAD

**Issue by nencinav** [IIC2115/Syllabus#77]
Hay que llenar la tabla con 2 nuevas columnas.¿Hay que obtener una con beautiful soup y otra con rematch o cada info conseguida debe ser obtenida utilizando ambas?

**Comment by nencinav** [comment]
Porque si no me equivoco, sirven para lo mismo. Buscar dentro de un texto.

**Comment by pcseisdedos** [comment]
La idea es ocupar ambos, te recomiendo revisar la [ayudantía](https://github.com/IIC2115/Syllabus-2020-2/blob/master/Ayudant%C3%ADas/Ayudant%C3%ADa%204/Web_Scraping.ipynb) del semestre pasado.

Saludos,
Pablo 😁👍
