### ISSUE TITLE
Duda sobre CountryCode como pk

### ISSUE THREAD

**Issue by Giovinco24** [IIC2115/Syllabus#77]
Hola, estoy realizando una tabla Country y quiero que el CountryCode sea primary key, ya que este digito no se deberia repetir en la tabla. Sin embargo, me esta tirando error de que no es unico (UNIQUE constraint failed) lo que me parece muy raro, porque en el enunciado dice que es el identificador unico de cada pais.

**Comment by jgfarias** [comment]
Puede ser porque el CountryCode es único para cada país, pero en la tabla "city" un mismo CountryCode se repite tantas veces como ciudades tenga el país (por ejemplo, el CountryCode de Chile es único en la tabla, pero se repite para ciudad que sea de Chile). Entonces, es único del país, pero no es único de cada instancia de la tabla

**Comment by Giovinco24** [comment]
Pero al poner SELECT DISTINCT no deberia estar solucionando  ese problema?

**Comment by Jamidd** [comment]
SELECT DISTINCT x, y, j te entrega todas las tuplas (x, y, j)  donde ninguna tupla es igual a otra. Sin embargo, si pueden haber dos tuplas que tengan el mismo elemento en j (si j no es primary key única, acuerdate que tambien se pueden tener dos o mas columnas como primary key). 
Saludos,
Jaime.
