### ISSUE TITLE
Pregunta misión 4, c)

### ISSUE THREAD

**Issue by jekipreos** [IIC2115/Syllabus#78]
En la misión 4c) se pide ordenar las 5 regiones mas ricas del mundo de forma ascendente, indicando el porcentaje de cada uno de sus usos de suelo, pero ordenando también estos por algún criterio por definir. No entiendo cómo se puede ordenar ese ranking de acuerdo a dos criterios, ya que, por ejemplo, si ordeno esas regiones de manera ascendente pero después las trato de ordenar ascendentemente por su porcentaje de suelo forestal, el orden inicial probablemente va a cambiar y no van a quedar ordenadas por riqueza.

**Comment by Jamidd** [comment]
Puedes dejar hardcodeado el orden de los porcentajes. Se pueden ordenar dos columnas simultáneamente `ORDER BY col_1 col_2` pero en este caso no tiene mucho sentido, ya que perderías el orden de los valores y no sería posible saber que es que. 
Saludos, 
Jaime

**Comment by jekipreos** [comment]
Hola, perdón pero no me queda muy claro lo que tengo que hacer... no entiendo tan bien lo que es hardcodear y de lo que averigüé tampoco entiendo cómo me serviría para lograr el objetivo. ¿Cómo hardcodeo algo así? ¿Modifico la base de datos? E incluso si hiciera eso, de todas formas el orden según los porcentajes hardcodeados podría hacer que el otro orden cambie o no? O la gracia es hardcodear los usos de suelo encontrando un orden particular tal que el orden por riqueza no cambie?

**Comment by jekipreos** [comment]
Ok, gracias!
