### ISSUE TITLE
Problema 'avanzado'

### ISSUE THREAD

**Issue by kdcarreno** [IIC2115/Syllabus#78]
No entiendo del video explicación . Otra forma de explicar este problema?

**Comment by kdcarreno** [comment]
Creo que entendi . Para n = 5 el output sería 3-1-4-5-2 ? me lo confirman porfa para saber si entendí bien

**Comment by FGarridoV** [comment]
Creo que con el enunciado y el video ya puedes saber si esta correcto o no. Sigue la misma lógica para comprobarlo.

**Comment by kdcarreno** [comment]
Profesor @FGarridoV 
Si entendiera el enunciado y me quedara claro el video no preguntaría.

**Comment by FGarridoV** [comment]
Si decimos más estariamos entregando pistas de su solución.
