### ISSUE TITLE
Lab 1b M1

### ISSUE THREAD

**Issue by Tomas-GrayD** [IIC2115/Syllabus#78]
Hola pablo! tengo la siguientes dudas:
1-  para esta pregunta,  estaría bien usar request por ejemplo para obtener datos por cada registro de genero como dijiste en otra issues (usando tambien la libreria rematch), y después insertar esos datos obtenidos en nuevas columnas de las tablas ya creadas, lo pregunto porque personalmente no he encontrado otra forma mas eficiente de realizar esta misión. 
2- se puede usar la libreria ssl y urlib.request que esta en la materia de web scraping? esta se utilizaría  solo para obtener el código de la pagina web.
Estaré atento.

Saludos.

**Comment by pcseisdedos** [comment]
Hola, sip..  puedes hacer ambas cosas que preguntas.

Saludos,
Pablo 😁👍

**Comment by Tomas-GrayD** [comment]
Hola pablo! me surgió otra duda:
una vez ya obtenido los datos y creado las columnas para insertar esos datos, como inserto los datos a una columna especifica?
pensé en usar como sale en los apuntes " INSER INTO nombre tabla (nombre columna) VALUE (dato)" pero no me funciona.

Saludos.

**Comment by pcseisdedos** [comment]
Hola Tomás, en principio el [`insert into`](https://www.sqlitetutorial.net/sqlite-insert/) debiera funcionar, quizás te faltó crear la nueva columna a la que le quieres insertar los datos  (no recuerdo si es necesario hacerlo o no en sqlite3). Puedes investigar al respecto, [`ALTER TABLE`](https://sqlite.org/lang_altertable.html) con un `ADD COLUMN` o también [`UPDATE`](https://www.sqlitetutorial.net/sqlite-update/) debieran funcionar, tienes que tener cuidado porque hay algunos comandos que no son soportados por sqlite3.

Saludos,
Pablo 😁👍
