### ISSUE TITLE
Pregunta L03, M3d

### ISSUE THREAD

**Issue by jgfarias** [IIC2115/Syllabus#79]
En esta pregunta, ¿tengo que entregar (output) UNA sola ciudad, que tiene la menor cantidad de hablantes (para cualquier idioma)?, ¿o tengo que entregar, para cada idioma, la ciudad en que hay menos hablantes de ese idioma?

**Comment by Jamidd** [comment]
Voy a asumir que te refieres a la M3d. 
En caso de que exista solo una que tenga la menor cantidad, entrega esa.
En caso de haber mas de una (con la misma cantidad), entrega todas estas. 
Saludos,
Jaime.

**Comment by FernandaNavarroE** [comment]
Hola!! la verdad es que tengo la misma duda y sigo sin entender a qué se refiere la pregunta :( 
Tengo que considerar la cantidad de idiomas que tiene cada ciudad y relacionarlas con su población? (asumiendo que se distribuye de forma homogénea) o debo hacerlo por cada uno de los lenguajes? 
Agradecería que lo explicaras en más detalle porfis :(
Saludos!!

**Comment by FGarridoV** [comment]
Debes identificar las ciudad en donde un idioma (cualquier idioma) se hable lo menos posible (pero al menos uno). Y si hay más de uno, especificar como lo indica @Jamidd.

**Comment by Jamidd** [comment]
Cada país tiene una distribución del uso de cada idioma.
Asume que esa misma distribución aplica para cada ciudad de ese país. 
Con esto puedes determinar cuantas personas en cada ciudad hablan que idioma.
Encuentra la ciudad que tenga la menor cantidad de personas hablando un idioma en particular, con la condición de que tiene que ser mas de 1.
Se entiende? Sino avisame. 
Saludos,
Jaime
