### ISSUE TITLE
Duda problema 2a

### ISSUE THREAD

**Issue by vgrivera** [IIC2115/Syllabus#79]
Hola,
Con lo que sale en el enunciado y lo que han dicho en issues (pregunta 2a. de stacks), no me queda claro que es lo que se debe retornar: una lista de número o una secuencia de números? 

Gracias

**Comment by Jamidd** [comment]
En el enunciado aparece una lista de números (en un cierto orden especifico). Eso es lo quede debe entregar como output tu función.
 
Jaime Middleton
