### ISSUE TITLE
Uso de librería Heap L1a

### ISSUE THREAD

**Issue by DanielCarrascoFalcon** [IIC2115/Syllabus#79]
Es posible utilizar la librería [heap](https://docs.python.org/3/library/heapq.html) para utilizarlos en la solución??

**Comment by pcseisdedos** [comment]
¿En qué pregunta?

**Comment by DanielCarrascoFalcon** [comment]
Pregunta III, ordenamiento de evaluaciones!

**Comment by pcseisdedos** [comment]
Ok, puedes usar heapq en esa pregunta.

Saludos,
Pablo 😁👍
