### ISSUE TITLE
Duda output datos_anden()

### ISSUE THREAD

**Issue by AndresNavarrete** [IIC2115/Syllabus#8]
Hola,

tengo la siguiente duda: Esta función debe retornar (1) cantidad de personas totales que llegaron al anden y (2) tiempo promedio de llegada de cada tren.¿ En (2) te refieres al tiempo entre trenes consecutivos?  

Además, puedes darme un ejemplo de los input de la función? Para ver el nombre del andén.

Gracias

**Comment by Hernan4444** [comment]
Hola,

Sobre la primera pregunta, pueden haber varias interpretaciones:
- Tiempo desde que un tren empieza a funcionar hasta que llega a la estación
- Tiempo desde que el tren sale de esa estación hasta que vuelve a ella.
- Tiempo desde que sale un tren y llega el siguiente.

Y a todos esos tiempos registrados, calcular el promedio. Por lo tanto preferimos dejar a tu criterio cual interpretación usar.

Sobre la segunda duda, hay en el enunciado (página 7).

Saludos ✌️
