### ISSUE TITLE
no pude instalar jupyter

### ISSUE THREAD

**Issue by dilanlopeg** [IIC2115/Syllabus#8]
luego de instalar pyhton y asegurandome de que la casilla de agregar al path estaba seleccionada procedi a intalar jupyter desde la cmd, luego de descargarse me arrojo los soguientes mensajes: 
WARNING: The script pygmentize.exe is installed in 'C:\Users\DILAN LOPEZ\AppData\Roaming\Python\Python37\Scripts' which is not on PATH.

intente ejecutar jupyter notebook pero me dice que no se reconoce el comando

**Comment by dilanlopeg** [comment]
ya encontre la solución, en windows es la siguiente:

    En Buscar, busque y seleccione: Sistema (Panel de control)
    Haga clic en el enlace Configuración avanzada del sistema.
    Haga clic en Variables de entorno. En la sección Variables del sistema, busque la variable de entorno PATH y selecciónela. Haga clic en Editar. Si no existe la variable de entorno PATH, haga clic en Nuevo.
    En la ventana Editar la variable del sistema (o Nueva variable del sistema, aqui se debe agregar la direccion en donde se encuentra jupyter), . Haga clic en Aceptar. Cierre todas las demás ventanas haciendo clic en Aceptar.
    Vuelva a abrir la ventana del indicador de comandos y ejecute el código de java.

**Comment by FGarridoV** [comment]
Perfecto! Así se soluciona, hay otro hilo con lo mismo #4

**Comment by xayovaniniz** [comment]
Hola! no entendí bien cual es la dirección que deberíamos agregar en el path, tendría que ser en el user? Gracias de antemano! @dilanlopeg

**Comment by FGarridoV** [comment]
@xayovaniniz Depende, si instalaste python como en el tutorial (en el sistema), entonces debes modificar el PATH del sistema, agregando la localización de jupyter. Si lo instalaste en tu usuario, bastaría modificar el PATH del usuario.

**Comment by fialvarado** [comment]
En este caso, como puedo saber donde quedó exactamente guardada la dirección de jupyter?? Para copiarla en el path digo yo..

**Comment by FGarridoV** [comment]
@fialvarado primero debes saber dónde esta Python. Lo instalaste en el sistema? o en el usuario?. Debes primero paréate en esa carpeta y luego, a partir de esa buscar: site-packages, dentro de esta ultima debiera estar Jupyter. 
Francisco

**Comment by fialvarado** [comment]
Aquí tengo la carpeta de python, pero no aparece nada relacionado a jupyter en site-packages. 

De todas formas logré abrir jupyter mediante el comando en terminal "python -m notebook", pero no sé si me permitirá después acceder a librerías u otras cosas instaladas en el computador (al no saber exactamente donde están guardados). 

![Captura de pantalla (162)](https://user-images.githubusercontent.com/69522692/90421935-22aa9480-e088-11ea-9c8b-7c96866ce1e4.png)

**Comment by FGarridoV** [comment]
@fialvarado No te preocupes, si puedes abrirlo no vas a tener problemas. Si quieres instalar una librería basta que utilices lo siguiente para instalar librerías:
pip install .. (en windows) ó
ppi3 install ..(en Mac)

Saludos
