### ISSUE TITLE
Preguntas Consultas A1

### ISSUE THREAD

**Issue by plourido** [IIC2115/Syllabus#8]
Holaaa, que tal??, espero que se encuentren bien y que tengan una buena tarde. Tengo una duda respecto a las consultas que debemos hacer en la actividad. Estas consultas se responden independientemente cada una? Es decir ocupo el json original para responder cada una? Se los pregunto ya que en la ultima consulta agrega personas a la estructura. Entonces eso podría afectar las respuestas de todas.

Ademas les quería preguntar si en cada consulta al momento de crear la función, le puedo entregar la estructura de dato utilizada también, como variable? 
Muchas gracias

**Comment by RonaldoSosa** [comment]
Hola. Las consultas son independientes una de otra, es decir, el resultado de una no depende del resultado de otra. El archivo entregado es para indicarles el formato que tendrán los archivos para su corrección y para que prueben su código. El código entregado debiese ser generalizado para así responder las consultas de los archivos con los que serán probado, los cuales tendrán el formato entregado del archivo personas.json.
