### ISSUE TITLE
L03 M4 b)

### ISSUE THREAD

**Issue by clementeramirez** [IIC2115/Syllabus#80]
Hola! para la M4 b), ordene a las regiones que mas contaminan en forma descendente, y puedo ordenar los paises que mas contaminan ascendentemente en cada region, pero no sé cómo limitar que sean solo 3 paises por region. hay alguna sugerencia de como hacerlo o existe algun comando que me pueda ayudar? muchas gracias

**Comment by Jamidd** [comment]
Échale un ojo a este link, te debería ayudar. http://www.schemamania.org/sql/
Saludos, 
Jaime
