### ISSUE TITLE
Problema 2b: Definir lista como cola

### ISSUE THREAD

**Issue by simonerenard** [IIC2115/Syllabus#80]
Hola!

En los apuntes de clases sale que en python se puede definir como una cola si ponemos lo siguiente:

cola = deque()

En mi caso me aparece el siguiente error:

NameError: name 'deque' is not defined

¿Esto tiene solución? o simplemente uso las colas como listas.

Gracias!

**Comment by mblejeune** [comment]
@simonerenard (soy solo otra alumna), quizas te falta importarlo!
con: from collections import deque al ppio del codigo!

**Comment by simonerenard** [comment]
@mblejeune gracias!!

ahí me funcionó!
