### ISSUE TITLE
Forma de evaluar las consultas

### ISSUE THREAD

**Issue by FernandaNavarroE** [IIC2115/Syllabus#81]
Hola!! Se me generó una duda respecto a la evaluación. En el enunciado se señala que el objetivo es desarrollar la consulta completamente, esto se refiere a que ya obteniendo el resultado que debería entregarme, obtendría las 0.5 decimas por consulta?? 

Saludos!!

**Comment by FGarridoV** [comment]
Vamos a revisar tanto la respuesta y la estructuración de tu consulta. Si responde a la pregunta, entonces tienes tu puntaje.
