### ISSUE TITLE
L1a p1 orden colores output (más de un output correcto)

### ISSUE THREAD

**Issue by Calomi** [IIC2115/Syllabus#81]
Para la pregunta 1 si el output correcto es 

`[0,1,1,2,0]`  
![image](https://user-images.githubusercontent.com/5609537/120878764-902e9f80-c58c-11eb-89ba-ea796c0c444c.png)

me surgió la duda de si el corrector automático considerará correcto los casos equivalentes a esta respuesta?, en caso que mi algoritmo pinte en un orden distinto.
por ejemplo:

`[0,1,1,0,2]`  
![image](https://user-images.githubusercontent.com/5609537/120878774-9cb2f800-c58c-11eb-9605-02a95b8dffe1.png)

`[0,2,2,1,0]`

`[2,1,1,2,0]`

o incluso que también son correctos pero no con la misma "estructura" de pintado

`[0, 1, 2, 2, 1]`
![image](https://user-images.githubusercontent.com/5609537/120878787-b6ecd600-c58c-11eb-80f8-0f78bab9d171.png)

**Comment by pcseisdedos** [comment]
Hola, el verificador que utilizaremos será algo del estilo:
1. Verificar si la cantidad de colores es mínima.
2. Pintar las estaciones según los colores definidos por el output.
3. Verificar que no haya posibilidad de confusión para los cristaloides.

Por lo tanto, los colores utilizados o el orden no debiera afectar.

Saludos,
Pablo 😁👍
