### ISSUE TITLE
Formato de entrega L03

### ISSUE THREAD

**Issue by FelipeUlloan** [IIC2115/Syllabus#81]
Estimados,
El programa como debe ser entregado? me refiero, debemos crear un programa "main" donde el ayudante ejecute nuestro código y vaya incluyendo inputs de acuerdo al problema que quiera revisar? o ellos editarán nuestro propio código en función del problema que quieran revisar? 
No sé si se entienda :(
Quedo atento! y muchas gracias!

**Comment by FGarridoV** [comment]
Como se menciono en clases, tu código debe tener implementado 5 funciones, una por cada problema que acepte los inputs definidos en el enunciado.

Saludos

**Comment by mblejeune** [comment]
Con que acepte los inputs ¿te refieres a que ustedes pondrán dentro de mi código la lista, número, etc a probar o no? Por ejemplo yo lo dejé de la forma: funcion(elemento) y elemento es una variable que cuenta dentro de mi código con una lista de ejemplo (para problema 1a) y la variable lista es la que ustedes deberán modificar para probar distintos ejemplos, sin la necesidad de mi código tener un input en el que interactúa con el usuario, ya que esto te lo pregunté en clases y me dijiste que no era necesario crearlo con input. Gracias !

**Comment by FGarridoV** [comment]
Si, es como dices, me refiero con inputs a las variables que recibe tu función.

Esta bien como lo tienes.

saludos

**Comment by eescobarj** [comment]
@FGarridoV la función con la que probarán los inputs, es posible que llamen a otras funciones. Esto es posible aclararlo en el readme?
