### ISSUE TITLE
Duda Corrección

### ISSUE THREAD

**Issue by ValeriaHernandezB** [IIC2115/Syllabus#82]
Con respecto a la corrección de los problemas, en la clase del día lunes se dijo que las estructuras de datos mencionadas en cada problema eran sugerencias para desarrollar cada código. Sin embargo, en la introducción del enunciado dice: "Para obtener el máximo de puntaje por problema, estos deben ser solucionados usando los tópicos indicados en cada uno de ellos. De lo contrario, sólo obtendrán una parte pequeña del puntaje". Quería saber si se respetará lo que se dijo en la sala. Gracias!

**Comment by FGarridoV** [comment]
Si! Se respetará lo de la clase. Pero es importante que usen correctamente las estructuras.

Saludos
