### ISSUE TITLE
Tablas propuestas

### ISSUE THREAD

**Issue by Leda7** [IIC2115/Syllabus#82]
Hola, quería saber si es necesario crear las tablas que nos propusieron denuevo, porque yo solo inserte los datos en las tablas propuestas.

**Comment by martinchino77** [comment]
Misma duda

**Comment by Jamidd** [comment]
Las tablas que subimos son un template en el que pueden basarse pero ustedes tienen que crear sus propias tablas. 
Saludos, 
Jaime

**Comment by FranciscaUlloa** [comment]
Osea no puedo llegar e insertar los datos en esas tablas? D: porque yo también solo hice eso y he estado trabajando con esas tablas para mis misiones ya

**Comment by FranciscaUlloa** [comment]
Igual puse como se deberían crear esas tablas, pero no las cree, sino que las deje comentadas. Puedo dejarlo asi?

**Comment by paulavonbrand** [comment]
hola!! yo tambien inserte la info en las tablas vacías que nos entregaron y he trabajado todo en base a ellas.

**Comment by pelayouc** [comment]
yo igual inserté la info en las tablas vacías

**Comment by FranciscaSepulveda** [comment]
yo igual la info la inserte en las tablas vacías, ya que había creado mis tablas propias y eran muy parecidas a la que subieron como template. Que hago al respecto?

**Comment by Jamidd** [comment]
Pueden ocuparlas y llenarlas pero tienen que dejar comentado el código que las crearía. Parte de la M1 es determinar que son capaces de crear sus propias tablas. No es necesario que se ejecute el código que crearía las tablas, pero tiene que por lo menos estar escrito y comentado.
Disculpen la confusión. 

Saludos, 
Jaime
