### ISSUE TITLE
Duda utilización for en Problema 1

### ISSUE THREAD

**Issue by mblejeune** [IIC2115/Syllabus#83]
Hola!  es posible usar una estructura de este tipo ?

for elemento in lista : 
----if una condicion sin in:
--------if algo in lista:
----else:
--------if algo in lista: 

ya que tengo entendido que se pueden usar máximo 2 for anidados que ese seria usar un for y un in (como en la estructura que escribí), pero dado que acá se usa o un in o el otro in dependiendo de mi condición para el for, me surgió la duda de si se podría utilizar. Esto de todas maneras se podría hacer con dos for, pero en términos de orden prefiero hacerlo así. 
Muchas gracias!!

**Comment by FGarridoV** [comment]
La restricción es no usar 3 iteraciones anidadas sobre toda la lista. Por nido se refiere a que estén en una cadena de llamados de tamaño 3.

Con esto, espero puedas resolver tu duda

**Comment by arielczerny** [comment]
@FGarridoV si es que entendi bien, se puede tener un for y luego fuera dos for más por separado cierto? EJ:
 
for i in algo:
       hacer algo

for j in algo:
      for j in algo:
             hacer algo

Eso esta correcto no?, porque sigue siendo O(n + n^2) = O(n^2)

**Comment by arielczerny** [comment]
se pueden tener un for solo y luego dos for enlazados? Según lo que tengo entendido es O(n + n^2) = O(n^2)

**Comment by pcseisdedos** [comment]
@arielczerny Exacto, la idea es que sea menor o igual a O(n^2)
