### ISSUE TITLE
ediciones a la base de datos 

### ISSUE THREAD

**Issue by rpmalonnek** [IIC2115/Syllabus#83]
al momento de agregar una aplicacion, el diccionario entregado no tiene informacion sobre el tipo de app (free or paid) , tampoco sobre Content Rating, esos valores los agrego de forma arbitraria ?

**Comment by Hernan4444** [comment]
Hola, sobre el tipo de app, si se indica el precio con lo cual se puede concluir dicha información. Sobre Content Rating, no quedó especificado correctamente. Así que queda a tu criterio.
