### ISSUE TITLE
ID aplicaciones

### ISSUE THREAD

**Issue by nnahumada** [IIC2115/Syllabus#84]
es necesario que la tabla de aplicaciones tengan un ID por aplicación(que creemos uno para cada aplicación) , o la llave puede ser  formada por el nombre y otros atributos que la hagan única( con UNIQUE)?

**Comment by Hernan4444** [comment]
Hola, puedes hacerlo de otra forma, debes justificar adecuadamente porque eso es razonable VS usar un ID como se solicita en el enunciado. Si tu justificación es correcta, no hay problema, pero si no es adecuada, creo que es mejor hacerlo como dice el enunciado.

Saludos ✌️
