### ISSUE TITLE
Ciudades sin distrito

### ISSUE THREAD

**Issue by FernandaNavarroE** [IIC2115/Syllabus#84]
Hola!! Hay algunas ciudades que no tienen registrado ningún distrito. Sin embargo, personalmente había relacionado los distritos con el país al que pertenecen, por lo que de igual forma se me genera una Id para ese distrito en particular, que pertenece solo a ese país, pero que no tiene nombre. Esto genera, que en el caso de que en un mismo país hayan más de 1 una ciudad que no tiene registrado un distrito, se asume que pertenecen al mismo distrito sin nombre.
Respecto a lo anterior, me causó la duda en la consulta M4 a) si me convendrá considerar aquellos distritos, que de cierta forma no existen, en mi ranking? o solo considero aquellos que realmente existen? o queda a mi criterio? ajjsjsjd

Saludos!!!

**Comment by FGarridoV** [comment]
Hola, Efectivamente queda a tu criterio siempre y cuando sea correcto. Por ejemplo, no es correcto decir que dos ciudades siempre van a pertenecer al mismo distrito "sin nombre". Por eso, es bueno que tomes tus decisiones, pero siempre con criterio.
