### ISSUE TITLE
Consulta get info

### ISSUE THREAD

**Issue by CristobalCaroF** [IIC2115/Syllabus#85]
En el enunciado dicen que tenemos que seguir el formato que ahi sale para el diccionario que entrega la consulta get_info ¿la información tiene que ser solamente la que sale en el ejemplo o tiene que ser toda la información de la aplicación? o sea, ¿es necesario ignorar todo lo que no sea name, categoria, rating, reviews, size e insalls?

**Comment by fagomez2** [comment]
Hola Cristobal! Si hay información que consideres relevante agregar en el método `get_info(app)`, puedes hacerlo (justifica tu decisión en el Readme). Mi recomendación es que no te compliques y devuelvas solo lo que que te piden en el ejemplo. Saludos!
