### ISSUE TITLE
¿Cómo puedo hacer para aplicar un WHERE solo a una columna de mi SELECT?

### ISSUE THREAD

**Issue by pelayouc** [IIC2115/Syllabus#85]
Por ejemplo si tengo algo así:
SELECT DISTINCT C...., COUNT (*) as Total, COUNT (*) as Cantidad FROM ... GROUP BY ...

Y quiero que mi segundo COUNT, es decir, mi tercer SELECT cuente filas solo bajo cierta condición, intenté hacer esto coun un WHERE, pero esta condición se me aplica para mis tres columnas (C.... y ambos COUNT).

**Comment by FGarridoV** [comment]
La función COUNT() cuenta las filas en la tabla resultante. Si deseas realizar más de un COUNT() entonces te sugiero que aparezca uno por cada consulta anidada. Es decir, definas una consulta y en ella cuentes y otra para contar otra cosa.

**Comment by pelayouc** [comment]
Es que yo para mi WHERE final necesito de los dos COUNT y si los anido pierdo el acceso a ellos en la última consulta ("la de más afuera")
