### ISSUE TITLE
Problema 3 L04

### ISSUE THREAD

**Issue by vnramirez** [IIC2115/Syllabus#85]
Hola!

He intentado replicar el ejemplo para entender el problema pero me da 6, no 8.

[1,1,2,4,2]
1) el par (1,1): sí
2) el par (1,2): sí
3) el par (1,4) sí
4) el par (1,2) no
5) el par (1,2) sí
6) el par (1,4) sí
7) el par (1,2) no
8) el par (2,4) no
9) el par (2,2) sí
10) el par (4,2) no

Qué estoy entendiendo/haciendo mal?
Saludos y gracias de antemano.

**Comment by kdcarreno** [comment]
todos los  (1,2) dan. En algunos casos te quedará 1*2 <=2 y en otros 1*2<=4. 
las únicas combinaciones que no funcionan son los 2*4
