### ISSUE TITLE
Como Obtener 5 Mejores de Cada Equipo

### ISSUE THREAD

**Issue by alejoeyzaguirre** [IIC2115/Syllabus#86]
Hola! Llevo bastante rato pegado en lo mismo y no logro filtrar los 5 jugadores más veteranos de cada equipo. Feliz si me pueden dar alguna sugerencia o algo por el estilo...

Gracias!

**Comment by pelayouc** [comment]
me sumo a la duda del compañero

**Comment by pelayouc** [comment]
es que si ocupo el ORDER BY Age DESC LIMIT 5 me tira como los jugadores más viejos de la liga pero yo quiero que me retorne los 5 más viejos por equipo

**Comment by dilanlopeg** [comment]
me sumo a la duda, 2 horas pensandolo:/

**Comment by Jamidd** [comment]
Revisen este link, los debería poder ayudar http://www.schemamania.org/sql/ :wink: 
Saludos,
Jaime
