### ISSUE TITLE
Ejemplo problema 2 - Gremlins

### ISSUE THREAD

**Issue by cjvergara1** [IIC2115/Syllabus#86]
Hola! Puede ser que el ejemplo del problema 2 este incorrecto? Si se parte con la lista [6,5,8,4,7,10,9], luego en el día 1 se convierten en demonios el 8 y el 7, en el día 2 solamente el 10, luego en el día 3 se convierte en demonio el 9, quedando la lista [6,5,4] por lo que no se crean más demonios. Así, la respuesta es "desde el día 4" y no desde el día 3 como aparece en el enunciado.

**Comment by isalvador95** [comment]
Tuve la misma duda que tú, pero llegué a la conclusión de que el 10 se incluye también en el día 1 porque come más que su predecesor que sería el 7, por más que el 7 se haya convertido en demonio el mismo día. Ahí sí se cumple que la respuesta es 3. Si algún ayudante o profesor puede confirmar esto sería bacán.

**Comment by Mcarriagada** [comment]
Yo pensé lo mismo que @cjvergara1 y desarrolle mi programa en base a eso, ya que si desaparece el 8 y el 7, el 10 ya no tiene a su izquierda al 7, porque ya desapareció. Espero que se pueda poner como supuesto ya que ya lo realizé de esta manera.

**Comment by idmdvan** [comment]
Hola,

La regla dice que la comparación se hace _al final del día_. En ese momento del día 1 y para la instancia de la que hablan, los gremlins en las posiciones 3, 5, y 6 han comido más que el de su izquierda (8, 7, y 10, respectivamente), por lo que se convierten en demonios. 

Es decir, la comparación la haces en un mismo instante, suponiendo que todos los gremlins que vienen del día anterior, siguen.

Espero que quede más claro, 

Daniel.
