### ISSUE TITLE
Citar códigos

### ISSUE THREAD

**Issue by isalvador95** [IIC2115/Syllabus#87]
En la primera clase el profesor mencionó que podíamos utilizar códigos encontrados en internet bajo ciertas consideraciones, siempre y cuando los citáramos. Estas citas deben ir en el Readme o en el código mismo?

**Comment by idmdvan** [comment]
Hola, 

Mejor en el código, así se entiende qué líneas son extraídas de Internet. No olvides poner el URL del código. Vale la pena recordar que la idea no es copiar y pegar código, sino que sea una fuente de ideas para encontrar soluciones al problema propuesto... lo ideal es que filtren lo que les sirve, y lo adapten a su algoritmo.

Saludos, 

Daniel.

**Comment by asnunez1** [comment]
Hola! En el enunciado del Lab 4 dice: **"No es necesario que utilicen sólo las estructuras de datos descritas en el material de clases, pueden utilizar cualquier estructura que facilite la resolución del ejercicio"**. Mi pregunta es: Si yo encontré en internet info de un código que me ayuda, en parte, a hacer un ejercicio de la tarea, pero esta parte de código es de algo que no hemos visto en clases, ¿Puedo usarlo para resolver un ejercicio, complementándolo con materia del capítulo 2? y en el read me. citar la página de internet con el código en que me apoyé para resolverlo? Gracias! :)
