### ISSUE TITLE
"3 Points" P03

### ISSUE THREAD

**Issue by cristobalverdugo** [IIC2115/Syllabus#88]
Hola!

Me di cuenta imprimiendo los valores de la columna 3Points que muchos valores son del tipo "None" cuando debiese ser un INTEGER según la información de las tablas. No sé si esto es un error mío, de la base de datos, o si debo tomar este "None" como si fuese un valor igual a 0.

Muchas Gracias!

**Comment by Jamidd** [comment]
Tomalo como creas que sea mejor y dejalo explicitado en un comentario en el código. Muchas veces ocurre que existen None's o Null's en bases de datos y tienes que manejarlos. 

Saludos,
Jaime

**Comment by miflores1** [comment]
Hola estoy tratando de usar
 SELECT 3Points
FROM State 
WHERE 3Points >0
ORDER BY Player
Pero no me acepta el 3Points y no se porque trate de arreglarlo de varias maneras pero todo a fracasado llevo en esto ya casi 2 horas y me estoy desesperando
