### ISSUE TITLE
Duda de eficiencia

### ISSUE THREAD

**Issue by simonerenard** [IIC2115/Syllabus#88]
Hola a todos,

¿La eficiencia cómo será medida?

Se que tiene que durar menos de 1 seg, pero esto depende del tamaño del input...

¿Nos podrían decir cual es el largo máximo que van a poner como inputs? (Por lo menos para los problemas 1 y 3)

En la primera pregunta, se dijo que no se pueden ocupar más de 2 for anidados, esto corre para las preguntas 2 y 3 también cierto?

**Comment by isalvador95** [comment]
Creo que sí corre lo de ocupar los for anidados al decir que no utilicemos fuerza bruta..

**Comment by halobel** [comment]
Revisen por favor esta [issue](https://github.com/IIC2115/Syllabus/issues/89#issuecomment-484557783) por el tema del tiempo y extensión de la lista. Lo de los for anidados va efectivamente por el lado de la fuerza bruta. Es posible que en algunos casos se necesitan más de dos for aninados, pero eso dependerá del problema. Lo importante, es que las soluciones no se basen en probar todos los casos posibles (eso es a lo que nos referimos con fuerza bruta en este caso).
