### ISSUE TITLE
Repetición de contratos por jugador

### ISSUE THREAD

**Issue by jicamelio** [IIC2115/Syllabus#89]
Que tengo que hacer con la repetición de los datos de los jugadores cuando tienen distintos contratos por el mismo equipo pero los puntos se repiten para cada uno de estos contratos. Por ejemplo en el caso de la foto, Brillante Weber tiene 3 contratos con TOR y se repiten los puntos de cada uno de ellos.

![Captura de Pantalla 2020-10-15 a la(s) 18 00 38](https://user-images.githubusercontent.com/69480558/96185369-2b94d680-0f10-11eb-9c61-8fc3aa46b1da.png)

**Comment by Jamidd** [comment]
Ve tu como crees que es mejor manejarlo (algo razonable) y dejalo explicitado en un comentario en el código. 
Saludos,
Jaime.
