### ISSUE TITLE
Diagrama del modelo de la base de datos.

### ISSUE THREAD

**Issue by memadrid** [IIC2115/Syllabus#89]
Hola! Quería saber si es posible que suban algún formato respecto al diagrama del modelo de datos, considerando que hay varios formatos (por ejemplo, ¿es necesario que se especifique el tipo de dato?)
Gracias.

**Comment by Hernan4444** [comment]
Hola, aquí hay un ejemplo de un diagrama del modelo de datos

![](https://upload.wikimedia.org/wikipedia/commons/f/f6/Ejemplo_Diagrama_E-R_extendido.PNG)

Como puedes notar, esto diferente entre las tablas de entidades, las tablas que unen entidades e indica los atributos de cada tabla.
