### ISSUE TITLE
Video Introducción al curso- Dirección para acceder a los libros y notas?

### ISSUE THREAD

**Issue by CarlosDanielD** [IIC2115/Syllabus#9]
Solicito la dirección para acceder a los libros del curso a los que se hace referencia en el minuto 30:18 del video, donde mismo se comenta más adelante que se publican las notas

**Comment by pcseisdedos** [comment]
No se bien a que te refieres, pero esa información se encuentra en el [SIDING](https://www.ing.uc.cl/#SIDING).

¡Saludos!
Pablo 😁👍

**Comment by CarlosDanielD** [comment]
Correcto.
Saludos
