### ISSUE TITLE
Fechas erróneas de actividades de capítulos 4 y 5

### ISSUE THREAD

**Issue by galvarado1** [IIC2115/Syllabus#9]
Hola,

Las fechas que aparecen en el programa para las actividades de los capítulos 4 y 5 son las mismas que las de los capítulos 2 y 3.

Saludos

**Comment by pcseisdedos** [comment]
Gracias por notificar el error, acabo de actualizar el programa del curso. De todas formas, en la primera clase el profesor agregó una slide con el cronograma, ahí las fechas son correctas.

Saludos,
Pablo 😁👍
