### ISSUE TITLE
Pregunta A1 consultas

### ISSUE THREAD

**Issue by mbertin1** [IIC2115/Syllabus#9]
En la consulta del nucleo familiar, si por ejemplo el maximo es de 7 personas pero existen dos familias diferentes que son de 7, debemos mostrar ambas o podemos asumir que es solo una?

**Comment by RonaldoSosa** [comment]
Hola. Bastaría con mostrar  solo una familia, pero deberían indicar que solo mostraran una, en caso de haber más.
