### ISSUE TITLE
Horarios

### ISSUE THREAD

**Issue by ravielr** [IIC2115/Syllabus#9]
Hola

Quería preguntar acerca de la función horarios ¿A qué se refiere con menor/mayor flujo de subida? Pues el flujo en la puerta siempre es 25pax/seg.
¿Podrían explicarlo más?

**Comment by FGarridoV** [comment]
Corresponde al flujo total o afluencia de personas que ingresan al tren. 

Es decir, deberas reconocer la estación que tenga la mayor y menor afluencia de personas que ingresan a los trenes luego de un día.

Saludos
Francisco
