### ISSUE TITLE
Sobre la generación de viajes y modos

### ISSUE THREAD

**Issue by vnramirez** [IIC2115/Syllabus#9]
Estimados,

Cuando empiezo un turno (el primer turno, digamos) y genero viajes, por ejemplo en las vialidades de los bordes, los viajes que se generan son comodoro.exponencial(1)? O el resultado de esa función debo usarlo para recalcular los viajes generados?

Y otra duda; si se generan 2 viajes en una celda del borde que es de vialidad, se asume que ambos viajes generados se harán en el mismo modo, y para cada uno de estos viajes debo calcular la ocupación aleatoria? O esos dos viajes podrían ser en modos distintos, y con ocupaciones distintas? Por ejemplo, que un viaje sea en auto (con una ocupación de 3) y en la misma celda ser genere un viaje en bus (con ocupación de 30)?

**Comment by FGarridoV** [comment]
Estimado, tu primera pregunta esta resuelta en el issue #6.

Respondiendo tu segunda duda, a cada viaje se le debe determinar el modo y la ocupación. Por lo tanto, corresponde al ejemplo que das.

Saludos,
Francisco

**Comment by vnramirez** [comment]
Gracias!

No me quedó muy claro lo de la generación de viajes. Por ejemplo para las oficina se sabe que su tasa es de lambda = 0.333 viajes/turno. Significa que en cada turno, cada oficina va a generar comdoro.exponencial(0.333) viajes?
Pongo el ejemplo de la oficina en particular porque con esa tasa, el resultado int() de esa función va a ser 0 *casi* siempre.

Saludos y gracias nuevamente.

**Comment by FGarridoV** [comment]
Estimado, 

Como dije en el otro issue, la exponencial representa **tiempo entre eventos** para una llegada poisson, no es la cantidad eventos.

Te recomiendo buscar la distribución en wikipedia y familiazarte con la información que entrega.

Ademas, te recuerdo que en el enunciado se muestra que el parámetro es (1/Lambda) no Lambda.

Saludos,
Francisco

**Comment by Mcarriagada** [comment]
Hola, a mi no me queda claro que si por ejemplo, utilizo la funcion comodoro.exponencial(1) para poder ver cada cuantos turnos se genera un viaje en dicha celda, ¿Debo generar automaticamente dicha cantidad de viajes en el primer turno? Luego, cada tantos turnos, dado por la función comodoro.exponencial(1) generar otra cantidad de viajes segun lo obtenido. Esto ultimo es lo que entiendo, pero no se si lo estoy considerando correctamente.

**Comment by FGarridoV** [comment]
Te daré un ejemplos:

Si quieres precargar todo desde un comienzo, para cada generador de viajes puedes generar muchas instancias de la exponencial hasta completar el intervalo de simulación. Y luego en la simulación generar los viajes cuando se indique. 

Por otro lado, luego de cada generación de viajes, tomas una instancia de la exponencial y registras para generar el próximo viaje en esa cantidad de turnos
