### ISSUE TITLE
cantidad de fouls por jugador

### ISSUE THREAD

**Issue by paulavonbrand** [IIC2115/Syllabus#90]
Hola! en la pregunta 1, debo imprimir sólo por equipo y los fouls de los 5 jugadores mas viejos como (EQUIPO, FOULS JUGADOR 1, FOULS JUGADOR 2,FOULS JUGADOR 3, FOULS JUGADOR 4, FOULS JUGADOR 5) ? O también sus nombres?

**Comment by paulavonbrand** [comment]
ayuda porfavor

**Comment by Jamidd** [comment]
Tienes que retornar (equipo, cantidad total de fouls de los 5 jugadores con mas fouls).

Saludos,
Jaime

**Comment by paulavonbrand** [comment]
ahhh que buena!!! pensaba que además de eso había que desagregarlo por jugador
muchas gracias!!!
