### ISSUE TITLE
Repetición de floats en lista

### ISSUE THREAD

**Issue by ccornejon** [IIC2115/Syllabus#90]
Hola! quería saber si la lista que se entrega al problema 1 puede tener números repetidos o no. En base a esto depende el cómo genero la lista. Por ejemplo, si uso random.sample() genero una lista sin números repetidos, mientras que si ocupo un for para generar la lista aleatoria si se pueden repetir números, lo que influye mucho en el tiempo de ejecución de mi código.

**Comment by pcseisdedos** [comment]
@ccornejon En principio no hay restricciones de ese tipo para la lista inicial L, por lo tanto podría tener números repetidos, pero debes preocuparte de no retornar dos o mas veces el mismo trío pitagórico por usar el número que se repite para construirlo multiples veces.
Pablo.

**Comment by asnunez1** [comment]
Hola! Entonces por ejemplo en el Problema 1: Si yo pruebo pasándole una lista muy grande de 10^4, donde hay muchos números 3, 4 y 5 dentro de la lista. En este caso el output debe ser solamente 1 único trio [3,4,5] ?

**Comment by pcseisdedos** [comment]
@asnunez1 Exacto, ningún trio debe estar repetido.
Notar que [3,4,5] y [4,3,5] son el mismo trío. Por lo tanto no deben salir ambos como output.
