### ISSUE TITLE
Count by version

### ISSUE THREAD

**Issue by ravielr** [IIC2115/Syllabus#91]
Hola, quería saber si pueden explayarse un poco más con la definición de esta consulta, porque del enunciado no queda muy claro qué es lo que hay que hacer.

**Comment by nnahumada** [comment]
me sumo a la consulta, no entendemos en que momento ocupamos las fechas date_1 y date:2

**Comment by Rslagos** [comment]
+2. Tengo la misma duda!

**Comment by Hernan4444** [comment]
Hola, se mandó un aviso al respecto.
<img width="663" alt="image" src="https://user-images.githubusercontent.com/15641721/46918634-8b1b1d00-cfaa-11e8-9900-0493d9e106c4.png">

Ahí se especificó que hacer con las fechas y luego, para lo filtrado, contar cuantas aplicaciones hay por versión y para cada versión indicar también cual es la categoría mejor evaluada mediante el *raiting promedio*

Saludos ✌️
