### ISSUE TITLE
P03

### ISSUE THREAD

**Issue by dilanlopeg** [IIC2115/Syllabus#91]
hola, como puedo limitar la cantidad de resultados pero por categoria?, no se tengo una tabla que tiene una columna llamada fruta que contiene el nombre de cada fruta, como podria obtener no se, 3 resultados pero por fruta, por ejemplo 3 piñas 3 manzanas 3 naranjas

**Comment by Jamidd** [comment]
Échale un vistazo a http://www.schemamania.org/sql/. Te debiera poder ayudar. 
Saludos,
Jaime.
