### ISSUE TITLE
Pregunta 3 LAB 04

### ISSUE THREAD

**Issue by cmujicai** [IIC2115/Syllabus#91]
En la pregunta 3, las fichas pueden tomar valor 0 y negativos? o consideramos valores desde 1 en adelante?

**Comment by Jamidd** [comment]
En el enunciado sale que recibe números enteros. 
Según Wikipedia:
"Un número entero es un elemento del conjunto numérico que contiene los números naturales N = { 1 , 2 , 3 , 4 , ⋯ }, sus opuestos y el cero"

Jaime Middleton
