### ISSUE TITLE
Formato de entrega LAB 04

### ISSUE THREAD

**Issue by asnunez1** [IIC2115/Syllabus#92]
Hola! Quería saber si el formato de entrega para el Laboratorio 04, es el mismo de la semana pasada? ¿Debe ser una función por cada problema necesariamente? Muchas gracias!

**Comment by Jamidd** [comment]
Efectivamente.
Es una función por cada problema. 
En caso contrario no se considera la pregunta.

Jaime Middleton

**Comment by roaastudillo** [comment]
¡Hola!

¿A qué van con que no se considera? Por ejemplo, para la respuesta de los Gremlins, yo tengo 2 funciones, la primera la uso dentro de la segunda, pero al final solo la segunda me resuelve el problema de los Gremlins. No se si se entiende, ¿eso estaría mal? ¿Debo unirlo todo en una solo función, o no importa?

Saludos :)

**Comment by Jamidd** [comment]
Debe haber una función por problema. Si estas llaman a otras funciones auxiliares no hay problema.

La idea es que por cada test que queramos correr, solo debamos tener una linea de código.

Ej. ( si se que está mal la indentación)
def problema1(input):
a = func_aux_1(xx)`
   ...
   return resultado

def problema2(input):
   ...
   return resultado

.....

**Comment by roaastudillo** [comment]
Perfect, gracias!
