### ISSUE TITLE
Duda Sobre Colores en L04 III

### ISSUE THREAD

**Issue by vgrivera** [IIC2115/Syllabus#93]
Hola

En su enunciado dice que las fichas se deben poner en hilera inicial de color rojo y luego según tramo seleccionado pasan a ser Azules.

Mi pregunta es debo hacer una función para asignar estos colores, por lo que la lista tendría asociado Valor del Elemento y un Color, o esto no es necesario y solo selecciono tramo y realizo el proceso de calcular el producto y compararlo con el Valor Máximo, sin considerar los colores??
Estoy un confundida con esta pregunta.

Saludos

**Comment by pcseisdedos** [comment]
Lo que debes hacer es encontrar el número de pares (i, j) que cumplen la condición, el proceso parte desde el punto inicial (todas las fichas rojas) en todos los casos, por lo tanto siempre todas las fichas entre i y j serán azules.
No se si esto responde a tu pregunta.
Pablo

**Comment by vgrivera** [comment]
Mi  duda pasa, por que pensaba que yo debía asignarle color a cada ficha por medio de un for, por lo que  cada elemento quedaría con un color asociado,  pero lo que entiendo que solo debo preocuparme de generar el tramo de selección de elementos y con ellos obtener el máximo y realizar la operación del producto, entiendo que lo del color, es solo una referencia de diferenciar las fichas, el tramo seleccionado y el total de la lista.

Así lo he entendido, espero estar en lo cierto

Muchos saludos y muchas gracias.
