### ISSUE TITLE
Archivos a entregar

### ISSUE THREAD

**Issue by fjgonzalez5** [IIC2115/Syllabus#93]
Hola! No me queda claro qué archivos debemos entregar en nuestro repositorio. ¿Debemos llenar el main.py con las funciones realizadas? ¿Qué pasa en ese caso con las tablas creadas y el filtro de datos? Si este no es el caso, ¿podemos entregar un archivo que contenga toda la informacion, cumpliendo con el formato de las funciones?

**Comment by oaleiva** [comment]
Tenemos la misma duda

**Comment by memadrid** [comment]
¿Es necesaria la modularización? No lo hice /:

**Comment by Hernan4444** [comment]
En vista que varios pensaron que solo se debía entregar el main.py con todo junto. No vamos a exigir que esté modularizado. No obstante sería ideal que puedan dejar comentarios de las cosas que hace su código para entender que parte está filtrando, cual está creando las tablas y cuando ya empiezan las funciones pedidas.
