### ISSUE TITLE
Archivos de testeo para Lab 04

### ISSUE THREAD

**Issue by Amanriquez11** [IIC2115/Syllabus#94]
Estimados, seria ideal que se subieran archivos de testeo para comprobar si nuestras funciones son lo suficientemente eficientes o no.  Me parece que esta es la forma mas correcta para que nosotros probemos y vayamos iterando sobre nuestras funciones hasta encontrar un optimo en eficiencia adecuado.
Saludos

**Comment by halobel** [comment]
Hola @Amanriquez11, revisa por favor la siguiente [issue](url), donde se toca el tema de la medición de eficiencia. A modo de resumen, si tu solución no es de fuerza bruta (algo que deben ser capaces de notar uds.), basta con que generes instancias aleatorias de los problemas para medir la eficiencia. En esta materia no estamos interesados en que entreguen la versión más eficiente posible, sino que usen estructuras de datos para no caer en soluciones poco eficientes, como la fuerza bruta. Si tu solución no es de fuerza bruta, entonces puedes estar tranquilo.
