### ISSUE TITLE
formato .py P03

### ISSUE THREAD

**Issue by jtjara1** [IIC2115/Syllabus#94]
¿Cuál es el formato en el .py? Esto lo pregunto porque se supone que el .py no debe tener ejecuciones. Dicho esto, mis consultas de SQL las meto en diferentes funciones o simplemente las dejo para ejecutar?

**Comment by Jamidd** [comment]
No te preocupes por eso (eso si, el .py debe contener solo tu código y tus comentarios).  Si puedes dejarla separada y ordenadas te vas a ganar la apreciación del ayudante. 
Saludos, 
Jaime.
