### ISSUE TITLE
Informe latex

### ISSUE THREAD

**Issue by jcvukasovic** [IIC2115/Syllabus#95]
Hola! 
En el enunciado dice que el informe debe tener una "Justificación de por qué el modelo escogido es el adecuado para el problema y las consultas planteadas.
Debe basarse en los criterios de consistencia para la justificación"

¿Cuales son los criterios de consistencia?

Gracias!

**Comment by Hernan4444** [comment]
Hola, nos queríamos referir a las Restricciones de integridad.

Saludos ✌️
