### ISSUE TITLE
Taj Gibson

### ISSUE THREAD

**Issue by pelayouc** [IIC2115/Syllabus#95]
Me pasa con este jugador que en la tabla salaries solo está en MIN, pero en la tabla Stats está en TOT, CHI, OKS, no está en MIN, por lo cual no puedo hacer el "nexo" entre ambas tablas a la hora de hacerla en python

**Comment by Jamidd** [comment]
Decide tu como crees que es mejor manejar este problema (de manera razonable) y dejalo comentado en el código. 
Saludos, 
Jaime.
