### ISSUE TITLE
Dudas eficiencia y coordinación

### ISSUE THREAD

**Issue by icandrade** [IIC2115/Syllabus#96]
Hola, 
Probé mi código en otro computador con un procesador más potente que el mío, y al probar para los mismos inputs se demora mucho menos. Por lo tanto, podrían especificar como probarán el "1 segundo" que aparece en el enunciado, ya que como les comento varía según el computador. 
Me parecería muy injusto que penalicen mucho por esto, ya que no hay nada claro y todos tenemos computadores distintos. @halobel , @FGarridoV por favor responder a la brevedad! 
Por otro lado, les pido por favor que den la información de manera alineada entre ustedes. El profesor me dijo en clases que en la pregunta uno daba igual si se repetían los tríos, ya que eso no estaba especificado en el enunciado. Sin embargo, en una issue sale que NO pueden estar repetidos. Sé que eso se soluciona en una línea... pero que sus comentarios no estén alineados crea mucha confusión y retrasa la planificación de todos. 
Muchas gracias!

**Comment by halobel** [comment]
Hola @icandrade, en el enunciado se indica que lo único que no puede repetirse son los índices de los elementos en la lista, no se menciona nada sobre los tríos en si, por lo que no hay restricción sobre ellos. Ahora, independiente de esto, creo que vale la pena que analices si dejar que se repitan (o no) es algo que afecta el tiempo de ejecución de tu solución, por lo que que más que un desalineamiento entre nosotros, tómalo com un hint sumamente explícito de nuestra parte.
En relación al tiempo de ejecución, sin duda podríamos haber sido más explícitos en la especificación, pero la gran cantidad de variaciones posibles (largo del input, velocidad del computador, si el computador está enchufado o no, versión de Python, etc) hacen que sea mucho más práctico para todos definir un cierto límite, como 1s, y luego adecuar el caso base a este (tal como como está mencionado en esta [issue](https://github.com/IIC2115/Syllabus/issues/89#issuecomment-484557783)). Este límite evita además que las soluciones de fuerza bruta sean aceptadas, por lo que todos ganamos.

**Comment by mblejeune** [comment]
@halobel profesor, pero en ese caso ¿no dependerá del computador del ayudante que revise nuestras tareas el tiempo de ejecución ? Ya que puede variar entre computadores, entonces creo yo que la revisión si tiene distinta velocidad de computador el mío con el del ayudante (asumiendo la velocidad de este podría ser menor) sería injusta. Ya que además se ha planteado que al ejecutar nuestros códigos en un computador con mejor velocidad (si es que se dice así ya que no soy experta en computadores) el tiempo de ejecución del mismo código resulta ser menor, por lo que con nuestro mismo código el tiempo puede variar dependiendo del computador del ayudante que nos toque a cada uno que nos revise. ¿Cómo se hará esto para que sea igual y justo para todos? muchas gracias!

**Comment by halobel** [comment]
Vamos a utilizar el mismo computador para evaluar la parte de eficiencia, así que no te preocupes, será todo corregido con el máximo nivel de justicia posible.
