### ISSUE TITLE
arrays

### ISSUE THREAD

**Issue by kdcarreno** [IIC2115/Syllabus#97]
Creé 2 listas auxiliares que quiero que inicien igual y a medida que avance en el codigo ir modificando sólo una. Pero se me modifican ambas. Por qué pasa eso o cómo lo arreglo ? No me había pasado antes. dejo un ejemplo

lista = [1,2,3]
lista_n0 = lista
lista_n0.append('hola')
lista_n1 = lista
    
print(lista_n0, lista_n1)
[1,2,3,'hola'] [1,2,3,'hola']

**Comment by Sabarriga** [comment]
Hola @kdcarreno ! Puedes usar el método _copy_ que viene implementado en las listas, y ahí entiendo que debiera funcionar.

**Comment by halobel** [comment]
Efectivamente, al igualar dos listas, lo que se hace es generar una referencia. Dicho en otras palabras, hace que ambas listas apunten a los mismo datos, por lo que una manera de efectivamente copiar es usando el método copy.

**Comment by fagomez2** [comment]
Hola Karla! Acá hay otra forma de hacerlo además de con copy. Lo siguiente hace una nueva lista con los mismos elementos de la primera.
```
lista = [1,2,3]
lista_n0 = lista[::]
lista_n0.append('hola')
print(lista)
>>> [1,2,3]
print(lista_n0)
>>> [1,2,3,'hola']
```
