### ISSUE TITLE
Evaluación presencial lab 5

### ISSUE THREAD

**Issue by javiprado** [IIC2115/Syllabus#98]
Estimados, dado que según el calendario académico oficial de la universidad, no se pueden hacer evaluaciones o controles el día de mañana (22 abril) por ser el primer día luego de semana santa, me gustaría que se pronunciaran respecto a qué va a pasar con la evaluación presencial de mañana.
Quedo atenta :)

**Comment by halobel** [comment]
Hola @javiprado, efectivamente mañana no pueden hacerse evaluaciones, por lo que la entrega presencial no corre para mañana. Fuera de eso, todo sigue de la misma manera.
Saludos

**Comment by stlara** [comment]
Hola profesor, esto quiere decir que hoy no habrá evaluación ni por avance ni por asistencia?

**Comment by bombanex** [comment]
Tengo la misma dida que @stlara. Al no haber evaluación tampoco hay nota por asistencia?

**Comment by Mcarriagada** [comment]
También tengo la mism duda, hoy se evaluará algo?

**Comment by bombanex** [comment]
@halobel @fagomez2 ?
