### ISSUE TITLE
AYUDA P03 :c, NO ENCUENTRO MI SINTAX ERROR

### ISSUE THREAD

**Issue by jtjara1** [IIC2115/Syllabus#98]
Yo trabajo en la pagina https://sqliteonline.com/ para poder ver de manera inmediata los selects. Resulta que la pregunta 1 me corre perfecto en esa pagina, pero al llevarlo al notebook, me tira error de sintaxis y ya no se qué puede ser. Quiero destacar que para la pregunta 2 hice lo mismo, me corrió bien, lo pegue en el notebook y me resultó altiro, pero no esta pasando eso en mi pregunta 1 y me daría una lata enorme no tener ese puntaje cuando tengo la consulta hecha. AYUDAAAAAA

**Comment by rosariopenalabbe** [comment]
Yo tengo el mismo error de sintaxis, con un (, tambien llevo todo el día con eso y no lo he podido solucionar

**Comment by jtjara1** [comment]
Al menos déjenme adjuntarles un pantallazo de mi consulta con el resultado ,para que vean que esta hecho y así no pierda tanto puntaje. Ojalá no me bajen puntaje por formato si es que adjunto una foto :c.

**Comment by acdelgado1** [comment]
Me pasó exactamente lo mismo, probé mi código en 3 computadores distintos y en el último me funcionó (mismo código), no se por qué pasa y para el laboratorio estoy teniendo el mismo problema

**Comment by jtjara1** [comment]
Update:

Le mandé mi cuaderno a un amigo y lo pudo correr sin ningún problema. Si se les ocurre algún motivo del porqué funcionó en su computador y no en el mio, estaria bacán que lo digan.

**Comment by acdelgado1** [comment]
Me pasó lo mismo!! y para el lab tb necesito ocupar estos comandos y no se como lo hare :(

**Comment by rosariopenalabbe** [comment]
Hola! yo sigo con el mismo problema y no puedo avanzar en el laboratorio con  este error :( porfavor si alguien encuentra el error avisen :(((

**Comment by caespinoza5** [comment]
¡Hola!

Al menos en google colab se puede solucionar de esta manera:

1. Agregar dos celdas al inicio, una con el siguiente código:

```python
!wget https://www.sqlite.org/src/tarball/sqlite.tar.gz?r=release -O sqlite.tar.gz
!tar xzf sqlite.tar.gz
%cd sqlite/
!./configure
!make sqlite3.c
%cd /content
!npx degit coleifer/pysqlite3 -f
!cp sqlite/sqlite3.[ch] .
!python setup.py build_static build
!cp build/lib.linux-x86_64-3.6/pysqlite3/_sqlite3.cpython-36m-x86_64-linux-gnu.so \
    /usr/lib/python3.6/lib-dynload/_sqlite3.cpython-36m-x86_64-linux-gnu.so
```

Y otra con el siguiente código:

```python
import sqlite3
sqlite3.sqlite_version 
```

2. Ejecutar la primera celda. Puede que se demore un poco.

3. Una vez que termine de correr la primera celda, hay que ir arriba a `Runtime > Restart Runtime`.

4. De ahí ejecutar la segunda celda. Debería aparecer una versión superior a 3.25 (a mi me aparece 3.33).

5. En las celdas después de estas 2, las consultas que les funcionan en los sitios web debería funcionarles con google colab. No se olviden de cargar la base de datos también.

**Comment by acdelgado1** [comment]
Muchas gracias ahí me funcionó!! :)

**Comment by ndcamhi98** [comment]
Hola, hago lo de las instrucciones y me sale un 3.22, creo que el primer código no me esta funcionando bien, me sale:
/bin/bash: wget: command not found
tar: Error opening archive: Failed to open 'sqlite.tar.gz'
[Errno 2] No such file or directory: 'sqlite/'
/Users/nicolascamhi/Desktop/Progra/L03
/bin/bash: ./configure: No such file or directory
make: *** No rule to make target `sqlite3.c'.  Stop.
[Errno 2] No such file or directory: '/content'
/Users/nicolascamhi/Desktop/Progra/L03
/bin/bash: npx: command not found
cp: sqlite/sqlite3.[ch]: No such file or directory
python: can't open file 'setup.py': [Errno 2] No such file or directory
cp: build/lib.linux-x86_64-3.6/pysqlite3/_sqlite3.cpython-36m-x86_64-linux-gnu.so: No such file or directory

Ayuda, no he podido hacer las del lab sin esto

**Comment by pelayouc** [comment]
Saben como se arregla para Jupyter?
