### ISSUE TITLE
Dataset lab 5

### ISSUE THREAD

**Issue by CarlosCarvajalGallegos** [IIC2115/Syllabus#98]
Al descargar el dataset del lab 5, ¿como podemos cargar el .db en pandas, dado que como NO es un csv, no podemos leerlo directamente, como en el lab 4. Existe posibilidad que se pueda dar la base de datos en .csv y no en .db?
Saludos.
Espero su respuesta.

**Comment by fnquinteros** [comment]
Hola! Busqué en Google "pandas open db" y el primer resultado contiene la información que necesitas.

Saludos.

**Comment by CarlosCarvajalGallegos** [comment]
Efectivamente es cierto. Pero todos los resultados aluden a que al abrir el .db necesitamos saber a priori el nombre de alguna tabla creada a en la base de datos (cosa que no sabemos) . Tampoco podemos iterar en el archivo .db  como para ir poblando alguna tabla creada.

**Comment by FGarridoV** [comment]
Estimado,

Parte de los desafíos de los laboratorios y del curso en general es que aprendan a resolver solos cierto tipo de situaciones. Tu consulta se puede resolver fácilmente usando Google. No es que seamos pesados con el tema, sino que se den cuenta que pueden resolver la mayoría de las dudas que tienen usando internet.

Saludos,
Francisco
