### ISSUE TITLE
funcion recursiva

### ISSUE THREAD

**Issue by kdcarreno** [IIC2115/Syllabus#99]
Hola, tengo el sgte problema:

def funcion_recursiva (n)
     bla bla bla
     a = 1
     b =2
      if algo :
            return  a,b
      else:
            funcion_recursiva(n-1)

a, b = funcion_recursiva (parametro)
**TypeError: cannot unpack non-iterable NoneType object** 

Google me dice "Probablemente tu funcion no alcanza la linea del return porque está dentro de un condicional o algo asi. Si una función termina su ejecución sin un return explícito, python hará que retorne None, lo que producirá el error que muestras. " 

No estoy entendiendo.. Tengo un return explícito. Si la última linea le pongo

aux = funcion_recursiva (parametro) 

me dice que aux es una clase. Cómo llamo a cada elemento si nunca definí una clase? traté de escribir el return como lista y tupla y tampoco funciona

**Comment by cjvergara1** [comment]
Prueba con,

if algo:
return a, b

else:
return funcion_recursiva(n-1)

Así creo que funciona!

**Comment by pcseisdedos** [comment]
Exacto! Tienes que retornar tu función recursiva como dice @cjvergara1 de lo contrario el return del caso base solo va a retornar en el nivel de profundidad de la última recursión y por defecto tu función recursiva retornará `None`  y no lo podrá desempaquetar cuando hagas
`a, b = funcion_recursiva (parametro)`
