### ISSUE TITLE
URGENTE prints en .py

### ISSUE THREAD

**Issue by paulavonbrand** [IIC2115/Syllabus#99]
Hola!!! Subí mi P03 como a las 23;40 pero me acabo de dar cuenta de que el .py lo subí con los prints de las consultas (como for e in cursor: print (e))
Y me acabo de acordar !!!!
Sería mejor dejarlo así? O subirlo como si fuese “atrasado” pero sacarle los prints??
😨😨😨😨😨

**Comment by pcseisdedos** [comment]
Da lo mismo en este caso si contiene o no los prints, incluso yo creo que es más sencillo no quitarlos y simplemente exportar el notebook como .py, pero para quienes borraron los prints y ejecuciones es igualmente válido en esta actividad.

Saludos,
Pablo 😁👍

**Comment by paulavonbrand** [comment]
fiuu que alivio muchisimas gracias!!
